<Input/> - migrate to stylable
wix/wix-style-react pull request #5657
Opened 2020-07-09 06:12 UTC by EgoziE

2020-07-09 06:44 UTC, WixBuildServer commented
### 🤖 Hi, I'm #Janet!

  A deploy preview of your PR was successfully released 🖼.

  You can find it under one of the following URLs:
  * https://www.wix.com/pages/wix-style-react.pr_5657/

2020-08-27 08:44 UTC, TalZa1810 requested changes
I has few comments and questions which I was not sure about.

2020-08-27 08:44 UTC, TalZa1810 commented on src/Input/Affix/Affix.js
> +    {({ size, inPrefix, inSuffix, roundInput, disabled, onInputClicked }) => (
The roundInput was previously forgotten and now added?

2020-08-27 08:44 UTC, TalZa1810 commented on src/Input/Input.driver.js
> +    hasSuffix: () =>
I would expect the implementation of `hasPrefix` and `hasSuffix` to be similar, no?

2020-08-27 08:44 UTC, TalZa1810 commented on src/Input/Input.driver.js
> +      element.hasAttribute(DATA_ATTR.PREFIX) && !!element.querySelector(style),
same here

2020-08-27 08:44 UTC, TalZa1810 commented on src/Input/Input.js
> +        !hideStatusSuffix && ['error', 'warning', 'loading'].includes(status),
maybe extracting all possible suffixes options to a constant

2020-08-27 08:44 UTC, TalZa1810 commented on src/Input/Input.uni.driver.js
> +    hasSuffix: async () =>
same question regarding the uni driver

2020-08-27 08:44 UTC, TalZa1810 commented on src/Input/ThemedInput.js
> +    return Object.fromEntries(
There was an issue with the `fromEntries` if I remember correctly, which is why we have the `filterObject` util:
https://github.com/wix/wix-style-react/blob/master/src/DropdownLayout/DropdownLayout.js#L16
https://github.com/wix/wix-style-react/blob/master/src/DropdownLayout/DropdownLayout.js#L377

2020-08-27 10:01 UTC, shlomitc requested changes

2020-08-27 10:01 UTC, shlomitc commented on src/Search/Search.js
> +    this.setState(stateChanges, () => {
are you sure about this change?

2020-08-27 10:01 UTC, shlomitc commented on src/NoBorderInput/NoBorderInput.st.css
> +.root input + div > div {
`st-extends` instead?

2020-08-27 10:01 UTC, shlomitc commented on src/MultiSelect/InputWithTags.scss
> +  width: 1px;
is this because it became a flex container? this could really be a risky change for other inputs as well

2020-08-31 11:05 UTC, EgoziE commented on src/Input/Input.js
> -      this._isClearFeatureEnabled && !!value && !status && !disabled;
Yes, it was requested by Domas

2020-08-31 11:05 UTC, EgoziE commented on src/Input/IconAffix/IconAffix.js
> +          inPrefix,
Yes, it was requested by Domas

2020-08-31 11:05 UTC, EgoziE commented on src/Input/Affix/Affix.js
> +    {({ size, inPrefix, inSuffix, roundInput, disabled, onInputClicked }) => (
Yes, it was requested by Domas

2020-08-31 12:59 UTC, EgoziE commented on src/ColorInput/ColorInput.js
> +      <Box verticalAlign="middle">
done

2020-08-31 15:50 UTC, EgoziE commented on src/ColorInput/ColorInput.js
> +      <Box verticalAlign="middle">
I need to revert this
It cannot be done because Using an Affix there makes an infinite focus loop

2020-08-31 16:07 UTC, EgoziE commented on src/Input/InputSuffix.js
> +          <Box key={key}>{suffix}</Box>
Only to keep the display: flex
I changed it

2020-08-31 16:17 UTC, EgoziE commented on src/Search/Search.js
> +    this.setState(stateChanges, () => {
I spoke with Ayelet the current implementation is broken and was fixed by mistake.
I added this line to keep the mistake, but now I'll remove it.

2020-08-31 16:18 UTC, EgoziE commented on src/MultiSelect/InputWithTags.scss
> +  width: 1px;
InputWithTags is the only component that explicitly abuses Input, therefore it's css looks really bad.
From what I understand it's used only in one place.

2020-09-02 08:12 UTC, EgoziE commented on src/NoBorderInput/NoBorderInput.st.css
> +.root input + div > div {
Not possible, noborderInput uses an internal part of input

2020-09-02 08:28 UTC, shlomitc commented on src/NoBorderInput/NoBorderInput.st.css
> +.root input + div > div {
what do you mean? isn't that exactly the idea of Stylable? to be able to target specific areas in the component?

2020-09-02 11:33 UTC, merged