Marketing page features footer
wix/wix-style-react pull request #5752
Opened 2020-07-26 14:04 UTC by sivanharel

### 🔦 Summary

...

### ✅ Checklist

- [ ] 👨‍💻 API change is approved by the UI Infra Developers 
- [ ] 👨‍🎨 UX change is approved by the Design System UX 
- 📚 Change is documented
  - [ ] Story
  - [ ] API description
  - [ ] Cheatsheet
  - [ ] Other (explain)
- 🔬 Change is tested
  - [ ] Component
  - [ ] Visual test

2020-07-26 14:47 UTC, WixBuildServer commented
### 🤖 Hi, I'm #Janet!

  A deploy preview of your PR was successfully released 🖼.

  You can find it under one of the following URLs:
  * https://www.wix.com/pages/wix-style-react.pr_5752/

2020-07-27 07:28 UTC, sivanharel commented on src/MarketingPageFeaturesFooter/docs/index.story.js
> +    buttonText: 'Hello World!',
Remove it

2020-07-27 07:29 UTC, sivanharel commented on src/MarketingPageFeaturesFooter/index.d.ts
> +  className?: string;
Remove it

2020-08-02 09:02 UTC, sivanharel commented on src/MarketingPageFeaturesFooter/MarketingPageFeaturesFooter.js
> +            size="small"
change to 'medium'

2020-08-02 09:12 UTC, sivanharel commented on src/MarketingPageFeaturesFooter/docs/index.story.js
> +              'This component is a footer for the MarketingPageLayout component.',
change to 'This component is used as a footer for the Marketing Page Layout.'

2020-08-04 06:33 UTC, sivanharel commented
@milkyfruit - I will make this component generic as well. And if you have more comments please let me know :)

2020-08-04 11:11 UTC, milkyfruit commented
@sivanharel yes, I think it can be renamed to `FeatureList`
I noticed this component behaves a bit different than TestimonialList, because it supports only 3 items per row,  then creates a grid:
![image](https://user-images.githubusercontent.com/1684587/89287235-40293880-d65c-11ea-8fb1-085dafa2ff60.png)

It's ok to support grid as well, but I think both components should have the same logic and then there should be `columns` prop, in case someone wants to show 4 or 2 features per row.

2020-08-06 09:01 UTC, sivanharel commented
@milkyfruit - Yes, I implemented two options and waited for your answer to the question I asked in the Zeplin :)
It is up to you, tell me what is the behavior that you prefer and I will implement it in the
 "featureList" as well.
For the grid option, it sounds like a great idea to add a columns prop that will determine the number of columns in the list.

2020-08-24 07:42 UTC, shlomitc requested changes

2020-08-27 08:10 UTC, shlomitc approved these changes
minor changes and we can merge

2020-08-27 08:10 UTC, shlomitc commented on src/FeatureList/FeatureList.uni.driver.js
> +  const byHook = hook => base.$(`[data-hook*="${hook}"]`);
can this be refactored to some general place? probably we have tons of these

2020-08-27 08:10 UTC, shlomitc commented on src/common/FluidColumns/index.d.ts
> +export default class FluidColumns extends React.PureComponent<FluidColumnsProps>{}
not a PureComponent

2020-08-27 09:11 UTC, merged