<ModalSelectorLayout/> - use new <CustomModalLayout/>
wix/wix-style-react pull request #5831
Opened 2020-08-13 08:56 UTC by bamai

### 🔦 Summary
https://jira.wixpress.com/browse/DSM-613
...

### ✅ Checklist

- [ ] 👨‍💻 API change is approved by the UI Infra Developers 
- [ ] 👨‍🎨 UX change is approved by the Design System UX 
- 📚 Change is documented
  - [ ] Story
  - [ ] API description
  - [ ] Cheatsheet
  - [ ] Other (explain)
- 🔬 Change is tested
  - [ ] Component
  - [ ] Visual test

2020-08-13 09:04 UTC, WixBuildServer commented
### 🤖 Hi, I'm #Janet!

  A deploy preview of your PR was successfully released 🖼.

  You can find it under one of the following URLs:
  * https://www.wix.com/pages/wix-style-react.pr_5831/

2020-08-13 11:09 UTC, shlomitc commented on src/ModalSelectorLayout/ModalSelectorLayout.js
>          data-hook={dataHook}
`dataHook` probably

2020-08-13 11:11 UTC, shlomitc commented on src/ModalSelectorLayout/ModalSelectorLayout.js
> +      <CustomModalLayout
Looking in the cheatsheet, previously the close button appeared
![image](https://user-images.githubusercontent.com/6093192/90128251-43fd3f00-dd6f-11ea-9944-5632f51ea81f.png)

While now it isn't
![image](https://user-images.githubusercontent.com/6093192/90128283-537c8800-dd6f-11ea-8d7a-a234d4145c4d.png)

can you check this out, please?

2020-08-13 11:12 UTC, shlomitc commented on src/ModalSelectorLayout/ModalSelectorLayout.js
> +      <CustomModalLayout
The initial rendering of the modal is broken
![image](https://user-images.githubusercontent.com/6093192/90128114-fc76b300-dd6e-11ea-84c8-8cf6e007a85a.png)

in oppose to the current one
![image](https://user-images.githubusercontent.com/6093192/90128137-0bf5fc00-dd6f-11ea-8004-6c39e522b2f1.png)

2020-08-16 09:03 UTC, lironch commented on src/ModalSelectorLayout/ModalSelectorLayout.js
> +      <CustomModalLayout
To show the close button in `CustomModalLayout` you need to pass a `onCloseButtonClicked` handler

2020-08-16 09:10 UTC, lironch commented on src/ModalSelectorLayout/ModalSelectorLayout.js
> +        showHeaderDivider
You probably don't need this unless it was requested specifically by Ayelet.
The header/footer dividers will show automatically according to your scroll position.

2020-08-16 09:13 UTC, lironch commented on src/ModalSelectorLayout/ModalSelectorLayout.js
> +        style={{ height, maxHeight, width: '600px' }}
Please avoid adding styles this way for now, when we will understand this is a must we will rethink what is the best way to do so.

2020-08-16 09:27 UTC, lironch commented on src/ModalSelectorLayout/ModalSelectorLayout.js
> +        onCloseButtonClick={onClose}
I'm not sure why this component need to expose both `onClose` and `onCancel` which represent the exact same use case for the component user.
@shlomitc i would consider deprecating one of them as part of this change

2020-08-16 09:31 UTC, lironch commented on src/ModalSelectorLayout/ModalSelectorLayout.js
> +          sideActions ? sideActions : multiple && this._renderFooterSelector()
Do we really have a good product justification to expose `sideActions` to the users of this component?
It means that in case they choose to use it you will probably lose the `select-all` behaviour of this component

2020-08-25 07:45 UTC, shlomitc requested changes

2020-08-25 07:45 UTC, shlomitc commented on src/ModalSelectorLayout/ModalSelectorLayout.js
> +    subtitle: PropTypes.string,
are you sure this is a required change? we usually allow passing nodes because of translation functions that return a node

2020-08-25 07:45 UTC, shlomitc commented on src/ModalSelectorLayout/ModalSelectorLayout.js
> +      <CustomModalLayout
@bamai - at least in the storybook preview - the cheatsheet is still not displaying the x button, please check it
https://www.wix.com/pages/wix-style-react.pr_5831/?path=/story/introduction-cheatsheet--components-cheatsheet

2020-08-25 07:45 UTC, shlomitc commented on src/ModalSelectorLayout/ModalSelectorLayout.js
> +              <Search
The search should stay sticky once scrolling the modal content, see how it cuts the content:
![image](https://user-images.githubusercontent.com/6093192/91146023-fe216e80-e6be-11ea-97cf-3358ef045a68.png)

After your change, the Search is scrolled with the content which isn't good

2020-08-25 07:45 UTC, shlomitc commented on src/ModalSelectorLayout/ModalSelectorLayout.js
> +        showHeaderDivider
@bamai - what's the decision here?

2020-08-25 07:45 UTC, shlomitc commented on src/ModalSelectorLayout/ModalSelectorLayout.js
> +        onCloseButtonClick={onClose}
You're probably right, but this widget is quite old and some wrong decisions were taken along the way.
Anyway, that's not urgent, so let's skip this for now

2020-08-25 07:45 UTC, shlomitc commented on src/ModalSelectorLayout/ModalSelectorLayout.js
> +          sideActions ? sideActions : multiple && this._renderFooterSelector()
same as before - let's not change the current product, it's an old component...

2020-09-01 13:50 UTC, shlomitc commented on src/ModalSelectorLayout/ModalSelectorLayout.js
> +        showHeaderDivider
currently, we decided to not apply any borders due to search sticky position limitations.
We will need to extend the ScrollContainer to support an additional `fixedHeader` in which the `Search` component will be placed. It will not be part of the scroll, but the divider will appear above it. We'll do it as a separate task

2020-09-01 13:55 UTC, shlomitc commented on src/ModalSelectorLayout/ModalSelectorLayout.scss
> +  height: calc(100% - #{$search-height});
not sure if this should actually be done with `flex` instead of `calc`

2020-09-13 11:35 UTC, shlomitc approved these changes

2020-09-13 14:58 UTC, merged