<MarketingPageLayoutContent /> - new component
wix/wix-style-react pull request #5838
Opened 2020-08-16 11:03 UTC by sivanharel

### 🔦 Summary

...

### ✅ Checklist

- [ ] 👨‍💻 API change is approved by the UI Infra Developers 
- [ ] 👨‍🎨 UX change is approved by the Design System UX 
- 📚 Change is documented
  - [ ] Story
  - [ ] API description
  - [ ] Cheatsheet
  - [ ] Other (explain)
- 🔬 Change is tested
  - [ ] Component
  - [ ] Visual test

2020-08-16 11:11 UTC, WixBuildServer commented
### 🤖 Hi, I'm #Janet!

  A deploy preview of your PR was successfully released 🖼.

  You can find it under one of the following URLs:
  * https://www.wix.com/pages/wix-style-react.pr_5838/

2020-08-19 14:36 UTC, sivanharel commented
@milkyfruit - What should be the description for the Advanced Example?

2020-08-19 14:44 UTC, milkyfruit commented
> @milkyfruit - What should be the description for the Advanced Example?

For each example description is added right after the checkmark, so It's this one:
Component supports 2 sizes – medium and large. Large is default. This property is used to build breakpoints.

2020-08-20 07:10 UTC, milkyfruit approved these changes

2020-08-20 11:54 UTC, TalZa1810 requested changes
Hey,
I've added some small comments. Let me know if something isn't clear.

2020-08-20 11:54 UTC, TalZa1810 commented on src/MarketingPageLayoutContent/docs/index.story.js
> +      component: <MarketingPageLayoutContent buttonText="Click me!" />,
generated form the generator. should be removed

2020-08-20 11:54 UTC, TalZa1810 commented on src/MarketingPageLayoutContent/docs/index.story.js
> +const code = config => baseCode({ components: allComponents, ...config });
not used, can be removed

2020-08-20 11:54 UTC, TalZa1810 commented on src/MarketingPageLayoutContent/docs/index.story.js
> +          <allComponents.Button size="large">Main Action</allComponents.Button>
instead of using this like this, you can simply import Button at the top of the file and use it as 
`<Button size="large">Main Action</Button>`

2020-08-20 11:54 UTC, TalZa1810 commented on src/MarketingPageLayoutContent/test/MarketingPageLayoutContent.visual.js
> +    describe: 'size',
This one can be also as: 
```
const sizes = Object.values(SIZES);

  {
    describe: 'Sizes',
    its: sizes.map(size => ({ it: size, props: { size } })),
  },

```

This way, if we add extra siae, the visual test will be added automatically after adding the extra size (in this case) to the constants file

2020-08-20 11:54 UTC, TalZa1810 commented on src/MarketingPageLayoutContent/MarketingPageLayoutContent.js
> +          <Box data-hook={dataHooks.titleContainer}>
```suggestion
          <Box dataHook={dataHooks.titleContainer}>
```

2020-08-20 11:54 UTC, TalZa1810 commented on src/MarketingPageLayoutContent/MarketingPageLayoutContent.js
> +          <Box data-hook={dataHooks.subtitleContainer} marginTop={2}>
```suggestion
          <Box dataHook={dataHooks.subtitleContainer} marginTop={2}>
```

2020-08-20 13:38 UTC, sivanharel commented on src/MarketingPageLayoutContent/docs/index.story.js
> +          <allComponents.Button size="large">Main Action</allComponents.Button>
Yes I know but I thought that since there is already an import for all the component so I can use it in that way but maybe it's less readable so I will change it

2020-08-24 05:31 UTC, sivanharel commented on src/MarketingPageLayoutContent/MarketingPageLayoutContent.js
> +            <div className={classes.overlineDivider} />
I didn't succeed to force the width since the "width: 100%" the declared in the component override the width that I'm passing. So I think I would add a container. I can also use "!important" but not sure it the best practice.

2020-08-24 06:25 UTC, sivanharel commented on src/MarketingPageLayoutContent/MarketingPageLayoutContent.uni.driver.js
> +  const byHook = hook => base.$(`[data-hook="${hook}"]`);
I added it to the common testing utils and after merging this PR I will update the other component to use it.
BTW there is a function findBaseByHook in the utils file but has [data-hook*="${hook}"] which match every element that its data hook name contains the string "${hook}" which in my case not relevant since I have for example data hook 'overline-container' and 'overline'.
Maybe it is not a good practice and I should remove the '*' instead of adding another function without the '*'. What do you think?

2020-08-24 07:50 UTC, milkyfruit commented on src/MarketingPageLayoutContent/MarketingPageLayoutContent.js
> +            <Box marginBottom="17px" color="D20">
The divider sits on a gridline, therefore divider's padding is 17px. 17px + 1px (divider's height) is 18px in total which is dividable by 6.
Overline text color should be – D20
Divider color should be – D60
Text title color should be – D10

2020-08-24 08:25 UTC, shlomitc commented on src/MarketingPageLayoutContent/MarketingPageLayoutContent.js
> +            <Box marginBottom="17px" color="D20">
@milkyfruit - aren't all of these colors already built-in inside our components? why do they need to be set specifically?

2020-08-27 09:36 UTC, sivanharel commented on src/MarketingPageLayoutContent/MarketingPageLayoutContent.js
> +            <Box marginBottom="17px" color="D20">
There is an option to pass a string or a node for all the following props: "overline", "title", "subtitle", and "content".
When passing a string the color is defined by the Text and Heading components. As I understood from @milkyfruit, he requested me to define colors also when passing a node si I defined the colors also in the containers.

2020-08-27 10:39 UTC, merged