Breadcrumbs ellipsis
wix/wix-style-react pull request #5843
Opened 2020-08-16 14:51 UTC by gendeld

### 🔦 Summary

...

### ✅ Checklist

- [ ] 👨‍💻 API change is approved by the UI Infra Developers 
- [ ] 👨‍🎨 UX change is approved by the Design System UX 
- 📚 Change is documented
  - [ ] Story
  - [ ] API description
  - [ ] Cheatsheet
  - [ ] Other (explain)
- 🔬 Change is tested
  - [ ] Component
  - [ ] Visual test

2020-08-16 14:59 UTC, WixBuildServer commented
### 🤖 Hi, I'm #Janet!

  A deploy preview of your PR was successfully released 🖼.

  You can find it under one of the following URLs:
  * https://www.wix.com/pages/wix-style-react.pr_5843/

2020-08-19 11:13 UTC, EgoziE requested changes
Please add a story with ellipsis

2020-08-19 11:13 UTC, EgoziE commented on src/Text/Text.js
> +      )}
Adding an external `wrapperClassName` is a good change, please add this exact same change to:
* Caption
* Heading

2020-09-03 09:49 UTC, EgoziE approved these changes

2020-09-03 09:49 UTC, EgoziE commented on src/Breadcrumbs/docs/index.story.js
> +              You can control the item's maximum width with the \`itemMaxWidth\` prop, where \`"max-content"\` disables ellipsizing completely.`,
😁 
```suggestion
              You can control the item's maximum width with the \`itemMaxWidth\` prop, where \`"max-content"\` disables ellipsis completely.`,
```

2020-09-06 09:17 UTC, merged