<DropdownLayout/> - fix the RTL css issue
wix/wix-style-react pull request #5881
Opened 2020-08-24 15:28 UTC by sivanharel

### 🔦 Summary

...

### ✅ Checklist

- [ ] 👨‍💻 API change is approved by the UI Infra Developers 
- [ ] 👨‍🎨 UX change is approved by the Design System UX 
- 📚 Change is documented
  - [ ] Story
  - [ ] API description
  - [ ] Cheatsheet
  - [ ] Other (explain)
- 🔬 Change is tested
  - [ ] Component
  - [ ] Visual test

2020-08-24 15:36 UTC, WixBuildServer commented
### 🤖 Hi, I'm #Janet!

  A deploy preview of your PR was successfully released 🖼.

  You can find it under one of the following URLs:
  * https://www.wix.com/pages/wix-style-react.pr_5881/

2020-08-25 07:57 UTC, TalZa1810 requested changes

2020-08-25 07:57 UTC, TalZa1810 commented on src/DropdownLayout/test/DropdownLayout.visual.js
> +          <RTLWrapper rtl={rtl}>
Maybe we can just run all tests for regular DropdownLayout and RTL DropdownLayout.
So in one screenshot we can have the regular version and the rtl one.

Also, rtl is a boolean so you can just use it this way:
```suggestion
          <RTLWrapper rtl>
```

2020-08-26 07:47 UTC, TalZa1810 approved these changes
looks good  :)

2020-08-26 10:34 UTC, merged