`<Ellipsis/>` - adding lineClamp
wix/wix-style-react pull request #5885
Opened 2020-08-25 12:54 UTC by TalZa1810

### 🔦 Summary
Adding `lineClamp` prop to `<Ellipsis/>`. 

### ✅ Checklist

- [ ] 👨‍💻 API change is approved by the UI Infra Developers 
- [ ] 👨‍🎨 UX change is approved by the Design System UX 
- 📚 Change is documented
  - [ ] Story
  - [ ] API description
  - [ ] Cheatsheet
  - [ ] Other (explain)
- 🔬 Change is tested
  - [ ] Component
  - [ ] Visual test

2020-08-25 13:03 UTC, WixBuildServer commented
### 🤖 Hi, I'm #Janet!

  A deploy preview of your PR was successfully released 🖼.

  You can find it under one of the following URLs:
  * https://www.wix.com/pages/wix-style-react.pr_5885/

2020-08-25 14:05 UTC, shlomitc requested changes

2020-08-25 14:05 UTC, shlomitc commented on src/common/Ellipsis/Ellipsis.js
> +      ellipsis && (this._widthCheck() || this._HeightCheck());
is it really necessary to check both for all cases?

2020-08-25 14:05 UTC, shlomitc commented on src/Text/Text.js
> +          style={style}
why is this needed?

2020-08-25 14:05 UTC, shlomitc commented on src/common/Ellipsis/Ellipsis.js
> +  _widthCheck = () => {
give this function a name that describes what it does

2020-08-25 14:05 UTC, shlomitc commented on src/common/Ellipsis/Ellipsis.js
> +        [
That's not very readable, don't you think?

2020-08-25 14:05 UTC, shlomitc commented on src/common/Ellipsis/Ellipsis.st.css
> +  -webkit-box-orient: vertical;
is this supported by all browsers?

2020-08-25 14:13 UTC, TalZa1810 commented on src/common/Ellipsis/Ellipsis.st.css
> +  -webkit-box-orient: vertical;
It is [not supported ](https://www.w3.org/TR/css-overflow-3/#propdef--webkit-line-clamp) in all browsers.  I've read [this article](https://medium.com/mofed/css-line-clamp-the-good-the-bad-and-the-straight-up-broken-865413f16e5) regarding the `line-clamp` css property and saw [this solution](https://codepen.io/nilsynils/pen/KgaRBo?editors=1100
).  
WDYT about this solution for unsupported browsers? 
There is another [suggested solution](https://codepen.io/nilsynils/pen/zKNpkm?editors=1111).

2020-08-25 14:30 UTC, shlomitc commented on src/common/Ellipsis/Ellipsis.st.css
> +  -webkit-box-orient: vertical;
What they suggest in the article is hiding some content in case line-clamp is not supported.
![image](https://user-images.githubusercontent.com/6093192/91186904-3b562280-e6f8-11ea-986b-1a8bd0cf43ba.png)

I guess that this can be considered a good enough fallback as long as the tooltip will appear

2020-09-03 09:43 UTC, TalZa1810 commented on src/Text/Text.js
> +          style={style}
It is needed since we don't know in advance how many lines the user wants to have. Therefore, it has to be inline styles.

2020-09-03 12:31 UTC, shlomitc requested changes

2020-09-03 12:31 UTC, shlomitc commented on src/common/Ellipsis/Ellipsis.js
> +      ...(ellipsis && maxLines && inlineStyle),
1. from this, it is unclear that you are passing the `style` entry. I need to go to `inlineStyle` only to understand there that you create the `style` entry.

2. In order to prefer confusion, I think it's better to give it a more indicative name. same as we have `ellipsisClasses`, use `ellipsisInilneStyle`. then the consumer of it understand what he attaches to his component

3. instead of inline styles, you can simply use css class + css variable. this means that the `style` object will contain the variable of `--max-lines` and you will use it in the `.maxLines` class

2020-09-03 12:31 UTC, shlomitc commented on src/Text/Text.js
> +          style={style}
so doesn't `RawText` should now open the `style` prop?

2020-09-06 08:31 UTC, shlomitc requested changes

2020-09-06 08:31 UTC, shlomitc commented on src/Text/index.d.ts
> +  style?: React.CSSProperties;
I'm actually not sure this is the right place since this is exported out as part of the `<Text/>` component, while your change is kind of internal as it stays in `RawText`.

2020-09-06 08:31 UTC, shlomitc commented on src/common/Ellipsis/Ellipsis.js
> +  _getEllipsisClasses = (ellipsis, maxLines) => (...classNames) =>
I really think using `classNames()` will make this much more readable and declerative

2020-09-06 08:31 UTC, shlomitc commented on src/common/Ellipsis/Ellipsis.st.css
> +.maxLines {
to keep it declerative - `.multiLine`

2020-09-06 08:31 UTC, shlomitc commented on src/common/Ellipsis/Ellipsis.js
> +      maxLines > 1 && ellipsis && classes.maxLines,
does it make sense to use both `text` and `maxLine`? aren't they overriding each other?

2020-09-06 08:43 UTC, TalZa1810 commented on src/common/Ellipsis/Ellipsis.js
> +      maxLines > 1 && ellipsis && classes.maxLines,
It just overrides `white-space` & `display`. I've removed the default prop of `maxLines = 1` because it broke some of the examples. That's why I check maxLines is bigger then 1.

2020-09-06 08:48 UTC, TalZa1810 commented on src/Text/index.d.ts
> +  style?: React.CSSProperties;
yep, I was confused because `RawText` doesn't have a specific `d.ts` file.

2020-09-06 09:14 UTC, shlomitc commented on src/common/Ellipsis/Ellipsis.js
> +  _classNames = () => (...classNames) => {
declarative function name, please :)

2020-09-06 09:14 UTC, shlomitc commented on src/common/Ellipsis/Ellipsis.js
> +      maxLines > 1 && ellipsis && classes.maxLines,
so let's do a small refactor.
one class that sets the common ellipsis styling (overflowing and such), another class that does single line ellipsis, and one last the does multiple lines

2020-09-06 11:11 UTC, TalZa1810 commented on src/common/Ellipsis/Ellipsis.js
> +      maxLines > 1 && ellipsis && classes.maxLines,
I've used stylable for this. not sure about the name of the main class name though.

2020-09-06 11:39 UTC, TalZa1810 commented on src/common/Ellipsis/Ellipsis.js
> +        className,
It seems that all components that use ellipsis: `Text`, `Caption` and `Heading`, it gets `className` and not array of classNames so I used stylable for this case and rename the variable.

2020-09-06 12:10 UTC, shlomitc commented on src/common/Ellipsis/Ellipsis.js
> +          multiline: maxLines > 1 && ellipsis,
this should be a single state since they can not live together

2020-09-13 07:14 UTC, shlomitc approved these changes
👍

2020-09-13 07:16 UTC, merged