Handle overflow of content in PreviewWidget
wix/wix-style-react pull request #5897
Opened 2020-08-27 14:41 UTC by AndriiTsarenko

### 🔦 Summary

...

### ✅ Checklist

- [ ] 👨‍💻 API change is approved by the UI Infra Developers 
- [ ] 👨‍🎨 UX change is approved by the Design System UX 
- 📚 Change is documented
  - [ ] Story
  - [ ] API description
  - [ ] Cheatsheet
  - [ ] Other (explain)
- 🔬 Change is tested
  - [ ] Component
  - [ ] Visual test

2020-08-27 16:14 UTC, WixBuildServer commented
### 🤖 Hi, I'm #Janet!

  A deploy preview of your PR was successfully released 🖼.

  You can find it under one of the following URLs:
  * https://www.wix.com/pages/wix-style-react.pr_5897/

2020-08-27 20:19 UTC, TalZa1810 requested changes
Hey, just some few comments

2020-08-27 20:19 UTC, TalZa1810 commented on src/PreviewWidget/PreviewWidget.js
> +import classNames from 'classnames';
No need to use classNames when using stylable

2020-08-27 20:19 UTC, TalZa1810 commented on src/PreviewWidget/PreviewWidget.js
> +            [classes.contentAreaScrollable]: scrollable,
This is basically a state which can be passed within the root div. You can check out the `contentOutline`  stylable state as a reference.

2020-08-30 08:57 UTC, EgoziE requested changes

2020-08-30 08:57 UTC, EgoziE commented on src/PreviewWidget/index.d.ts
> +  scrollable?: boolean;
Please add to type test file PreviewWidget.tsx

2020-08-31 10:39 UTC, milkyfruit approved these changes
Looks good from design side.

2020-08-31 11:53 UTC, merged