InputArea's required attribute
wix/wix-style-react pull request #5898
Opened 2020-08-27 17:34 UTC by tyv

closes #5886 

### 🔦 Summary

Added required attribute to the base component, wrote unit test and added to the relevant drivers method `getRequired`

### ✅ Checklist

- 📚 Change is documented
  - [ ] Story
  - [x] API description
  - [ ] Cheatsheet
  - [ ] Other (explain)
- 🔬 Change is tested
  - [x] Component
  - [ ] Visual test

2020-08-27 20:32 UTC, tyv commented
can I sign commits afterwards? without force push?

2020-08-28 09:36 UTC, WixBuildServer commented
### 🤖 Hi, I'm #Janet!

  A deploy preview of your PR was successfully released 🖼.

  You can find it under one of the following URLs:
  * https://www.wix.com/pages/wix-style-react.pr_5898/

2020-08-30 08:36 UTC, EgoziE requested changes

2020-08-30 08:36 UTC, EgoziE commented on src/InputArea/test/InputArea.spec.js
> +      });
Please add a test that checks required is false.

2020-08-31 09:04 UTC, merged