add AreaChart component
wix/wix-style-react pull request #5901
Opened 2020-08-30 13:56 UTC by ChenAlmagor

### 🔦 Summary

...

### ✅ Checklist

- [ ] 👨‍💻 API change is approved by the UI Infra Developers 
- [ ] 👨‍🎨 UX change is approved by the Design System UX 
- 📚 Change is documented
  - [ ] Story
  - [ ] API description
  - [ ] Cheatsheet
  - [ ] Other (explain)
- 🔬 Change is tested
  - [ ] Component
  - [ ] Visual test

2020-08-30 14:17 UTC, EgoziE requested changes

2020-08-30 14:17 UTC, EgoziE commented on perfer.config.js
> +  ['AreaChart.bundle.min.js', 10],
Please fill in the real value + 2
Try `npm run test:performance` for the real value
And sort alphabetically

2020-08-30 14:17 UTC, EgoziE commented on perfer.config.js
> +  ['AreaChart.min.css', 1],
sort alphabetically

2020-08-30 14:17 UTC, EgoziE commented on src/AreaChart/types.ts
> +}
Please define all types in `index.d.ts`

2020-08-30 14:17 UTC, EgoziE commented on stories/index.js
> +require('../src/AreaChart/docs/index.story');
Move to correct position

2020-09-03 09:12 UTC, WixBuildServer commented
### 🤖 Hi, I'm #Janet!

  A deploy preview of your PR was successfully released 🖼.

  You can find it under one of the following URLs:
  * https://www.wix.com/pages/wix-style-react.pr_5901/

2020-09-16 15:08 UTC, ayeletr commented
Hi, @ChenAlmagor 
I looked at this in SB, few comments:

**1.** In the first example there's no text in the first tooltip. this can't happen. I don't want to show unreal examples, it's ether without a tooltip or tooltip with content.
![image](https://user-images.githubusercontent.com/34542112/93354319-8968cc80-f845-11ea-9a47-2579c651c935.png)

**2.** there's something wrong with the last tooltip: the small arrow doesn't sit correctly, is this WSR tooltip?
![image](https://user-images.githubusercontent.com/34542112/93354580-d0ef5880-f845-11ea-8210-beb1899a98e6.png)
if not, this is how it should be placed:
![image](https://user-images.githubusercontent.com/34542112/93355036-4e1acd80-f846-11ea-984a-bdbe5ecc0a94.png)

**3.** Let's show another example with points between the x labels, to show that the labels don't have to be connected to info points (you can have less labels but show same amount of info) like this:
![image](https://user-images.githubusercontent.com/34542112/93355856-2d9f4300-f847-11ea-8468-a67314480c92.png)

Thanks!

2020-09-17 10:54 UTC, ayeletr commented
Looks good to me :)

2020-09-17 10:57 UTC, ayeletr commented
I forgot about the keyboard behavior, can we add it? (for accessibility) @shlomitc @ChenAlmagor @EgoziE

2020-09-21 14:29 UTC, EgoziE requested changes

2020-09-21 14:29 UTC, EgoziE commented on src/AreaChart/AreaChart.js
> +    const dataset = (data || []).map(i => i.value);
Add `data: []` to defaultProps instead

2020-09-21 14:29 UTC, EgoziE commented on src/AreaChart/docs/index.story.js
> +              'This line here should briefly describe component in just a sentence or two. It should be short and easy to read.',
This line here should briefly describe component in just a sentence or two. It should be short and easy to read. :)

2020-09-21 14:29 UTC, EgoziE commented on src/AreaChart/docs/index.story.js
> +          example({
I think it will be better to extract examples to a separate file, take a look at other components, they have 'examples.js' file in docs folder.

2020-09-22 12:44 UTC, ChenAlmagor commented on src/AreaChart/AreaChart.js
> +    const dataset = (data || []).map(i => i.value);
but it should not be the default value, the minimum should be 2 different points... it's just a defensive code.

2020-09-23 11:05 UTC, merged