<FunnelChart/> component
wix/wix-style-react pull request #5904
Opened 2020-08-31 06:16 UTC by MayaHamo

New component - <FunnelChart/>

### ✅ Checklist

- [X] 👨‍💻 API change is approved by the UI Infra Developers @EgoziE 
- [X] 👨‍🎨 UX change is approved by the Design System UX 
- 📚 Change is documented
  - [X] Story
  - [X] API description

- 🔬 Change is tested
  - [ ] Component
  - [ ] Visual test

2020-08-31 10:54 UTC, EgoziE requested changes

2020-08-31 10:54 UTC, EgoziE commented on perfer.config.js
> +  ['FunnelChart.bundle.min.js', 10],
Please fill in the real value + 2
Try npm run test:performance for the real value
And sort alphabetically

2020-08-31 10:54 UTC, EgoziE commented on perfer.config.js
> +  ['FunnelChart.min.css', 1],
sort alphabetically

2020-08-31 10:54 UTC, EgoziE commented on src/FunnelChart/FunnelBadge/FunnelBadge.scss
> +@import '../../colors.scss';
We don't use scss anymore, please migrate it to Stylable.

2020-08-31 10:54 UTC, EgoziE commented on src/FunnelChart/FunnelLabel/FunnelLabel.scss
> +.funnelLabel {
We don't use scss anymore, please migrate it to Stylable.

2020-08-31 10:54 UTC, EgoziE commented on src/FunnelChart/UnitsText/UnitsText.scss
> +.overflower {
We don't use scss anymore, please migrate it to Stylable.

2020-08-31 10:54 UTC, EgoziE commented on src/FunnelChart/utils/currencies.js
> +export const CURRENCIES = [
@shlomitc what are we going to do with this?

2020-08-31 10:54 UTC, EgoziE commented on src/FunnelChart/utils/numberFormatters.js
> +import { CURRENCIES } from './currencies';
@shlomitc same question

2020-08-31 10:54 UTC, EgoziE commented on stories/index.js
> +require('../src/FunnelChart/docs/index.story');
move to correct position

2020-08-31 10:59 UTC, MayaHamo commented on src/FunnelChart/FunnelBadge/FunnelBadge.scss
> +@import '../../colors.scss';
@EgoziE also on aux component?
I saw that on internal component there is scss

I'll migrate

2020-08-31 11:00 UTC, EgoziE commented
Please take the time to sign your commits, CI will fail automatically without it.
https://github.com/wix/wix-style-react/blob/master/docs/contribution/CREATE_PR.md

2020-08-31 11:01 UTC, MayaHamo commented on src/FunnelChart/utils/currencies.js
> +export const CURRENCIES = [
analytics imports this function from `import { getCurrencyByKey } from '@wix/locale-dataset-javascript';`
but I didn't want to install new deps

2020-08-31 11:13 UTC, MayaHamo commented on perfer.config.js
> +  ['FunnelChart.bundle.min.js', 10],
`npm run test:performance` doesn't help with the "real value" -
what exactly does it means? 12?

2020-08-31 11:33 UTC, WixBuildServer commented
### 🤖 Hi, I'm #Janet!

  A deploy preview of your PR was successfully released 🖼.

  You can find it under one of the following URLs:
  * https://www.wix.com/pages/wix-style-react.pr_5904/

2020-08-31 12:25 UTC, EgoziE commented on src/FunnelChart/FunnelBadge/FunnelBadge.scss
> +@import '../../colors.scss';
yes

2020-08-31 12:26 UTC, EgoziE commented on src/FunnelChart/utils/currencies.js
> +export const CURRENCIES = [
wix-style-react should not deal with:
* Locales
* Currencies
* Translations
* Geography
etc.

I'll discuss with Shlomi about it.

2020-08-31 12:28 UTC, EgoziE commented on perfer.config.js
> +  ['FunnelChart.bundle.min.js', 10],
![image](https://user-images.githubusercontent.com/35173937/91719745-8cee2980-eb9e-11ea-989d-2f6826bab1be.png)

so 37 it is

2020-08-31 13:43 UTC, MayaHamo commented on perfer.config.js
> +  ['FunnelChart.bundle.min.js', 10],
thanks

2020-08-31 13:47 UTC, MayaHamo commented on src/FunnelChart/utils/currencies.js
> +export const CURRENCIES = [
I think I can remove it, checking

2020-09-06 16:14 UTC, shlomitc requested changes
that's the initial chunk. I went over mostly the small units to clean all the dirt and then I'll focus on the main component as well

2020-09-06 16:14 UTC, shlomitc commented on src/FunnelChart/FunnelLabel/FunnelLabel.js
> +import { Text } from '../../index';
```suggestion
import Text from '../../Text';
```

2020-09-06 16:14 UTC, shlomitc commented on src/FunnelChart/FunnelLabel/FunnelLabel.js
> +export const FunnelLabel = props => (
```suggestion
export const FunnelLabel = ({value, label}) => (
```

2020-09-06 16:14 UTC, shlomitc commented on src/FunnelChart/UnitsText/UnitsText.st.css
> +    }
is this really needed?

2020-09-06 16:14 UTC, shlomitc commented on src/FunnelChart/UnitsText/UnitsText.js
> +  disableCompact: PropTypes.bool,
is this used?

2020-09-06 16:14 UTC, shlomitc commented on src/FunnelChart/UnitsText/UnitsText.js
> +  }
maybe the logic here be the if you do not provide a number - it should be presented as it was supplied? wrapped by a regular text component?

2020-09-06 16:14 UTC, shlomitc commented on src/FunnelChart/UnitsText/UnitsText.js
> +  disableTooltip: false,
is this used?

2020-09-06 16:14 UTC, shlomitc commented on src/FunnelChart/UnitsText/UnitsText.js
> +  precision: 0,
is this used?

2020-09-06 16:14 UTC, shlomitc commented on src/FunnelChart/UnitsText/UnitsText.js
> +  compactPrecision: 0,
it defaults to 0 but the only usage of it is [here](https://github.com/wix/wix-style-react/pull/5904/files#diff-6e3d3ea2755b3f384eb9fb993327605bR20) and it passes 1.
so maybe it is not needed and default should be 1?

2020-09-06 16:14 UTC, shlomitc commented on src/FunnelChart/UnitsText/UnitsText.js
> +import React from 'react';
I've got a hunch that this component was just copied and not thoroughly investigated.
if all my comments and with "not needed" - then we can actually ditch it and only use the number formatters in places we need in the code. less code - better

2020-09-06 16:14 UTC, shlomitc commented on src/FunnelChart/FunnelChart.uni.driver.d.ts
> +  getLabel(index: number): Promise<string>;
```suggestion
  getLabelAt(index: number): Promise<string>;
```
and fix in the actual code as well

2020-09-06 16:14 UTC, shlomitc commented on src/FunnelChart/utils/numberFormatters.js
> +};
since this is pure logic, I think we can add a few unit tests here.
another option will be covering it in visuals, but I think it could be easier to cover in unitests

2020-09-07 08:36 UTC, shlomitc requested changes

2020-09-07 08:51 UTC, MayaHamo commented on src/FunnelChart/FunnelChart.js
> +          }
I can add tests

2020-09-07 08:51 UTC, MayaHamo commented on src/FunnelChart/FunnelChart.js
> +                    styles={{ top: `${badgeTopPosition}%` }}
done

2020-09-07 08:51 UTC, MayaHamo commented on src/FunnelChart/FunnelBadge/FunnelBadge.st.css
> +.badgeWrapper {
done

2020-09-07 08:52 UTC, MayaHamo commented on src/FunnelChart/docs/index.story.js
> +            source: `<FunnelChart data={[
done

2020-09-07 08:52 UTC, MayaHamo commented on src/FunnelChart/UnitsText/UnitsText.st.css
> +  @supports (flex-wrap: wrap) {
removed it

2020-09-07 09:05 UTC, MayaHamo commented on src/FunnelChart/FunnelLabel/FunnelLabel.js
> +          </Text>
on visual: https://github.com/wix/wix-style-react/blob/funnel-chart-component/src/FunnelChart/test/FunnelChart.visual.js#L31

2020-09-07 10:32 UTC, shlomitc commented on src/FunnelChart/FunnelLabel/FunnelLabel.js
> +          </Text>
is this also showing the `-`?

2020-09-07 10:32 UTC, shlomitc commented on src/FunnelChart/UnitsText/UnitsText.js
> +import { Text } from '../../index';
fix the import

2020-09-07 11:02 UTC, MayaHamo commented on src/FunnelChart/FunnelBadge/FunnelBadge.js
> +        tabIndex="0"
I'm migrating now to `<Focusable/>`, but it doesn't make tabIndex redundant, it's only provide css class and props, right?

2020-09-07 11:10 UTC, MayaHamo commented on src/FunnelChart/FunnelLabel/FunnelLabel.js
> +          </Text>
yes

2020-09-07 11:59 UTC, shlomitc commented on src/FunnelChart/FunnelBadge/FunnelBadge.js
> +        tabIndex="0"
you're probably right

2020-09-07 13:31 UTC, MayaHamo commented
@shlomitc I did not reply to `UnitsText` comments cause I've deleted it

2020-09-07 13:31 UTC, MayaHamo commented on src/FunnelChart/FunnelLabel/FunnelLabel.js
> +      <div>
I refactored this component

2020-09-07 13:32 UTC, MayaHamo commented on src/FunnelChart/FunnelLabel/FunnelLabel.st.css
> +.funnelLabel {
done

2020-09-07 13:32 UTC, MayaHamo commented on src/FunnelChart/utils/numberFormatters.js
> +};
sure, I'll add tests

2020-09-08 10:52 UTC, MayaHamo commented on src/FunnelChart/utils/numberFormatters.js
> +};
https://github.com/wix/wix-style-react/pull/5904/commits/2a20075a0a3b9ebe57ac09f8b73a083f9d611294

2020-09-10 19:24 UTC, EgoziE requested changes
Please take the time to write some documentation and comments in places with complicated logic.

2020-09-10 19:24 UTC, EgoziE commented on src/FunnelChart/FunnelBadge/index.d.ts
> +  onTooltipShow?: Function,
Please add a specific signature to this function

2020-09-10 19:24 UTC, EgoziE commented on src/FunnelChart/test/FunnelChart.tsx
> +      data={data}
missing all props

2020-09-10 19:24 UTC, EgoziE commented on src/FunnelChart/docs/index.story.js
> +            text: 'A simple example with compact preview',
Please change title and description to be more informative.

2020-09-10 19:24 UTC, EgoziE commented on src/FunnelChart/docs/index.story.js
> +          code({
change "code" to "example" (like the previous example)

2020-09-10 19:24 UTC, EgoziE commented on src/FunnelChart/FunnelLabel/FunnelLabel.js
> +      </div>
No need to wrap Text in another div, if you want the text to be block and not inline, use the `tagName` prop

2020-09-10 19:25 UTC, MayaHamo commented on src/FunnelChart/FunnelLabel/FunnelLabel.js
> +      </div>
yes I know, 
it didn't work for some reason

2020-09-13 08:29 UTC, MayaHamo commented on src/FunnelChart/FunnelBadge/FunnelBadge.js
> +        <span className={st(classes.badgeContent)}>
it's a copied implementation (same as all components on this PR :) ).

2020-09-13 08:29 UTC, MayaHamo commented on src/FunnelChart/FunnelBadge/FunnelBadge.st.css
> +  cursor: pointer;
https://github.com/wix/wix-style-react/pull/5904#discussion_r487499454

I'll remove it.

2020-09-13 10:28 UTC, MayaHamo commented on src/FunnelChart/test/FunnelChart.tsx
> +      data={data}
with its default value?

2020-09-13 10:41 UTC, EgoziE commented on src/FunnelChart/test/FunnelChart.tsx
> +      data={data}
For all components, boolean props default value is false
In type tests just add the prop without any value (which means it will be true)

2020-09-13 10:59 UTC, shlomitc requested changes
some strange behavior when dropping value to 0. the difference from 0 to a non-0 value is not displaying an incline.
![image](https://user-images.githubusercontent.com/6093192/93016302-e3a92980-f5c8-11ea-8ea6-e2b08f9c9c36.png).

also, when both values are the same value, the difference shows 100%, but is that true? should that should be 0?
![image](https://user-images.githubusercontent.com/6093192/93016349-2f5bd300-f5c9-11ea-8ba3-bf7de35a6ddf.png)

and the last one - shouldn't it be 10% difference?
![image](https://user-images.githubusercontent.com/6093192/93016370-50bcbf00-f5c9-11ea-9d39-13d444bd9ce1.png)

2020-09-13 10:59 UTC, shlomitc commented on src/FunnelChart/FunnelChart.st.css
> +    transform: translate(calc(-50% - 12px), calc(-100% - 6px)) !important;
are you sure the `!important` here is needed?

2020-09-13 11:12 UTC, shlomitc commented on src/FunnelChart/FunnelLabel/FunnelLabel.js
> +      <Text dataHook={dataHooks.labelText} size="small" secondary ellipsis>
in case `label` is missing, you can simply remove the `Text` component. this will make sure that if all labels are missing it will not take the extra height

2020-09-13 11:48 UTC, MayaHamo commented on src/FunnelChart/FunnelLabel/FunnelLabel.js
> +      <Text dataHook={dataHooks.labelText} size="small" secondary ellipsis>
`label` is required, `value` is not, 
do we want to change it?

2020-09-13 11:53 UTC, shlomitc commented on src/FunnelChart/FunnelLabel/FunnelLabel.js
> +      <Text dataHook={dataHooks.labelText} size="small" secondary ellipsis>
I didn't see this requirement in the specs, so if it's not mentioned in any way, simply ignore this comment

2020-09-13 12:20 UTC, MayaHamo commented on src/FunnelChart/FunnelLabel/FunnelLabel.js
> +      <Text dataHook={dataHooks.labelText} size="small" secondary ellipsis>
I can add it, but I'm sure what is the meaning of FunnelChart without labels

2020-09-13 12:20 UTC, MayaHamo commented on src/FunnelChart/FunnelChart.st.css
> +    transform: translate(calc(-50% - 12px), calc(-100% - 6px)) !important;
removed it

2020-09-13 12:20 UTC, MayaHamo commented on src/FunnelChart/FunnelChart.js
> +  const renderFunnelBadge = (currItem, nextItem, badgeTopPosition) => {
extracted

2020-09-13 15:35 UTC, shlomitc commented on src/FunnelChart/FunnelLabel/FunnelLabel.js
> +      <Text dataHook={dataHooks.labelText} size="small" secondary ellipsis>
you're probably right, we can resolve this

2020-09-14 07:25 UTC, shlomitc approved these changes
Approved from dev perspective
UX review will be done by @ayeletr

2020-09-14 11:14 UTC, ayeletr reviewed
Hi, I think it looks good. my only comment is that "PercentageDifference" is very specific and if possible I'd change it to just "Difference" all over.

2020-09-14 11:25 UTC, MayaHamo commented
@ayeletr do you mean only change the naming? cause we can change it from "PercentageDifference" to "Difference" but the difference will still be in percentage.

2020-09-14 19:50 UTC, merged

2020-09-14 19:50 UTC, ayeletr commented
Yes

2020-09-15 10:39 UTC, MayaHamo commented
Cool, I saw that @shlomitc  renamed it :)