<MarketingPageLayout/> - new component
wix/wix-style-react pull request #5909
Opened 2020-08-31 12:33 UTC by sivanharel

### 🔦 Summary

...

### ✅ Checklist

- [ ] 👨‍💻 API change is approved by the UI Infra Developers 
- [ ] 👨‍🎨 UX change is approved by the Design System UX 
- 📚 Change is documented
  - [ ] Story
  - [ ] API description
  - [ ] Cheatsheet
  - [ ] Other (explain)
- 🔬 Change is tested
  - [ ] Component
  - [ ] Visual test

2020-08-31 12:41 UTC, WixBuildServer commented
### 🤖 Hi, I'm #Janet!

  A deploy preview of your PR was successfully released 🖼.

  You can find it under one of the following URLs:
  * https://www.wix.com/pages/wix-style-react.pr_5909/

2020-09-01 13:34 UTC, sivanharel commented
@milkyfruit-
I have just finished the development, I made all the changes that were needed according to our conversation.
The only thing I should do is to update the storybook examples. I will do it when you will sent it to me.
Please make a UX review when you have time.

2020-09-03 09:58 UTC, EgoziE approved these changes

2020-09-03 09:58 UTC, EgoziE commented on src/MarketingPageLayout/test/MarketingPageLayout.spec.js
> +  });
```suggestion
  afterEach(cleanup);
```

2020-09-03 11:06 UTC, sivanharel commented on src/MarketingPageLayout/MarketingPageLayout.st.css
> +}
lol.. I use to define padding according to the size prop:
.footerContainer {
}

.root:size(medium) .footerContainer {
  padding: 0 value(spacing48);
}

.root:size(large) .footerContainer {
  padding: 0 value(spacing90);
}

2020-09-03 22:29 UTC, milkyfruit requested changes
Hi, @sivan, I went over the PR and wrote down the update story examples and minor fixes.

**Component Fixes**
- [x] missing divider above the footer
- [ ] Size prop should be split into two props – VerticalPadding and HorizontalPadding

**Side Task**
This probably needs a new jira task:
- [ ] `<Text><ul><li>` should have 6px margins between items.
- [ ] `<Text size="small"><ul><li>` should have 9px margins between items. 

### Examples

- [x] **Description**
MarketingPageLayout is a container capable of displaying a brief introduction about a product and its key features. Use it to promote new products that site owners are unaware of.

- [x] **Structure**
Component includes the following sections: a content, an image and a footer. Use content area to add text descriptions, image area to show a preview of promoted product, footer area to emphasize key features or user testimonials.

-  [ ] **Size**
_Let's discuss first if size prop will be split into two, then the text can be adjusted_

Component supports 2 sizes – medium and large. They should be used together with the breakpoints. Size medium should be used for screen sizes that are 1463 by 629 and smaller. Size large should be used for screen sizes that are 1464 by 630 pixels and larger.

medium size:
```
<MarketingPageLayout
  size="medium"
  content={
    <MarketingPageLayoutContent
      size="medium"
      overline="Medium overline"
      title="Medium title"
      content={
        <Text size="small">
          <ul>
            <li>Medium content item one</li>
            <li>Medium content item two</li>
            <li>Medium content item three</li>
          </ul>
        </Text>
      }
      actions={<Button size="medium">Medium Action</Button>}
    />
  }
  image={<Image />}
/>;
```

large size:
```
<MarketingPageLayout
  size="large"
  content={
    <MarketingPageLayoutContent
      size="large"
      overline="Large overline"
      title="Large title"
      content={
        <Text size="medium">
          <ul>
            <li>Large content item one</li>
            <li>Large content item two</li>
            <li>Large content item three</li>
          </ul>
        </Text>
      }
      actions={<Button size="large">Large Action</Button>}
    />
  }
  image={<Image />}
/>;
```

- [x] **Footer with Feature List**
Component lets to insert additional information to the footer. Use FeatureList to display top features that need additional descriptions and visual emphasis.

```
<MarketingPageLayout
  content={
    <MarketingPageLayoutContent
      title="Upgrade Your Site with a Premium Plan"
      content="Wix gives you everything you need for a stunning website. Upgrade your site to Premium and get even more."
      actions={<Button skin="premium" size="large">Upgrade Your Site</Button>}
    />
  }
  image={<Image />}
  footer={
    <FeatureList
      features={[
        {
          id: '0001',
          image: <Image width={60} height={60} />,
          title: 'Remove Wix Ads',
          text:
            "Enjoy a website that's completely your own brand by removing Wix ads.",
        },
        {
          id: '0002',
          image: <Image width={60} height={60} />,
          title: 'Connect a Custom Domain',
          text: 'Get your business found with a custom domain.',
        },
        {
          id: '0003',
          image: <Image width={60} height={60} />,
          title: 'Accept Online Payment',
          text: 'Let your customers and clients pay you online at checkout.',
        },
      ]}
    />
  }
/>;
```

- [x] **Footer With Testimonial List**
Use TestimonialList in the footer to show real user feedback, so site owners can learn how others users see the promoted product.
```
<MarketingPageLayout
  content={
    <MarketingPageLayoutContent
      title="Reach the Right Shoppers on Facebook & Instagram"
      subtitle="Get set up and Wix’s AI will take care of the rest"
      content={
        <Text>
          <ul>
            <li>Show your ad to the people most likely to buy</li>
            <li>Test your ad non-stop to see what’s working </li>
            <li>Optimize your budget to get you the best results </li>
          </ul>
        </Text>
      }
      actions={<Button size="large">Start Now</Button>}
    />
  }
  image={<Image />}
  footer={
    <TestimonialList
      testimonials={[
        {
          id: '0001',
          avatar: <Avatar name="Guy in glasses" size="size60" />,
          text: 'I love it! It helped me to increase the sales.',
          authorName: 'John Smith',
        },
        {
          id: '0002',
          avatar: <Avatar name="Person with a hat" size="size60" />,
          text: 'Amazing! It is simple to use, I had no struggle to setup.',
          authorName: 'Templeton Peck',
        },
        {
          id: '0003',
          avatar: <Avatar name="Smiling lady" size="size60" />,
          text: 'A perfect tool for creating ad campaigns that sell.',
          authorName: 'Bosco B.A.',
        },
      ]}
    />
  }
/>;
```

2020-09-06 08:03 UTC, sivanharel commented
@milkyfruit - Hi Domas, I made all the changes that you asked besides the splitting of the size prop.
It is not clear what did you mean when writing: "Size prop should be split into two props – VerticalPadding and HorizontalPadding".

As you said at our last meeting the padding is added to the content and to the image sections but can be removed only from the image so we decided to change the naming of the props: "sidePadding" ==> "ImageHorizontalPadding" , "verticalPadding" ==> "ImageVerticalPadding".

In addition, we said that the padding values are changed according to the size prop:
medium size ==> the vertical padding (top and bottom) is 30px, the horizontal padding (right and left) is 48px
large size ==> the vertical padding (top and bottom) is 48px, the horizontal padding (right and left) is 90px

Regarding the side tasks can you please open Jira tasks for them?

The Partners team is waiting for this component so let's discuss about "the size prop" and push to merge it.

2020-09-06 12:07 UTC, milkyfruit commented
@sivanharel in order not to block Partners Team, let's launch without `size` prop at all for now.
Paddings should be controlled separately:
- top and bottom: medium: 30, large: 48 
- left and right: medium: 48, large: 90

2020-09-06 15:31 UTC, sivanharel commented
@milkyfruit - ok fine I can remove the size prop but if I will do it how will the padding be controlled? 
We have to define if it's medium or large in order to know how much space to declare. So we need a prop for it...

2020-09-07 09:36 UTC, milkyfruit approved these changes
@sivanharel the changes look good, I think it can be merged.

2020-09-07 10:49 UTC, shlomitc approved these changes
great, really minor stuff

2020-09-07 10:49 UTC, shlomitc commented on stories/symbolsComponentsMapping/symbols.js
> +  marketingPageLayout: '2.1f Marketing Page',
is the `f` in "2.1f" intentional?

2020-09-07 10:49 UTC, shlomitc commented on src/MarketingPageLayout/MarketingPageLayout.st.css
> +}
extra `;`

2020-09-07 11:02 UTC, sivanharel commented on stories/symbolsComponentsMapping/symbols.js
> +  marketingPageLayout: '2.1f Marketing Page',
As I understood yes (it's also written in the spec) but I will verify it with Domas again.

2020-09-07 11:05 UTC, milkyfruit commented on stories/symbolsComponentsMapping/symbols.js
> +  marketingPageLayout: '2.1f Marketing Page',
yes, in UX Story it's indexed as part of 2.1 Page story as one of the layouts:
![image](https://user-images.githubusercontent.com/1684587/92381284-368b6880-f113-11ea-857b-2d38cae10a0b.png)

2020-09-07 11:20 UTC, merged