`<TableActionCell />` - small actions
wix/wix-style-react pull request #5911
Opened 2020-09-01 11:48 UTC by frontned

### 🔦 Summary

Hey, it would be nice if we could control the action sizes of `<TableActionCell />`. Also we require it in our new functionality:
https://app.zeplin.io/project/5d384bf711d0c52e94d0667c/screen/5f3e0b90381141143e03b31f

### ✅ Checklist

- [ ] 👨‍💻 API change is approved by the UI Infra Developers
- [ ] 👨‍🎨 UX change is approved by the Design System UX
- 📚 Change is documented
  - [x] Story
  - [x] API description
- 🔬 Change is tested
  - [ ] Component
  - [x] Visual test

2020-09-01 11:59 UTC, WixBuildServer commented
### 🤖 Hi, I'm #Janet!

  A deploy preview of your PR was successfully released 🖼.

  You can find it under one of the following URLs:
  * https://www.wix.com/pages/wix-style-react.pr_5911/

2020-09-13 11:17 UTC, EgoziE requested changes

2020-09-13 11:17 UTC, EgoziE commented on src/TableActionCell/TableActionCell.js
> +  popoverMenuButtonSize: PropTypes.oneOf(['small', 'medium']),
Is it really needed to separate between an overall "size" prop and the specific popover "popoverMenuButtonSize"?

I think it's better to have a single global size prop that will make everything the same size.

2020-09-13 11:17 UTC, EgoziE commented on src/TableActionCell/TableActionCell.js
> +          size={size || 'medium'}
In all places you use `size={size || 'medium'}` just use the size and set 'medium' under TableActionCell.defaultProps

2020-09-15 12:55 UTC, milkyfruit requested changes
The prop looks great, only the example should be updated — small buttons should use small icons.

2020-09-15 12:55 UTC, milkyfruit commented on src/TableActionCell/docs/examples/SmallButtonsExample.js
> +          icon: <Star />,
Small buttons should use small icons. This one should be `<StarSmall />`

2020-09-15 12:55 UTC, milkyfruit commented on src/TableActionCell/docs/examples/SmallButtonsExample.js
> +          icon: <Download />,
DownloadImportSmall

2020-09-15 12:55 UTC, milkyfruit commented on src/TableActionCell/docs/examples/SmallButtonsExample.js
> +          icon: <Duplicate />,
DuplicateSmall

2020-09-15 12:55 UTC, milkyfruit commented on src/TableActionCell/docs/examples/SmallButtonsExample.js
> +          icon: <Print />,
PrintSmall

2020-09-15 13:20 UTC, frontned commented on src/TableActionCell/docs/examples/SmallButtonsExample.js
> +          icon: <Star />,
There is not `<StarSmall />` in icons

2020-09-22 10:48 UTC, merged