Testkit updating documentation
wix/wix-style-react pull request #5913
Opened 2020-09-01 15:26 UTC by sivanharel

### 🔦 Summary

Improving the existing testkit descriptions by the new standard.

Components:

- <SidebarDivider/>

- <StarsRatingBar/>

- <SocialButton/>

### ✅ Checklist

- [ ] 👨‍💻 API change is approved by the UI Infra Developers 
- [ ] 👨‍🎨 UX change is approved by the Design System UX 
- 📚 Change is documented
  - [ ] Story
  - [ ] API description
  - [ ] Cheatsheet
  - [ ] Other (explain)
- 🔬 Change is tested
  - [ ] Component
  - [ ] Visual test

2020-09-01 15:34 UTC, WixBuildServer commented
### 🤖 Hi, I'm #Janet!

  A deploy preview of your PR was successfully released 🖼.

  You can find it under one of the following URLs:
  * https://www.wix.com/pages/wix-style-react.pr_5913/

2020-09-02 06:52 UTC, EgoziE requested changes
🥳

2020-09-02 06:52 UTC, EgoziE commented on src/FeatureList/FeatureList.uni.driver.js
> +     * @param featureIndex - the index of the feature in the features array (starts from 0)
@param should have a type
for example

@param {string} name
@param {number} age

2020-09-02 11:50 UTC, EgoziE approved these changes

2020-09-02 11:50 UTC, merged