<TextButton/> - add ellipsis prop
wix/wix-style-react pull request #5945
Opened 2020-09-08 14:09 UTC by gendeld

### 🔦 Summary

...

### ✅ Checklist

- [ ] 👨‍💻 API change is approved by the UI Infra Developers 
- [ ] 👨‍🎨 UX change is approved by the Design System UX 
- 📚 Change is documented
  - [ ] Story
  - [ ] API description
  - [ ] Cheatsheet
  - [ ] Other (explain)
- 🔬 Change is tested
  - [ ] Component
  - [ ] Visual test

2020-09-08 14:17 UTC, WixBuildServer commented
### 🤖 Hi, I'm #Janet!

  A deploy preview of your PR was successfully released 🖼.

  You can find it under one of the following URLs:
  * https://www.wix.com/pages/wix-style-react.pr_5945/

2020-09-08 16:58 UTC, shlomitc requested changes

2020-09-08 16:58 UTC, shlomitc commented on src/TextButton/TextButton.js
> +          { skin, underline, weight, size, fluid, ellipsis },
not sure this state is needed

2020-09-08 16:58 UTC, shlomitc commented on src/TextButton/TextButton.st.css
> +  -st-states: skin(string), underline(string), weight(string), size(string), fluid, ellipsis;
not sure this state is needed

2020-09-08 16:58 UTC, shlomitc commented on src/TextButton/docs/examples.js
> +  <TextButton fluid ellipsis>
if both fluid and ellipsis are needed, then you can decide that once the `ellipsis` prop is on, it can simply apply the `fluid` styles as well

2020-09-14 20:07 UTC, shlomitc approved these changes
awesomeness. Please fix also this example according to the new behavior - https://github.com/wix/wix-style-react/blob/master/src/DropdownBase/docs/examples.js#L242-L271

2020-09-17 07:08 UTC, merged