<PopoverMenu.MenuItem/> <ListItemAction/> - add subtitle property
wix/wix-style-react pull request #5960
Opened 2020-09-10 14:13 UTC by elad-barack

#5687 # 🔦 Summary

Added a "subtitle" option for a PopoverMenu.MenuItem & ListItemAction(The "PopoverMenu.MenuItem" component is using it, so had to add the support to ListItemAction first)

### ✅ Checklist

- [ ] 👨‍💻 API change is approved by the UI Infra Developers 
- [x] 👨‍🎨 UX change is approved by the Design System UX @ayeletr 
- 📚 Change is documented
  - [x] Story
  - [x] API description
  - [x] Cheatsheet
  - [x] Other (explain) - ListIconAction/README.md , PopoverMenu/compound.md
- 🔬 Change is tested
  - [x] Component
  - [x] Visual test

2020-09-10 19:30 UTC, EgoziE commented
Hey @elad-barack 
Who did you contact with from our team about this change?
Was this change approved by someone from our UX?

2020-09-11 08:05 UTC, elad-barack commented
Hi, I did aproove the design (of the feature, not the PR yet) with @ayeletr and Yael Raz. Didn't speak to someone from the dev team yet. Can we do it on Sunday?

2020-09-13 12:21 UTC, EgoziE requested changes

2020-09-13 12:21 UTC, EgoziE commented on src/PopoverMenu/PopoverMenu.js
> +          subtitle: child.props.subtitle,
Please add it to PopoverMenuItemProps in the relevant d.ts file and type test (tsx file)

2020-09-13 13:29 UTC, elad-barack commented on src/PopoverMenu/PopoverMenu.js
> +          subtitle: child.props.subtitle,
Done

2020-09-14 07:53 UTC, EgoziE approved these changes
Looks good, is it still waiting for UX review?

2020-09-14 08:02 UTC, elad-barack commented
@EgoziE Yes, accidentally asked you to approve. But It's always better to get one step closer :)

2020-09-14 12:03 UTC, ayeletr commented
Hi, @elad-barack 
small comments:

**1.** on this example:
![image](https://user-images.githubusercontent.com/34542112/93081702-56350a80-f698-11ea-88da-030695f62733.png)
please add icons to each line. I don't want to show unreal examples.

**2.** When the content is very long and there's ellipsis, there's no padding on the right side. need to have 24px padding there.
![image](https://user-images.githubusercontent.com/34542112/93083262-03108700-f69b-11ea-98a4-2ee0d6877787.png)
(I see it also happen for the title, maybe it something that was exist)

Thanks!

2020-09-16 11:52 UTC, merged