<ColorPicker/> - refactor story page
wix/wix-style-react pull request #5965
Opened 2020-09-13 08:37 UTC by tatiPodolskaya

### 🔦 Summary

...

### ✅ Checklist

- [ ] 👨‍💻 API change is approved by the UI Infra Developers 
- [ ] 👨‍🎨 UX change is approved by the Design System UX 
- 📚 Change is documented
  - [ ] Story
  - [ ] API description
  - [ ] Cheatsheet
  - [ ] Other (explain)
- 🔬 Change is tested
  - [ ] Component
  - [ ] Visual test

2020-09-14 07:51 UTC, WixBuildServer commented
### 🤖 Hi, I'm #Janet!

  A deploy preview of your PR was successfully released 🖼.

  You can find it under one of the following URLs:
  * https://www.wix.com/pages/wix-style-react.pr_5965/

2020-09-14 11:36 UTC, sivanharel reviewed
Great job!
There are some comments here.
Let's talk with Asaf Zinger about the examples.

2020-09-14 11:36 UTC, sivanharel commented on src/ColorPicker/docs/index.story.js
> +            title: 'Simple usage',
Please change the first letter of each word to be a capital letter.
'Simple usage' ==> 'Simple Usage'

2020-09-14 11:36 UTC, sivanharel commented on src/ColorPicker/docs/index.story.js
> +              'Previous selected color and current one can be shown below the picker area.',
I think that this could be a better description but let's talk with Assaf Zinger.
"Whether to display the previously selected color. Used for comparing the current and previous selected colors."

2020-09-14 11:36 UTC, sivanharel commented on src/ColorPicker/docs/index.story.js
> +    onAdd: value => value,
Since the "onAdd" is not a required prop it shouldn't be here.
You can keep it in the example prop.

2020-09-14 11:36 UTC, sivanharel commented on src/ColorPicker/docs/index.story.js
> +    addTooltipContent: 'Add your color',
It should be an array of objects with label and value properties: {label:"", value: ""}
So in this case it should be:

addTooltipContent: [
      {
        label: 'With add tooltip content',
        value: 'Add your color',
      },
    ],

2020-09-14 11:36 UTC, sivanharel commented on src/ColorPicker/docs/index.story.js
> +    value: 'lightblue',
Same as I wrote on below on "addTooltipContent".
The playground is broken as a result of the syntax error here.
You should change it to the correct form :)
It could be: 
value: [{label: 'Example Value', value: 'lightblue'}],

2020-09-14 12:26 UTC, sivanharel requested changes
Great job!
There are some comments here.
Let's talk with Asaf Zinger about the examples.

2020-09-15 14:02 UTC, sivanharel commented on src/ColorPicker/docs/examples.js
> +    previous: '#34b7eb',
Since the component gets only the current value (in the value prop) and in the initial state it sets the previous color to be the current I would say that it is confusing to write here 2 different values.
I suggest setting both of them to the same color also in your state.

2020-09-15 14:13 UTC, sivanharel approved these changes

2020-09-16 10:40 UTC, merged