<EmptyState/> - refactor story page
wix/wix-style-react pull request #5979
Opened 2020-09-15 07:09 UTC by tatiPodolskaya

### 🔦 Summary

...

### ✅ Checklist

- [ ] 👨‍💻 API change is approved by the UI Infra Developers 
- [ ] 👨‍🎨 UX change is approved by the Design System UX 
- 📚 Change is documented
  - [ ] Story
  - [ ] API description
  - [ ] Cheatsheet
  - [ ] Other (explain)
- 🔬 Change is tested
  - [ ] Component
  - [ ] Visual test

2020-09-15 07:18 UTC, WixBuildServer commented
### 🤖 Hi, I'm #Janet!

  A deploy preview of your PR was successfully released 🖼.

  You can find it under one of the following URLs:
  * https://www.wix.com/pages/wix-style-react.pr_5979/

2020-09-15 07:25 UTC, sivanharel commented on src/EmptyState/docs/index.story.js
> +            text: `Component can have title, subtitle and image (image URL or a node to render).`,
The EmptyState has a title, subtitle, and image (image URL or a node to render). All of these props are optional.

2020-09-15 07:33 UTC, sivanharel commented on src/EmptyState/docs/examples.js
> +                <RadioGroup value={this.state.theme} onChange={(theme) => this.setState({theme})} display={'horizontal'} align={'center'}>
It's a very nice idea to add a radio button with all the options but usually, we display all of them one after the other in order to see the differences more easily.
Use <Layout> and <Cell> in order to achive it.

<Layout>
     <Cell> option 1 </Cell>
     <Cell> option 2 </Cell>
     <Cell> option 3 </Cell>
</Layout>

2020-09-15 07:35 UTC, sivanharel commented on src/EmptyState/docs/examples.js
> +                    <RadioGroup value={this.state.align} onChange={(align) => this.setState({align})} display={'horizontal'} align={'center'}>
Change this as well:)

2020-09-15 07:40 UTC, sivanharel reviewed
You did an awesome work!!

2020-09-15 07:40 UTC, sivanharel commented on src/EmptyState/docs/examples.js
> +                <RadioGroup value={this.state.theme} onChange={(theme) => this.setState({theme})} display={'horizontal'} align={'center'}>
You can take a look at the StarsRatingBar component for reference

2020-09-15 09:23 UTC, sivanharel requested changes
Great
It looks better with the "code()" examples.
There is only a very small comment

2020-09-15 09:23 UTC, sivanharel commented on src/EmptyState/docs/index.story.js
> +const code = config => baseCode({ components: allComponents, ...config });
This should be right below the 
`const example = config => baseExample({ components: allComponents, ...config });`
And if you don't use the example variable you could delete it.

2020-09-15 09:23 UTC, sivanharel commented on src/EmptyState/docs/index.story.js
> +          importExample("import { EpmtyState } from 'wix-style-react';"),
You don't need to pass any value here, it generates it automatically.
keep it like this `importExample()`

2020-09-15 14:04 UTC, sivanharel approved these changes

2020-09-16 10:33 UTC, sivanharel commented on src/EmptyState/docs/index.story.js
> +    ],
It will be even nicer to add another option called "Without Title".
It will empsize that this is optional :)
title: [{ label: 'With Title', value: 'You don't have any items yet' }, {label: 'Without Title', value: ''}],
(Same in the Subtitle examples)

2020-09-16 10:33 UTC, sivanharel commented on src/EmptyState/docs/index.story.js
> +    title: [{ label: 'Title', value: `You don't have any items yet` }],
In the value, you could change the ` to '

2020-09-16 10:48 UTC, sivanharel approved these changes

2020-09-16 12:04 UTC, merged