<Collapse /> - refactor story page
wix/wix-style-react pull request #5984
Opened 2020-09-15 11:00 UTC by tatiPodolskaya

### 🔦 Summary

...

### ✅ Checklist

- [ ] 👨‍💻 API change is approved by the UI Infra Developers 
- [ ] 👨‍🎨 UX change is approved by the Design System UX 
- 📚 Change is documented
  - [ ] Story
  - [ ] API description
  - [ ] Cheatsheet
  - [ ] Other (explain)
- 🔬 Change is tested
  - [ ] Component
  - [ ] Visual test

2020-09-15 11:08 UTC, WixBuildServer commented
### 🤖 Hi, I'm #Janet!

  A deploy preview of your PR was successfully released 🖼.

  You can find it under one of the following URLs:
  * https://www.wix.com/pages/wix-style-react.pr_5984/

2020-09-15 13:50 UTC, sivanharel requested changes
Looks good.
Just change the div in your example for some component from the library.

2020-09-15 13:50 UTC, sivanharel commented on src/Collapse/docs/examples.js
> +                    <div style={contentStyle}>
Put here a component from the library instead of this div. Could be RadioGroup that wrap RadioButton or an Input wrapped with a FormField like in the playground example.

2020-09-16 06:14 UTC, sivanharel approved these changes

2020-09-16 10:39 UTC, merged