<DropdownLayout /> - refactor story page
wix/wix-style-react pull request #5999
Opened 2020-09-17 11:28 UTC by tatiPodolskaya

### 🔦 Summary

...

### ✅ Checklist

- [ ] 👨‍💻 API change is approved by the UI Infra Developers 
- [ ] 👨‍🎨 UX change is approved by the Design System UX 
- 📚 Change is documented
  - [ ] Story
  - [ ] API description
  - [ ] Cheatsheet
  - [ ] Other (explain)
- 🔬 Change is tested
  - [ ] Component
  - [ ] Visual test

2020-09-17 11:37 UTC, WixBuildServer commented
### 🤖 Hi, I'm #Janet!

  A deploy preview of your PR was successfully released 🖼.

  You can find it under one of the following URLs:
  * https://www.wix.com/pages/wix-style-react.pr_5999/

2020-09-17 13:32 UTC, sivanharel requested changes
Very good work!!!!
I will review the code that related to the playground after you will finish the development :)

2020-09-17 13:32 UTC, sivanharel commented on src/DropdownLayout/docs/index.story.js
> +const optionsExampleBuilder = num =>
No need for all this calculation If you only use it once. You could save a simple const with explicit values.

2020-09-17 13:32 UTC, sivanharel commented on src/DropdownLayout/docs/examples.js
> +            { id: 'fith option', value: 'title #5' },
You have here a small typo
fith ==> fifth

2020-09-17 13:32 UTC, sivanharel commented on src/DropdownLayout/docs/examples.js
> +    fixedHeader={
Use our Box component instead of a div:

`<Box
      backgroundColor="lightgreen"
      height="40px"
      align="center"
      verticalAlign="middle"
    >
      <Text>Custom header</Text>
    </Box>`

2020-09-17 13:32 UTC, sivanharel commented on src/DropdownLayout/docs/examples.js
> +        <div style={{backgroundColor: 'lightblue', height: '40px', display: 'flex', alignItems: 'center', justifyContent: 'center'}}>
Change it also to using Box and Text components

2020-09-17 13:38 UTC, sivanharel commented on src/DropdownLayout/docs/index.story.js
> +// const optionsExampleBuilder = num =>
remove this comment

2020-09-22 09:32 UTC, TalZa1810 commented
Adding it to the cheatsheet in a different PR: https://github.com/wix/wix-style-react/pull/6012

2020-09-22 13:04 UTC, TalZa1810 commented on src/DropdownLayout/DropdownLayout.st.css
> -  content_container_height: 260px;
not used within the stylesheet

2020-09-22 13:45 UTC, TalZa1810 commented
I haven't added the descriptions to all the uni driver functions. Let me know if I should add them.

2020-09-22 14:06 UTC, TalZa1810 commented on src/DropdownLayout/docs/examples.js
> +      overrideStyle: true,
I wasn't sure whether to add this to the example too

2020-09-22 14:18 UTC, TalZa1810 commented
Also, I wasn't sure whether to add an example of the `inContainer` prop usage. 
@milkyfruit please let me know what you think about the examples and descriptions :)

2020-09-25 10:51 UTC, milkyfruit requested changes
@TalZa1810 I edited few descriptions and tweaked some examples to match a little more real use cases. Please update the examples. 

### Changes in storybook
- [x] Please update description text style to match examples' text style.


### Changes in examples

- [x] **Description**
DropdownLayout wraps multiple options into a list. It’s used in various select components like dropdown, autocomplete or multiselect. It appears when a select component is clicked. Use it to set up and style a list of selectable dropdown options, like selecting a country or similar. Examples show available configurations for select components options. For creating dropdown like components, please refer to DropdownBase.

- [x] Simple Example -> **Structure**
Dropdown layout’s option is an object with a unique id and a value. To have a disabled option, a property of disabled: true should be added to the option object.
```
<Box height="144px">
  <DropdownLayout
    options={[
      { id: 1, value: 'Option 1' },
      { id: 2, value: 'Option 2' },
      { id: 3, value: 'Option 3' },
      { id: 4, value: 'Option 4 is disabled', disabled: true },
    ]}
    visible
  />
</Box>;
```

- [x] **Fixed Header and Footer**
Component supports adding content to fixed header and footer. Use it to add actions like “see all options”.
```
<Box height="234px">
  <DropdownLayout
    options={[
      { id: 1, value: 'Option 1' },
      { id: 2, value: 'Option 2' },
      { id: 3, value: 'Option 3' },
      { id: 4, value: 'Option 4' },
      { id: 5, value: 'Option 5' },
      { id: 6, value: 'Option 6' },
      { id: 7, value: 'Option 7' },
      { id: 8, value: 'Option 8' },
      { id: 9, value: 'Option 9' },
      { id: 10, value: 'Option 10' },
    ]}
    fixedHeader={<ListItemAction title="Fixed Header" />}
    fixedFooter={<ListItemAction title="Fixed Footer" />}
    maxHeightPixels="234px"
    visible
  />
</Box>;
```

- [x] Organized Options: Title, Divider -> **Grouped Options**
_Description remains the same_
```
<Box height="180px">
  <DropdownLayout
    options={[
      { id: 0, value: 'Group 1', title: true },
      { id: 1, value: 'Option 1' },
      { id: 3, value: 'Option 2' },
      { id: 4, value: '-' },
      { id: 5, value: 'Option 3' },
    ]}
    visible
  />
</Box>;
```
- [x] **Render Function Options**
_Description remains the same_
```
() => {
  const customBuilderFunction = id => 'builder option ' + id;

  const options = [
    { id: 1, value: customBuilderFunction(1) },
    { id: 2, value: customBuilderFunction(2) },
    {
      id: 3,
      overrideStyle: true,
      value: (
        <Box width="100%" padding="6px 0 6px 24px">
          <Text>
            builder <b>option</b> 3
          </Text>
        </Box>
      ),
    },
    listItemSelectBuilder({
      prefix: <Avatar size="size30" />,
      title: 'Builder option 4',
      subtitle: 'This option uses ListItemSelect',
    }),
  ];

  return (
    <Box height="184px">
      <DropdownLayout visible options={options} selectedId={2} />
    </Box>
  );
};
```

### Questions and Thoughts

- DropdownLayout _Maximum Height and Minimum Width_ props are different DropdownBase `maxHeight`, `maxWidth`, `minWidth` props. Can users pass these props to dropdown or multiselect component? I think we should explain how they could be used.
- DropdownLayout size property is not aligned with [ListItemSelect](https://www.wix-style-react.com/?path=/story/components-api-components--listitemselect). I think it should be aligned. Do you know if there's anyone using this prop? Until then, do we have to expose size example?
- `Title:'true'` and `value:'-'` prop styles are different from [LisItemSection](https://www.wix-style-react.com/?path=/story/components-api-components--listitemsection). They should be aligned, so I opened a [jira ticket](https://jira.wixpress.com/browse/DSM-871).

2020-10-01 13:10 UTC, milkyfruit approved these changes

2020-10-01 13:49 UTC, merged

2020-10-01 18:15 UTC, shlomitc commented on src/DropdownLayout/DropdownLayout.js
> +  /** Whether the `<DropdownLayout/>` is in a container component. If `true`, some styles such as shadows, positioning and padding will be added the the component contentContainer. */
a deprecation message should be also for this prop - it should always be true

2020-10-01 18:15 UTC, shlomitc commented on src/DropdownLayout/DropdownLayout.js
> +  /** Should show or hide the component */
this should also be deprecated, should always be true

2020-10-01 18:15 UTC, shlomitc commented on src/DropdownLayout/DropdownLayout.js
>    dropDirectionUp: PropTypes.bool,
this should also be deprecated

2020-10-01 18:15 UTC, shlomitc commented on src/DropdownLayout/DropdownLayout.js
> +  /** Callback function called whenever the user press the `Escape` keyboard.*/
this logic should be deprecated and moved to the opening unit (DropdownBase, InputWithOptions)

2020-10-01 18:15 UTC, shlomitc commented on src/DropdownLayout/DropdownLayout.js
>    closeOnSelect: PropTypes.bool,
this logic should be deprecated and moved to the opening unit (DropdownBase, InputWithOptions)

2020-10-01 18:15 UTC, shlomitc commented on src/DropdownLayout/DropdownLayout.js
> +        '<DropdownLayout/> - itemHeight prop is deprecated and will be removed in the next major release.',
what should be used instead?

2020-10-01 18:15 UTC, shlomitc commented on src/DropdownLayout/docs/index.story.js
> +              title: 'Related Components',
I'd expect that if we mention these components, we will see some usage of it in the examples. why didn't we add a section about it? @milkyfruit - what do you think?

2020-10-01 20:57 UTC, TalZa1810 commented on src/DropdownLayout/DropdownLayout.js
> +  /** Whether the `<DropdownLayout/>` is in a container component. If `true`, some styles such as shadows, positioning and padding will be added the the component contentContainer. */
The default value of this prop is `false`:
https://github.com/wix/wix-style-react/blob/master/src/DropdownLayout/DropdownLayout.js#L685

That's why I thought doing this at a different PR dedicated for this because it will affect also other components which use `DropdownLayout`.

2020-10-01 21:11 UTC, TalZa1810 commented on src/DropdownLayout/DropdownLayout.js
> +        '<DropdownLayout/> - itemHeight prop is deprecated and will be removed in the next major release.',
When I've checked `wix-private`, I saw only one usage of this prop. We thought that we should have one size (the default one) and if we want a different size, it will be the item responsibility to set its height.

2020-10-02 03:55 UTC, shlomitc commented on src/DropdownLayout/DropdownLayout.js
> +        '<DropdownLayout/> - itemHeight prop is deprecated and will be removed in the next major release.',
So this recommendation should be it