<SparklineChart/> - creating SparklineChart component
wix/wix-style-react pull request #6000
Opened 2020-09-17 12:58 UTC by ofirbedarshi

### 🔦 Summary

...

### ✅ Checklist

- [ ] 👨‍💻 API change is approved by the UI Infra Developers 
- [ ] 👨‍🎨 UX change is approved by the Design System UX 
- 📚 Change is documented
  - [ ] Story
  - [ ] API description
  - [ ] Cheatsheet
  - [ ] Other (explain)
- 🔬 Change is tested
  - [ ] Component
  - [ ] Visual test

2020-09-17 14:17 UTC, TalZa1810 commented
Hi @ofirbedarshi , can you please sign your commits:
https://github.com/wix/wix-style-react/blob/master/docs/contribution/CREATE_PR.md#sign-commits

Otherwise, the CI won't run :)

2020-09-21 06:53 UTC, ofirbedarshi commented
> Hi @ofirbedarshi , can you please sign your commits:
> https://github.com/wix/wix-style-react/blob/master/docs/contribution/CREATE_PR.md#sign-commits
> 
> Otherwise, the CI won't run :)

2020-09-21 10:00 UTC, WixBuildServer commented
### 🤖 Hi, I'm #Janet!

  A deploy preview of your PR was successfully released 🖼.

  You can find it under one of the following URLs:
  * https://preview.wix-style-react.com/pr_6000

2020-09-21 12:48 UTC, EgoziE commented
Is this a valid case?

![image](https://user-images.githubusercontent.com/35173937/93768294-dd96f680-fc21-11ea-8637-5e00779aebc6.png)

2020-09-21 12:58 UTC, EgoziE requested changes

2020-09-21 12:58 UTC, EgoziE commented on src/SparklineChart/SparklineChart.st.css
> +}
Not used anywhere

2020-09-21 12:58 UTC, EgoziE commented on src/SparklineChart/ChartTooltip.st.css
> +}
Not used anywhere

2020-09-21 12:58 UTC, EgoziE commented on src/SparklineChart/ChartTooltip.js
> +export const ChartTooltip = props => {
In order for this Popover to look like our Tooltip, you should use the Text component internally.
Our Text component already implement all the relevant typography definitions.

1. Remove `style={{ fontSize: 0 }}` and all other styling
2. Use Text component inside Popover.Content
3. Take a look at our Zeplin to mimic the exact style of our Tooltip (margins/paddings etc.)

2020-09-21 12:58 UTC, EgoziE commented on src/SparklineChart/docs/index.story.js
> +          }),
This example can be merged with the first one with a nice description

2020-09-21 12:58 UTC, EgoziE commented on src/SparklineChart/docs/index.story.js
> +            text: 'Simple sparkline chart component.',
This line should describe what this component is all about.
For example something like:
"A sparkline chart represent trends in a series of values as a line with an area"

If needed please ask for help from UX with this description.

2020-09-21 12:58 UTC, EgoziE commented on src/SparklineChart/test/SparklineChart.tsx
> +// }
Don't forget

2020-09-21 12:58 UTC, EgoziE commented on src/SparklineChart/SparklineChart.js
> +import * as d3 from 'd3';
This will not work well with tree shaking.
You need to import only the relevant functions you require.

2020-09-21 12:58 UTC, EgoziE commented on src/SparklineChart/SparklineChart.js
> +  data: PropTypes.arrayOf(
data should be required

2020-09-21 12:58 UTC, EgoziE commented on src/SparklineChart/SparklineChart.js
> +    const minMax = getDatasetMax([adaptedDataSet]);
Can be simply replaced by 

```suggestion
    const max = d3.max(adaptedDataSet, d => d.value);
    const min = d3.min(adaptedDataSet, d => d.value);
```

the utility can be removed as well.

2020-09-21 12:58 UTC, EgoziE commented on src/SparklineChart/SparklineChart.js
> +    const dataContainer = container.select(classSelector('dataContainer'));
This is not good, classes will be minified and the element won't be found.
Use stylable classes directly

2020-09-22 11:09 UTC, ofirbedarshi commented on src/SparklineChart/ChartTooltip.js
> +export const ChartTooltip = props => {
For bullet 3: I styled it exactly like the sparkline UX guidelines. If It needs to be changed, I believe it must go thru the UX first. I'll talk with our UX to check if the design is matches

2020-09-24 13:10 UTC, EgoziE requested changes

2020-09-24 13:10 UTC, EgoziE commented on src/SparklineChart/SparklineChart.js
> +      .duration(300)
let's make it a constant

2020-09-29 07:43 UTC, ofirbedarshi commented on src/SparklineChart/SparklineChart.js
> +    );
This is for supporting multiple tooltips on the same line, but it doesnt relevant anymore, I'll remove it

2020-09-29 07:43 UTC, ofirbedarshi commented on src/SparklineChart/SparklineChart.js
> +      .duration(300)
the duration?

2020-09-29 07:45 UTC, EgoziE commented on src/SparklineChart/SparklineChart.js
> +      .duration(300)
yes

2020-09-29 08:35 UTC, ofirbedarshi commented on src/SparklineChart/SparklineChart.st.css
> +.dataContainer{}
This file must be kept even if its empty for configurations or something? Or can I delete it?

2020-10-11 07:30 UTC, EgoziE approved these changes

2020-10-11 07:30 UTC, merged