VariableInput: add readOnly prop
wix/wix-style-react pull request #6005
Opened 2020-09-21 10:04 UTC by splintor

### 🔦 Summary
Add `readOnly` prop to `<VariableInput>`, similar to what we have for `<Input>` ([Slack discussion](https://wix.slack.com/archives/C39FTGUBZ/p1600670672020700)).

### ✅ Checklist

- [X] 👨‍💻 API change is approved by the UI Infra Developers (@EgoziE)
- [X] 👨‍🎨 UX change is approved by the Design System UX (@milkyfruit)
- 📚 Change is documented
  - [X] Story
  - [X] API description
- 🔬 Change is tested
  - [X] Component
  - [X] Visual test

2020-09-21 10:18 UTC, WixBuildServer commented
### 🤖 Hi, I'm #Janet!

  A deploy preview of your PR was successfully released 🖼.

  You can find it under one of the following URLs:
  * https://preview.wix-style-react.com/pr_6005

2020-09-21 11:12 UTC, milkyfruit requested changes
@splintor The hover style and behaviour is not according to input specs.

- [ ] Allow to focus and select the text
- [ ] Add the hover style
- [ ] Change border color

Please check the input and input specs:
https://www.wix-style-react.com/?path=/story/components-api-components--input
https://zpl.io/2ERjBxM

2020-09-21 11:34 UTC, splintor commented
@milkyfruit 
1. Allow to focus and select the text - seems to work from what I checked. Do you see something else?
2. I don't have permission to open zpl.io/2ERjBxMSh. I'll try to work with what I see in `<Input>` code, but would be nice if you can provide me access.

2020-09-21 12:04 UTC, milkyfruit commented
1. I can select the text, but the input doesn't show focus outline and other styles:

VariableInput:
![image](https://user-images.githubusercontent.com/1684587/93763733-a07b3600-fc1a-11ea-8d19-59f2ae2819f7.png)

Input:
![image](https://user-images.githubusercontent.com/1684587/93763755-a83ada80-fc1a-11ea-8bfc-e1bd35d40100.png)

2. My back, I pasted the wrong link. This should work: https://zpl.io/2ERjBxM

2020-09-21 13:40 UTC, splintor commented
I pushed a fix that fixes the border and background colors on hover and focus.

Since the draft.js control sets `contenteditable` to `false` when `readOnly`, it doesn't have focus by default. To make it focusable so we will have focus outline, [we need to set its `tabIndex`](https://web.dev/control-focus-with-tabindex/). To achieve this, I added `tabIndex` prop to the `<VariableInput>` component, and set its default to `0` if `readOnly` is set. @EgoziE, please make sure it is OK with you.

2020-09-22 06:52 UTC, milkyfruit approved these changes

2020-09-23 08:22 UTC, shlomitc commented on src/VariableInput/VariableInput.js
> +      tabIndex,
I think this prop is not needed. the `tabIndex` hack internally doesn't relate to it.
if `tabIndex` is need for some reason, it should be applied to the root element.

2020-09-23 08:22 UTC, shlomitc commented on src/VariableInput/VariableInput.js
> +    const tabIndexToUse = tabIndex || (readOnly ? 0 : undefined);
this logic can be removed and inlined `tabIndex={readlOnly ? 0 : undefined }`

2020-09-23 18:59 UTC, splintor commented on src/VariableInput/VariableInput.js
> +    const tabIndexToUse = tabIndex || (readOnly ? 0 : undefined);
Removed - please review.

2020-09-23 19:00 UTC, splintor commented on src/VariableInput/VariableInput.js
> +      tabIndex,
Removed.

2020-09-24 08:17 UTC, EgoziE approved these changes

2020-09-24 08:17 UTC, merged