<InputArea /> - refactor story page
wix/wix-style-react pull request #6008
Opened 2020-09-21 15:20 UTC by yardenez

### 🔦 Summary

...

### ✅ Checklist

- [ ] 👨‍💻 API change is approved by the UI Infra Developers 
- [ ] 👨‍🎨 UX change is approved by the Design System UX 
- 📚 Change is documented
  - [ ] Story
  - [ ] API description
  - [ ] Cheatsheet
  - [ ] Other (explain)
- 🔬 Change is tested
  - [ ] Component
  - [ ] Visual test

2020-09-21 15:21 UTC, yardenez commented on src/InputArea/docs/index.story.js
> +            text: 'General inputArea container',
Should I change the description to another text?

2020-09-21 16:21 UTC, WixBuildServer commented
### 🤖 Hi, I'm #Janet!

  A deploy preview of your PR was successfully released 🖼.

  You can find it under one of the following URLs:
  * https://preview.wix-style-react.com/pr_6008

2020-09-22 09:34 UTC, EgoziE requested changes

2020-09-22 09:34 UTC, EgoziE commented on src/InputArea/docs/examples.js
> +export const standard = `
Standard
A simple use with a placeholder
```
<InputArea placeholder="This is a placeholder" resizable />
```

Letter counting
InputArea can indicate how many letters was typed, in order to show the counter you should set both `maxLength` and `hasCounter`. 
```
<InputArea value ="I typed exactly 37 letters out of 100" resizable maxLength={100} hasCounter />
```

Disabled and Read only
InputArea supports `disabled` and `readOnly` states
```
<Layout>
  <Cell>
    <InputArea placeholder="This is a placeholder" resizable disabled />
  </Cell>
  <Cell>
    <InputArea placeholder="This is a placeholder" resizable readOnly />
  </Cell>
</Layout>
```

With status
InputArea supports `error`, `warning`, and `loading` status
```
<Layout>
  <Cell>
    <InputArea placeholder="This is a placeholder" resizable status="error" />
  </Cell>
  <Cell>
    <InputArea placeholder="This is a placeholder" resizable status="warning" />
  </Cell>
  <Cell>
    <InputArea placeholder="This is a placeholder" resizable status="loading" />
  </Cell>
</Layout>
```

2020-09-22 09:34 UTC, EgoziE commented on src/InputArea/docs/index.story.js
> +            text: 'General inputArea container',
change to:

A multi-line text input component

2020-09-22 10:50 UTC, EgoziE approved these changes

2020-09-22 10:51 UTC, merged