<RichTextInputArea /> - convert scss to stylable
wix/wix-style-react pull request #6019
Opened 2020-09-23 11:55 UTC by yardenez

### 🔦 Summary

...

### ✅ Checklist

- [ ] 👨‍💻 API change is approved by the UI Infra Developers 
- [ ] 👨‍🎨 UX change is approved by the Design System UX 
- 📚 Change is documented
  - [ ] Story
  - [ ] API description
  - [ ] Cheatsheet
  - [ ] Other (explain)
- 🔬 Change is tested
  - [ ] Component
  - [ ] Visual test

2020-09-23 12:03 UTC, WixBuildServer commented
### 🤖 Hi, I'm #Janet!

  A deploy preview of your PR was successfully released 🖼.

  You can find it under one of the following URLs:
  * https://preview.wix-style-react.com/pr_6019

2020-09-23 12:15 UTC, yardenez commented on src/RichTextInputArea/RichTextInputArea.st.css
> +@st-global-custom-property --wsr-color-30, --wsr-color-50, --wsr-color-10, --min-height, --max-height;
Is this necessary? wasn't sure

2020-09-24 08:09 UTC, EgoziE requested changes

2020-09-24 08:09 UTC, EgoziE commented on src/RichTextInputArea/RichTextInputArea.st.css
> +  -st-mixin: medium font-mixin(family value(helveticanueu55));
```suggestion
  -st-mixin: text-medium-normal;
```

2020-09-24 08:09 UTC, EgoziE commented on src/RichTextInputArea/RichTextInputArea.st.css
> +    -st-mixin: medium font-mixin(family value(helveticanueu45))
```suggestion
    -st-mixin: text-medium-thin;
```

2020-09-24 08:09 UTC, EgoziE commented on src/RichTextInputArea/RichTextInputArea.st.css
> +  -st-mixin: medium font-mixin(family value(helveticanueu45))
```suggestion
    -st-mixin: text-medium-thin;
```

2020-09-24 08:09 UTC, EgoziE commented on src/RichTextInputArea/RichTextInputArea.st.css
> +  -st-named: medium, font-mixin, helveticanueu45, helveticanueu55;
Instead of all that, just import `text-medium-normal` and `text-medium-thin`

2020-09-24 13:45 UTC, EgoziE approved these changes

2020-09-24 14:47 UTC, merged