<CustomModalLayout/> - add dropdown example for storybook
wix/wix-style-react pull request #6026
Opened 2020-09-24 10:02 UTC by sivanharel

### 🔦 Summary

...

### ✅ Checklist

- [ ] 👨‍💻 API change is approved by the UI Infra Developers 
- [ ] 👨‍🎨 UX change is approved by the Design System UX 
- 📚 Change is documented
  - [ ] Story
  - [ ] API description
  - [ ] Cheatsheet
  - [ ] Other (explain)
- 🔬 Change is tested
  - [ ] Component
  - [ ] Visual test

2020-09-24 10:10 UTC, WixBuildServer commented
### 🤖 Hi, I'm #Janet!

  A deploy preview of your PR was successfully released 🖼.

  You can find it under one of the following URLs:
  * https://preview.wix-style-react.com/pr_6026

2020-09-24 10:43 UTC, TalZa1810 approved these changes
looks good, just a tiny note.

2020-09-24 10:43 UTC, TalZa1810 commented on src/CustomModalLayout/docs/examples/DropdownExample.js
> +import { Checkbox, Dropdown } from 'wix-style-react';
no need for the imports. it renders this without the imports.

2020-09-24 13:19 UTC, EgoziE requested changes

2020-09-24 13:19 UTC, EgoziE commented on src/CustomModalLayout/docs/examples/DropdownExample.js
> +          popoverProps={{ appendTo: 'window' }}
```suggestion
          popoverProps={{ appandTo: 'window' }}
```

2020-09-24 13:20 UTC, EgoziE commented on src/CustomModalLayout/docs/examples/DropdownExample.js
> +          popoverProps={{ appendTo: 'window' }}
#sorry

2020-09-25 07:54 UTC, milkyfruit requested changes
@sivanharel please add the descriptions to the example:

**Opening popovers form a modal**
CustomModalLayout doesn't let to overflow the content. To make popover elements work properly they need to be used with popover prop `appendTo` set to `window`.

2020-09-29 06:34 UTC, merged