Wix style react/card folder tabs
wix/wix-style-react pull request #6037
Opened 2020-09-29 08:07 UTC by vaidas-slav

### 🔦 Summary

Added CardFolderTabs component

To do:
- Fix sanity tests

### ✅ Checklist

- [ ] 👨‍💻 API change is approved by the UI Infra Developers 
- [ ] 👨‍🎨 UX change is approved by the Design System UX 
- 📚 Change is documented
  - [ ] Story
  - [ ] API description
  - [ ] Cheatsheet
  - [ ] Other (explain)
- 🔬 Change is tested
  - [ ] Component
  - [ ] Visual test

2020-09-29 08:48 UTC, WixBuildServer commented
### 🤖 Hi, I'm #Janet!

  A deploy preview of your PR was successfully released 🖼.

  You can find it under one of the following URLs:
  * https://preview.wix-style-react.com/pr_6037

2020-10-05 12:33 UTC, ayeletr commented
Hi,

Here are my comments:

1- first - on the Description tab: I would expect the top title on the Description page would be “Description” instead of “Basic Example”.

2 - The description: I don’t understand this sentence: “CardFolderTabs combined with CardFolderTabs.”

I suggest this description: Card with folder tabs allows content distribution within a card. Switching between the different content areas is done by using the tabs at the top of the card.

3 - in the Example: the selected tab should have the words “Selected Tab” instead of “Nice Tab”. the second tab should be named “Second Tab…”

4 - on the example itself: there’s a very small movement looks like 1px between the card and the tabs:
![image](https://user-images.githubusercontent.com/34542112/95079976-0fc74e80-0720-11eb-8f95-a6e886636484.png)
 
5 - the other 3 corners of the cards are square, and should be round (8px). I don’t want us to show wrong or unreal things in the example.
![image](https://user-images.githubusercontent.com/34542112/95079999-1786f300-0720-11eb-9f7b-5b9e00fecc35.png)
 
6 - would be nice to have a “Disable” toggle at the Playground tab.

2020-10-06 09:34 UTC, justinara requested changes
- [ ] Name first example "Structure" with a description "CardFolderTabs consist of a list of tabs and a content area." In example have tab names: Selected Tab, Second Tab, Third Tab, Disabled Tab 
- [ ] Showcase ellipsis and full name on a tooltip in a separate example "maxTabWidth". Add a description "Tab can have a specified max width. Long names will have ellipsis overflow with a tooltip containing full name."

2020-10-08 14:47 UTC, justinara requested changes
- [ ] Change mouse cursor to pointer
- [ ] Shadow of a selected tab is a little visible on the left side, even though i see that it uses same values as described in zeplin - let's move it to the right side a little
![image](https://user-images.githubusercontent.com/67683352/95473805-21615e00-098d-11eb-90f9-0dd60f07ba76.png)

2020-10-15 11:42 UTC, justinara requested changes
- [ ] Reset tab button side margins to 0 to avoid weird spacing in other browsers 
![image](https://user-images.githubusercontent.com/67683352/96118322-01cdb680-0ef4-11eb-8494-c78021426014.png)
- [ ] Add 30px right side margin for tabs container to prevent them from reaching the right side of a card. 
![image](https://user-images.githubusercontent.com/67683352/96118676-815b8580-0ef4-11eb-8b1f-92469ee22e91.png)

2020-10-16 10:55 UTC, justinara approved these changes

2020-10-20 08:58 UTC, TalZa1810 requested changes
Few tiny comments

2020-10-20 08:58 UTC, TalZa1810 commented on src/CardFolderTabs/test/CardFolderTabs.spec.js
> +
I would add another test here checking that the correct content is rendered after clicking on a different Tab.

2020-10-20 08:58 UTC, TalZa1810 commented on src/CardFolderTabs/test/CardFolderTabs.tsx
> +      <CardFolderTabs.Tab id="1" name="name" children={<div />} />
a `disabled` is also a prop of the Tab component

2020-10-20 08:58 UTC, TalZa1810 commented on src/CardFolderTabs/CardFolderTabs.uni.driver.js
> +    getIsTabDisabledById: async tabId =>
Maybe renaming this to `checkIsTabDisabledById` ? since it returns a boolean it's more intuitive.

2020-11-01 11:46 UTC, merged