Feat/address input
wix/wix-style-react pull request #6049
Opened 2020-10-01 06:14 UTC by MSiliunas

### 🔦 Summary

Adds a new internal component - `<AddressInput />`.

### ✅ Checklist

- [x] 👨‍💻 API change is approved by the UI Infra Developers 
- [x] 👨‍🎨 UX change is approved by the Design System UX 
- 📚 Change is documented
  - [x] Story
  - [x] API description
  - [ ] Cheatsheet
  - [ ] Other (explain)
- 🔬 Change is tested
  - [x] Component
  - [ ] Visual test

2020-10-01 08:17 UTC, EgoziE requested changes

2020-10-01 08:17 UTC, EgoziE commented on src/AddressInput/test/AddressInput.spec.js
> +    expect(await driver.getInputValue()).toEqual(text);
Might look a bit too much, but we encourage testing the before and after.

```suggestion
    expect(props.onChange.called).toEqual(false);
    expect(await driver.getInputValue()).toEqual('');

    await driver.enterText(text);

    expect(props.onChange.called).toEqual(true);
    expect(await driver.getInputValue()).toEqual(text);
```

2020-10-01 08:17 UTC, EgoziE commented on src/AddressInput/test/AddressInput.tsx
> +      className="className"
Type test
Just add all props available here

2020-10-01 09:57 UTC, EgoziE requested changes

2020-10-01 09:57 UTC, EgoziE commented on perfer.config.js
> +  ['AddressInput.bundle.min.js', 10],
Change to 62 (according to the bundle size test) and keep sorted

2020-10-01 09:57 UTC, EgoziE commented on perfer.config.js
> +  ['AddressInput.min.css', 1],
keep sorted

2020-10-01 14:45 UTC, lironch commented on src/AddressInput/AddressInput.js
> +      inputValue: value.value,
Shouldn't this be `value.description`? assuming `description` will be part of the option object propTypes

2020-10-11 08:14 UTC, WixBuildServer commented
### 🤖 Hi, I'm #Janet!

  A deploy preview of your PR was successfully released 🖼.

  You can find it under one of the following URLs:
  * https://preview.wix-style-react.com/pr_6049

2020-10-27 16:06 UTC, EgoziE approved these changes

2020-10-28 08:31 UTC, merged