test(protractor): merge protractor tests runs
wix/wix-style-react pull request #6058
Opened 2020-10-06 18:30 UTC by argshook

this PR merges `npm run test3:e2e` and `npm run test4:e2e` into one:
`npm run test3:e2e`

in total there are 26 files that define protractor tests
in total they take ~1000 seconds
however, actual build takes more time because there are other tasks
involved, like `npm run test:e2e-runtime`.

`npm run test:e2e-runtime` currently is run before both
`protractor1.conf.js` and `protractor2.conf.js` which is excessive.

### 🔦 Summary

...

### ✅ Checklist

- [ ] 👨‍💻 API change is approved by the UI Infra Developers 
- [ ] 👨‍🎨 UX change is approved by the Design System UX 
- 📚 Change is documented
  - [ ] Story
  - [ ] API description
  - [ ] Cheatsheet
  - [ ] Other (explain)
- 🔬 Change is tested
  - [ ] Component
  - [ ] Visual test

2020-10-06 18:38 UTC, WixBuildServer commented
### 🤖 Hi, I'm #Janet!

  A deploy preview of your PR was successfully released 🖼.

  You can find it under one of the following URLs:
  * https://preview.wix-style-react.com/pr_6058

2020-10-07 11:28 UTC, shlomitc requested changes

2020-10-07 11:28 UTC, shlomitc commented on package.json
> +    "test:e2e": "build-storybook -c ./.storybook/e2e && npm run test:e2e-only",
since you removed this from the `test:e2e`, it also removed it from the `test` task.
in that case, you should explicitly add it there so all tests could be run in a single build.

2020-10-07 11:28 UTC, shlomitc commented on package.json
> +    "test6:sanity": "npm run lint && npm run sanity && npm run test:e2e-runtime",
The sanity task was supposed to give some quick indication for failing structure instead of waiting for long runs, but it seems to become some kind of a "common" task.

lint - runs on src code and should fail fast for such issues.
sanity - runs on src code for the autotools. that's kind of "smoke" tests, but it runs on a bundle, so it must have a build phase.
e2e-runtime - runs on the real project output.

I think the right thing to do will be the e2e-runtime to a separate task

2020-10-07 11:28 UTC, shlomitc commented on protractor1.conf.js
> +const components = [
I think it's better to have both lists in the same file, that way it's easy to see the entire picture.

2020-10-07 11:28 UTC, shlomitc commented on protractor2.conf.js
> +const components = [
what happens if I forget to add here a file? will it be missing from the tests?
Maybe it's better that only one will rune a specific set of tests while the other will run "all-but-the-specific-ones"

2020-10-07 12:08 UTC, argshook commented on package.json
> +    "test:e2e": "build-storybook -c ./.storybook/e2e && npm run test:e2e-only",
`npm run test` has `npm run sanity`, which, with my change, also has `e2e-runtime`. Thus, running `npm run test` will also run `e2e-runtime`

2020-10-07 12:19 UTC, shlomitc commented on package.json
> +    "test:e2e": "build-storybook -c ./.storybook/e2e && npm run test:e2e-only",
it runs `sanity`, not `test6:sanity`.
`sanity` contains only the autotools, not the e2e-runtime.

2020-10-07 12:33 UTC, argshook commented on protractor2.conf.js
> +const components = [
> what happens if I forget to add here a file? will it be missing from the tests?

yes, test will not be run with protractor. I think this is what we want
and having a list of specific entries is what discourages of manually
adding new `e2e.js`. It's also not part of generator for a long time.

these lists are not "take all tests, split in half", but:

* take all e2e tests
* sort by the length of time they take in CI
* split into two lists, while keeping the length of time in both lists similar.

it is to solve a problem of `test3:e2e` taking 22 mins, while
`test4:e2e` takes 11, and make them both ~15 mins. This essentially wins
us 7 mins of CI waiting time for a complete build

| protractor1.conf.js time | component       | protractor2.conf.js time | component                 |
| ---                      | ---             | ---                      | ---                       |
| 257                      | TableActionCell | 196                      | Page                      |
| 90                       | InputArea       | 104                      | DatePicker                |
| 52                       | MultiSelect     | 60                       | Range                     |
| 41                       | Stepper         | 43                       | Search                    |
| 30                       | RadioGroup      | 41                       | StatisticsWidget          |
| 28                       | Slider          | 29                       | MultiSelectCheckbox       |
| 23                       | DropdownLayout  | 23                       | MessageBox                |
| 14                       | Table           | 20                       | RichTextInputArea         |
| 13                       | FilePicker      | 20                       | PageHeader                |
| 12                       | Tabs            | 13                       | DataTable                 |
| 11                       | AudioPlayer     | 12                       | CardGalleryItem           |
|                          |                 | 1                        | InputWithOptions          |
|                          |                 | 1                        | MultiSelectFocusBehaviour |
| 571                      | total time (s)  | 563                      | total time (s)            |

> Maybe it's better that only one will rune a specific set of tests while the other will run "all-but-the-specific-ones"

i can think of something more sophisticated but i'm not sure it's worth
the effort, especially considering that in future we want to use
different methods for running e2e (maybe eyes-storybook with better
hover/scroll/etc support, maybe sled, maybe puppeteer etc)

2020-10-07 12:35 UTC, argshook commented on package.json
> +    "test:e2e": "build-storybook -c ./.storybook/e2e && npm run test:e2e-only",
ah, you're right, i'll add `e2e-runtime` also to `test`

although it's only relevant for local, not sure anyone ever runs full test suite locally

2020-10-07 12:37 UTC, argshook commented on protractor1.conf.js
> +const components = [
do you mean to export them from `protractor.conf.js` and reuse in
`protractor1.conf.js` and `protractor2.conf.js`?

2020-10-07 12:41 UTC, shlomitc commented on protractor1.conf.js
> +const components = [
whatever name you think of.
just to have the list of all tests (by component names) in the same file

2020-10-07 12:47 UTC, argshook commented on package.json
> +    "test6:sanity": "npm run lint && npm run sanity && npm run test:e2e-runtime",
`sanity` in my mind can include the current `e2e-runtime` as its pretty lightweight.

adding dedicated `e2e-runtime` is a right thing to do, but i'd like to
have it as a separate task, because it requires ci people involvement.

`e2e-runtime` should also do more thorough testing than it does right
now, but it should be separate task.

goal here is to just reduce the maximum time it takes for all e2es in CI

2020-10-07 12:48 UTC, shlomitc commented on protractor2.conf.js
> +const components = [
I thought of something like this:

```
const specificComponents = ['InputArea', 'MultiSelect',,,,,,,];

//1 - specific ones
specs: components.map(component => `src/${component}/**/*.e2e.js`)

//2 - all but specific ones
specs: `src/![${specificComponents.join(', ')]}/**/*.e2e.js`,
```

Regarding not adding new "e2e"s. yeah, but you know - if someone needs to add it, it's easier if it simply works instead of figuring out that it needs to be added to some file (as it's not documented, new contributors are not familiar with this constrain, even not all team members are aware of it...)

2020-10-07 15:25 UTC, shlomitc commented on package.json
> +    "test6:sanity": "npm run lint && npm run sanity && npm run test:e2e-runtime",
probably not that critical

2020-10-07 17:51 UTC, shlomitc approved these changes

2020-10-07 17:51 UTC, shlomitc commented on scripts/components-for-e2e-tests.js
> +/*
Not sure that “scripts” is the right place for it, but I guess that’s not a biggie

2020-10-08 06:25 UTC, argshook commented on scripts/components-for-e2e-tests.js
> +/*
yep, i moved it to `test` folder, it's a more appropriate location

2020-10-08 06:45 UTC, merged