`<DropdownLayout/>`- align design
wix/wix-style-react pull request #6065
Opened 2020-10-08 15:39 UTC by TalZa1810

### 🔦 Summary
WIP

### ✅ Checklist

- [ ] 👨‍💻 API change is approved by the UI Infra Developers 
- [ ] 👨‍🎨 UX change is approved by the Design System UX 
- 📚 Change is documented
  - [ ] Story
  - [ ] API description
  - [ ] Cheatsheet
  - [ ] Other (explain)
- 🔬 Change is tested
  - [ ] Component
  - [ ] Visual test

2020-10-08 15:48 UTC, WixBuildServer commented
### 🤖 Hi, I'm #Janet!

  A deploy preview of your PR was successfully released 🖼.

  You can find it under one of the following URLs:
  * https://preview.wix-style-react.com/pr_6065

2020-10-11 11:34 UTC, TalZa1810 commented
Hi @milkyfruit ,
I’ve aligned the design of the title and divider to use the builders instead of the previous design:
https://preview.wix-style-react.com/pr_6065/?path=/story/components-api-components--dropdownlayout

As for the selectable option, I’ll do this at a different PR.
The divider has paddings since the ListItemSection divider has paddings. Let me know if it’s fine on your end.

2020-10-12 07:19 UTC, milkyfruit requested changes
@TalZa1810 
The example showing a title is good.
For old users to keep their prefered visual look please update `title:true` option to look like `type:'subheader'`

2020-10-12 11:36 UTC, TalZa1810 commented on src/DropdownLayout/DropdownLayout.js
> +   * - value `<function / string / node>` *required*: can be a string, react element or a builder function.
I've removed the description in order to promote using builders instead of using objects. However, this option is also supported within the code.

2020-10-12 11:37 UTC, TalZa1810 commented on src/DropdownLayout/docs/examples.js
> +    listItemSectionBuilder({
updated the example to use builders instead of the previous version

2020-10-12 11:38 UTC, TalZa1810 commented on src/DropdownLayout/DropdownLayout.js
> +    return option;
Currently returns either an object or a builder. This method will be updated in the next phase of the visual change.

2020-10-12 11:51 UTC, milkyfruit approved these changes

2020-10-12 20:15 UTC, merged