Add item changes for tpa
wix/wix-style-react pull request #6079
Opened 2020-10-12 14:53 UTC by sivanharel

### 🔦 Summary

...

### ✅ Checklist

- [ ] 👨‍💻 API change is approved by the UI Infra Developers 
- [ ] 👨‍🎨 UX change is approved by the Design System UX 
- 📚 Change is documented
  - [ ] Story
  - [ ] API description
  - [ ] Cheatsheet
  - [ ] Other (explain)
- 🔬 Change is tested
  - [ ] Component
  - [ ] Visual test

2020-10-12 15:29 UTC, WixBuildServer commented
### 🤖 Hi, I'm #Janet!

  A deploy preview of your PR was successfully released 🖼.

  You can find it under one of the following URLs:
  * https://preview.wix-style-react.com/pr_6079

2020-10-12 17:28 UTC, shlomitc requested changes

2020-10-12 17:28 UTC, shlomitc commented on src/AddItem/AddItem.js
> +    return isBoxChild && isStringInnerChild;
consider a more generic solution using a render function
```jsx
<AddItem>
  {() => <div>this will not apply text styles</div>}
</AddItem>
```

2020-10-12 17:28 UTC, shlomitc commented on src/AddItem/AddItem.st.css
> +  border-color: value(D10-30);
are you sure `dashed` isn't needed?

2020-10-13 07:05 UTC, sivanharel commented on src/AddItem/AddItem.js
> +    return isBoxChild && isStringInnerChild;
sounds like a good idea.

2020-10-13 07:12 UTC, sivanharel commented on src/AddItem/AddItem.st.css
> +  border-color: value(D10-30);
It is not needed since it defined at the ".root:theme(dashes)".
The only change that is needed is the color.

2020-10-14 21:51 UTC, shlomitc commented on src/AddItem/AddItem.js
> +    /** any renderable node or a render function */
worth mentioning that in the case of a render function, text styles will not be applied. you should also back this with a visual test if possible

2020-10-14 21:51 UTC, shlomitc commented on src/AddItem/index.d.ts
> +  children?: React.ReactNode | Function;
```suggestion
  children?: React.ReactNode | () => React.ReactNode;
```

2020-10-14 21:51 UTC, shlomitc commented on src/AddItem/AddItem.js
> +      AddItemIcon = <Icon width="31" height="31" />;
I think that it could be better if it's set only on the default icon since it's a very specific fit of this icon to the component's size constraints. WDYT?

2020-10-14 21:51 UTC, shlomitc commented on src/AddItem/AddItem.js
> +      AddItemIcon = <Icon width="26" height="26" style={{ flexShrink: 0 }} />;
same

2020-10-15 07:07 UTC, sivanharel commented on src/AddItem/AddItem.js
> +      AddItemIcon = <Icon width="31" height="31" />;
I agree.. But the style={{ flexShrink: 0 }} is must be added in the tiny icon since it should be display vertical in this case. But I could add it to the css.

2020-10-15 11:43 UTC, shlomitc reviewed
very last comments, I think we can merge afterwards

2020-10-15 11:43 UTC, shlomitc commented on src/AddItem/AddItem.js
> +          },
consider refactoring it out to a static variable to avoid re-renders of the function component.

const 
```jsx
const AddItemButtonIcons = {
  tiny: () => <Add width="26" height="26" />,
  small: AddItemSmall,
  medium: AddItemMedium,
  large: AddItemLarge,
  image: () => <AddMedia width="31" height="31" />,
};
```

```suggestion
          AddItemButton: AddItemButtonIcons
```

2020-10-15 11:43 UTC, shlomitc commented on src/AddItem/AddItem.st.css
> +.content:size(tiny) svg {
instead of a global selector, you can target it as a general `icon` class
```css
.content:size(tiny) .icon {
  flex-shrink: 0;
}
```
each icon will be rendered with this class name:
```jsx
return <Icon className={classes.icon}/>;
```

and each icon is responsible to pass this class name
```jsx
tiny: ({className}) => <Add className={className} width="26" height="26" />
```

2020-10-15 17:26 UTC, shlomitc approved these changes

2020-10-18 12:15 UTC, merged