Adding business dashboard theme
wix/wix-style-react pull request #6082
Opened 2020-10-12 19:39 UTC by adicicurel

### 🔦 Summary

Adding the new business dashboard theme
Initial commit

### ✅ Checklist

- [ ] 👨‍💻 API change is approved by the UI Infra Developers  @shlomitc 
- [ ] 👨‍🎨 UX change is approved by the Design System UX  @shlomitc
- 📚 Change is documented
  - [V] Story
  - [V] API description
  - [ ] Cheatsheet
  - [ ] Other (explain)
- 🔬 Change is tested
  - [ ] Component
  - [ ] Visual test

2020-10-13 08:02 UTC, shlomitc requested changes
Please take the time to [sign your commits](https://github.com/wix/wix-style-react/blob/master/docs/contribution/CREATE_PR.md#sign-commits),
CI won't run otherwise

https://github.com/wix/wix-style-react/blob/master/docs/contribution/CREATE_PR.md#sign-commits

2020-10-13 08:02 UTC, shlomitc commented on src/Themes/businessDashboard/docs/components/CircularProgressBar.js
> +  <FontUpgrade>
```suggestion
  
```
If I understand correctly, what you say is that all of the components should get the `Madefor` font out of the box. According to this implementation, it means that every project who will use this theme will need to add also the FontUpgrade, which is bad because it means the theme isn't implemented with the right fonts.
You need to make Madefor as part of your theme file and components definitions.

So there are two options:
1. Explicitly define in each component's css that it should use the Madefor styles using the `font-mixin(family Madefor)` from the [`typography.st.css`](https://github.com/wix/wix-style-react/blob/4149e8e9c5c846d885d8c7fd159fa3931361eb48/src/Foundation/stylable/typography.st.css#L13) file.
2. extend the `ThemeProvider` component to get a `componentWrapper` prop that accepts a node and applies it as a child so it will look like this:
```jsx
<ThemeContext.Provider value={{ icons: theme.icons }}>
  {componentWrapper ? componentWrapper({children}) : children}
</ThemeContext.Provider>
```
and then in your `BusinessDashboard.js` file, you will add
```js
export default ({ active } = {}) => ({
  className: active === false ? '' : classes.root,
  componentWrapper: ({children}) => <FontUpgrade>{children}</FontUpgrade>
});
```

Make sure that you test it with this flag off:
![image](https://user-images.githubusercontent.com/6093192/95831870-4285ce00-0d42-11eb-9c60-cf8631c1680e.png)

2020-10-13 18:19 UTC, adicicurel commented on src/Themes/businessDashboard/foundations/colors.st.css
> +  BLUE: #116dff;
Added the B05, B10... according to the colors Shira sent

2020-10-14 21:19 UTC, shlomitc commented on src/Themes/businessDashboard/foundations/typography.st.css
> +.T06 {
I assume you looked in the EditorX theme, I don't think it's needed for your case.

2020-10-14 21:19 UTC, shlomitc commented on src/Themes/businessDashboard/index.js
> +export { default as businessDashboardTheme } from './BusinessDashboard';
please rename to `theme` so it will be consistent with all other themes

2020-10-14 21:19 UTC, shlomitc commented on src/Themes/businessDashboard/index.d.ts
> +export function businessDashboardTheme(options?: ThemeOptions): ThemeInterface;
rename

2020-10-14 21:27 UTC, WixBuildServer commented
### 🤖 Hi, I'm #Janet!

  A deploy preview of your PR was successfully released 🖼.

  You can find it under one of the following URLs:
  * https://preview.wix-style-react.com/pr_6082

2020-10-15 04:35 UTC, adicicurel commented on src/Themes/businessDashboard/foundations/typography.st.css
> +.T06 {
removed

2020-10-15 04:37 UTC, adicicurel commented on src/Themes/businessDashboard/components/Button.st.css
> +  padding: 0 SP5 0 6px;
sorry, added import to spacing

2020-10-15 04:39 UTC, adicicurel commented on src/Themes/businessDashboard/index.js
> +export { default as businessDashboardTheme } from './BusinessDashboard';
changed back

2020-10-18 09:12 UTC, merged

2020-11-09 19:39 UTC, EgoziE reviewed
Please take a look

2020-11-09 19:39 UTC, EgoziE commented on src/Themes/businessDashboard/components/Button.st.css
> +  padding: 0 SP2 0 6px;
@adicicurel It's supposed to be `value(SP2)` right?