<SectionHelper/> - unify paddings with no close button
wix/wix-style-react pull request #6097
Opened 2020-10-15 11:24 UTC by Zivilekin

### 🔦 Summary

Curently Section Helper content has left padding set to 24px, and right padding to 42px at all times. Let's change it depending on a presence of a close button: 

    -keep padding as it is (left 24px, right 42px) when section helper has a close button
    -if close button is removed unify both sides padding to be 24px

2020-10-15 11:47 UTC, EgoziE commented
Thanks for submitting this PR.
Please take the time to read how to properly create a PR for wix-style-react with signed commits.

https://github.com/wix/wix-style-react/blob/master/docs/contribution/CREATE_PR.md

2020-10-16 06:58 UTC, WixBuildServer commented
### 🤖 Hi, I'm #Janet!

  A deploy preview of your PR was successfully released 🖼.

  You can find it under one of the following URLs:
  * https://preview.wix-style-react.com/pr_6097

2020-10-19 08:51 UTC, argshook requested changes

2020-10-19 08:51 UTC, argshook commented on src/SectionHelper/test/SectionHelper.visual.js
> +            onAction={() => undefined}
```suggestion
            onAction={() => undefined}
```
probably not needed

2020-10-19 08:51 UTC, argshook commented on src/SectionHelper/test/SectionHelper.visual.js
> +            onClose={() => undefined}
```suggestion
            onClose={() => undefined}
```
probably not needed

2020-10-19 08:51 UTC, argshook commented on src/SectionHelper/test/SectionHelper.visual.js
> +            onAction={() => undefined}
```suggestion
            onAction={() => undefined}
```
probably not needed

2020-10-19 08:51 UTC, argshook commented on src/SectionHelper/test/SectionHelper.visual.js
> +            onClose={() => undefined}
```suggestion
            onClose={() => undefined}
```
probably not needed

2020-10-19 08:51 UTC, argshook commented on src/SectionHelper/test/SectionHelper.visual.js
> +            title="Look at this really long and important message that could in some cases contain many lengthy words like psychophysicotherapeutics!"
`actionText` and `title` are the same in both example, would be nice to have this content only once in a variable

2020-10-19 09:08 UTC, daugerdas commented on src/SectionHelper/test/SectionHelper.visual.js
> +            onClose={() => undefined}
seems that CloseButton is not displayed then

2020-10-19 09:09 UTC, daugerdas commented on src/SectionHelper/test/SectionHelper.visual.js
> +            onClose={() => undefined}
seems that CloseButton is not displayed then

2020-10-19 09:36 UTC, argshook approved these changes
great work! :+1:

2020-10-20 09:19 UTC, merged