<SelectorList/>
wix/wix-style-react pull request #6098
Opened 2020-10-15 14:06 UTC by gendeld

### 🔦 Summary

...

### ✅ Checklist

- [ ] 👨‍💻 API change is approved by the UI Infra Developers 
- [ ] 👨‍🎨 UX change is approved by the Design System UX 
- 📚 Change is documented
  - [ ] Story
  - [ ] API description
  - [ ] Cheatsheet
  - [ ] Other (explain)
- 🔬 Change is tested
  - [ ] Component
  - [ ] Visual test

2020-10-15 14:15 UTC, WixBuildServer commented
### 🤖 Hi, I'm #Janet!

  A deploy preview of your PR was successfully released 🖼.

  You can find it under one of the following URLs:
  * https://preview.wix-style-react.com/pr_6098

2020-10-27 13:06 UTC, EgoziE requested changes

2020-10-27 13:06 UTC, EgoziE commented on src/SelectorList/SelectorList.uni.driver.d.ts
> +  scrollDown: () => Promise<boolean>;
Let's discuss Testkit API
I think It's a good opportunity not to expose drivers as a return value!
@shlomitc Any objections to make this change

2020-10-27 13:06 UTC, EgoziE commented on src/SelectorList/ToggleAllCheckbox/ToggleAllCheckbox.js
> +ToggleAllCheckbox.defaultProps = {
Missing PropTypes
and types* (d.ts + tsx file)

*It's better to split types to the compounds/internal components folders and require in the main d.ts file

2020-11-02 09:22 UTC, EgoziE approved these changes

2020-11-03 09:07 UTC, EgoziE approved these changes

2020-11-03 09:54 UTC, merged