<DropdownBase/> - add "getSelectedOption" to testkit
wix/wix-style-react pull request #6115
Opened 2020-10-20 13:21 UTC by bamai

### 🔦 Summary
https://jira.wixpress.com/browse/DSM-879
...

### ✅ Checklist

- [ ] 👨‍💻 API change is approved by the UI Infra Developers 
- [ ] 👨‍🎨 UX change is approved by the Design System UX 
- 📚 Change is documented
  - [ ] Story
  - [ ] API description
  - [ ] Cheatsheet
  - [ ] Other (explain)
- 🔬 Change is tested
  - [ ] Component
  - [ ] Visual test

2020-10-20 13:32 UTC, WixBuildServer commented
### 🤖 Hi, I'm #Janet!

  A deploy preview of your PR was successfully released 🖼.

  You can find it under one of the following URLs:
  * https://preview.wix-style-react.com/pr_6115

2020-12-09 15:10 UTC, TalZa1810 requested changes
Hey, 
I've added some few comments. Let me know if something is unclear.

2020-12-09 15:10 UTC, TalZa1810 commented on src/DropdownLayout/DropdownLayout.js
> +          selectedId === 0 ? `${selectedId}` : selectedId,
```suggestion
          `${selectedId}`,
```

Add than you can test this for both string and number at the tests file

2020-12-09 15:10 UTC, TalZa1810 commented on src/DropdownLayout/test/DropdownLayout.spec.js
> +    it('should return the selected option', async () => {
add here tests for both id that is a number or a string

2020-12-10 08:59 UTC, TalZa1810 approved these changes

2020-12-10 12:41 UTC, merged