Theme bm linear progress bar
wix/wix-style-react pull request #6136
Opened 2020-10-27 07:55 UTC by adicicurel

### 🔦 Summary

Adding LinearProgressBar to Business Dashboard theme 

### ✅ Checklist

- [ ] 👨‍💻 API change is approved by the UI Infra Developers 
- [ ] 👨‍🎨 UX change is approved by the Design System UX 
- 📚 Change is documented
  - [ ] Story
  - [ ] API description
  - [ ] Cheatsheet
  - [ ] Other (explain)
- 🔬 Change is tested
  - [ ] Component
  - [ ] Visual test

2020-10-27 08:05 UTC, WixBuildServer commented
### 🤖 Hi, I'm #Janet!

  A deploy preview of your PR was successfully released 🖼.

  You can find it under one of the following URLs:
  * https://preview.wix-style-react.com/pr_6136

2020-10-27 08:36 UTC, shlomitc commented on src/Themes/businessDashboard/components/LinearProgressBar.st.css
> +.root:skin(standard)::barForeground {
need to add also `background: D60` for the barBackground

2020-10-27 08:36 UTC, shlomitc commented on src/Themes/businessDashboard/docs/components/LinearProgressBar.js
> +<ThemeProvider theme={theme({ active: true })}>
can't we simply set `active: true` as the default value? That would make code examples much cleaner

2020-10-27 08:36 UTC, shlomitc commented on src/LinearProgressBar/test/LinearProgressBar.visual.js
> +    });
Why did you need to add another test phase? There are already tests for all the different themes: https://github.com/wix/wix-style-react/pull/6136/files#diff-410caa42a341168a81e4bafe9b20528c389e0c66a09602df5a42e1d20ee6789bR72

Also, by exposing `runTests` only for this section, it means other tests will not run for your theme which isn't consistent with the other theme tests that we created.

2020-10-27 08:36 UTC, shlomitc requested changes

2020-10-27 08:36 UTC, shlomitc commented on src/LinearProgressBar/test/LinearProgressBar.visual.js
> +import Heading from '../../Text';
not needed

2020-11-02 21:46 UTC, dimafeldman commented on src/Themes/businessDashboard/docs/components/LinearProgressBar.js
> +<ThemeProvider theme={theme({ active: true })}>
yep, good idea. adjusted

2020-11-02 21:48 UTC, adicicurel commented on src/Themes/businessDashboard/docs/components/LinearProgressBar.js
> +<ThemeProvider theme={theme({ active: true })}>
it already have a default active: true, just remove it from the docs components

2020-11-03 08:33 UTC, shlomitc approved these changes

2020-11-03 10:39 UTC, shlomitc requested changes

2020-11-03 10:39 UTC, shlomitc commented on src/Themes/businessDashboard/components/LinearProgressBar.st.css
> +.root:skin(standard)::barForeground {
@dimafeldman - now seeing the visual tests failing - the overrides should be applied only for the `success` state and not for the standard one. can you please fix it?

2020-11-03 10:48 UTC, shlomitc commented on src/Themes/businessDashboard/docs/components/LinearProgressBar.js
> +  <LinearProgressBar value={30}/>
```suggestion
  <LinearProgressBar skin="success" value={30}/>
```

2020-11-03 14:05 UTC, merged