Skeleton group
wix/wix-style-react pull request #6141
Opened 2020-10-27 15:05 UTC by mharsat

### 🔦 Summary

New components:

- SkeletonGroup
- SkeletonLine
- SkeletonCircle
- SkeletonRectangle

### ✅ Checklist

- [ ] 👨‍💻 API change is approved by the UI Infra Developers 
- [ ] 👨‍🎨 UX change is approved by the Design System UX 
- 📚 Change is documented
  - [ ] Story
  - [ ] API description
  - [ ] Cheatsheet
  - [ ] Other (explain)
- 🔬 Change is tested
  - [ ] Component
  - [ ] Visual test

2020-10-27 15:38 UTC, EgoziE requested changes

2020-10-27 15:38 UTC, EgoziE commented on src/SkeletonGroup/SkeletonGroup.uni.driver.d.ts
> +  hasChildernSkin(): Promise<boolean>;
Skin is a pure visual prop, therefore there's no need to test it programatically.
Visual tests are enough

2020-10-27 15:38 UTC, EgoziE commented on src/SkeletonRectangle/docs/index.story.js
> +import React from 'react';
A single story page is enough for all Skeleton components.
They are not complex enough to have a separate story page.

2020-10-27 15:38 UTC, EgoziE commented on src/colors.scss
> +$D40-20: rgba($D40, 0.2);
This file is about to be deprecated, no need to add colors here

2020-10-28 10:22 UTC, WixBuildServer commented
### 🤖 Hi, I'm #Janet!

  A deploy preview of your PR was successfully released 🖼.

  You can find it under one of the following URLs:
  * https://preview.wix-style-react.com/pr_6141

2020-10-29 10:17 UTC, EgoziE requested changes

2020-10-29 10:17 UTC, EgoziE commented on src/SkeletonRectangle/SkeletonRectangle.st.css
> +}
Not used anywhere

2020-10-29 10:17 UTC, EgoziE commented on src/SkeletonCircle/SkeletonCircle.st.css
> +}
Not used anywhere

2020-10-29 10:17 UTC, EgoziE commented on src/SkeletonLine/SkeletonLine.st.css
> +}
Not used anywhere

2021-01-11 09:58 UTC, assafzi commented
Approved by UX.
Looks great.
Thanks!

2021-01-13 20:59 UTC, EgoziE requested changes

2021-01-13 20:59 UTC, EgoziE commented on src/Sidebar/index.d.ts
> +import SidebarBackButton from "../SidebarBackButton";
looks like a mistake :)

2021-01-13 20:59 UTC, EgoziE commented on src/SkeletonGroup/SkeletonGroup.st.css
> +  }*/
If it's not needed, can be deleted.

2021-01-13 20:59 UTC, EgoziE commented on src/SkeletonGroup/docs/index.story.js
> +
SkeletonGroup needs to have a background, use this pattern to add a background:
```
componentWrapper: ({ component }) => (...)
```
Take a look at `Palette` component for reference.

2021-01-14 08:31 UTC, EgoziE approved these changes
@bamai Looks good, let's merge it when all tests pass!

2021-01-14 09:24 UTC, merged