SidebarSectionItem suffix 30% to support madeFor font
wix/wix-style-react pull request #6146
Opened 2020-10-28 07:39 UTC by dht

2020-10-28 07:49 UTC, shlomitc requested changes
Thanks for this PR!
Please take the time to [sign your commits](https://github.com/wix/wix-style-react/blob/master/docs/contribution/CREATE_PR.md#sign-commits), CI won't run otherwise

I think we might want to add an additional margin between the suffix and the content, but I'm waiting for a response from @ayeletr

2020-10-28 07:49 UTC, shlomitc commented on src/SidebarSectionItem/SidebarSectionItem.st.css
> +  min-width: 30%;
min-width should still be kept 24px, but the max-width should be set to 30%

2020-10-28 07:49 UTC, shlomitc commented on src/SidebarSectionItem/SidebarSectionItem.st.css
>    justify-content: center;
I think a small adjustment will be needed here since now the content will be centered, while it should probably be aligned to the end

2020-10-28 08:10 UTC, dht commented on src/SidebarSectionItem/SidebarSectionItem.st.css
> +  min-width: 30%;
max-width 30% will make sure the suffix is not to big.
The [ticket|https://jira.wixpress.com/browse/WOSBM-3398] describes a situation in which the suffix space for the "new" badge is too small and thus invokes the ellipsis mechanism.
Am I wrong?

2020-10-28 08:13 UTC, WixBuildServer commented
### 🤖 Hi, I'm #Janet!

  A deploy preview of your PR was successfully released 🖼.

  You can find it under one of the following URLs:
  * https://preview.wix-style-react.com/pr_6146

2020-10-28 08:31 UTC, shlomitc commented
@dht 
![image](https://user-images.githubusercontent.com/6093192/97411246-aa264680-1908-11eb-87d5-1848cce1f671.png)

2020-10-28 14:09 UTC, dht commented on src/SidebarSectionItem/SidebarSectionItem.st.css
> +  min-width: 30%;
@shlomitc Would it be at possible to have a quick Zoom call regarding this? I feel a very short synced communication could help me push this forward

2020-11-09 11:01 UTC, shlomitc commented
hey @dht - any updates on this one?

2020-11-10 13:04 UTC, dht commented
@s

> hey @dht - any updates on this one?

Yes, I've committed the needed changes. Loved the idea of the virtual files. Do they also represent the tests?

2020-11-11 08:46 UTC, dht commented
@shlomitc probably should have mentioned you in my last comment

2020-11-11 12:24 UTC, merged