Added business dashboard theming for Heading & Text components
wix/wix-style-react pull request #6157
Opened 2020-11-01 13:31 UTC by dimafeldman

### 🔦 Summary

...

### ✅ Checklist

- [ ] 👨‍💻 API change is approved by the UI Infra Developers 
- [ ] 👨‍🎨 UX change is approved by the Design System UX 
- 📚 Change is documented
  - [ ] Story
  - [ ] API description
  - [ ] Cheatsheet
  - [ ] Other (explain)
- 🔬 Change is tested
  - [ ] Component
  - [ ] Visual test

2020-11-01 13:38 UTC, WixBuildServer commented
### 🤖 Hi, I'm #Janet!

  A deploy preview of your PR was successfully released 🖼.

  You can find it under one of the following URLs:
  * https://preview.wix-style-react.com/pr_6157

2020-11-01 18:26 UTC, shlomitc requested changes

2020-11-01 18:26 UTC, shlomitc commented on src/Themes/businessDashboard/foundations/typography.st.css
> +@st-global-custom-property --wsr-font-family, --wsr-font-weight-bold;
not needed. if you know the specific font weights, simply apply them

2020-11-01 18:26 UTC, shlomitc commented on src/Themes/businessDashboard/foundations/typography.st.css
> +  -st-mixin: heading-h2, weight-mixin(weight var(--wsr-font-weight-bold, 400));
If this is the same as the original h2, then no need to redeclare it.
If only a specific property is needed, you can apply it.
for example, if you need a different weight, you can simply import the `thin`/`normal`/`bold` tokens from the foundation directory

2020-11-01 18:26 UTC, shlomitc commented on src/Themes/businessDashboard/foundations/typography.st.css
> +  -st-named: heading-h3, heading-h4, heading-h5, weight-mixin, font-mixin;
From the stylable docs, you can rename the variables when imported. this means you are not bound to the variables and your tokens can be called `heading-h*`

```suggestion
  -st-named: heading-h3 as heading-h3-original, heading-h4 as heading-h4--original, heading-h5 as heading-h5-original, weight-mixin, font-mixin;
```


![image](https://user-images.githubusercontent.com/6093192/97810869-a0da0880-1c7f-11eb-9a96-74c1a641d34d.png)

2020-11-01 18:26 UTC, shlomitc commented on src/Themes/businessDashboard/foundations/typography.st.css
> +  -st-mixin: heading-h3, weight-mixin(weight var(--wsr-font-weight-bold, 400));
I'm actually not sure you even need to use `-st-mixin` here.
I think that simply applying the font size and line-height is enough.

the same for the rest of the styles

2020-11-01 18:26 UTC, shlomitc commented on src/Themes/businessDashboard/components/TextButton.st.css
> +  -st-mixin: weight-mixin(weight var(--wsr-font-weight-bold, 400));
I think you can simplify it.
instead of importing the `weight-mixin`, simply import the `thin`/`normal`/`bold` tokens from the foundation directory

2020-11-02 08:01 UTC, dimafeldman commented on src/Text/test/Text.visual.js
> +                  children={'ABCDEFGHIJKLMNOPQRSTUVWXYZ'}
I didn't change this one, it's just github diff is a bit confused. you can see that it just shifted down following the wrapping of `runTests`

2020-11-02 08:25 UTC, dimafeldman commented on src/Themes/businessDashboard/foundations/typography.st.css
> +  -st-named: heading-h3, heading-h4, heading-h5, weight-mixin, font-mixin;
thanks! it looks like I don't need it at all following your previous suggestions

2020-11-02 09:50 UTC, shlomitc approved these changes
perfect!

2020-11-02 09:50 UTC, merged