update <Text/> component to support ul circle list style and update o…
wix/wix-style-react pull request #6165
Opened 2020-11-02 14:55 UTC by michalavraham

…l margin

https://jira.wixpress.com/browse/DSM-941

### 🔦 Summary

...

### ✅ Checklist

- [ ] 👨‍🎨 UX change is approved by the Design System UX 
@milkyfruit

2020-11-02 15:04 UTC, WixBuildServer commented
### 🤖 Hi, I'm #Janet!

  A deploy preview of your PR was successfully released 🖼.

  You can find it under one of the following URLs:
  * https://preview.wix-style-react.com/pr_6165

2020-11-02 16:09 UTC, EgoziE requested changes
Please edit the last example to this:
```
<Text listStyle="checkmark">
  The list below is built using standard "ul"/"ol" and "li" HTML tags.
  <ul>
    <li>First list item</li>
    <li>Second list item</li>
    <li>Third list item</li>
  </ul>
  <ol>
    <li>First list item</li>
    <li>Second list item</li>
    <li>Third list item</li>
  </ol>
</Text>
```

With this description:
Text component provides a style for HTML based lists. Using the `listStyle` prop, an unordered list items can be styled as `checkmark` (default) or `circle `.

To add this change, check files:
`src/Text/docs/index.story.js`
`src/Text/docs/examples.js`

2020-11-04 16:06 UTC, milkyfruit requested changes
@michalavraham @EgoziE 


[Link to zeplin specs](https://app.zeplin.io/project/5c8f6f1f9f489505cac756dc/screen/5f8757c22297a49126132d83/)

Changelist:
- [ ] `<ul/>` with `size="medium"` and `listStyle="circle"` should use the icon in size of 24x24 instead of 22x22
![image](https://user-images.githubusercontent.com/1684587/98135009-06203a80-1ec8-11eb-91a1-3f6c06f470ea.png)
- [x] The distance between ol/ul list icon and the text should be 6px instead of 0.
- [ ] `<ul/>` with `size="small"` should use an icon with artboard of 18x18 instead of 24 (ConfirmSmall,  CircleSmallFilledSmall).
- [ ] `<ul/>` and `<ol/>` groups should have 6px top and bottom margins instead of 16px
- [ ] `<li/>` should have bottom margins set based on text size:
Medium - 6px, Small - 9px, Tiny - 6px (except the last one shhould have 0)
![image](https://user-images.githubusercontent.com/1684587/98133750-a6755f80-1ec6-11eb-915b-b6fa4a13fa14.png)
![image](https://user-images.githubusercontent.com/1684587/98133758-a9705000-1ec6-11eb-8876-f82461238c8a.png)
![image](https://user-images.githubusercontent.com/1684587/98133781-affec780-1ec6-11eb-868f-75f75537df46.png)
- [ ] `<p/>` should have 6px top and bottom margins

2020-11-10 09:59 UTC, milkyfruit approved these changes

2020-11-10 14:09 UTC, merged