<Search/> - fix value on blur
wix/wix-style-react pull request #6169
Opened 2020-11-03 10:07 UTC by daugerdas

### 🔦 Summary

If a custom `value` is set in `onBlur()`, expandable `<Search/>` does not change the `value` correctly when element loses focus 

[DSM-939](https://jira.wixpress.com/browse/DSM-939), Github issue #5818 

Issues:
- If `value` is set to `""` in `onBlur()` and `<Search/>` is expandable, the input becomes unresponsive after deleting/clearing text and element losing focus
- If `value` is set to a custom string in `onBlur()` and `<Search/>` is expandable, the input collapses and shows `onClear` button when element loses focus and there is no text in the input

This fix:
- Checks collapse logic in `_onBlur()` only after the state is updated when element loses focus

At first was thinking that the issue is if `value` is set to `null` in `onBlur()`, then the text in the input box does not change when element loses focus. So made a unit test and made a check if `null` is being assigned to `value` to add empty string instead. But probably `null` should not be used for `value` in a controlled component, so reverted it

2020-11-03 10:41 UTC, WixBuildServer commented
### 🤖 Hi, I'm #Janet!

  A deploy preview of your PR was successfully released 🖼.

  You can find it under one of the following URLs:
  * https://preview.wix-style-react.com/pr_6169

2020-11-03 12:48 UTC, daugerdas commented
Added commit 7b79e8d with a fix and unit test for an additional issue:
- If `value` is set to custom in `onBlur()` and `<Search/>` is controlled/expandable, when clicked on `clearButton`, `<Search/>` collapses and `clearButton` is displayed even though there is a default value in the input

![image](https://user-images.githubusercontent.com/14166408/97987212-933d9380-1de3-11eb-84ac-8f23ba754972.png)

This commit: Checks in `_onClear()` whether input is empty before collapsing it

2020-11-03 15:14 UTC, argshook requested changes

2020-11-03 15:14 UTC, argshook commented on src/Search/test/Search.spec.js
> +              this.setState({ value: '' });
this is real magic coming from the `makeControlled` utility, i'd suggest not to use it, cause it's not entirely clear what `this.setState` really does.

perhaps instead make a local reusable controlled version of Search and
reuse that, something like:

```
const MockSearch = () => {
  const [value, setValue] = React.useState('');

  return (
    <Search
      expandable
      value={value}
      onBlur={() => setValue('')}
    />
  );
};
```

2020-11-03 15:14 UTC, argshook commented on src/Search/test/Search.spec.js
> +        expect(await driver.isCollapsed()).toBe(true);
here, along other tests, it would be worthwhile to also check value in input with `inputDriver.getText()`

2020-11-03 15:18 UTC, argshook commented
> But probably null should not be used for value in a controlled component

correct, react throws a warning when `<input value={null}/>`:

```
Warning: `value` prop on `input` should not be null. Consider using an empty string to clear the component or `undefined` for uncontrolled components.
```

2020-11-04 10:22 UTC, daugerdas commented on src/Search/Search.js
> +    onBlur && (await onBlur(event));
currently was not able to come up with a better solution to this. Ideas that I had:
- to write `Promise` instead of async/await
- to handle collapse logic inside `componentDidUpdate()`, but then there should be a boolean to check if element is not in focus/might be not expected UI behaviour
- inside of `onBlur()` to check if `this._getIsControlled()` and then `setTimeout` to `0` for checking collapse logic

Was thinking that the best option would be to have a callback function in `setState()`, but in this case `setState()` would be defined inside `onBlur()`, so it is not accessible

2020-11-04 14:17 UTC, daugerdas commented on src/Search/test/Search.spec.js
> +              this.setState({ value: '' });
A question about reusable controlled version of Search - would be better to have a custom `onChange()` there (as in eda6b89)? I reverted it as I thought that may affect `test5:types` and it does not have an affect on current unit tests

2020-11-04 14:18 UTC, daugerdas commented
`test5:types` test is failing with the following error:
`error: Your local changes to the following files would be overwritten by checkout: src/Search/Search.js`
Error still exists after reverting last commit, a commit before that (9cd6b57) passed `test5:types`

2020-11-04 16:10 UTC, argshook commented on src/Search/test/Search.spec.js
> +              this.setState({ value: '' });
changes in `.spec.js` files have no impact on `test5:types`, there's likely some other issue.

regarding if it's better to have `onChange` or not, it's up to you, neither is better or worse.

2020-11-04 16:12 UTC, argshook commented on src/Search/test/Search.spec.js
> +              this.setState({ value: '' });
please try to pull latest `master` and rebase this branch on it. This should fix the `test5:types` issue

2020-11-05 09:17 UTC, argshook approved these changes
great effort!

2020-11-05 09:27 UTC, merged