<AddressInputOption/> - new component
wix/wix-style-react pull request #6191
Opened 2020-11-05 16:08 UTC by bamai

### 🔦 Summary

https://jira.wixpress.com/browse/DSM-624

### ✅ Checklist

- [ ] 👨‍💻 API change is approved by the UI Infra Developers 
- [ ] 👨‍🎨 UX change is approved by the Design System UX 
- 📚 Change is documented
  - [ ] Story
  - [ ] API description
  - [ ] Cheatsheet
  - [ ] Other (explain)
- 🔬 Change is tested
  - [ ] Component
  - [ ] Visual test

2020-11-08 12:17 UTC, WixBuildServer commented
### 🤖 Hi, I'm #Janet!

  A deploy preview of your PR was successfully released 🖼.

  You can find it under one of the following URLs:
  * https://preview.wix-style-react.com/pr_6191

2020-11-08 13:38 UTC, EgoziE requested changes
Also, long text should be truncated with ellipsis according to the spec

2020-11-08 13:38 UTC, EgoziE commented on src/AddressInput/AddressInput.js
> -        highlight
Please leave a comment with a TODO to fix once highlight is fixed

2020-11-08 13:38 UTC, EgoziE commented on src/AddressInputOption/AddressInputOption.uni.driver.js
> +    },
`getOptionLayout` is not needed here, this is a pure visual prop.
Therefore no need to test it with unit-tests.

2020-11-08 13:38 UTC, EgoziE commented on src/AddressInputOption/AddressInputOption.js
> +      <Box display="flex" margin="auto">
Box is `display="flex"` by default

2020-11-08 13:38 UTC, EgoziE commented on src/AddressInputOption/AddressInputOption.js
> +        prefix={<Box>{prefix}</Box>}
Why is it needed to wrap it inside a box?

2020-11-08 13:45 UTC, EgoziE requested changes

2020-11-08 13:45 UTC, EgoziE commented on src/AddressInputOption/docs/index.story.js
> +          importExample(),
Import example should show the builder too, take a look at `ListItemSelect` for reference.

2020-11-08 14:02 UTC, bamai commented on src/AddressInputOption/AddressInputOption.js
> +        prefix={<Box>{prefix}</Box>}
because otherwise the icons are not centered, this is how icons are used in the examples of ListItemSelect in storybook

2020-11-18 12:04 UTC, TalZa1810 commented on src/AddressInputOption/AddressInputOption.js
> +          optionLayout === OPTION_LAYOUT.DOUBLE_LINE &&
I think that this should be exported to a function like you did with the title

2020-11-18 12:05 UTC, TalZa1810 commented on src/AddressInputOption/AddressInputOption.js
> +  overrideStyle: true,
this should be changed to `overrideOptionStyle: true`

2020-11-18 12:10 UTC, TalZa1810 commented on src/AddressInputOption/AddressInputOption.js
> +          secondaryLabel && (
I think that the secondary label should be exported to a render function and than you can use it both in the `renderTitle` method and the return value.

2020-11-18 14:30 UTC, TalZa1810 commented on src/AddressInputOption/AddressInputOption.js
> +        {secondaryLabel && optionLayout === OPTION_LAYOUT.SINGLE_LINE && (
I would say that semantically the `secondaryLabel` should be used as the `ListItemSelect` subtitle. Ideally, IMHO, I would choose where to place it (single line or multiline) using stylable state. We should check whether it's possible with the current implementation of the `ListItemSelect` (maybe extending ListItemSelect styles and change a bit the current implementation to use css rather than a prop).
@EgoziE WDYT?

2020-11-19 10:55 UTC, TalZa1810 requested changes
Hi Mai,
I have some more comments regarding this PR. Also, I saw some issues with the playground:
![selected playground](https://user-images.githubusercontent.com/24567980/99652653-c2e5d000-2a60-11eb-9ab9-833284fa3dcd.png)
![disabled playground](https://user-images.githubusercontent.com/24567980/99652696-d1cc8280-2a60-11eb-8813-f549c323c1fe.png)
![disabled playgroubd](https://user-images.githubusercontent.com/24567980/99652731-ddb84480-2a60-11eb-8cc2-29a15d5c86e2.png)


After the fixes, I recommend asking a UX to go over the examples and descriptions to make sure that we agree on the examples and descriptions.

2020-11-19 10:55 UTC, TalZa1810 commented on src/AddressInputOption/index.d.ts
> +  selected?: boolean;
This should be getting from the `DropdownLayout` and not from the builder itself. 
```suggestion
```

2020-11-19 10:55 UTC, TalZa1810 commented on src/AddressInputOption/index.d.ts
> +  highlighted?: boolean;
This should be getting from the `DropdownLayout` and not from the builder itself.
```suggestion
```

2020-11-19 10:55 UTC, TalZa1810 commented on src/AddressInputOption/index.d.ts
> +  displayLabel?: string;
This should be changed to `label`.
```suggestion
  label?: string;
```

2020-11-19 10:55 UTC, TalZa1810 commented on src/AddressInputOption/test/AddressInputOption.tsx
> +  const { disabled, id, overrideOptionStyle, value } = addressInputOptionBuilder({
The builder returns also label

2020-11-19 10:55 UTC, TalZa1810 commented on src/AddressInputOption/docs/index.story.js
> +            text: 'Addresses can be displayed in a single line or double lines',
```suggestion
            text: 'Addresses can be displayed as a single line (default) or double lines',
```

2020-11-19 10:55 UTC, TalZa1810 commented on src/AddressInputOption/docs/examples.js
> +        mainLabel="main label"
```suggestion
        optionLayout="single-line"
        mainLabel="main label"
```

2020-11-19 10:55 UTC, TalZa1810 commented on src/AddressInputOption/docs/examples.js
> +      {id: 2, value: 'label 3' },
Why do we need this option example here?

2020-11-19 10:55 UTC, TalZa1810 commented on src/AddressInputOption/docs/examples.js
> +</Box>
no need to wrap this within Box if we use the `inContainer` prop

2020-11-19 10:55 UTC, TalZa1810 commented on src/AddressInputOption/docs/examples.js
> +    options={[
Maybe we can add here also an example of the Affixes usages.

2020-11-19 10:55 UTC, TalZa1810 commented on src/AddressInputOption/docs/index.story.js
> +            text: 'AddressInputOption can be created using builders.',
```suggestion
            text: All properties work together and can be combined in various ways. It can be rendered as standalone or as part of dropdown using builders.',
```

2020-11-19 10:55 UTC, TalZa1810 commented on src/AddressInputOption/docs/index.story.js
> +            title: 'builder example',
```suggestion
            title: 'Advanced Example',
```

2020-11-19 10:55 UTC, TalZa1810 commented on src/AddressInputOption/docs/index.story.js
> +    // https://github.com/wix/wix-ui/blob/master/packages/wix-storybook-utils/docs/usage.md#using-list
You can use this section to demonstrate more complex examples. for example a custom suffix / prefix etc. 
You can check out the wix-ui documentation to read more about it and check other examples that we have within the library as a reference.

2020-11-29 12:46 UTC, TalZa1810 requested changes
I've added some more comments and questions.

2020-11-29 12:46 UTC, TalZa1810 commented on src/AddressInputOption/AddressInputOption.js
> +        subtitle={<Text {...secondaryTextProps}>{secondaryLabel}</Text>}
Can we do that using purely css?

2020-11-29 12:46 UTC, TalZa1810 commented on src/AddressInputOption/AddressInputOption.js
> +        title={<Text {...textProps}>{mainLabel}</Text>}
same comment

2020-11-29 12:46 UTC, TalZa1810 commented on src/AddressInputOption/docs/examples.js
> +    {id: 2, value: 'label 3' },
Why do we need this example? it's not really related to `AddressInputOption`.

2020-11-29 12:46 UTC, TalZa1810 commented on src/AddressInputOption/docs/index.story.js
> +    prefix: <ToolBoxIcon />,
I would add here also the `optionLayout` prop

2020-11-29 12:46 UTC, TalZa1810 commented on src/AddressInputOption/docs/index.story.js
> +import { addressInputOptionBuilder } from 'wix-style-react';`),
Let's add a link to this documentation from the DropdownLayout page (just to the table with links).

2020-11-29 12:46 UTC, TalZa1810 commented on src/AddressInputOption/test/AddressInputOption.visual.js
> +        it: 'disabled with double line layout',
no need to add a test for the combination of double / single line with the disabled state.
They are not really related. you can add the disabled state to the previous `describe` and change the title to `option state`

2020-11-29 12:46 UTC, TalZa1810 commented on src/AddressInputOption/test/AddressInputOption.visual.js
> +        it: 'selected with secondary label',
This test is not really related to the option state. It can be removed. You can add the secondary label and affixes to all the options to test how the secondary label looks like for all possible option states.

2020-11-29 12:46 UTC, TalZa1810 commented on src/AddressInputOption/test/AddressInputOption.visual.js
> +      options={[
The builders should be wrapped with `DropdownLayout` and not `AddressInput`.
Let's make each option test something else instead of all options test the same scenario.
So it's basically a combination of-
option layout, prefix, suffix selected and disabled options.

2020-11-29 12:46 UTC, TalZa1810 commented on src/AddressInputOption/test/AddressInputOption.visual.js
> +        it: 'selected with suffix',
selected state is not really related to `Affixes` tests

2020-11-29 12:46 UTC, TalZa1810 commented on src/AddressInputOption/test/AddressInputOption.visual.js
> +        it: 'default',
```suggestion
        it: 'default',
        props: {},
```

2020-11-29 12:46 UTC, TalZa1810 commented on src/AddressInputOption/AddressInputOption.js
> +      showDelay: 300,
`Text` component doesn't have this prop. Have you referred to `enterDelay`?

2020-11-29 12:46 UTC, TalZa1810 commented on src/AddressInputOption/test/storySettings.js
> +  category: Category.COMPONENTS,
Maybe we should put this under WIP for now?
wdyt? @EgoziE

2020-11-29 13:00 UTC, EgoziE commented on src/AddressInputOption/test/storySettings.js
> +  category: Category.COMPONENTS,
I'm not against, but why?

2020-11-29 13:19 UTC, TalZa1810 commented on src/AddressInputOption/test/storySettings.js
> +  category: Category.COMPONENTS,
because we won't use this within AddressInput yet.

2020-11-29 14:11 UTC, EgoziE commented on src/AddressInputOption/test/storySettings.js
> +  category: Category.COMPONENTS,
Okay, make sure to add a reminder for users not to use it (like other components in WIP)

2020-12-02 15:40 UTC, gendeld commented on src/AddressInputOption/AddressInputOption.js
> +/** This component is responsible of transforming a given prediction object and display-props into a valid address option according to the UX guidelines. */
This doesn't transform a prediction object (?), there's no mapping of raw data.

2020-12-02 15:42 UTC, gendeld commented on src/AddressInputOption/AddressInputOption.js
> +        suffix={<Box>{suffix}</Box>}
Why the Box?

2020-12-02 15:44 UTC, gendeld commented on src/AddressInputOption/AddressInputOption.js
> +  /** Determines the options layout to display*/
Maybe explain more about what this means

2020-12-02 15:50 UTC, gendeld commented on src/AddressInputOption/AddressInputOption.js
> +  /** Shows the default location icon next to the option, can receive alternative prefix node or a `false` value to hide it.*/
You should write what the prop does first, not what the default behaviour is (comments are used to generate component API)

2020-12-03 10:02 UTC, bamai commented on src/AddressInputOption/AddressInputOption.js
> +        suffix={<Box>{suffix}</Box>}
the box makes sure that icons are centered, this is how it is documented in ListItemSelect storybook page

2020-12-03 12:18 UTC, TalZa1810 requested changes
Hi Mai,
I've added some more comments here.
After the fixes, please ask UX for a review of the descriptions and examples.
Also, let's make sure we understand how the ellipsis should be implemented when there are mainLabel and secondaryLabel. Please add the screenshots of what we've discussed here for transparency.

Thanks.

2020-12-03 12:18 UTC, TalZa1810 commented on src/AddressInputOption/AddressInputOption.js
> +  /** Whether to display `mainLabel` and `secondaryLabel` side by side (`single-line`) or one under the other (`double-line`)*/
```suggestion
  /** Sets the layout of `mainLabel` and `secondaryLabel`. The possible options can be either side by side: `single-line` or double lined: `double-line`*/
```

2020-12-03 12:18 UTC, TalZa1810 commented on src/AddressInputOption/AddressInputOption.js
> +  /** Shows provided node before option. Displays location icon by default.*/
```suggestion
  /** Sets the provided node as prefix.*/
```

Default value description is generated anyways when you set defaultProps.

2020-12-03 12:18 UTC, TalZa1810 commented on src/AddressInputOption/AddressInputOption.uni.driver.d.ts
> +  getMainLabel(): Promise<string>;
```suggestion
  getMainLabelText(): Promise<string>;
```

2020-12-03 12:18 UTC, TalZa1810 commented on src/AddressInputOption/AddressInputOption.uni.driver.d.ts
> +  getSecondaryLabel(): Promise<string>;
```suggestion
  getSecondaryLabelText(): Promise<string>;
```

2020-12-03 12:18 UTC, TalZa1810 commented on src/AddressInputOption/docs/index.story.js
> +              'This component is responsible of transforming a given prediction object and display-props into a valid address option according to the UX guidelines.',
Is this the description given by UX?

2020-12-03 12:18 UTC, TalZa1810 commented on src/AddressInputOption/docs/index.story.js
> +              'Component has prefix and suffix areas. Default prefix is location icon.',
is this the description given by UX?

2020-12-03 12:18 UTC, TalZa1810 commented on src/AddressInputOption/index.d.ts
> +  displayLabel?: string;
should be removed. part of the builder, not the component itself.

2020-12-03 12:18 UTC, TalZa1810 commented on src/AddressInputOption/test/AddressInputOption.tsx
> +      displayLabel='display label'
should be removed

2020-12-03 13:10 UTC, bamai commented on src/ListItemSelect/ListItemSelect.st.css
> +.subtitle{
I added it in order to add the subtitle className to ListItemSelect so that I can override it in AddressInputOption (without these lines classes.subtitle in js file doesn't work)

2020-12-03 13:49 UTC, bamai commented
I'm not sure what is the correct ellipsis behaviour. Currently this is how it looks like:
<img width="784" alt="Screen Shot 2020-12-03 at 10 37 20" src="https://user-images.githubusercontent.com/57489465/101025530-63b6ae00-357e-11eb-81b0-773a8af77727.png">
<img width="773" alt="Screen Shot 2020-12-03 at 15 48 23" src="https://user-images.githubusercontent.com/57489465/101026036-11c25800-357f-11eb-98c8-1ef3b2730ed1.png">


should it stay this way or should I change it to the following behaviour?
<img width="780" alt="Screen Shot 2020-12-03 at 10 40 34" src="https://user-images.githubusercontent.com/57489465/101025700-9bbdf100-357e-11eb-9100-9c0a32cf4b15.png">

2020-12-03 14:15 UTC, TalZa1810 commented on src/AddressInputOption/test/AddressInputOption.spec.js
> +    expect(await driver.getMainLabel()).toBe('label');
```suggestion
    expect(await driver.getMainLabelText()).toBe('label');
```

2020-12-03 14:17 UTC, TalZa1810 commented on src/AddressInputOption/test/AddressInputOption.spec.js
> +    expect(await driver.getSecondaryLabel()).toBe('secondary label');
```suggestion
    expect(await driver.getSecondaryLabelText()).toBe('secondary label');
```

2020-12-03 15:22 UTC, TalZa1810 commented on src/ListItemSelect/ListItemSelect.st.css
> +.subtitle{
As explained, no need to extend `Text` here, just adding a class.

2020-12-03 15:25 UTC, shlomitc commented on src/ListItemSelect/ListItemSelect.st.css
> +.subtitle{
if it's is sitting on a `Text` component, then it is a good practice to extend `Text`

2020-12-06 13:03 UTC, ayeletr commented
Hi, 
I checked the SB, here are some comments:
1. Why do we call it <AddressInputOption/>? can we call it Address Input Item?
2. Description: " this component is used to display an address item mainly in Address Input component."
3. question: who determine what content gos in the main label and what dos in the 2nd label? the vertical or is fixed option?

other then that - looks good to me :)

2020-12-09 10:03 UTC, TalZa1810 approved these changes
Few tiny comments regarding the descriptions. Can be committed from the PR itself. Afterwards, can be merged.

2020-12-09 11:19 UTC, merged