Adding circular progress bar label
wix/wix-style-react pull request #6192
Opened 2020-11-05 16:55 UTC by adicicurel

### 🔦 Summary

...

### ✅ Checklist

- [ ] 👨‍💻 API change is approved by the UI Infra Developers 
- [ ] 👨‍🎨 UX change is approved by the Design System UX 
- 📚 Change is documented
  - [ ] Story
  - [ ] API description
  - [ ] Cheatsheet
  - [ ] Other (explain)
- 🔬 Change is tested
  - [ ] Component
  - [ ] Visual test

2020-11-05 17:04 UTC, WixBuildServer commented
### 🤖 Hi, I'm #Janet!

  A deploy preview of your PR was successfully released 🖼.

  You can find it under one of the following URLs:
  * https://preview.wix-style-react.com/pr_6192

2020-11-05 17:34 UTC, shlomitc requested changes
Looks great!
one minor request for change + please add a visual test for the new label prop

2020-11-05 17:34 UTC, shlomitc commented on src/Themes/businessDashboard/docs/businessDashboard.story.js
> +export function createExample() {
looks like a mistake

2020-11-05 17:34 UTC, shlomitc commented on src/CircularProgressBar/docs/index.story.js
> +            description: 'Displaying a label in percentage.',
```suggestion
            description: 'Displaying a textual label',
```

2020-11-05 17:34 UTC, shlomitc commented on src/CircularProgressBar/docs/examples.js
> +  <CircularProgressBar label="1/5" showProgressIndication error errorMessage="some error" value={20} />
I think you can keep only this and remove the other examples

2020-11-05 17:43 UTC, adicicurel commented on src/CircularProgressBar/docs/examples.js
> +  <CircularProgressBar label="1/5" showProgressIndication error errorMessage="some error" value={20} />
i will remove the percentage, but the success is still valid.
Thanks

2020-11-05 17:46 UTC, adicicurel commented on src/Themes/businessDashboard/docs/businessDashboard.story.js
> +export function createExample() {
removed

2020-11-07 09:09 UTC, adicicurel commented
> Looks great!
> one minor request for change + please add a visual test for the new label prop

done

2020-11-08 07:50 UTC, merged