Add Business Dashboard theming for Sidebar Components
wix/wix-style-react pull request #6198
Opened 2020-11-08 13:50 UTC by ronenst

### 🔦 Summary

Add Business Dashboard theming for Sidebar Components 

### ✅ Checklist

- [x] 👨‍🎨 UX change is approved by the Design System UX 
- 📚 Change is documented
  - [x] Story
- 🔬 Change is tested
  - [x] Visual test

2020-11-08 15:07 UTC, shlomitc reviewed
Small comments while you're still working on it.
Also, please take the time to [sign your commits](https://github.com/wix/wix-style-react/blob/master/docs/contribution/CREATE_PR.md#sign-commits), CI won't run otherwise

2020-11-08 15:07 UTC, shlomitc commented on src/SidebarBackButton/SidebarBackButton.js
>                  classes.BackButton,
simply rename this in the stylable file to `.root`. it will be consistent with the rest of the components and won't require an additional class

2020-11-08 15:07 UTC, shlomitc commented on src/Themes/businessDashboard/docs/components/Sidebar.js
> +  <ThemeProvider theme={theme({ active: true })}>
you can ditch the `active`, it is active by default

2020-11-08 15:22 UTC, WixBuildServer commented
### 🤖 Hi, I'm #Janet!

  A deploy preview of your PR was successfully released 🖼.

  You can find it under one of the following URLs:
  * https://preview.wix-style-react.com/pr_6198

2020-11-09 09:06 UTC, shlomitc requested changes

2020-11-09 09:15 UTC, ronenst commented on src/Sidebar/Sidebar.js
>      const css = { ...defaultCss, ...this.props.classNames };
I could but I'd need to rename `classes.gradient` and `classes.slider`, should I?

2020-11-09 09:35 UTC, ronenst commented on src/Sidebar/Sidebar.js
> +    );
Tried this, but using classnames as property keys with boolean values for `st()` doesn't work, I think it's only meant for states?

That is: `st({ [css.sideBar]: true }) === st({ [classes.root]: true }) === ''`

2020-11-09 10:23 UTC, shlomitc commented on src/Sidebar/Sidebar.js
> +    );
you're right, they are not stylable states. darn. ok so you can do something like this:
```js
const rootClasses = st(
  css.root,
  classNames(
    css.sidebar,
    {
      [css.hiddenSideBar]: this.props.isHidden,
      [css.light]: this.props.skin === sidebarSkins.light,
    }
  )
);
```

2020-11-09 10:36 UTC, shlomitc commented on src/Sidebar/Sidebar.js
>      const css = { ...defaultCss, ...this.props.classNames };
It's not that great that we still have `gradient` both in the `scss` and in the `.st.css` files. I'd put them both in the `scss` and then it won't override each other. Basically, it means just moving this part:
```scss
.gradient {
  height: $gradientHeight;
  min-height: $gradientHeight;
  position: -webkit-sticky;
  position: sticky;
  bottom: 0;
  background-image: linear-gradient(to bottom, $gradientColor , $mainBackgroundColor);
  pointer-events: none;

  &.light {
    background-image: linear-gradient(to bottom, rgba($D80, 0), $D80);
  }
}
```

if it's too complex, then you can keep it as `classes`

2020-11-10 08:56 UTC, ronenst commented
@shlomitc I converted `<Sidebar/>` to stylable, it didn't turn out ideal because I need to use the classNames instead of states for the slider animation classes.

I'm actually not sure why the `classNames` prop exists really, I don't think it's used and it's not really how WSR works?

Even so, maybe classess should be added, not replace the existing classes...

2020-11-10 10:07 UTC, ronenst commented
There are two failing visual tests for sidebar, but it looks like the problem is actually in the baseline image? Unless I'm mixing them up? In the storybook of the PR 

The test based on this:
https://github.com/wix/wix-style-react/blob/master/src/Sidebar/test/Sidebar.visual.js#L113

https://wixeyes.applitools.com/app/test-results/00000251797301950001/00000251797300358330/steps/1?accountId=mE99eP8CUn9UTSXSv98L3OSaJ0NZmAcY6Wndx6WSHODdY110&mode=step-editor

2020-11-10 10:23 UTC, ronenst commented
actually nvm checking an issue with the skins...

2020-11-10 11:43 UTC, ronenst commented
These still seem relevant:

> There are two failing visual tests for sidebar, but it looks like the problem is actually in the baseline image? Unless I'm mixing them up? In the storybook of the PR
> 
> For the light skin test here:
> [https://github.com/wix/wix-style-react/blob/master/src/Sidebar/test/Sidebar.visual.js#L50](https://github.com/wix/wix-style-react/blob/master/src/Sidebar/test/Sidebar.visual.js?rgh-link-date=2020-11-10T10%3A07%3A06Z#L50)
> 
> This is the comparison:
> [wixeyes.applitools.com/app/test-results/00000251797301950001/00000251797300360331/steps/1?accountId=mE99eP8CUn9UTSXSv98L3OSaJ0NZmAcY6Wndx6WSHODdY110&mode=step-editor](https://wixeyes.applitools.com/app/test-results/00000251797301950001/00000251797300360331/steps/1?accountId=mE99eP8CUn9UTSXSv98L3OSaJ0NZmAcY6Wndx6WSHODdY110&mode=step-editor)
> 
> The test based on this which shows two skins side by side:
> [https://github.com/wix/wix-style-react/blob/master/src/Sidebar/test/Sidebar.visual.js#L113](https://github.com/wix/wix-style-react/blob/master/src/Sidebar/test/Sidebar.visual.js?rgh-link-date=2020-11-10T10%3A07%3A06Z#L113)
> 
> This is the comparison:
> [wixeyes.applitools.com/app/test-results/00000251797301950001/00000251797300358330/steps/1?accountId=mE99eP8CUn9UTSXSv98L3OSaJ0NZmAcY6Wndx6WSHODdY110&mode=step-editor](https://wixeyes.applitools.com/app/test-results/00000251797301950001/00000251797300358330/steps/1?accountId=mE99eP8CUn9UTSXSv98L3OSaJ0NZmAcY6Wndx6WSHODdY110&mode=step-editor)

2020-11-11 20:43 UTC, merged

2020-11-11 20:44 UTC, shlomitc commented
excellent job!