WIP Card theme
wix/wix-style-react pull request #6207
Opened 2020-11-09 15:06 UTC by dimafeldman

### 🔦 Summary

...

### ✅ Checklist

- [ ] 👨‍💻 API change is approved by the UI Infra Developers 
- [ ] 👨‍🎨 UX change is approved by the Design System UX 
- 📚 Change is documented
  - [ ] Story
  - [ ] API description
  - [ ] Cheatsheet
  - [ ] Other (explain)
- 🔬 Change is tested
  - [ ] Component
  - [ ] Visual test

2020-11-09 15:16 UTC, WixBuildServer commented
### 🤖 Hi, I'm #Janet!

  A deploy preview of your PR was successfully released 🖼.

  You can find it under one of the following URLs:
  * https://preview.wix-style-react.com/pr_6207

2020-11-11 21:20 UTC, shlomitc requested changes

2020-11-11 21:20 UTC, shlomitc commented on src/Themes/businessDashboard/components/Card/Header.st.css
> +.root::titleWrapper h3 {
targeting the tag element like `h3` isn't a good idea. We always need to target the public apis as exposed in the stylesheet.

Can't you simply add margins to the `titleWrapper`? if so, then that's the easy solution.
If not, you'll need to do the following small change in the Card Header component: https://github.com/wix/wix-style-react/blob/77a62db25539472f397a4ce7b16738ac6e31c939/src/Card/Header/Header.js#L38
you'll need to add a className here:
```jsx
<Heading
  dataHook={DataHooks.title}
  className={classes.title}
  appearance="H3"
  children={title}
/>
```

an in the stylable file of it, just expose the right class
```css
:import {
  -st-from: "../../Heading/Heading.st.css"
  -st-default: Heading;
}
.title {
  -st-extends: Heading;
}
```

then change your selector to `.root::titleWrapper::title`

2020-11-12 08:45 UTC, dimafeldman commented on src/Themes/businessDashboard/components/Card/Header.st.css
> +.root::titleWrapper h3 {
Thanks @shlomitc !
I added the className as you suggested

2020-11-12 09:36 UTC, shlomitc commented on src/Themes/businessDashboard/test/businessDashboard.visual.js
> +<<<<<<< HEAD
looks like a wrong merge commit

2020-11-12 09:39 UTC, dimafeldman commented on src/Themes/businessDashboard/test/businessDashboard.visual.js
> +<<<<<<< HEAD
oh wow! fixing. sorry

2020-11-12 10:45 UTC, merged