<PageFooter/> - Component, CSS, Storybook and test
wix/wix-style-react pull request #6215
Opened 2020-11-10 09:31 UTC by omerbra

### 🔦 Summary

...

### ✅ Checklist

- [ ] 👨‍💻 API change is approved by the UI Infra Developers 
- [ ] 👨‍🎨 UX change is approved by the Design System UX 
- 📚 Change is documented
  - [ ] Story
  - [ ] API description
  - [ ] Cheatsheet
  - [ ] Other (explain)
- 🔬 Change is tested
  - [ ] Component
  - [ ] Visual test

2020-11-10 09:41 UTC, WixBuildServer commented
### 🤖 Hi, I'm #Janet!

  A deploy preview of your PR was successfully released 🖼.

  You can find it under one of the following URLs:
  * https://preview.wix-style-react.com/pr_6215

2020-11-10 15:41 UTC, EgoziE requested changes
1. File `src/PageFooter/constants.js` can be deleted
2. optional - you can add a "child verification" to make sure the component can render only intended containers (and one of each at most)

2020-11-10 15:41 UTC, EgoziE commented on src/PageFooter/test/PageFooter.tsx
> +      className="className"
Missing divider prop and all 3 sub components (with dummy content, an empty <div /> is enough)

2020-11-10 15:41 UTC, EgoziE commented on src/PageFooter/docs/index.story.js
> +      }),
Extract examples to a different file (example.js)
You can take any other component as reference

2020-11-10 15:41 UTC, EgoziE commented on src/PageFooter/PageFooter.js
> +  <>
This should be a real div with 'classes.root' (and rename the current root to "container" or something else)
This root element you need to contain `max-width` and margins.
(that's because the divider should be affected by this constraint too)

2020-11-11 15:29 UTC, EgoziE requested changes

2020-11-11 15:29 UTC, EgoziE commented on src/PageFooter/test/PageFooter.tsx
> +      <End />
I prefer you use `PageFooter.Start` explicitly so it won't confuse. Just "Start" is a bit too generic

2020-11-11 15:29 UTC, EgoziE commented on src/PageFooter/test/PageFooter.tsx
> +      <End />
```suggestion
      <PageFooter.Start children={<div />} />
      <PageFooter.Center children={<div />} />
      <PageFooter.End children={<div />} />
```

2020-11-11 16:11 UTC, milkyfruit requested changes
- [x] When all 3 cells are used and start, end cells are uneven, the center cell isn't aligned centered. It should be fixed.
- [x] When only `End` is set, it should align to the end
![image](https://user-images.githubusercontent.com/1684587/98834141-87874800-2447-11eb-8cb6-5e34e68d80fe.png)
- [x] When only `Center` is set, it should be centered
![image](https://user-images.githubusercontent.com/1684587/98834035-66bef280-2447-11eb-933b-38f61588b214.png)
- [x] When only 'Center' and 'End' are set, center cell should be centered, end cell should align to the end:
![image](https://user-images.githubusercontent.com/1684587/98835387-07fa7880-2449-11eb-8679-362d86bdd84f.png)
- [ ] [ComposerHeader sets margins for children automatically](https://www.wix-style-react.com/?path=/story/components-api-components--composerheader), it should do the same here.

2020-11-11 16:30 UTC, milkyfruit commented
### Description

### Examples

- [ ] **Structure**
```
<PageFooter>
  <PageFooter.Start>
    <Box border="dashed 1px" width="100%" align="center">
      start
    </Box>
  </PageFooter.Start>
  <PageFooter.Center>
    <Box border="dashed 1px" width="100%" align="center">
      center
    </Box>{' '}
  </PageFooter.Center>
  <PageFooter.End>
    <Box border="dashed 1px" width="100%" align="center">
      end
    </Box>
  </PageFooter.End>
</PageFooter>;
```

- [ ] **Divider**
```
<PageFooter divider>
  <PageFooter.Start>
    <Box border="dashed 1px" width="100%" align="center">
      start
    </Box>
  </PageFooter.Start>
  <PageFooter.Center>
    <Box border="dashed 1px" width="100%" align="center">
      center
    </Box>{' '}
  </PageFooter.Center>
  <PageFooter.End>
    <Box border="dashed 1px" width="100%" align="center">
      end
    </Box>
  </PageFooter.End>
</PageFooter>;
```
- [ ] Usage
```
<Layout cols={1}>
  <PageFooter>
    <PageFooter.Center>
      <Pagination currentPage={4} totalPages={7} />
    </PageFooter.Center>
  </PageFooter>
  <PageFooter>
    <PageFooter.End>
      <Button size="medium" priority="secondary">
        Cancel
      </Button>
      <Button size="medium">Save</Button>
    </PageFooter.End>
  </PageFooter>
  <PageFooter>
    <PageFooter.Start>
      <Button size="medium" skin="inverted" prefixIcon={<Icons.ArrowLeft />}>
        Go Back
      </Button>
    </PageFooter.Start>
    <PageFooter.End>
      <Button size="medium" priority="secondary">
        Skip
      </Button>
      <Button size="medium">Go Next</Button>
    </PageFooter.End>
  </PageFooter>
</Layout>;
```

- [ ] Advanced Example
```
<Page>
  <Page.Header
    title="Page Title"
    onBackClicked={() => alert('cool')}
    actionsBar={
      <Box>
        <Button priority="secondary">Cancel</Button>
        <Box marginLeft="SP2">
          <Button>Save</Button>
        </Box>
      </Box>
    }
  />
  <Page.Content>
    <Layout>
    <Cell span={12}>
    <Card>
      <Card.Header title="Card Title"></Card.Header>
      <Divider />
      <Card.Content>
        <Box border="dashed 1px" padding="SP6">
          Card Content
        </Box>
      </Card.Content>
    </Card>
    </Cell>
    <Cell span={12}>
    <PageFooter>
      <PageFooter.End>
        <Box marginRight="SP2">
          <Button size="medium" priority="secondary">
            Cancel
          </Button>
        </Box>
        <Button size="medium">Save</Button>
      </PageFooter.End>
    </PageFooter>
    </Cell>
    </Layout>
  </Page.Content>
</Page>;
```

2020-11-11 16:40 UTC, milkyfruit commented
@omerbra @EgoziE I added descriptions and examples in the comment above.

2020-11-12 13:34 UTC, EgoziE approved these changes

2020-11-12 15:00 UTC, milkyfruit reviewed
Great work @omerbra and @EgoziE! Let's change this example's layout to coast to coast and we're good to merge:
![image](https://user-images.githubusercontent.com/1684587/98956195-69cde780-2508-11eb-97f2-07e279208c5b.png)

Learn what's coast to coast example in Page component story:
https://www.wix-style-react.com/?path=/story/components-api-components--page

2020-11-12 15:58 UTC, milkyfruit approved these changes

2020-11-12 16:00 UTC, merged