<AutoCompleteWithLabel/> - Added maxHeightPixel property
wix/wix-style-react pull request #6217
Opened 2020-11-10 10:19 UTC by omerbra

### 🔦 Summary

...

### ✅ Checklist

- [ ] 👨‍💻 API change is approved by the UI Infra Developers 
- [ ] 👨‍🎨 UX change is approved by the Design System UX 
- 📚 Change is documented
  - [ ] Story
  - [ ] API description
  - [ ] Cheatsheet
  - [ ] Other (explain)
- 🔬 Change is tested
  - [ ] Component
  - [ ] Visual test

2020-11-10 10:30 UTC, WixBuildServer commented
### 🤖 Hi, I'm #Janet!

  A deploy preview of your PR was successfully released 🖼.

  You can find it under one of the following URLs:
  * https://preview.wix-style-react.com/pr_6217

2020-11-10 13:49 UTC, EgoziE requested changes
Add this prop to:
1. `static propTypes` (in the same file) + comment explaining what this prop is
2. Type definition - in file `index.d.ts`
3. Type test - in file `AutoCompleteWithLabel.tsx`

2020-11-10 21:07 UTC, EgoziE approved these changes

2020-11-11 10:06 UTC, EgoziE approved these changes

2020-11-11 11:31 UTC, merged