Business dashboard theming for ListItemAction & ListItemSection
wix/wix-style-react pull request #6228
Opened 2020-11-11 11:55 UTC by dimafeldman

### 🔦 Summary

...

### ✅ Checklist

- [ ] 👨‍💻 API change is approved by the UI Infra Developers 
- [ ] 👨‍🎨 UX change is approved by the Design System UX 
- 📚 Change is documented
  - [ ] Story
  - [ ] API description
  - [ ] Cheatsheet
  - [ ] Other (explain)
- 🔬 Change is tested
  - [ ] Component
  - [ ] Visual test

2020-11-11 12:05 UTC, WixBuildServer commented
### 🤖 Hi, I'm #Janet!

  A deploy preview of your PR was successfully released 🖼.

  You can find it under one of the following URLs:
  * https://preview.wix-style-react.com/pr_6228

2020-11-16 17:28 UTC, shlomitc requested changes

2020-11-16 17:28 UTC, shlomitc commented on src/PopoverMenu/PopoverMenu.js
> +      <ThemeProviderConsumerBackwardCompatible>
this solution should be applied in the `Popover` component instead

2020-11-16 17:28 UTC, shlomitc commented on src/Themes/businessDashboard/docs/components/ListItemAction.js
> +    >
remove

2020-11-16 17:28 UTC, shlomitc commented on src/Themes/businessDashboard/docs/components/ListItemAction.js
> +        visible
add `inContainer`

2020-11-16 17:28 UTC, shlomitc commented on src/Themes/businessDashboard/components/DropdownLayout.st.css
> +}
redundant

2020-11-16 18:02 UTC, shlomitc commented on src/Themes/businessDashboard/BusinessDashboard.st.css
> +  PopoverMenu.root {
I think that once this is done in the `Popover` component, then change it to `Popover`

2020-11-16 18:16 UTC, shlomitc commented on src/Themes/businessDashboard/components/DropdownLayout.st.css
> +.root::options::-webkit-scrollbar-thumb {
I think you need to control also the `::-webkit-scrollbar`. it seems like the width is too big.
![image](https://user-images.githubusercontent.com/6093192/99291547-abcc9580-2848-11eb-8a40-6edb48ebe5a8.png)

2020-11-17 08:35 UTC, dimafeldman commented on src/Themes/businessDashboard/components/DropdownLayout.st.css
> +.root::options::-webkit-scrollbar-thumb {
fixed

2020-11-17 09:54 UTC, merged