Feat/styled nestable list
wix/wix-style-react pull request #6231
Opened 2020-11-11 12:12 UTC by AndriiTsarenko

### 🔦 Summary

...

### ✅ Checklist

- [ ] 👨‍💻 API change is approved by the UI Infra Developers 
- [ ] 👨‍🎨 UX change is approved by the Design System UX 
- 📚 Change is documented
  - [ ] Story
  - [ ] API description
  - [ ] Cheatsheet
  - [ ] Other (explain)
- 🔬 Change is tested
  - [ ] Component
  - [ ] Visual test

2020-11-11 12:21 UTC, WixBuildServer commented
### 🤖 Hi, I'm #Janet!

  A deploy preview of your PR was successfully released 🖼.

  You can find it under one of the following URLs:
  * https://preview.wix-style-react.com/pr_6231

2020-11-12 17:58 UTC, EgoziE requested changes
Thanks for this PR! You did an amazing job!

I wrote some inline comments, just one more thing which is not critical but if you have the time it can be nice to have:
We use Stylable as our css preprocessor, so some best practices you know from scss doesn't apply here.
So instead of using "classnames" for conditional styling, we use Stylable states.
For example:
Instead of:
```
        <div
          className={classNames(classes.verticalArrow, {
            [classes.lastItemVerticalArrow]: isLastChild,
            [classes.previewArrows]: isPreview,
          })}
        >
```

You should write:
```
        <div
          className={st(classes.verticalArrow, {
            lastChild: isLastChild,
            preview: isPreview,
          })}
        >
```
And the css should be something like:
```
.verticalArrow {
  -st-states: lastChild, preview;
}

.verticalArrow:lastChild { ... }

.verticalArrow:preview { ... }
```

2020-11-12 17:58 UTC, EgoziE commented on src/StyledNestableList/docs/index.story.js
> +              'This line here should briefly describe component in just a sentence or two. It should be short and easy to read.',
```suggestion
              'A styled list with drag and drop and nesting capabilities.',
```

2020-11-12 17:58 UTC, EgoziE commented on stories/index.js
> +require('../src/StyledNestableList/docs/index.story');
Move it up under Components API

2020-11-12 17:58 UTC, EgoziE commented on src/StyledNestableList/StyledNestableList.uni.driver.d.ts
> +  getButtonText(): Promise<string>;
Should be removed

2020-11-12 17:58 UTC, EgoziE commented on src/StyledNestableList/StyledNestableList.uni.driver.js
> +      findByHook(base, dataHooks.styledNestableListButton).text(),
Should be removed

2020-11-12 17:58 UTC, EgoziE commented on src/StyledNestableList/StyledNestableList.st.css
> +  background-color: white;
Please change to D80

2020-11-12 17:58 UTC, EgoziE commented on src/StyledNestableList/StyledNestableList.st.css
> +}
Empty classes are removed on build, please remove them or add any style property to them

2020-11-12 17:58 UTC, EgoziE commented on src/StyledNestableList/StyledNestableList.js
> +  renderArrow = ({ isLastChild = false, isPreview = false, depth } = {}) => {
depth is not used, should it be?

2020-11-12 17:58 UTC, EgoziE commented on src/StyledNestableList/StyledNestableList.js
> +          display={'block'}
Change to a simple div with a className

2020-11-12 17:58 UTC, EgoziE commented on src/StyledNestableList/StyledNestableList.js
> +  renderArrow = ({ isLastChild = false, isPreview = false, depth } = {}) => {
Add an underscore to all functions to mark them as private
e.g.
renderArrow => _ renderArrow

2020-11-12 17:58 UTC, EgoziE commented on src/StyledNestableList/StyledNestableList.js
> +  items: PropTypes.arrayOf(NodeShape),
Unfortunately our AutoDocs doesn't know how to display complex types, so just write it down as a comment
```suggestion
  /**
   * * __id__ - Specifies the item id
   * * __isCollapsed__ - Whether to render the items children
   * * __children__ - A list of children of type item
   * * All other TableListItem props
   */
  items: PropTypes.arrayOf(NodeShape),
```

2020-11-16 13:40 UTC, milkyfruit commented
That's amazing, Andrii!
I've a bunch of questions, please don't be scared.
- [ ] Component has a prop `preventChangeDepth`, however it still allows to leave the parent and move to another parent. Do you think we should have another prop, which would restrict that?
- [ ] `addItemLabel` Does it allow to apply different labels to separate add items? I see there might be a need for that.
- [ ] If nesting is restricted (maxDepth is set to 1), how can I expose "add Item"?

2020-11-16 14:05 UTC, justinara requested changes
Great job so far! But I have quite a few comments from my side.. some are minor and small adjustments, some a little more complex:

- [x] Picked up item should have a hover style (table list item with B50 background colour and drag handle in colour B10)
- [x] Picked up item is missing drop shadow https://drive.google.com/open?id=1FrKXSjJGD3xZRh4gwcnWBJzlWQiXYL1z
- [x] Picked up item has a 1px border from all sides. Should not have that
<img width="818" alt="Screenshot at Nov 16 15-33-48" src="https://user-images.githubusercontent.com/67683352/99258390-297cab00-2821-11eb-8f62-70ad389f1e34.png">

- [ ] Cursor should be `grabbing` type  once item is picked up and dragged

![image](https://user-images.githubusercontent.com/67683352/99258443-42855c00-2821-11eb-8094-662bde4e7dca.png)

- [x] At the moment I'm not able to hide bottom divider line for last item on the list using table list item prop `showDivider={false}` - it doesn't work :/

- [x] Children items should collapse once parent item is picked up: https://drive.google.com/open?id=19QxLIXD2cOKK9GFwxAJUrUCyrFp1yoEg - this should include "Add new" as well

- [x] When changing the level of an item, arrow icon should be displayed on a grey drop target background: 

![image](https://user-images.githubusercontent.com/67683352/99259404-a0ff0a00-2822-11eb-894a-1b081cc3e675.png). animated preview: https://drive.google.com/open?id=1yYIDS1jkKLT07S4eG6-MJZr146Y5qIMO

- [ ] Missing animations in general. Items should slide vertically as per preview here: https://drive.google.com/open?id=1GYnjdaKI6sMkLXpteDOl01pfFE5ZYXZa. Sliding on y axis starts once picked up item reaches the middle of an item below/above it.

- [ ] `Prevent nodes from dragging with drag disabled icon` example doesn't work as expected. If item has `draggable`: true and `dragDisabled`:true,  you should not be able to drag and change the location of that specific item. But you can at the moment: 

![image](https://user-images.githubusercontent.com/67683352/99260521-2afba280-2824-11eb-9c00-9cfb19816267.png)

- [ ] Drop target change to third level happens too early, it it displayed once second level should be shown only: 

![image](https://user-images.githubusercontent.com/67683352/99261187-081dbe00-2825-11eb-8766-fda60997ffc4.png) 
Please follow these guidelines : 
![image](https://user-images.githubusercontent.com/67683352/99261216-1370e980-2825-11eb-91e6-a545e4f4117d.png)

Please also check animations section in zeplin specs, and previews here: https://drive.google.com/open?id=1x54N2459v-6aCZbTXfwXLhMJGRFh0RAA

2020-11-16 14:26 UTC, justinara commented
Also, another question - would it be possible to add keyboard accessibility in this effort as well? Drag grip can be focused once user navigates through page with TAB key click:
![image](https://user-images.githubusercontent.com/67683352/99263053-6055bf80-2827-11eb-863b-beb2a6176977.png)

How can it be picked up and reordered?
1. Item is picked up by ENTER key click (keeps focus on drag grip, has a hover style of list item and a shadow): 
![image](https://user-images.githubusercontent.com/67683352/99263278-a743b500-2827-11eb-866c-8e8a84eb4d03.png)
2. You can move it up on the same level with ARROW UP
3. You can move it down on the same level with ARROW DOWN
4. You can make it a child item by pressing on ARROW RIGHT
5. You can change its level from child to parent by pressing ARROW LEFT
6. Item is released / submitted to new spot on ENTER click as well.

Thoughts on how much development time that would require?

2020-11-18 08:30 UTC, AndriiTsarenko commented
Draggable, drag disabled, and read-only I did like so:
On item:
draggable: true - draggable and with drag icon
draggable: false - is not draggable and disabled drag icon
by default draggable is true.

On component
readOnly - readOnly mode
@milkyfruit

2020-11-18 09:14 UTC, milkyfruit commented
> Draggable, drag disabled, and read-only I did like so:
> On item:
> draggable: true - draggable and with drag icon
> draggable: false - is not draggable and disabled drag icon
> by default draggable is true.
> 
> On component
> readOnly - readOnly mode
> @milkyfruit

Looks great, @AndriiTsarenko ! We can move the story to WIP folder and then merge it:
![image](https://user-images.githubusercontent.com/1684587/99509627-abd6ad80-298e-11eb-9445-b7ff3fa16de0.png)
This way you'll be able to start using in your project, and once @justinara comments are resolved the story will be moved to Components folder.

2020-11-18 12:27 UTC, merged

2020-12-21 12:44 UTC, AndriiTsarenko commented on src/StyledNestableList/StyledNestableList.st.css
> +}
Done in 
https://github.com/wix/wix-style-react/pull/6416