Updated font version in stylesheet imports
wix/wix-style-react pull request #6232
Opened 2020-11-11 12:24 UTC by Zivilekin

### 🔦 Summary

In stylesheet imports @wix/wix-fonts updated to 1.10.0

2020-11-11 12:33 UTC, WixBuildServer commented
### 🤖 Hi, I'm #Janet!

  A deploy preview of your PR was successfully released 🖼.

  You can find it under one of the following URLs:
  * https://preview.wix-style-react.com/pr_6232

2020-11-11 12:40 UTC, EgoziE requested changes

2020-11-11 12:40 UTC, EgoziE commented on .storybook/visual/preview-head.html
> +  href="//static.parastorage.com/unpkg/@wix/wix-fonts@1.10.0/media/WixMadeforTextVF_W_Wght.9b7def89.woff2"
I don't think this is the correct file, when you released the new version the hash changed.
Please check it

2020-11-16 11:20 UTC, mykas approved these changes
Double checked it. Seems it works well.

2020-11-16 11:20 UTC, merged