<NumberInput /> - add hideStepper property
wix/wix-style-react pull request #6233
Opened 2020-11-11 12:29 UTC by Oripi

### 🔦 Summary

This adds a property `hideStepper` that hides the stepper (up/down arrows) when the property is set to `true` and a `suffix` or `prefix` element is provided.
The idea is to use the component for price inputs, to get all `Number` functionality without the irrelevant stepper behaviour.
slack discussion here: https://wix.slack.com/archives/CR7P4A1UP/p1604846942007600

### ✅ Checklist

- [] 👨‍💻 API change is approved by the UI Infra Developers  
- [x] 👨‍🎨 UX change is approved by the Design System UX @assafzi 
- 📚 Change is documented
  - [x] Story
  - [x] API description
  - [ ] Cheatsheet
  - [ ] Other (explain)
- 🔬 Change is tested
  - [ ] Component
  - [x] Visual test

2020-11-11 12:39 UTC, WixBuildServer commented
### 🤖 Hi, I'm #Janet!

  A deploy preview of your PR was successfully released 🖼.

  You can find it under one of the following URLs:
  * https://preview.wix-style-react.com/pr_6233

2020-11-11 16:46 UTC, EgoziE requested changes

2020-11-11 16:46 UTC, EgoziE commented on src/NumberInput/NumberInput.js
> +            {!(hideStepper && (suffix || prefix)) && (
This logic is just a UX guideline.
We cannot have one prop to affect another's functionality, only `hideStepper={true}` should hide the stepper regardless suffix / prefix.

2020-11-11 16:46 UTC, EgoziE commented on src/NumberInput/NumberInput.js
> +  /** If set to true - hides the stepper. A `suffix` or a `prefix` must be provided to hide the stepper */
Also change the description

2020-11-11 17:12 UTC, Oripi commented on src/NumberInput/NumberInput.js
> +            {!(hideStepper && (suffix || prefix)) && (
that's not what @assafzi said. according to him something similar happens in `ColorPicker`

2020-11-11 17:13 UTC, Oripi commented on src/NumberInput/NumberInput.js
> +            {!(hideStepper && (suffix || prefix)) && (
generally i prefer it like this too (why force something like this...?) but he needs to approve it

2020-11-11 17:13 UTC, Oripi commented on src/NumberInput/NumberInput.js
> +  /** If set to true - hides the stepper. A `suffix` or a `prefix` must be provided to hide the stepper */
if we change the above i'll change this too

2020-11-11 17:15 UTC, EgoziE commented on src/NumberInput/NumberInput.js
> +            {!(hideStepper && (suffix || prefix)) && (
I spoke with @milkyfruit about it, not everything that is right for UX is right for dev

2020-11-12 09:04 UTC, assafzi commented on src/NumberInput/NumberInput.js
> +            {!(hideStepper && (suffix || prefix)) && (
Spoke with @milkyfruit and Ayelet. Let's keep it as @EgoziE said, but please add an example of this with something like "When stepper is hidden you should display other numerical visual clues like affix/suffix".
That's acceptable @EgoziE ?

2020-11-12 09:06 UTC, EgoziE commented on src/NumberInput/NumberInput.js
> +            {!(hideStepper && (suffix || prefix)) && (
@assafzi Let's not leave documentation for contributors.
Can you please write the full example with description? then Ori will add it to the PR

2020-11-14 20:25 UTC, assafzi commented on src/NumberInput/NumberInput.js
> +            {!(hideStepper && (suffix || prefix)) && (
Sure!

### Title
Hide Stepper

### Description
In order to keep the component's functionality, another visual clue should be added, such as prefix or suffix.

### Example
`<NumberInput hideStepper prefix={<Input.Affix>$</Input.Affix>} placeholder="0" />`


@EgoziE is it OK?

2020-11-15 14:50 UTC, EgoziE approved these changes

2020-11-15 15:19 UTC, merged