<Page/> - migrate to Stylable
wix/wix-style-react pull request #6241
Opened 2020-11-12 15:53 UTC by daugerdas

### 🔦 Summary

Migrate `<Page/>` to Stylable

Description: [DSM-1052](https://jira.wixpress.com/browse/DSM-1052)

2020-11-12 16:06 UTC, WixBuildServer commented
### 🤖 Hi, I'm #Janet!

  A deploy preview of your PR was successfully released 🖼.

  You can find it under one of the following URLs:
  * https://preview.wix-style-react.com/pr_6241

2020-11-13 12:36 UTC, mykas requested changes

2020-11-13 12:36 UTC, mykas commented on src/Page/Page.js
> +          className={`${classes.gradientBackground} ${this.props.gradientClassName}`}
Lets use here `st` command to merge classnames.

2020-11-13 12:36 UTC, mykas commented on src/Page/Page.st.css
> +
lets remove empty spaces

2020-11-13 12:36 UTC, mykas commented on src/Page/Page.st.css
> +
lets remove this space

2020-11-13 12:39 UTC, mykas commented on src/Page/Page.st.css
> +
lets remove the space

2020-11-13 12:50 UTC, mykas commented on src/Page/Page.st.css
> +  /* Should be synced with JS Page value */
Maybe could be achieved through this: https://stylable.io/docs/guides/runtime

2020-11-16 08:04 UTC, mykas approved these changes
Good job! 🏆  Let's test this before meging as we talked about in projects that use this component.

2020-11-16 13:06 UTC, merged