Added an option to theme the CircularProgressBar success icon
wix/wix-style-react pull request #6251
Opened 2020-11-15 18:50 UTC by dimafeldman

### 🔦 Summary

...

### ✅ Checklist

- [ ] 👨‍💻 API change is approved by the UI Infra Developers 
- [ ] 👨‍🎨 UX change is approved by the Design System UX 
- 📚 Change is documented
  - [ ] Story
  - [ ] API description
  - [ ] Cheatsheet
  - [ ] Other (explain)
- 🔬 Change is tested
  - [ ] Component
  - [ ] Visual test

2020-11-15 19:00 UTC, WixBuildServer commented
### 🤖 Hi, I'm #Janet!

  A deploy preview of your PR was successfully released 🖼.

  You can find it under one of the following URLs:
  * https://preview.wix-style-react.com/pr_6251

2020-11-16 07:50 UTC, shlomitc requested changes

2020-11-16 07:50 UTC, shlomitc commented on src/ThemeProvider/test/ThemeProvider.tsx
> +          CircleLoaderCheck: {
this should be named the same as the component name and not as the icon name

2020-11-16 07:50 UTC, shlomitc commented on src/Themes/businessDashboard/icons/CircleLoaderCheck.js
> +          id="Path-2"
remove

2020-11-16 07:50 UTC, shlomitc commented on src/Themes/businessDashboard/icons/CircleLoaderCheck.js
> +      <g transform="translate(-18.000000, -21.000000)" fill="currentcolor">
remove all properties. maybe the "transform" can stay but, but all fill and stroke rules should be removed.
The guidelines for a well-structured SVG can be found here: https://github.com/wix/wix-ui/tree/master/packages/wix-ui-icons-common#guidelines

2020-11-16 07:50 UTC, shlomitc commented on src/Themes/businessDashboard/icons/CircleLoaderCheck.js
> +  <svg
add `fill="currentcolor"`

2020-11-16 08:01 UTC, dimafeldman commented on src/ThemeProvider/test/ThemeProvider.tsx
> +          CircleLoaderCheck: {
updated. but what about cases where we will need to update multiple icons for the same component? a multiple level object?

2020-11-16 08:12 UTC, shlomitc commented on src/ThemeProvider/test/ThemeProvider.tsx
> +          CircleLoaderCheck: {
in that case, we nest the different icons. for example: https://github.com/wix/wix-style-react/blob/95bf74694cb0b9c3d44d5f2dd118405c4a27939a/src/ThemeProvider/index.d.ts#L12

2020-11-16 18:00 UTC, merged