Typography- medium weight
wix/wix-style-react pull request #6256
Opened 2020-11-16 14:52 UTC by TalZa1810

### 🔦 Summary
Adding medium weight to typography. Still in progress. Should be merged after https://github.com/wix-private/wix-fonts/pull/7

### ✅ Checklist

- [ ] 👨‍💻 API change is approved by the UI Infra Developers 
- [ ] 👨‍🎨 UX change is approved by the Design System UX 
- 📚 Change is documented
  - [ ] Story
  - [ ] API description
  - [ ] Cheatsheet
  - [ ] Other (explain)
- 🔬 Change is tested
  - [ ] Component
  - [ ] Visual test

2020-11-17 09:43 UTC, WixBuildServer commented
### 🤖 Hi, I'm #Janet!

  A deploy preview of your PR was successfully released 🖼.

  You can find it under one of the following URLs:
  * https://preview.wix-style-react.com/pr_6256

2020-11-17 17:10 UTC, EgoziE requested changes
Simi lev

2020-11-17 17:10 UTC, EgoziE commented on src/FontUpgrade/FontUpgrade.st.css
> +@st-global-custom-property --wsr-font-family, --wsr-font-weight-regular, --wsr-font-weight-medium , --wsr-font-weight-bold, --wix-font-stack, --wix-font-weight-regular, --wix-font-weight-bold;
```suggestion
@st-global-custom-property --wsr-font-family, --wsr-font-weight-regular, --wsr-font-weight-medium, --wsr-font-weight-bold;
@st-global-custom-property --wix-font-stack,  --wix-font-weight-regular, --wix-font-weight-medium, --wix-font-weight-bold;
```

2020-11-17 17:10 UTC, EgoziE commented on src/FontUpgrade/FontUpgrade.st.css
> +  --wsr-font-weight-medium: var(--wsr-font-weight-medium);
```suggestion
  --wsr-font-weight-medium: var(--wix-font-weight-medium);
```

2020-11-18 10:51 UTC, TalZa1810 commented
Yep, I have a meeting with her so we can go through all the changes :)

2020-11-24 15:26 UTC, TalZa1810 commented on src/FontUpgrade/FontUpgrade.st.css
> +  --wsr-font-weight-medium: var(--wix-font-weight-medium);
```suggestion
  --wsr-font-weight-medium: var(--wix-font-weight-medium, 530);
```

2020-11-29 10:35 UTC, ayeletr approved these changes

2020-11-30 08:25 UTC, EgoziE requested changes

2020-11-30 08:25 UTC, EgoziE commented on src/Stepper/components/StepMarker.st.css
> -
Now all typography is inherited from base stepper, right?

2020-11-30 08:25 UTC, EgoziE commented on src/VariableInput/EditorUtilities.js
> +            <span className={classes.textWrapper} />{' '}
What should be here? a space?
I'm not sure it's right to add an actual space character here...

2020-11-30 08:48 UTC, TalZa1810 commented on src/VariableInput/EditorUtilities.js
> +            <span className={classes.textWrapper} />{' '}
It's the eslint adds this automatically. The space here is how it is implemented. Removing the space makes the tests fail.

2020-11-30 08:50 UTC, TalZa1810 commented on src/Notification/TextLabel/TextLabel.spec.js
> -
Because the TextLabel is now wrapped with FontUpgrade, so the test is failing. Also, this is tested anyways with the visuals so that's why I've removed this.

2020-11-30 08:59 UTC, TalZa1810 commented on src/Stepper/components/StepMarker.st.css
> -
yes, I've removed this to `Step.st.css` because I had to use this in both places so it made more sense using this there. 
It is used under `.marker` class there.

2020-11-30 09:13 UTC, EgoziE commented on src/VariableInput/EditorUtilities.js
> +            <span className={classes.textWrapper} />{' '}
🤮

2020-11-30 09:14 UTC, TalZa1810 commented on src/VariableInput/EditorUtilities.js
> +            <span className={classes.textWrapper} />{' '}
🤣 🤣

2020-12-01 12:00 UTC, merged