<Card/> - add withShadow prop
wix/wix-style-react pull request #6257
Opened 2020-11-16 15:16 UTC by yogevitz

### 🔦 Summary

add a boolean `withShadow` prop (default: false) to the `<Card/>` component

### ✅ Checklist

- [x] 👨‍💻 API change is approved by the UI Infra Developers @EgoziE 
- [x] 👨‍🎨 UX change is approved by the Design System UX @milkyfruit 
- 📚 Change is documented
  - [x] API description
- 🔬 Change is tested
  - [x] Component

2020-11-16 15:25 UTC, WixBuildServer commented
### 🤖 Hi, I'm #Janet!

  A deploy preview of your PR was successfully released 🖼.

  You can find it under one of the following URLs:
  * https://preview.wix-style-react.com/pr_6257

2020-11-16 15:54 UTC, EgoziE requested changes
Looks good, just please add one visual test.
To `src/Card/Card.visual.js`

2020-11-17 11:41 UTC, milkyfruit requested changes

2020-11-17 11:41 UTC, milkyfruit commented on src/Card/Card.st.css
> +  box-shadow: 0 2px 4px 0 rgba(22, 45, 61, 0.12), 0 0 6px 0 rgba(22, 45, 61, 0.12);
@yogevitz please use $shadow-20 instead: https://github.com/wix/wix-style-react/blob/68bc0787283669dfd2257122518cf9e7c6cf32c3/src/colors.scss#L103

2020-11-17 11:41 UTC, milkyfruit commented on src/Card/index.d.ts
> +  withShadow?: boolean;
@yogevitz @EgoziE Do we have some convention how boolean props should be named?
In WSR lib I found variety of solutions, but it seems usually named "verb" + "noun". Therefore I suggest to rename `withShadow` to `showShadow`.

`<TableListItem showDivider />`
`<Accordion hideShadow />`
`<Popover showArrow />`
`<ListItemSelect checkbox />`

2020-11-17 12:23 UTC, yogevitz commented on src/Card/Card.st.css
> +  box-shadow: 0 2px 4px 0 rgba(22, 45, 61, 0.12), 0 0 6px 0 rgba(22, 45, 61, 0.12);
done :)

2020-11-17 12:24 UTC, yogevitz commented on src/Card/index.d.ts
> +  withShadow?: boolean;
@EgoziE wdyt?

2020-11-17 16:45 UTC, EgoziE commented on src/Card/index.d.ts
> +  withShadow?: boolean;
Sure, I don't mind, showShadow is fine by me

2020-11-18 08:26 UTC, yogevitz commented on src/Card/index.d.ts
> +  withShadow?: boolean;
done :)

2020-11-18 10:08 UTC, EgoziE approved these changes

2020-11-18 10:13 UTC, merged