Added box-shadow theming support & updated business dashboard shadow overrides
wix/wix-style-react pull request #6263
Opened 2020-11-17 13:34 UTC by dimafeldman

### 🔦 Summary

...

### ✅ Checklist

- [ ] 👨‍💻 API change is approved by the UI Infra Developers 
- [ ] 👨‍🎨 UX change is approved by the Design System UX 
- 📚 Change is documented
  - [ ] Story
  - [ ] API description
  - [ ] Cheatsheet
  - [ ] Other (explain)
- 🔬 Change is tested
  - [ ] Component
  - [ ] Visual test

2020-11-17 13:50 UTC, WixBuildServer commented
### 🤖 Hi, I'm #Janet!

  A deploy preview of your PR was successfully released 🖼.

  You can find it under one of the following URLs:
  * https://preview.wix-style-react.com/pr_6263

2020-11-18 09:31 UTC, EgoziE requested changes

2020-11-18 09:31 UTC, EgoziE commented on src/Foundation/stylable/shadows.st.css
> +.shadow10 { box-shadow: var(--shadow10, 0 2px 1px 0 value(s2), 0 0 3px 0 value(s1)); }
We prefer that design constants will not be mixins if the css is not complex.
Please change is to:
```
:vars {
  shadow10: var(--shadow10, 0 2px 1px 0 value(s2), 0 0 3px 0 value(s1));
}
```

and use it like before:

```
box-shadow: value(shadow10);
```

2020-11-18 11:35 UTC, dimafeldman commented on src/Foundation/stylable/shadows.st.css
> +.shadow10 { box-shadow: var(--shadow10, 0 2px 1px 0 value(s2), 0 0 3px 0 value(s1)); }
updated. thanks!

2020-11-18 11:45 UTC, EgoziE requested changes

2020-11-18 11:45 UTC, EgoziE commented on src/Themes/businessDashboard/BusinessDashboard.st.css
> +@st-global-custom-property --shadow10, --shadow20, --shadow30, --shadow40;
Oh sorry just now I noticed that it's global.
This means you can accidentally override those from an external css source.
I suggest to remove `@st-global-custom-property` and import those variables just like you import any other variable.

2020-11-18 15:09 UTC, EgoziE commented on src/Themes/businessDashboard/BusinessDashboard.st.css
> +@st-global-custom-property --shadow10, --shadow20, --shadow30, --shadow40;
Ok so I reached a conclusion it's not possible use scoped css variables as a stylable variable value.
Bottom line, let's keep those variables as global, BUT in order to reduce any possible overrides, let's change the name from `--shadow-10` to `--wsr-shadow-10`

2020-11-18 15:26 UTC, dimafeldman commented on src/Themes/businessDashboard/BusinessDashboard.st.css
> +@st-global-custom-property --shadow10, --shadow20, --shadow30, --shadow40;
updated, thanks!

2020-11-18 15:30 UTC, EgoziE approved these changes

2020-11-19 08:50 UTC, merged