Adding support readme file
wix/wix-style-react pull request #6264
Opened 2020-11-17 14:40 UTC by TalZa1810

### 🔦 Summary
Adding a [support readme file](https://docs.github.com/en/free-pro-team@latest/github/building-a-strong-community/adding-support-resources-to-your-project).
Still in progress.

2020-11-17 14:51 UTC, WixBuildServer commented
### 🤖 Hi, I'm #Janet!

  A deploy preview of your PR was successfully released 🖼.

  You can find it under one of the following URLs:
  * https://preview.wix-style-react.com/pr_6264

2020-11-17 15:38 UTC, wildcard commented on SUPPORT.md
> +#### New issue guidelines
Could you link or show an example of a good issue?

2020-11-17 16:39 UTC, TalZa1810 commented on SUPPORT.md
> +#### New issue guidelines
done

2020-11-18 10:22 UTC, wildcard approved these changes
I think everything is here, we'll handle separated support flows for internal and external audience on a different PR.

@TalZa1810 & @EgoziE it's a job well done IMHO ❤️

2020-11-19 13:04 UTC, TalZa1810 commented
The images don't load since it is still in a PR. It should look fine when it is merged to master. I'll make sure after it is merged that we don't have issues with it.

2020-11-22 09:03 UTC, shlomitc commented on SUPPORT.md
> +# Support
In files with lots of topics, it is common to add a "table of contents" that you can brief all topics jump to the relevant one

2020-11-22 18:00 UTC, TalZa1810 commented on SUPPORT.md
> +2. Check out our [Cheetsheet](https://www.wix-style-react.com/?path=/story/introduction-cheatsheet--components-cheatsheet) which includes a view of most of the library components inventory and links
sometimes users don't know which component to use in order to implement a certain design, so referring them to have a look at the cheatsheet could resolve this type of questions.

2020-11-22 22:00 UTC, wildcard commented on SUPPORT.md
> +2. Check out our [Cheetsheet](https://www.wix-style-react.com/?path=/story/introduction-cheatsheet--components-cheatsheet) which includes a view of most of the library components inventory and links
It's very interesting! So apparently our users don't review the entire library options before starting to work with it?

My best guess would to ask our library users to review all basic components before starting to use it & on the above bullet we can emphasize this notion (know all existing components before asking, there's a good chance that existing components will solve your [future] problem)

2020-11-22 22:04 UTC, wildcard commented on SUPPORT.md
> +1. Check whether there is an example that fits your scenario in [Wix Style React Storybook](https://www.wix-style-react.com).
I think it's a great idea to include such a piece in our docs 💯 

I would suggest we create a codesandbox with WSR (I want to do it 😅, but don't hold your breath I'm not as swift as you 🙃 )

2020-11-22 22:05 UTC, wildcard commented on SUPPORT.md
> +# Support
Yes! I want to do it ❤️

2020-11-22 22:21 UTC, wildcard commented on SUPPORT.md
> +7. Something is broken? Have you updated your Wix Style React version? Check the [change log](https://github.com/wix/wix-style-react/blob/master/CHANGELOG.md) for breaking changes and the [migration
It's a good practice to keep things lean. I love the amount of details here, but I think you're right let's create another `md` in the docs for "My Build failed, what now?"

We can link to it here & in the FAQ in various questions

2020-11-26 16:32 UTC, EgoziE reviewed
Great initiative!!!
Overall I think the support section should be more of a low level guide, very detailed and explanatory, like we explain face to face or in the channel.

2020-11-26 16:32 UTC, EgoziE commented on SUPPORT.md
> +## Debugging Strategies and Reporting an issue 🧐
```suggestion
## Handling Issues 🧐
```

2020-11-26 16:32 UTC, EgoziE commented on SUPPORT.md
> +- Taking your current code and strip it's features slowly, one by one, until you reach to the point where things work. Than, slowly add them back again so you are able to find the what causes the iss
```suggestion
When you run into an issue, don't panic, we have some recommendations how to solve it:
- Look for similar working examples in our documentation and try to find perhaps you missed something.
- Try to isolate the problem, comment out wrappers and other features gradually until you find the source of the problem.
- Verify that the latest version of wsr is installed (in node_modules, not package.json)
- Try to find whether there are external CSS that might override parts of our components.

If you **suspect** the issue you encountered is related to the component itself, before you report an issue try to verify by:
- Recreate the issue in our playground.
- Pin wsr to a prior version to see if there's no issue there.

Once you're absolutely sure the issue is ours, please let us know through the channel or by reporting an issue.
```

2020-11-29 15:49 UTC, TalZa1810 commented
The table of content doesn't work properly within storybook so I"m not sure whether to add this or remove this.
As for the content, do you have more notes or can I merge this?

2020-11-29 18:57 UTC, wildcard commented
The links is not working even if you generate relative links?

Maybe we should do a build step to rewrite urls before building the storybook?

2020-11-30 06:12 UTC, jonathanadler approved these changes
Wow, looks great!

2020-11-30 14:33 UTC, wildcard commented on SUPPORT.md
> +## Table of Content
@TalZa1810 I took the liberty to run `npx remark SUPPORT.md --use toc --output`

on the file to fix the toc ❤️

2020-11-30 14:35 UTC, wildcard approved these changes
@TalZa1810 I think you're wonderful! & this PR is a reflection of your dedication & big heart ❤️ 

You did more than a good job, this is a job well done
Thank you for teaching me how to care about your community

WixEng & me salute you 🖖

2020-11-30 14:52 UTC, shlomitc commented on package.json
> +    "remark-toc": "^7.0.0",
this doesn't seem to be used, so let's remove them

2020-11-30 15:01 UTC, wildcard commented on package.json
> +    "remark-toc": "^7.0.0",
I used those to rewire the toc 

see https://github.com/wix/wix-style-react/pull/6264#discussion_r532639866

2020-11-30 17:51 UTC, shlomitc commented on package.json
> +    "remark-toc": "^7.0.0",
If it isn't used as part of a build step, then this should not be a dependency.
Since it's already generated and doesn't need to be run again, we can remove it from the dependencies

2020-11-30 18:32 UTC, wildcard commented on package.json
> +    "remark-toc": "^7.0.0",
You're right, let's not include it as part of the code for now.

If we choose in the future to compile (as a build step) our me files we can always add it.

2020-11-30 18:35 UTC, wildcard requested changes
Removing remark deps

2020-11-30 18:35 UTC, wildcard commented on package.json
> +    "remark-toc": "^7.0.0",
```suggestion
```

2020-11-30 18:40 UTC, wildcard approved these changes
No extra deps now 💪

2020-12-01 09:11 UTC, wildcard commented
I'm checking why the TOC links is not working on storybook + why images are broken

2020-12-02 15:18 UTC, gendeld commented on SUPPORT.md
> +Each component has a story page that describes all the interesting states in which a component supports.
```suggestion
Each component has a story page that describes all the interesting states of which a component supports.
```

2020-12-02 15:19 UTC, gendeld commented on SUPPORT.md
> +Each component has a story page that describes all the interesting states in which a component supports.
Or just without the which all together 🤷‍♂️

2020-12-02 15:21 UTC, gendeld commented on SUPPORT.md
> +A story page has one or more of the following sections:
```suggestion
A story page has one or more of the following tabs:
```

2020-12-02 15:23 UTC, gendeld commented on SUPPORT.md
> +`src/ComponentName/test/<ComponentName>.spec.js`
```suggestion
`src/<ComponentName>/test/<ComponentName>.spec.js`
```

2020-12-02 15:25 UTC, gendeld commented on SUPPORT.md
> +*   Look for similar working examples in our documentation and try to find perhaps you've missed something.
```suggestion
*   Look for similar working examples in our documentation and try to find if perhaps you've missed something.
```

2020-12-02 15:29 UTC, gendeld approved these changes

2020-12-02 15:34 UTC, TalZa1810 commented on SUPPORT.md
> +Each component has a story page that describes all the interesting states in which a component supports.
```suggestion
Each component has a story page that describes all the interesting states that are supported.
```

2020-12-07 12:26 UTC, merged

2020-12-16 17:55 UTC, splintor commented on SUPPORT.md
> +    *   [Reporting an issue ![github-mark](/GitHub-Mark-32px.png)](#reporting-an-issue-github-mark)
This `gitub-mark` uses incorrect pass and doesn't look good in https://github.com/wix/wix-style-react/blob/master/SUPPORT.md

This applies to its three occurrences in this file.