Business Dashboard Input Override
wix/wix-style-react pull request #6265
Opened 2020-11-17 15:01 UTC by justtal

### 🔦 Summary

Business Dashboard theme override for Input component. Added search component examples to story book also.

### ✅ Checklist

- [ ] 👨‍💻 API change is approved by the UI Infra Developers 
- [ ] 👨‍🎨 UX change is approved by the Design System UX 
- 📚 Change is documented
  - [ ] Story
  - [ ] API description
  - [ ] Cheatsheet
  - [ ] Other (explain)
- 🔬 Change is tested
  - [ ] Component
  - [ ] Visual test

2020-11-17 15:03 UTC, TalZa1810 commented
Hi @justtal ,
Please [sign your commits](https://github.com/wix/wix-style-react/blob/master/docs/contribution/CREATE_PR.md#sign-commits) so that CI will run on your PR.

2020-11-17 15:08 UTC, justtal commented
@TalZa1810 Done. Thanks!

2020-11-17 15:17 UTC, WixBuildServer commented
### 🤖 Hi, I'm #Janet!

  A deploy preview of your PR was successfully released 🖼.

  You can find it under one of the following URLs:
  * https://preview.wix-style-react.com/pr_6265

2020-11-17 19:16 UTC, shlomitc requested changes

2020-11-17 19:16 UTC, shlomitc commented on src/Themes/businessDashboard/components/Input.st.css
> +.root::clearButtonWrapper button {
instead of targeting the global button element, please add an extendable class API to the `CloseButton` here https://github.com/wix/wix-style-react/blob/master/src/Input/InputSuffix.js#L42
`<CloseButton className={classes.clearButton}`

and in the `input.st.css` file:

```css
:import {
  -st-from: "../../../CloseButton/CloseButton.st.css";
  -st-default: CloseButton;
}

.clearButton {
  -st-extends: CloseButton;
}
```

Then you can target the correct button size. for example:
```css
.root::clearButton {
  background-clor: value(B50)
}

.root::clearButton:size(medium) {
  width: 24px;
  height: 24px;
}
```

2020-11-17 19:16 UTC, shlomitc commented on src/Themes/businessDashboard/components/Input.st.css
> +}
You should theme the `IconAffix` css: https://github.com/wix/wix-style-react/blob/master/src/Input/IconAffix/IconAffix.js#L10

create a separate theme file for it

2020-11-18 12:11 UTC, justtal commented on src/Themes/businessDashboard/components/Input.st.css
> +.root::clearButtonWrapper button {
Done

2020-11-18 12:11 UTC, justtal commented on src/Themes/businessDashboard/components/Input.st.css
> +}
Done

2020-11-18 13:31 UTC, shlomitc requested changes

2020-11-18 13:31 UTC, shlomitc commented on src/Input/test/Input.visual.js
> +  storiesOf('Input', module).add('status indicator', () => {
```suggestion
  storiesOf(storiesTitle, module).add('status indicator', () => {
```

2020-11-18 13:31 UTC, shlomitc commented on src/Input/test/Input.visual.js
> +  storiesOf('Input', module).add('prefix/suffix', () => {
```suggestion
  storiesOf(storiesTitle, module).add('prefix/suffix', () => {
```

2020-11-18 13:31 UTC, shlomitc commented on src/Input/test/Input.visual.js
> +  storiesOf('Input', module).add('rtl', () => {
```suggestion
  storiesOf(storiesTitle, module).add('rtl', () => {
```

2020-11-18 19:18 UTC, merged