<MarketingLayout/> - add size tiny
wix/wix-style-react pull request #6269
Opened 2020-11-17 16:09 UTC by yogevitz

### 🔦 Summary

add `size: tiny` for `<MarketingLayout/>` component

### ✅ Checklist

- [x] 👨‍💻 API change is approved by the UI Infra Developers @EgoziE 
- [x] 👨‍🎨 UX change is approved by the Design System UX @milkyfruit 
- 📚 Change is documented
  - [x] Story
  - [x] API description
- 🔬 Change is tested
  - [x] Visual test

2020-11-17 16:18 UTC, WixBuildServer commented
### 🤖 Hi, I'm #Janet!

  A deploy preview of your PR was successfully released 🖼.

  You can find it under one of the following URLs:
  * https://preview.wix-style-react.com/pr_6269

2020-11-19 08:59 UTC, EgoziE reviewed
@milkyfruit Ready for UX review

2020-11-19 08:59 UTC, EgoziE commented on src/MarketingLayout/components/Title.js
> +        <div>{children}</div>
Missing data-hook

```suggestion
        <div data-hook={MARKETING_LAYOUT_TITLE}>{children}</div>
```

2020-11-20 08:41 UTC, milkyfruit requested changes
@yogevitz @EgoziE 
- [x] For size tiny **text column span** should be `8` instead of `9`
- [ ] For size tiny **image column span** should be `3` instead of `2`
- [ ] Let's slightly adjust example to show image size as in spec:
```
<MarketingLayout
  title="Tiny Size Layout"
  description="This layout requires less attention. It can promote side features that might add value, but are not mandatory to achieve main goals."
  actions={<Button size="small">Get Started</Button>}
  size="tiny"
  image={
    <Box width="100%" align="right">
      <Image width="96px" height="96px" />
    </Box>
  }
/>;
```

Preview in the spec:
![image](https://user-images.githubusercontent.com/1684587/99778629-9a231080-2b1c-11eb-97cc-af3ded882730.png)

Everything else looks great, after layout is fixed, we can merge it 👍

2020-11-22 09:48 UTC, yogevitz commented
@milkyfruit column spans and example fixed 👍

2020-11-23 08:02 UTC, milkyfruit approved these changes
@yogevitz @EgoziE looks great!

2020-11-23 13:10 UTC, EgoziE approved these changes

2020-11-23 13:10 UTC, merged