<MarketingLayout/> - add direction prop
wix/wix-style-react pull request #6283
Opened 2020-11-19 15:32 UTC by yogevitz

### 🔦 Summary

add `direction` prop for `<MarketingLayout/>` component

### ✅ Checklist

- [x] 👨‍💻 API change is approved by the UI Infra Developers @EgoziE 
- [x] 👨‍🎨 UX change is approved by the Design System UX @milkyfruit 
- 📚 Change is documented
  - [x] Story
  - [x] API description
- 🔬 Change is tested
  - [x] Component
  - [x] Visual test

2020-11-19 15:44 UTC, WixBuildServer commented
### 🤖 Hi, I'm #Janet!

  A deploy preview of your PR was successfully released 🖼.

  You can find it under one of the following URLs:
  * https://preview.wix-style-react.com/pr_6283

2020-11-20 08:54 UTC, milkyfruit requested changes
@yogevitz @EgoziE 
- [ ] When direction is set to vertical, image should occupy all 12 columns same as text. Now it occupies only 2 or 4 cols depending on set size:
![image](https://user-images.githubusercontent.com/1684587/99779970-84aee600-2b1e-11eb-8d51-ad42085b6afb.png)

Everything else looks great, it can merged once column span is fixed.

2020-11-22 09:26 UTC, yogevitz commented
@milkyfruit image column span fixed

2020-11-23 08:04 UTC, milkyfruit approved these changes

2021-01-05 15:19 UTC, yogevitz commented
@EgoziE you can merge this one as well

2021-01-06 09:22 UTC, EgoziE requested changes

2021-01-06 09:22 UTC, EgoziE commented on src/MarketingLayout/MarketingLayout.st.css
> +:global([dir="rtl"]) .root:size(large):direction(horizontal) {
I didn't find any mention to `:direction(vertical)` in css so just to make sure, there are no paddings for this direction at all?

2021-01-06 09:22 UTC, EgoziE commented on src/MarketingLayout/MarketingLayout.st.css
> +
Maybe regarding my previous comment, this class can be replaced by `.root:direction(vertical)` in some way?

2021-01-06 09:22 UTC, EgoziE commented on src/MarketingLayout/MarketingLayout.st.css
> +}
Maybe regarding my previous comment, this class can be replaced by .root:direction(vertical) in some way?

2021-01-12 15:25 UTC, yogevitz commented on src/MarketingLayout/MarketingLayout.st.css
> +:global([dir="rtl"]) .root:size(large):direction(horizontal) {
I think so, @milkyfruit can you approve?

2021-01-12 15:36 UTC, yogevitz commented on src/MarketingLayout/MarketingLayout.st.css
> +
I tried, but since the horizontal layout uses `<Layout/>` it's problematic

2021-01-12 15:36 UTC, yogevitz commented on src/MarketingLayout/MarketingLayout.st.css
> +}
same for this one

> I tried, but since the horizontal layout uses `<Layout/>` it's problematic

2021-01-14 15:02 UTC, milkyfruit approved these changes
Looks great!

2021-01-14 15:02 UTC, milkyfruit commented on src/MarketingLayout/MarketingLayout.st.css
> +:global([dir="rtl"]) .root:size(large):direction(horizontal) {
Correct, no paddings

2021-01-18 11:55 UTC, TalZa1810 commented
Please let me know before merging.
I'm currently working on this component and there are some conflicts with your current implementation: https://github.com/wix/wix-style-react/pull/6568

2021-01-25 08:58 UTC, TalZa1810 commented
Hi @yogevitz ,
Any updates with this PR?

2021-01-25 12:50 UTC, yogevitz commented
hey @TalZa1810, I merged conflicts from master :)

2021-01-26 11:53 UTC, TalZa1810 commented
Hi @yogevitz 
I tried to generalize this more:
```
  _renderContent = () => {
    const { size, direction } = this.props;
    let { spacer, image, content } = cellSpansBySize[size];

    const isVertical = direction === DIRECTIONS.vertical;
    const layoutGap = size === SIZES.tiny ? '24px' : '30px';

    if(isVertical){
      image = 12;
    }

    const spacerCell = this._renderSpacerCell(spacer);
    const imageCell = this._renderImageCell(image);
    const contentCell = this._renderContentCell(content);

    return <Layout gap={layoutGap}>
      {isVertical?
        this._renderVerticalCells({ imageCell, contentCell}) :
        this._renderHorizontalCells({ imageCell, contentCell, spacerCell})}
    </Layout>
  };

  _renderHorizontalCells({ imageCell, contentCell, spacerCell } ) {
    const { inverted , size} = this.props;
    const shouldUseSpacer = size !== SIZES.tiny;

    return inverted
        ? [imageCell, contentCell, shouldUseSpacer && spacerCell]
        : [contentCell, shouldUseSpacer && spacerCell, imageCell]
  }

  _renderVerticalCells({ imageCell, contentCell}) {
    const { inverted } = this.props;
    return inverted ? [contentCell, imageCell ] : [imageCell, contentCell ]
  }
```

it probably can be improved a bit but the main thing is that we use just `Layout` (the same one) for all combinations.
no need to add extra css.

Also, I've added an example for vertical wrapped with Card and it doesn't look good. I think this should be fixed too.
Let me know what you think. We can do this together if there are further questions.

2021-02-02 09:28 UTC, TalZa1810 commented
Hey,
It's pretty old PR and it makes it difficult to rebase this with all the changes that were merged. I'm closing this one and creating a new one for this feature instead so that we can merge this soon: https://github.com/wix/wix-style-react/pull/6691

2021-02-02 09:28 UTC, closed without merging