<VerticalTabs> activeTabId <VerticalTabsItem> id props change to be string or number
wix/wix-style-react pull request #6290
Opened 2020-11-22 08:40 UTC by tzelonm

Issue:
https://github.com/wix/wix-style-react/issues/6185

### 🔦 Summary
<VerticalTabs> activeTabId prop and <VerticalTabsItem> id prop, changed type to be string or number.

### ✅ Checklist

-  ✅ 👨‍💻 API change is approved by the UI Infra Developers @EgoziE

2020-11-22 09:10 UTC, EgoziE requested changes
Thanks for this PR!
Please take the time to read our guide [How to create a PR for wix-style-react](https://github.com/wix/wix-style-react/blob/master/docs/contribution/CREATE_PR.md), you must sign your commits in order for CI to run.

Moreover, please add this type also to:
* src/VerticalTabs/index.d.ts
* src/VerticalTabsItem/index.d.ts
* src/VerticalTabs/test/VerticalTabs.tsx
* src/VerticalTabsItem/test/VerticalTabsItem.tsx

If needed, read more [here](https://github.com/wix/wix-style-react/blob/master/docs/contribution/COMPONENT_STRUCTURE.md)

2020-11-30 09:38 UTC, EgoziE commented
@tzelonm Are you going to continue this PR or shall I close it for inactivity?

2020-12-01 10:48 UTC, tzelonm commented
Yes, sorry.
I will continue to work on it next week.

2020-12-10 08:47 UTC, EgoziE commented
Closing for inactivity.

2020-12-10 08:47 UTC, closed without merging