Themes | Business Dashboard - Misc Sidebar Fixes
wix/wix-style-react pull request #6295
Opened 2020-11-22 17:46 UTC by ronenst

### 🔦 Summary

...

### ✅ Checklist

- [ ] 👨‍💻 API change is approved by the UI Infra Developers 
- [ ] 👨‍🎨 UX change is approved by the Design System UX 
- 📚 Change is documented
  - [ ] Story
  - [ ] API description
  - [ ] Cheatsheet
  - [ ] Other (explain)
- 🔬 Change is tested
  - [ ] Component
  - [ ] Visual test

2020-11-22 17:56 UTC, WixBuildServer commented
### 🤖 Hi, I'm #Janet!

  A deploy preview of your PR was successfully released 🖼.

  You can find it under one of the following URLs:
  * https://preview.wix-style-react.com/pr_6295

2020-11-22 20:09 UTC, EgoziE requested changes

2020-11-22 20:09 UTC, EgoziE commented on src/SidebarBackButton/test/SidebarBackButton.visual.js
> +        testWithTheme(
1. We don't recommend changing visual tests in the same PR with code changes, this way you might break something without noticing, I suggest adding visuals first (we'll merge it quickly).
2. Please add a gray background color (#f0f4f7 is fine) to the "light skin" test in order to test it correctly.

![image](https://user-images.githubusercontent.com/35173937/99915887-2d239c80-2d0f-11eb-9bf5-5d6a62ee4c02.png)

2020-11-22 21:18 UTC, ronenst commented on src/SidebarBackButton/test/SidebarBackButton.visual.js
> +        testWithTheme(
Thanks, opened here:
https://github.com/wix/wix-style-react/pull/6298

Please note this PR will "break" the added Dashboard Theme visual tests light skin, due to the fix here: [`10c4e4d` (#6295)](https://github.com/wix/wix-style-react/pull/6295/commits/10c4e4db952282105bf67c8c666adf54d16c4286#diff-8ae4d1d7b9c6fdf29d5d1906a4ed36b662221cc37a70db497606d68f4dea730fR15)

2020-11-22 21:21 UTC, ronenst commented
There is also a bug with the typography of MadeFor in the sidebar skin, it should be 500 with bold being 700 but it's currently all set to 400. I understand that's a separate fix and shouldn't be handled by the sidebar styles according to this discussion:
https://wix.slack.com/archives/C01B85QAU2E/p1606034777006400

2020-11-23 08:21 UTC, EgoziE commented
@ronenst We're working on Madefor adjustments don't worry.
Maybe you can help us merge this: https://github.com/wix-private/business-manager/pull/3002 😉

2020-11-23 10:26 UTC, ronenst commented
@EgoziE All failing visual test seem to be bug fixes and should be approved, shall I approve them?

2020-11-23 11:00 UTC, EgoziE commented
Leave approving to me, this is my best indicator in review :)

2020-11-23 11:02 UTC, EgoziE approved these changes

2020-11-23 11:02 UTC, merged