<Carousel/> - add controlsTypeOnEdges prop
wix/wix-style-react pull request #6300
Opened 2020-11-23 09:45 UTC by yogevitz

### 🔦 Summary

Added `controlsTypeOnEdges` prop to the `<Carousel/>` component.
This prop is relevant for use when the `infinite` prop is `false`.
The default value is `disabled` and the newly presented state appears when the prop is set to `hidden`.

### ✅ Checklist

- [x] 👨‍💻 API change is approved by the UI Infra Developers @EgoziE 
- [x] 👨‍🎨 UX change is approved by the Design System UX @milkyfruit 
- 📚 Change is documented
  - [x] Story
  - [x] API description
- 🔬 Change is tested
  - [x] Component
  - [x] Visual test

2020-11-23 09:55 UTC, WixBuildServer commented
### 🤖 Hi, I'm #Janet!

  A deploy preview of your PR was successfully released 🖼.

  You can find it under one of the following URLs:
  * https://preview.wix-style-react.com/pr_6300

2020-11-23 11:36 UTC, EgoziE requested changes

2020-11-23 11:36 UTC, EgoziE commented on src/Carousel/SliderArrow/SliderArrow.js
> +    (isDisabled && controlsTypeOnEdges === 'hidden') || (
This variable was called `isDisabled` because it was the only option.
Now that we have two options, I think we can rename it to something more clear like "isControlOnEdge"

2020-11-23 11:36 UTC, EgoziE commented on src/Carousel/SliderArrow/SliderArrow.js
> +    (isDisabled && controlsTypeOnEdges === 'hidden') || (
Moreover, although correct, this condition is a bit complicated to understand at first look.
Can you please simplify it? (if-else or something)

2020-11-23 13:18 UTC, yogevitz commented on src/Carousel/SliderArrow/SliderArrow.js
> +    (isDisabled && controlsTypeOnEdges === 'hidden') || (
refactored :)

2020-11-23 13:29 UTC, EgoziE commented
@milkyfruit Ready for UX review

2020-11-23 16:03 UTC, milkyfruit reviewed
The behaviour is great, however I'm not sure if the prop name is clear, it raises a question what is an edge.
Maybe we could name it to something like:
- `controlsInactive`
- `controlsStartEnd`
- `controlsFirstLast`

@yogevbd @EgoziE What are your opinions?

2020-11-23 16:18 UTC, yogevbd commented
@milkyfruit you tagged the wrong yogev :D
@yogevitz

2020-11-25 08:45 UTC, yogevitz commented
renamed `controlsTypeOnEdges` to `controlsStartEnd`
@milkyfruit

2020-11-25 11:30 UTC, EgoziE approved these changes

2020-11-25 11:31 UTC, merged