<TrendIndicator/> - add new component
wix/wix-style-react pull request #6305
Opened 2020-11-23 16:37 UTC by fantua

### 🔦 Summary

...

### ✅ Checklist

- [ ] 👨‍💻 API change is approved by the UI Infra Developers 
- [ ] 👨‍🎨 UX change is approved by the Design System UX 
- 📚 Change is documented
  - [ ] Story
  - [ ] API description
  - [ ] Cheatsheet
  - [ ] Other (explain)
- 🔬 Change is tested
  - [ ] Component
  - [ ] Visual test

2020-11-23 17:24 UTC, EgoziE requested changes

2020-11-23 17:24 UTC, EgoziE commented on src/TrendIndicator/TrendIndicator.js
> +    };
data-hook can be part of the root element directly.
dataAttrs.inverted can be deleted, we test pure visual props with visual tests, no need to test it with unit-tests too.

2020-11-23 17:24 UTC, EgoziE commented on perfer.config.js
> +  ['TrendIndicator.bundle.min.js', 10],
Change value to 38 and sort alphabetically.

2020-11-23 17:24 UTC, EgoziE commented on perfer.config.js
> +  ['TrendIndicator.min.css', 1],
Just sort alphabetically.

2020-11-23 17:24 UTC, EgoziE commented on src/TrendIndicator/TrendIndicator.st.css
> +}
This component should not be focusable, this can be deleted.
Focusable adds a blue border like so:
![image](https://user-images.githubusercontent.com/35173937/99992486-12a8fc00-2dbf-11eb-99ab-5e6e0477d525.png)

2020-11-23 17:24 UTC, EgoziE commented on src/TrendIndicator/TrendIndicator.st.css
> +  -st-states: skin(string);
We prefer to use explicit values like so:

```suggestion
  -st-states: skin(enum(neutral, positive, negative));
```

2020-11-23 17:24 UTC, EgoziE commented on src/TrendIndicator/docs/index.story.js
> +          }),
Please use example source from a single "examples.js" file that export strings only.
You can take a look at any other component as reference, like CheckToggle.

2020-11-23 17:28 UTC, fantua commented on stories/index.js
> +require('../src/Timeline/docs/index.story');
nope, now it's sorted alphabetically

2020-11-23 18:27 UTC, fantua commented on perfer.config.js
> +  ['TrendIndicator.bundle.min.js', 10],
done

2020-11-23 18:27 UTC, fantua commented on perfer.config.js
> +  ['TrendIndicator.min.css', 1],
done

2020-11-23 18:27 UTC, fantua commented on src/TrendIndicator/TrendIndicator.st.css
> +}
fixed

2020-11-23 18:28 UTC, fantua commented on src/TrendIndicator/TrendIndicator.st.css
> +  -st-states: skin(string);
fixed

2020-11-23 18:28 UTC, fantua commented on src/TrendIndicator/docs/index.story.js
> +          }),
done

2020-11-23 18:36 UTC, WixBuildServer commented
### 🤖 Hi, I'm #Janet!

  A deploy preview of your PR was successfully released 🖼.

  You can find it under one of the following URLs:
  * https://preview.wix-style-react.com/pr_6305

2020-11-24 13:58 UTC, EgoziE requested changes
For the failing unit-test
Just add to file `testkit/component-definitions.js`
This:
```
  TrendIndicator: {
    props: {
      value: 0,
    },
  },
```

2020-11-24 13:58 UTC, EgoziE commented on src/TrendIndicator/docs/index.story.js
> +              'This line here should briefly describe component in just a sentence or two. It should be short and easy to read.',
TrendIndicator shows a percentage based positive or negative trend

2020-11-24 13:58 UTC, EgoziE commented on src/TrendIndicator/TrendIndicator.st.css
> +  color: currentColor !important;
Using important is not good, I'll take a look at it.

2020-11-25 09:12 UTC, milkyfruit approved these changes
@fantua @EgoziE the component works great!

2020-11-25 09:23 UTC, EgoziE approved these changes

2020-11-25 09:23 UTC, merged