do not merge - only for testing
wix/wix-style-react pull request #6310
Opened 2020-11-24 13:22 UTC by roibWix

### 🔦 Summary

...

### ✅ Checklist

- [ ] 👨‍💻 API change is approved by the UI Infra Developers 
- [ ] 👨‍🎨 UX change is approved by the Design System UX 
- 📚 Change is documented
  - [ ] Story
  - [ ] API description
  - [ ] Cheatsheet
  - [ ] Other (explain)
- 🔬 Change is tested
  - [ ] Component
  - [ ] Visual test

2020-11-24 13:32 UTC, WixBuildServer commented
### 🤖 Hi, I'm #Janet!

  A deploy preview of your PR was successfully released 🖼.

  You can find it under one of the following URLs:
  * https://preview.wix-style-react.com/pr_6310

2020-12-10 08:46 UTC, EgoziE requested changes

2020-12-10 08:46 UTC, EgoziE commented on src/Selector/Selector.js
> +import { style, classes } from './Selector.st.css';
We use the "st" alias for style.
Just for uniformity, please change it.

2020-12-10 08:46 UTC, EgoziE commented on src/Selector/Selector.js
> +    className: PropTypes.string,
Also please add it to the `d.ts` file

2020-12-10 08:46 UTC, EgoziE commented on src/Selector/Selector.js
> +    className: PropTypes.string,
And type test (tsx file)

2020-12-13 06:16 UTC, roibWix commented on src/Selector/Selector.js
> +import { style, classes } from './Selector.st.css';
done

2020-12-13 06:39 UTC, roibWix commented on src/Selector/Selector.js
> +    className: PropTypes.string,
what does it mean 'type test'?

2020-12-13 06:39 UTC, roibWix commented on src/Selector/Selector.js
> +    className: PropTypes.string,
@EgoziE

2020-12-13 12:22 UTC, EgoziE approved these changes

2020-12-13 12:25 UTC, merged