<Carousel/> - add showEdgesGradient and edgesGradientColor props
wix/wix-style-react pull request #6311
Opened 2020-11-24 14:54 UTC by yogevitz

### 🔦 Summary

Added `showEdgesGradient` and `edgesGradientColor` props for `<Carousel/>` component.

### ✅ Checklist

- [x] 👨‍💻 API change is approved by the UI Infra Developers @EgoziE 
- [x] 👨‍🎨 UX change is approved by the Design System UX @milkyfruit 
- 📚 Change is documented
  - [x] Story
  - [x] API description
- 🔬 Change is tested
  - [x] Component
  - [x] Visual test

2020-11-24 15:03 UTC, WixBuildServer commented
### 🤖 Hi, I'm #Janet!

  A deploy preview of your PR was successfully released 🖼.

  You can find it under one of the following URLs:
  * https://preview.wix-style-react.com/pr_6311

2020-11-25 09:17 UTC, milkyfruit commented on src/Carousel/Carousel.js
> +    showEdgesGradient: PropTypes.bool,
@yogevitz @EgoziE do we need 2 props to control this gradient?
It could one prop 'gradient value', when it's blank it shows nothing, when it's with value, it would show the gradient with its value. What do you think?

2020-11-25 09:17 UTC, milkyfruit commented on src/Carousel/Carousel.js
> +    showEdgesGradient: PropTypes.bool,
also, about the naming, maybe `sideGradientColor` would be simpler?

2020-11-25 09:19 UTC, EgoziE requested changes
@milkyfruit Ready for UX review

2020-11-25 09:19 UTC, EgoziE commented on src/Carousel/Carousel.st.css
> +  background: linear-gradient(to left, rgba(240, 244, 247, 0) 50%, var(--edgesGradientColor, value(D70)));
For backwards compatibility define the same property twice with and without the css variable, like so:
```suggestion
  background: linear-gradient(to left, rgba(240, 244, 247, 0) 50%, value(D70));
  background: linear-gradient(to left, rgba(240, 244, 247, 0) 50%, var(--edgesGradientColor, value(D70)));
```

2020-11-25 09:19 UTC, EgoziE commented on src/Carousel/Carousel.st.css
> +  background: linear-gradient(to right, rgba(240, 244, 247, 0) 50%, var(--edgesGradientColor, value(D70)));
same comment

2020-11-25 09:19 UTC, EgoziE commented on src/Carousel/index.d.ts
> +  edgesGradientColor?: string;
```suggestion
  edgesGradientColor?: React.CSSProperties['color'];
```

2020-11-25 09:33 UTC, yogevitz commented on src/Carousel/Carousel.js
> +    showEdgesGradient: PropTypes.bool,
I used 2 props so we could have a default color for the gradient (D70)
If there is no need for this default I will remove the gradient flag prop

2020-11-25 12:23 UTC, yogevitz commented on src/Carousel/Carousel.js
> +    showEdgesGradient: PropTypes.bool,
@milkyfruit do we need the default color?

2020-11-25 12:36 UTC, milkyfruit commented on src/Carousel/Carousel.js
> +    showEdgesGradient: PropTypes.bool,
I think it's cleaner to have 1 prop, and promote D70, via example in a snippet.
Products might need to use D80, D70, D10 colors, therefore I don't see a need to have a default.

2020-11-25 12:39 UTC, yogevitz commented on src/Carousel/Carousel.js
> +    showEdgesGradient: PropTypes.bool,
np, will make the change :)

2020-11-26 10:29 UTC, milkyfruit approved these changes

2020-12-23 15:45 UTC, EgoziE commented
Closing in favor of new Carousel

2020-12-23 15:45 UTC, closed without merging