Analytics Summary Box
wix/wix-style-react pull request #6312
Opened 2020-11-24 16:08 UTC by justame

### 🔦 Summary

...

### ✅ Checklist

- [ ] 👨‍💻 API change is approved by the UI Infra Developers 
- [ ] 👨‍🎨 UX change is approved by the Design System UX 
- 📚 Change is documented
  - [ ] Story
  - [ ] API description
  - [ ] Cheatsheet
  - [ ] Other (explain)
- 🔬 Change is tested
  - [ ] Component
  - [ ] Visual test

2020-11-25 13:06 UTC, WixBuildServer commented
### 🤖 Hi, I'm #Janet!

  A deploy preview of your PR was successfully released 🖼.

  You can find it under one of the following URLs:
  * https://preview.wix-style-react.com/pr_6312

2020-11-29 09:11 UTC, EgoziE requested changes

2020-11-29 09:11 UTC, EgoziE commented on src/AnalyticsSummaryCard/AnalyticsSummaryCard.js
> +  isPercentageVisible: true,
We don't allow boolean props to be set as true by default.
You can rename this prop to "hidePercentage" and make it false instead.

2020-11-29 09:11 UTC, EgoziE commented on src/AnalyticsSummaryCard/AnalyticsSummaryCard.st.css
> +}
These should be changed to Stylable states.
Take a look at [Stylable Pseudo Classes](https://stylable.io/docs/references/pseudo-classes)

2020-11-29 09:11 UTC, EgoziE commented on src/AnalyticsSummaryCard/AnalyticsSummaryCard.js
> +AnalyticsSummaryCard.propTypes = {
Don't forget to add a comment before each propType, this is important for automatic documentation

2020-12-02 15:50 UTC, EgoziE commented on src/AnalyticsSummaryCard/index.d.ts
> +import IconButton from '../IconButton';
Are you going to use IconButton?

2020-12-02 15:51 UTC, EgoziE commented
@milkyfruit ready for UX review

2020-12-02 16:29 UTC, justame commented on src/AnalyticsSummaryCard/index.d.ts
> +import IconButton from '../IconButton';
I should remove it

2020-12-07 13:16 UTC, assafzi commented
> @milkyfruit ready for UX review

UX is here.
The component looks good.
I have some questions/improvements

- [ ] Icon Button's skin should be Inverted
`<IconButton skin="inverted"> 
`

- [ ] Sparkline should have tooltip on hover as described in the component's page
https://snipboard.io/R3Md4V.jpg

- [ ] Title and value tooltip - when the field is empty there's no need to display a tooltip
https://snipboard.io/ahRSW4.jpg

- [ ] isTrendVisible prop should be next to the Trend prop in the playground (currently is on misc props). It will make more sense
https://snipboard.io/wKpImy.jpg

- [ ] Why invertedTrend prop is needed?
https://snipboard.io/5gCX01.jpg

- [ ] Need to add mouse and keyboard a11y as described in the spec
https://zpl.io/adl4PWp


I'm working on better examples in the description tab. Will add it tomorrow.

2020-12-09 10:27 UTC, assafzi commented
Following previous comment, here's a better description examples

- [ ] **Simple Usage**
A simple example.
![image](https://user-images.githubusercontent.com/66679639/101615921-61899f00-3a17-11eb-8f72-b88ffece037f.png)


- [ ] **Footer**
Summary card can have a footer for extra content.
The footer is a node box with no height limitation.
![image](https://user-images.githubusercontent.com/66679639/101616019-81b95e00-3a17-11eb-8e39-10eef3f88fa8.png)

- [ ] **Trend**
The trend indicates the change of the value in percentage.
It has 2 modes:
Positive - colored green with arrow upwards
Negative - colored red with arrow downwards.
 If there’s no change in value, trend won’t be displayed.
![image](https://user-images.githubusercontent.com/66679639/101616290-e1176e00-3a17-11eb-825d-67c31a702f67.png)

- [ ] **Action Button**
Summary card can have action button inside to assist with any action needed, since it’s a node.
![image](https://user-images.githubusercontent.com/66679639/101616413-01472d00-3a18-11eb-8ed9-c5348cb5d37f.png)

- [ ] **Clickable Card**
Card can be clickable or not.
![image](https://user-images.githubusercontent.com/66679639/101616720-67cc4b00-3a18-11eb-8853-f525412ff277.png)

- [ ] **Loader**
Card supports loading state. It will replace the action button when it’s active. If the card is clickable it won’t be as long the loader is active. 
![image](https://user-images.githubusercontent.com/66679639/101616973-b37ef480-3a18-11eb-8d0f-e861b3b3a734.png)

- [ ] **Sparkline Width**
Sparkline width is set by px only. The minimum width is 69px.
![image](https://user-images.githubusercontent.com/66679639/101617137-ee812800-3a18-11eb-87a1-17b23b92eb68.png)

- [ ] **Tooltip On Title**
If needed, the title can have tooltip to better explain the context.
![image](https://user-images.githubusercontent.com/66679639/101617280-20928a00-3a19-11eb-8859-53c7e822f22d.png)

- [ ] **Tooltip On Value**
When value appears as abbreviated number, tooltip will appear on hover.
![image](https://user-images.githubusercontent.com/66679639/101617361-3607b400-3a19-11eb-9ad8-4edd308ca004.png)

Also, in the API, in the onClick, please change the description of it to indicate clearer that it controls the clickable on card.
- [ ]  Card would be clickable

2020-12-21 09:17 UTC, merged

2020-12-21 11:48 UTC, assafzi commented
UX approve. Thanks.