Use places autocomplete
wix/wix-style-react pull request #6324
Opened 2020-11-26 16:14 UTC by gendeld

### 🔦 Summary

...

### ✅ Checklist

- [ ] 👨‍💻 API change is approved by the UI Infra Developers 
- [ ] 👨‍🎨 UX change is approved by the Design System UX 
- 📚 Change is documented
  - [ ] Story
  - [ ] API description
  - [ ] Cheatsheet
  - [ ] Other (explain)
- 🔬 Change is tested
  - [ ] Component
  - [ ] Visual test

2020-11-26 16:24 UTC, WixBuildServer commented
### 🤖 Hi, I'm #Janet!

  A deploy preview of your PR was successfully released 🖼.

  You can find it under one of the following URLs:
  * https://preview.wix-style-react.com/pr_6324

2020-11-30 13:39 UTC, shlomitc requested changes

2020-11-30 13:39 UTC, shlomitc commented on src/hooks/usePlacesAutocomplete/usePlacesAutocomplete.spec.js
> +    expect(result.current.ready).toBe(false);
what exactly is this `current` thing? It's repeated all across the tests. can't the `renderHelper` just return it?

2020-11-30 13:39 UTC, shlomitc commented on src/hooks/usePlacesAutocomplete/usePlacesAutocomplete.js
> +  const getPredictionsRef = useRef(
I don't like that a `getPredictionsRef` actually changes the prediction state.
we use the `get` prefix for getters.
Also, I think it's best that it would actually return a value and not the ref.

2020-11-30 13:39 UTC, shlomitc commented on src/hooks/usePlacesAutocomplete/usePlacesAutocomplete.spec.js
> +jest.useFakeTimers();
Instead of mocking, I think it's better to make the original hook configurable. that way you don't care about the actual implementation

2020-11-30 13:39 UTC, shlomitc commented on src/hooks/usePlacesAutocomplete/usePlacesAutocomplete.spec.js
> +const wait = milliseconds =>
this probably repeats in multiple areas in the system, simply reuse an existing one

2020-11-30 13:39 UTC, shlomitc commented on src/hooks/usePlacesAutocomplete/usePlacesAutocomplete.spec.js
> +    });
```suggestion
    await waitForDebounce(fetchDelay)
```

2020-12-02 08:58 UTC, gendeld commented on src/hooks/usePlacesAutocomplete/usePlacesAutocomplete.js
> +        setFetchState({ loading: false, predictions: newPredictions });
As far as I know, React doesn't know to batch state updates inside asynchronous callbacks, so updating two states will cause an extra re-render.
Because these states are linked, it makes sense to combine them.

2020-12-02 10:18 UTC, shlomitc commented on src/hooks/usePlacesAutocomplete/usePlacesAutocomplete.js
> +        setFetchState({ loading: false, predictions: newPredictions });
interesting. I obviously lack some hooks knowledge, but this sounds like something that can be solved, so let's discuss it later in private

2020-12-02 12:14 UTC, gendeld commented on src/hooks/usePlacesAutocomplete/usePlacesAutocomplete.spec.js
> +    expect(result.current.ready).toBe(false);
`@testing-library/react-hooks` saves result as ref and updates it as it changes, so when we want to recheck return value of hook throughout a test we can always use `result.current` which will return the latest value.

2020-12-03 09:17 UTC, gendeld commented on src/hooks/usePlacesAutocomplete/usePlacesAutocomplete.js
> +    clearPredictions,
I think it's probably better to have clearing not debounced, I now also increase the request id on clear to stop async updates that were started before clear

2020-12-03 09:24 UTC, shlomitc commented on src/hooks/usePlacesAutocomplete/usePlacesAutocomplete.js
> +    clearPredictions,
yes, clearing should be immediate (and probably stop any denounced action)

2020-12-10 11:23 UTC, merged