<ListItemSelect/> and <BadgeSelectItem/> allow to control prefix padding and expose size and suffix props
wix/wix-style-react pull request #6330
Opened 2020-11-29 10:28 UTC by bamai

### 🔦 Summary

https://jira.wixpress.com/browse/DSM-1139

2020-11-29 10:39 UTC, WixBuildServer commented
### 🤖 Hi, I'm #Janet!

  A deploy preview of your PR was successfully released 🖼.

  You can find it under one of the following URLs:
  * https://preview.wix-style-react.com/pr_6330

2020-11-29 16:21 UTC, TalZa1810 requested changes
Hi Mai,
I've added some questions and notes for things I wasn't sure about.
Feel free to send me a message if something is not clear.

2020-11-29 16:21 UTC, TalZa1810 commented on src/BadgeSelectItem/BadgeSelectItem.js
> +      prefixMarginRight={prefixMarginRight ? prefixMarginRight : '0px'}
If it's a capability that we want to add to the `ListItemSelect`, we should add this check to the ListItemSelect itself and not here

2020-11-29 16:21 UTC, TalZa1810 commented on src/BadgeSelectItem/docs/index.story.js
> +            text: '',
Let's add some description here. You can consult @milkyfruit what's an appropriate description for this kind of example.

2020-11-29 16:21 UTC, TalZa1810 commented on src/BadgeSelectItem/BadgeSelectItem.js
> +  prefixMarginRight: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
I'm not sure how flexible we want this to be. Maybe just `0px` or `6px` instead of being too flexible. 
@milkyfruit WDYT? 
If it's just two possible options, we would probably want to rename this as well.

2020-11-29 16:21 UTC, TalZa1810 commented on src/ListItemSelect/ListItemSelect.js
> +          <Box marginRight={prefixMarginRight}>
Why using both Box and css?
We want to avoid using Box wrappers when possible (for the same reason we had to refactor `<ListItemSelect/>` for the `<AddressInputOption/>` issue).

2020-11-29 16:21 UTC, TalZa1810 commented on src/ListItemSelect/docs/index.story.js
> +          example({
Are these the examples you've discussed with Domas? Can you please elaborate?

2020-11-30 11:58 UTC, milkyfruit commented on src/BadgeSelectItem/BadgeSelectItem.js
> +  prefixMarginRight: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
if it would be `true` or `false` would it have the same default state for all the options or each option could have a different value?
Right now it's `0` for title option, and `6px` for title+subtitle option.

2020-11-30 12:06 UTC, shlomitc commented on src/BadgeSelectItem/BadgeSelectItem.js
> +  prefixMarginRight: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
I'm not sure why this is needed. can't the BaseSelect component customize the ListItemSelect using css only?

2020-11-30 12:13 UTC, TalZa1810 commented on src/BadgeSelectItem/BadgeSelectItem.js
> +  prefixMarginRight: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
It's a capability that @milkyfruit wanted us to add to the `ListItemSelect` in general, not just the `BadgeSelectItem`. We wanted this capability to be customisable by the user. 

@milkyfruit do we have another example besides the `BadgeSelectItem` where the user would need/want to customise this?

2020-12-01 07:56 UTC, milkyfruit commented on src/BadgeSelectItem/BadgeSelectItem.js
> +  prefixMarginRight: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
at the moment, no. But I see that the same issue might occur also using other prefixes.

2020-12-01 08:02 UTC, shlomitc commented on src/BadgeSelectItem/BadgeSelectItem.js
> +  prefixMarginRight: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
@milkyfruit - by other prefixes you mean other predefined list items?
if so, then we can always encapsulate it in each list item.
we can always open such a prop, but I want to make sure it makes sense

2020-12-01 10:42 UTC, milkyfruit commented on src/BadgeSelectItem/BadgeSelectItem.js
> +  prefixMarginRight: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
Bookings use subtitle only when additional info exists:
![image](https://user-images.githubusercontent.com/1684587/100729838-f403c000-33d1-11eb-8bab-85fc2013fef1.png)

I see it can happen with `ListItemSelect` when used with avatar or other prefix:
![image](https://user-images.githubusercontent.com/1684587/100730061-3d540f80-33d2-11eb-8c98-377ac8d35fa6.png)

Making it as a string instead of a boolean would save us a trouble, because it's already controlled by subtitle prop:
![image](https://user-images.githubusercontent.com/1684587/100730383-a76cb480-33d2-11eb-89ac-bac1e3e8d547.png)
![image](https://user-images.githubusercontent.com/1684587/100730388-a9cf0e80-33d2-11eb-8624-297edd0cd9e6.png)

2020-12-01 10:51 UTC, milkyfruit commented on src/ListItemSelect/docs/index.story.js
> +          example({
The example can be improved to this, to explain when this prop should be used:

- [ ] PrefixMarginRight
`prefixMarginRight` prop allows to control prefix's margin-right. It's used to align text when a dropdown contains items with and without a subtitle.

```
<Layout cols={1} gap={0}>
  <ListItemSelect
    title="Prefix margin right is 0 (default when no subtitle)"
    prefix={
      <Box>
        <Icons.Toolbox />
      </Box>
    }
  />
  <ListItemSelect
    title="Prefix margin right was overriden to 6px (now it aligns text aligns with bottom item)"
    prefixMarginRight="6px"
    prefix={
      <Box>
        <Icons.Toolbox />
      </Box>
    }
  />
  <ListItemSelect
    title="Prefix margin right is 6px (default when no subtitle)"
    subtitle="default when there ia a subtitle"
    prefix={
      <Box>
        <Icons.Toolbox />
      </Box>
    }
  />
</Layout>;
```

2020-12-01 10:53 UTC, milkyfruit commented on src/BadgeSelectItem/docs/index.story.js
> +            text: '',
- [ ] Suffix
Component has a suffix area. If plain text or icon is inserted, component automatically inverts the color when selected.

2020-12-03 16:10 UTC, bamai commented on src/BadgeSelectItem/BadgeSelectItem.js
> +  prefixMarginRight: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
Hi :)
So how should this be implemented? Do we want to expose a new prop or add changes in css?
@shlomitc @milkyfruit

2020-12-03 18:20 UTC, shlomitc commented on src/BadgeSelectItem/BadgeSelectItem.js
> +  prefixMarginRight: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
What I see here is only when the subtitle appears, which is already covered in the `ListItemSelect` subtitle prop.
If that's the only case, then maybe the `BadgeSelectItem` should have a subtitle prop as well.

If no other objections, we can remove this prop

2020-12-06 10:12 UTC, bamai commented
Currently the additional prefix margin is removed only in BadgeSelectItem. Does it need to be changed in ListItemSelect as well?

2020-12-06 16:10 UTC, TalZa1810 commented on src/BadgeSelectItem/BadgeSelectItem.js
> +      className={st(classes.root, {}, className)}
```suggestion
      className={st(classes.root, className)}
```

With stylable 3 no need for an empty object.

2020-12-06 16:15 UTC, TalZa1810 commented
We've decided that currently we'll fix this just with `BadgeSelectItem`. If we decide to fix this with `ListItemSelect`, we should create a dedicated task for it and update the zeplin spec.

2020-12-09 13:28 UTC, milkyfruit approved these changes

2020-12-10 08:50 UTC, TalZa1810 approved these changes
Two tiny comments. After you fix this, it can be merged :)

2020-12-10 08:50 UTC, TalZa1810 commented on src/BadgeSelectItem/test/BadgeSelectItem.visual.js
> +    describe: 'badge select sizes',
let's add the size explicit here. You can do it like it's done with the `skins` describe

2020-12-10 08:50 UTC, TalZa1810 commented on src/BadgeSelectItem/test/BadgeSelectItem.visual.js
> +          suffix: (
Let's add a simple `<div/>` with inline styles here rather than a component. Than, if there's an issue with the `Badge` component, it will not make this test fail as well.

2020-12-13 10:52 UTC, merged