Wsr provider
wix/wix-style-react pull request #6360
Opened 2020-12-07 15:44 UTC by TalZa1810

### 🔦 Summary
Creating a generic provider to use for our different feature toggles and use this for the Heading Spacing feature.
Still in progress.

Related Jira: https://jira.wixpress.com/browse/DSM-1044 

### ✅ Checklist

- [ ] 👨‍💻 API change is approved by the UI Infra Developers 
- [ ] 👨‍🎨 UX change is approved by the Design System UX 
- 📚 Change is documented
  - [ ] Story
  - [ ] API description
  - [ ] Cheatsheet
  - [ ] Other (explain)
- 🔬 Change is tested
  - [ ] Component
  - [ ] Visual test

2020-12-09 11:38 UTC, WixBuildServer commented
### 🤖 Hi, I'm #Janet!

  A deploy preview of your PR was successfully released 🖼.

  You can find it under one of the following URLs:
  * https://preview.wix-style-react.com/pr_6360

2020-12-14 11:23 UTC, justinara approved these changes

2020-12-14 11:49 UTC, shlomitc requested changes

2020-12-14 11:49 UTC, shlomitc commented on src/WixStyleReactProvider/constants.js
> +  headingSpacing: 'heading-spacing',
AFAIK, the heading spacing is part of a bigger "Layout And Spacing" design change.
I think we should have a single feature for all of this

2020-12-14 11:49 UTC, shlomitc commented on src/WixStyleReactProvider/WixStyleReactProvider.js
> +  as: 'span',
is this the correct default? this will probably wrap an entire app

2020-12-14 11:49 UTC, shlomitc commented on src/WixStyleReactProvider/WixStyleReactProvider.js
> +class WixStyleReactProvider extends React.PureComponent {
Since no state is used, it can be a function component

2020-12-14 11:49 UTC, shlomitc commented on src/WixStyleReactProvider/WixStyleReactProvider.st.css
> +.root {}
if it's empty, let's remove it

2020-12-14 11:49 UTC, shlomitc commented on src/WixStyleReactProvider/test/WixStyleReactProvider.private.uni.driver.js
> +    isFeatureActive: async featureName => {
why is it private?

2020-12-14 11:49 UTC, shlomitc commented on src/WixStyleReactProvider/test/WixStyleReactProvider.visual.js
> +HeadingTests({ themeName, testWithTheme });
I think we should add these tests as part of each component and not as part of the provider.
Since each feature is implemented differently (possibly just a logic change and not visual), then the component knows about it and is responsible to change it.

2020-12-14 11:49 UTC, shlomitc commented on src/WixStyleReactProvider/test/WixStyleReactProvider.visual.js
> +const themeName = 'Wix Style React Provider';
this is not a valid theme

2020-12-14 11:49 UTC, shlomitc commented on src/WixStyleReactProvider/test/WixStyleReactProvider.visual.js
> +import React from 'react';
in general, I don't think we need it

2020-12-14 11:49 UTC, shlomitc commented on src/WixStyleReactProvider/test/storySettings.js
> +  dataHook: 'story-wix-style-react-provider',
`dataHook` is redundant. let's remove it also from the generator

2020-12-14 12:24 UTC, TalZa1810 commented on src/WixStyleReactProvider/WixStyleReactProvider.st.css
> +.root {}
In the next PR, I want to add the fontUpgrade feature and this class will be used.
(I have the files already, just waiting for this PR to be merged first).

2020-12-14 12:25 UTC, TalZa1810 commented on src/WixStyleReactProvider/test/WixStyleReactProvider.private.uni.driver.js
> +    isFeatureActive: async featureName => {
Do we want to expose this to our users? I thought that we want to check this just for our unit tests.

2020-12-14 13:03 UTC, shlomitc commented on src/WixStyleReactProvider/test/WixStyleReactProvider.private.uni.driver.js
> +    isFeatureActive: async featureName => {
you tell me. if it's not something useful, then why bother testing it? it also affects the dom since you're putting a lot of data attributes

2020-12-14 14:32 UTC, TalZa1810 commented
I've added the Madefor to the `st.css` file of the provider since this feature is related to the Madefor.

2020-12-14 14:34 UTC, shlomitc commented on src/WixStyleReactProvider/WixStyleReactProvider.st.css
> +}
there's a lot more logic for it, in the `FontUpgrade` component.
instead of copying, simply reuse the `<FontUpgrade/>` component in the js file (it also has an `active` state)

2020-12-14 14:36 UTC, shlomitc commented on src/WixStyleReactProvider/WixStyleReactProvider.js
> +  features: PropTypes.object,
let's mention here which features we provide. this will also be documented so it's important

2020-12-14 14:41 UTC, shlomitc commented on src/WixStyleReactProvider/constants.js
> +  layoutSpacing: 'layout-spacing',
Since these features are public APIs, we should give them meaningful names. let's be more explicit here (same as our roadmap plans task)
`reducedSpacingAndImprovedLayout`

2020-12-14 14:47 UTC, TalZa1810 commented on src/WixStyleReactProvider/WixStyleReactProvider.st.css
> +}
All the new features that we add, are related to the Madefor anyways. 
Don't we want the general Provider to use the Madefor only?

Another option is adding the fontUpgrade as a feature for the general Provider (another attribute for the `features` prop).

2020-12-14 14:56 UTC, shlomitc commented on src/WixStyleReactProvider/WixStyleReactProvider.st.css
> +}
Use the component in the js and activate it only when the layout and spacing feature toggle is on

2020-12-15 20:25 UTC, shlomitc commented on src/WixStyleReactProvider/WixStyleReactProvider.js
> +      <FontUpgrade
I think it's better to make this as the child element instead of becoming the root.
This will probably be removed in the next major version, so it will be easier to unplug it

2020-12-15 20:25 UTC, shlomitc commented on src/WixStyleReactProvider/constants.js
> +  providerContent: 'provider-content',
this will become redundant once changing the order of the FontUpgrade component

2020-12-17 13:11 UTC, TalZa1810 commented on src/WixStyleReactProvider/WixStyleReactProvider.js
> +      <FontUpgrade
Is this what you meant? https://github.com/wix/wix-style-react/pull/6360/commits/05090d069093e455ac3a41084ba2f9b239a63e85

2020-12-17 13:41 UTC, shlomitc commented on src/WixStyleReactProvider/WixStyleReactProvider.js
> +      <FontUpgrade
```jsx
<WixStyleReactContext.Provider value={features}>
  {React.createElement(
    as,
    {
      'data-hook': dataHook,
      className: className
      [dataAttr.layoutSpacing]: reducedSpacingAndImprovedLayout || null,
    },
    <FontUpgrade
      as={as}
      active={reducedSpacingAndImprovedLayout}
    >
      {children}
    </FontUpgrade>
  )}
</WixStyleReactContext.Provider>
```

2020-12-20 11:51 UTC, merged