Typography - adjust font weight for a specific family
wix/wix-style-react pull request #6373
Opened 2020-12-10 11:34 UTC by EgoziE

This is a rough POC to set different weights for specific font families.

This is the result for weight 500 vs 800 
![image](https://user-images.githubusercontent.com/35173937/101766965-3e7cef00-3aec-11eb-8e1a-5d79c6f2a0ee.png)

2020-12-10 11:40 UTC, shlomitc requested changes

2020-12-10 11:40 UTC, shlomitc commented on src/Foundation/stylable/typography.st.css
> +@import url('https://fonts.googleapis.com/css2?family=Noto+Sans+JP:wght@100&display=swap');
this will cause the font to be added to all stylesheets.
This of a way that we can opt-int specific locales (hint, theming)

2020-12-10 11:50 UTC, EgoziE commented on src/Foundation/stylable/typography.st.css
> +@import url('https://fonts.googleapis.com/css2?family=Noto+Sans+JP:wght@100&display=swap');
It was just a quick POC to see this is technically possible.
Now we can discuss the logistics :)

2020-12-30 11:25 UTC, EgoziE commented
Closing for inactivity, when time comes we'll create a new PR.

2020-12-30 11:25 UTC, closed without merging