Image border
wix/wix-style-react pull request #6379
Opened 2020-12-13 10:50 UTC by roibWix

### 🔦 Summary

...

### ✅ Checklist

- [ ] 👨‍💻 API change is approved by the UI Infra Developers 
- [ ] 👨‍🎨 UX change is approved by the Design System UX 
- 📚 Change is documented
  - [ ] Story
  - [ ] API description
  - [ ] Cheatsheet
  - [ ] Other (explain)
- 🔬 Change is tested
  - [ ] Component
  - [ ] Visual test

2020-12-13 11:00 UTC, WixBuildServer commented
### 🤖 Hi, I'm #Janet!

  A deploy preview of your PR was successfully released 🖼.

  You can find it under one of the following URLs:
  * https://preview.wix-style-react.com/pr_6379

2020-12-14 08:32 UTC, EgoziE requested changes

2020-12-14 08:32 UTC, EgoziE commented on src/Image/Image.st.css
> +  border: 1px solid calc_rgba(value(D10), 0.12);
@milkyfruit We don't have `D10-12` currently
Do you want us to add it to the palette or use a color we already have?

2020-12-14 08:32 UTC, EgoziE commented on src/Image/docs/examples/showBorder.js
> +</Layout>
Merge all examples into one file

2020-12-14 08:32 UTC, EgoziE commented on src/Image/docs/examples/showBorder.js
> +</Layout>
remove ={true}

2020-12-14 08:32 UTC, EgoziE commented on src/Image/test/Image.visual.js
> +      },
remove

2020-12-14 09:00 UTC, roibWix commented on src/Image/docs/examples/showBorder.js
> +</Layout>
done

2020-12-14 09:00 UTC, roibWix commented on src/Image/test/Image.visual.js
> +      },
done

2020-12-14 13:16 UTC, milkyfruit requested changes
@roibWix great work! I have 2 small requests:

- [ ] `showBorder` prop makes image 2px larger. It should remain the same size
- [ ] Example should have a description:
"When content is light, the image can appear with a border to make image ratio visible."

2020-12-14 13:23 UTC, milkyfruit commented on src/Image/Image.st.css
> +  border: 1px solid calc_rgba(value(D10), 0.12);
yes, let's add it to the palette.

2020-12-15 07:00 UTC, roibWix commented on src/Image/Image.st.css
> +  border: 1px solid calc_rgba(value(D10), 0.12);
done

2020-12-15 12:35 UTC, EgoziE approved these changes

2020-12-15 12:37 UTC, merged