<Image/> -  border radius prop
wix/wix-style-react pull request #6384
Opened 2020-12-14 09:46 UTC by roibWix

### 🔦 Summary

...

### ✅ Checklist

- [ ] 👨‍💻 API change is approved by the UI Infra Developers 
- [ ] 👨‍🎨 UX change is approved by the Design System UX 
- 📚 Change is documented
  - [ ] Story
  - [ ] API description
  - [ ] Cheatsheet
  - [ ] Other (explain)
- 🔬 Change is tested
  - [ ] Component
  - [ ] Visual test

2020-12-14 09:48 UTC, roibWix commented
@EgoziE waiting for <image/> show border prop to merge. need to rebase for the examples.js file

2020-12-14 09:56 UTC, WixBuildServer commented
### 🤖 Hi, I'm #Janet!

  A deploy preview of your PR was successfully released 🖼.

  You can find it under one of the following URLs:
  * https://preview.wix-style-react.com/pr_6384

2020-12-14 14:21 UTC, EgoziE requested changes

2020-12-14 14:21 UTC, EgoziE commented on src/Image/Image.js
> +      style={{ ...style, ...imgStyle, ...{ borderRadius } }}
I believe no spread is needed:

```suggestion
      style={{ ...style, ...imgStyle, borderRadius }}
```

2020-12-14 14:21 UTC, EgoziE commented on src/Image/Image.js
> +  borderRadius: '8px',
This can be removed, because you already get the default value from the CSS file

2020-12-14 14:21 UTC, EgoziE commented on src/Image/index.d.ts
> +  borderRadius? : string,
If the type is pure CSS property, we use the direct type for it:

```suggestion
  borderRadius?: React.CSSProperties['borderRadius'];
```

2020-12-15 07:05 UTC, roibWix commented on src/Image/Image.js
> +      style={{ ...style, ...imgStyle, ...{ borderRadius } }}
done

2020-12-15 07:06 UTC, roibWix commented on src/Image/Image.js
> +  borderRadius: '8px',
@EgoziE we don't want to keep it for the table of the API section? (default value)

2020-12-15 08:00 UTC, roibWix commented on src/Image/index.d.ts
> +  borderRadius? : string,
done

2020-12-16 13:40 UTC, EgoziE approved these changes

2020-12-16 14:02 UTC, milkyfruit approved these changes
@roibWix PR looks great!

2020-12-16 14:12 UTC, merged