<AddressInput/> - update to match design spec
wix/wix-style-react pull request #6400
Opened 2020-12-15 16:51 UTC by gendeld

### 🔦 Summary

...

### ✅ Checklist

- [ ] 👨‍💻 API change is approved by the UI Infra Developers 
- [ ] 👨‍🎨 UX change is approved by the Design System UX 
- 📚 Change is documented
  - [ ] Story
  - [ ] API description
  - [ ] Cheatsheet
  - [ ] Other (explain)
- 🔬 Change is tested
  - [ ] Component
  - [ ] Visual test

2020-12-15 16:53 UTC, gendeld commented on src/AddressInput/AddressInput.js
> +  _onChange = event => {
Debouncing is being implemented at the hook level

2020-12-15 16:54 UTC, gendeld commented on src/AddressInput/AddressInput.js
> +  _getInputValue = () => {
Allow passing `value` prop to have controlled input

2020-12-15 16:54 UTC, gendeld commented on src/AddressInput/AddressInput.js
> +  _renderOptions = () => {
Add Empty and Loading states to component

2020-12-15 16:55 UTC, gendeld commented on src/AddressInput/AddressInput.js
> +    const showLoadingStatusIndicator = isLoading && !isDropdownOpen;
In spec, when dropdown is closed - loader is shown on the input,
and when it is open, loader is shown in the dropdown instead

2020-12-15 16:56 UTC, gendeld commented on src/AddressInput/AddressInput.js
> +        placeholder={placeholder}
Add placeholder

2020-12-15 16:57 UTC, gendeld commented on src/AddressInput/AddressInput.js
> +  status: PropTypes.oneOf(['loading']),
Currently there are no `error` or `warning` states described in the spec

2020-12-16 13:16 UTC, WixBuildServer commented
### 🤖 Hi, I'm #Janet!

  A deploy preview of your PR was successfully released 🖼.

  You can find it under one of the following URLs:
  * https://preview.wix-style-react.com/pr_6400

2020-12-20 11:58 UTC, EgoziE requested changes

2020-12-20 11:58 UTC, EgoziE commented on src/AddressInput/AddressInput.js
> +      this.props.onChange(event);
For readability only destruct onChange from this.props

2020-12-20 11:58 UTC, EgoziE commented on src/AddressInput/AddressInput.js
> +  _onChange = event => {
k

2020-12-20 11:58 UTC, EgoziE commented on src/AddressInput/AddressInput.js
> +    const noResultsFound = !options || !options.length;
Just for readability:
```suggestion
    const noResultsFound = !options || options.length === 0;
```

2020-12-20 11:58 UTC, EgoziE commented on src/AddressInput/AddressInput.js
> +    const showLoadingStatusIndicator = isLoading && !isDropdownOpen;
Sound like something that should be mentioned as a comment for future possible questions.

2020-12-20 11:58 UTC, EgoziE commented on src/AddressInput/AddressInput.js
> +  status: PropTypes.oneOf(['loading']),
I know that it's not described directly in Address Input page, but this component is part of the Input family and "status" is a basic behavior of IC.Input family.
Therefore I wouldn't remove it.

2020-12-20 11:58 UTC, EgoziE commented on src/AddressInput/AddressInput.js
> +  noResultsText: 'No results found',
This is not a good idea in my opinion.
It assumes that English is the default language, let's talk with UX, if they want this prop to have a value no matter what, maybe we should make it mandatory.

2020-12-20 11:58 UTC, EgoziE commented on src/AddressInput/index.d.ts
> +  status?: 'loading';
same comment

2020-12-20 11:58 UTC, EgoziE commented on src/AddressInput/index.d.ts
> +  noResultsText?: string | React.ReactNode;
String is a sub  type of React.ReactNode
```suggestion
  noResultsText?: React.ReactNode;
```

2020-12-20 13:39 UTC, EgoziE approved these changes

2020-12-21 11:54 UTC, assafzi commented
UX here.
Looks great.
only 2 things to improve:

- [ ] Add, at the description that this component uses <AddressInputItem/>, like this:
![image](https://user-images.githubusercontent.com/66679639/102774585-f2576780-4393-11eb-9cd6-6f78c81eb755.png)

- [ ] Loader should be before the clear button (now it's after)
![image](https://user-images.githubusercontent.com/66679639/102774392-9096fd80-4393-11eb-8562-7ce885a12c8d.png)

2020-12-21 14:04 UTC, merged

2020-12-21 21:08 UTC, assafzi commented
Approved by UX
Great descriptions!
Thanks