Checkbox - add properties selectionAreaSkin and selectionAreaPadding
wix/wix-style-react pull request #6403
Opened 2020-12-16 12:02 UTC by assafganor

#pr

2020-12-16 12:13 UTC, WixBuildServer commented
### 🤖 Hi, I'm #Janet!

  A deploy preview of your PR was successfully released 🖼.

  You can find it under one of the following URLs:
  * https://preview.wix-style-react.com/pr_6403

2020-12-16 15:06 UTC, EgoziE requested changes

2020-12-16 15:06 UTC, EgoziE commented on src/Checkbox/index.d.ts
> +  SelectionAreaPadding?: React.CSSProperties['padding'];
Please also add a type test for these two props (in file src/Checkbox/test/Checkbox.tsx)

2020-12-16 21:19 UTC, assafganor commented on src/Checkbox/index.d.ts
> +  SelectionAreaPadding?: React.CSSProperties['padding'];
added and fix typos

2020-12-16 21:22 UTC, assafganor commented on src/Checkbox/Checkbox.st.css
> +}
I moved the border and padding to the label so all area will be "active"

2020-12-17 08:48 UTC, EgoziE requested changes

2020-12-17 08:48 UTC, EgoziE commented on src/Checkbox/Checkbox.js
> +            style={{ padding: selectionAreaPadding }}
This extra div breaks visual tests.
Take a look at ListItemSelect component for example:
https://preview.wix-style-react.com/pr_6403/?path=/story/components-api-components--listitemselect

2020-12-22 09:07 UTC, milkyfruit approved these changes
@assafganor this PR looks great.

2020-12-23 08:33 UTC, EgoziE approved these changes

2020-12-23 08:33 UTC, merged