<RadioGroup /> - add `selectionAreaSkin` and `selectionAreaPadding` props
wix/wix-style-react pull request #6408
Opened 2020-12-17 00:37 UTC by assafganor

### 🔦 Summary
New props for `selectionArea`:
`selectionAreaSkin` and `selectionAreaPadding` 

https://app.zeplin.io/project/5c8f6f1f9f489505cac756dc/screen/5c9b502feb413e0ab95466be
...

### ✅ Checklist

- [ ] 👨‍💻 API change is approved by the UI Infra Developers 
- [x] 👨‍🎨 UX change is approved by the Design System UX 
- 📚 Change is documented
  - [x] Story
  - [x] API description
  - [ ] Cheatsheet
  - [ ] Other (explain)
- 🔬 Change is tested
  - [ ] Component
  - [ ] Visual test

2020-12-17 00:49 UTC, WixBuildServer commented
### 🤖 Hi, I'm #Janet!

  A deploy preview of your PR was successfully released 🖼.

  You can find it under one of the following URLs:
  * https://preview.wix-style-react.com/pr_6408

2020-12-17 09:20 UTC, EgoziE commented
@assafganor Hey
Please pay attention to visual tests, it seems there are extra margin/padding somewhere
![image](https://user-images.githubusercontent.com/35173937/102468190-e39e4700-4059-11eb-9b24-137ad08265ca.png)

2020-12-20 09:33 UTC, EgoziE requested changes

2020-12-20 09:33 UTC, EgoziE commented on src/RadioGroup/RadioButton/RadioButton.js
> +              [classes.checked]: checked,
These states exist in a higher element already. (classes.radioWrapper)

2020-12-20 09:33 UTC, EgoziE commented on src/RadioGroup/RadioButton/RadioButton.js
> +              style={{ padding: selectionAreaPadding }}
Is this extra div mandatory?
Padding can be part of the label itself.

2020-12-20 10:01 UTC, assafganor commented on src/RadioGroup/RadioButton/RadioButton.js
> +              style={{ padding: selectionAreaPadding }}
if padding will be part of label , the padding that I added for the outlined selectionAreaSkin will be override.
I needed to separate the `selectionAreaPadding` from the `selectionAreaSkin` that adds border/padding to label

2020-12-20 10:24 UTC, assafganor commented on src/RadioGroup/RadioButton/RadioButton.js
> +              [classes.checked]: checked,
removed and updated css

2020-12-20 11:34 UTC, EgoziE commented on src/RadioGroup/RadioButton/RadioButton.js
> +              style={{ padding: selectionAreaPadding }}
I see what you mean.
Well, in order to remove the extra div and for the CSS to be readable and understandable without padding games, in my opinion the best solution here is to have a permanent border for all states with a relevant color for each state.

2020-12-20 11:36 UTC, EgoziE commented on src/RadioGroup/RadioButton/RadioButton.js
> +              style={{ padding: selectionAreaPadding }}
What do you think?
(same goes for the Checkbox PR)

2020-12-20 16:02 UTC, assafganor commented on src/RadioGroup/RadioButton/RadioButton.js
> +              style={{ padding: selectionAreaPadding }}
It's not only color, we still need padding/border games because
default is:
border 1px , padding: 1px
and checked is:
border: 2px , padding: 0

Maybe I'll use variables for the padding and border values?
$SelectionAreaBorderWidth: '1px'
$SelectionAreaPadding: '1px'
$SelectionAreaBorderWidthChecked: '2px'
$SelectionAreaPaddingChecked: '0px'

2020-12-21 10:31 UTC, assafganor commented on src/RadioGroup/RadioButton/RadioButton.js
> +              style={{ padding: selectionAreaPadding }}
@EgoziE  Do you have other idea how to make it more readable? or how can we do it without border/padding games?
I thought about `box-sizing: border-box` but we don't know the width and height.

2020-12-21 15:44 UTC, EgoziE commented on src/RadioGroup/RadioButton/RadioButton.js
> +              style={{ padding: selectionAreaPadding }}
I understand the complexity of this design.
In order not to block you, let's take this solution with the extra div, we'll probably refactor the component sometime soon to remove classnames library anyway.

2020-12-21 16:00 UTC, milkyfruit reviewed
@assafganor `selectionAreaSkin="outlined"` looks great.
It's strange that `selectionAreaPadding` when set to `1px` it's not 1 but 15 pixels. Why it's implemented this way? I think we should give a full control.

2020-12-21 22:07 UTC, assafganor commented
@milkyfruit 
I thought about our needs and missed your instructions in Zeplin, so I just added padding to the default values, instead of override it completely.

2020-12-22 09:03 UTC, milkyfruit commented
> @milkyfruit
> I thought about our needs and missed your instructions in Zeplin, so I just added padding to the default values, instead of override it completely.

@assafganor I think it should let to override all the padding, otherwise prop is confusing.

2020-12-22 09:26 UTC, assafganor commented
> > @milkyfruit
> > I thought about our needs and missed your instructions in Zeplin, so I just added padding to the default values, instead of override it completely.
> 
> @assafganor I think it should let to override all the padding, otherwise prop is confusing.

I agree, I fixed it

2020-12-23 08:30 UTC, EgoziE approved these changes

2020-12-23 08:30 UTC, merged