Documentation improvements
wix/wix-style-react pull request #6412
Opened 2020-12-17 13:38 UTC by roibWix

### 🔦 Summary

...

### ✅ Checklist

- [ ] 👨‍💻 API change is approved by the UI Infra Developers 
- [ ] 👨‍🎨 UX change is approved by the Design System UX 
- 📚 Change is documented
  - [ ] Story
  - [ ] API description
  - [ ] Cheatsheet
  - [ ] Other (explain)
- 🔬 Change is tested
  - [ ] Component
  - [ ] Visual test

2020-12-17 13:48 UTC, WixBuildServer commented
### 🤖 Hi, I'm #Janet!

  A deploy preview of your PR was successfully released 🖼.

  You can find it under one of the following URLs:
  * https://preview.wix-style-react.com/pr_6412

2020-12-23 12:24 UTC, EgoziE requested changes

2020-12-23 12:24 UTC, EgoziE commented on src/CardGalleryItem/CardGalleryItem.uni.driver.js
> +   * Trigger hover state on the element.
`Triggers` is for events and callbacks

```suggestion
   * Hovers the component.
```

2020-12-23 12:24 UTC, EgoziE commented on src/CardGalleryItem/CardGalleryItem.uni.driver.js
> +   * Return a boolean for the primary action clickability.
For boolean return value, the description should be:
"Checks whether xxx"

2020-12-23 12:24 UTC, EgoziE commented on src/Checkbox/Checkbox.uni.driver.js
> +     * Click on the component root element.
We try to follow Google guides for documentation.
This is a very long read, this is the relevant section:
https://developers.google.com/style/api-reference-comments

Bottom line "Use present tense for all descriptions."

2020-12-23 17:10 UTC, TalZa1810 commented on src/CircularProgressBar/docs/index.story.js
> +          example({
If you want to know more about the sections API, you can read [here](https://github.com/wix/wix-ui/blob/master/packages/wix-storybook-utils/docs/sections.md#sections).

2020-12-24 09:06 UTC, EgoziE requested changes

2020-12-24 09:06 UTC, EgoziE commented on src/ColorPicker/ColorPicker.js
> +   * @param {_color}
The pattern of @param is:

@param {\<TYPE\>} \<NAME\> \<DESCRIPTION\>

2020-12-24 09:06 UTC, EgoziE commented on src/ColorPicker/ColorPicker.js
> +   * @returns {Void}
If the function returns void, remove the @returns statement

2020-12-24 14:25 UTC, EgoziE approved these changes

2020-12-24 14:32 UTC, merged