Styled nestable list fixes
wix/wix-style-react pull request #6416
Opened 2020-12-20 10:18 UTC by AndriiTsarenko

### 🔦 Summary

...

### ✅ Checklist

- [ ] 👨‍💻 API change is approved by the UI Infra Developers 
- [ ] 👨‍🎨 UX change is approved by the Design System UX 
- 📚 Change is documented
  - [ ] Story
  - [ ] API description
  - [ ] Cheatsheet
  - [ ] Other (explain)
- 🔬 Change is tested
  - [ ] Component
  - [ ] Visual test

2020-12-20 10:30 UTC, WixBuildServer commented
### 🤖 Hi, I'm #Janet!

  A deploy preview of your PR was successfully released 🖼.

  You can find it under one of the following URLs:
  * https://preview.wix-style-react.com/pr_6416

2020-12-21 12:07 UTC, AndriiTsarenko commented on src/BadgeSelectItem/BadgeSelectItem.js
> +  skin: PropTypes.string,
This triggered error in storybook

2020-12-21 12:07 UTC, AndriiTsarenko commented on src/NestableList/Container.js
Collapse is buggy for now so I don't use collapse.

2020-12-21 12:08 UTC, AndriiTsarenko commented on src/NestableList/Container.js
> +          const veryLastItem =
This is needed to hide the bottom border on the last item or the action button

2020-12-21 12:08 UTC, AndriiTsarenko commented on src/NestableList/Container.js
> +              {!item.isCollapsed && (
Grouped children a little

2020-12-21 13:08 UTC, justinara requested changes
Nice job! I see it's keyboard accessible now! But I noticed a slight difference from the specs - before being able to reorder item, you should "pick it up" by pressing ENTER key down. Once picked up item get the same drop shadow and a background colour. You can check the full flow in the specs: https://zpl.io/bJJm8rD

2020-12-23 16:09 UTC, EgoziE requested changes
Please add to all non public functions an underscore.

2020-12-23 16:09 UTC, EgoziE commented on src/StyledNestableList/StyledNestableList.js
> +        break;
Just for readability, default should be the last case.

2020-12-29 08:13 UTC, merged