Add documentation yaml to collect documentation for internal DOCs too
wix/wix-style-react pull request #6425
Opened 2020-12-22 13:09 UTC by itaiche

### 🔦 Summary
Adding the documentation to internal repo
...

### ✅ Checklist

2020-12-22 15:22 UTC, TalZa1810 requested changes
Few typos that I've found

2020-12-22 15:22 UTC, TalZa1810 commented on documentation.yaml
> +    - file: usage-with-create-stylable-app.md
```suggestion
    - file: docs/usage/usage-with-create-stylable-app.md
```

2020-12-22 15:22 UTC, TalZa1810 commented on documentation.yaml
> +      title: FAQ/TypeScriptw
```suggestion
      title: FAQ/TypeScript
```

2020-12-22 15:23 UTC, TalZa1810 commented
Also, make sure that [you sign your commits ](https://github.com/wix/wix-style-react/blob/master/docs/contribution/CREATE_PR.md#sign-commits)so that the CI will run

2020-12-22 15:30 UTC, itaiche commented on documentation.yaml
> +  category: fe-guild
Nope, this is aligned with our internal docs path.
It's not `fed-guild` :)

2020-12-22 15:41 UTC, WixBuildServer commented
### 🤖 Hi, I'm #Janet!

  A deploy preview of your PR was successfully released 🖼.

  You can find it under one of the following URLs:
  * https://preview.wix-style-react.com/pr_6425

2020-12-23 09:53 UTC, TalZa1810 approved these changes

2020-12-23 09:53 UTC, merged