Tag - migrate to stylable
wix/wix-style-react pull request #6432
Opened 2020-12-23 11:11 UTC by Zivilekin

2020-12-23 11:24 UTC, WixBuildServer commented
### 🤖 Hi, I'm #Janet!

  A deploy preview of your PR was successfully released 🖼.

  You can find it under one of the following URLs:
  * https://preview.wix-style-react.com/pr_6432

2020-12-23 15:21 UTC, EgoziE requested changes

2020-12-23 15:21 UTC, EgoziE commented on src/Tag/Tag.st.css
> +:global(.rtl) .root:size(tiny),
I see all our `:global(.rtl)` styles here are related to margin and padding.
Let's remove **all** of them in favor of:
- margin-block-start
- margin-block-end
- padding-block-start
- padding-block-end

Note, don't use `margin-block` or `padding-block` without the starts/end suffix

2021-01-06 08:44 UTC, mykas commented on src/Tag/Tag.js
> +    const clickable = onClick !== noop;
Lets remove this noop  usage and instead do: `!!onClick`

2021-01-06 08:46 UTC, mykas commented on src/Tag/Tag.st.css
> +  max-width: -moz-available;
I think that browser based prefixes are handled by the webpack already. No need to add special handling

2021-01-06 08:47 UTC, mykas commented on src/Tag/Tag.st.css
> +  max-width: stretch;
I think we have a problem here. `stretch` is not supported by most of the browsers like safari, firefox: https://developer.mozilla.org/en-US/docs/Web/CSS/max-width

Some kind of other solution must be found here

2021-01-06 08:50 UTC, mykas commented on src/Tag/Tag.st.css
> +.root:not(:disabled):theme(standard) {
I wonder if you remove this `:not(:disabled)`. Does it work?

2021-01-06 13:37 UTC, mykas commented on src/Tag/Tag.st.css
> +  max-width: stretch;
to resolve the issue a separate task has been created.

2021-01-06 13:42 UTC, mykas approved these changes
Good job, Zivile! Really, I mean it!

2021-01-06 14:59 UTC, merged