<Accordion /> - Add items size prop
wix/wix-style-react pull request #6436
Opened 2020-12-24 12:43 UTC by mjurfest

### 🔦 Summary

Add items size prop to Accordion.

### ✅ Checklist

- 📚 Change is documented
  - [x] Story
  - [x] API description
- 🔬 Change is tested
  - [x] Visual test

2020-12-24 12:50 UTC, EgoziE requested changes

2020-12-24 12:50 UTC, EgoziE commented on src/Accordion/AccordionItem/AccordionItem.js
> +            className={st(classes.header, { size }, className)}
`className` prop should not be part of this element

2020-12-24 13:04 UTC, WixBuildServer commented
### 🤖 Hi, I'm #Janet!

  A deploy preview of your PR was successfully released 🖼.

  You can find it under one of the following URLs:
  * https://preview.wix-style-react.com/pr_6436

2020-12-30 11:16 UTC, EgoziE approved these changes

2020-12-30 14:16 UTC, EgoziE approved these changes

2020-12-30 14:16 UTC, merged