<Accordion/> - introduce builders
wix/wix-style-react pull request #6442
Opened 2020-12-27 14:25 UTC by EgoziE

Builders for Accordion!
![image](https://user-images.githubusercontent.com/35173937/103172959-26350000-4860-11eb-98f1-7df52f799067.png)

2020-12-27 14:26 UTC, EgoziE commented
```
<Accordion
  items={[
    accordionSectionItemBuilder({
      title: "I'm an Accordion Section Item !",
    }),
    accordionItemBuilder({
      title: 'First Row',
      children: (
        <Text>
          Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
          eiusmod tempor incididunt ut labore et dolore magna aliqua
        </Text>
      ),
    }),
  ]}
/>
```

2020-12-27 14:27 UTC, EgoziE commented
@shlomitc This is needed because we got request for a "section accordion item"
I'd love to hear your thoughts about this PR

2020-12-27 15:03 UTC, WixBuildServer commented
### 🤖 Hi, I'm #Janet!

  A deploy preview of your PR was successfully released 🖼.

  You can find it under one of the following URLs:
  * https://preview.wix-style-react.com/pr_6442

2020-12-28 16:06 UTC, TalZa1810 approved these changes
Seems fine.
Just for transparency- 
this is PR is to help our contributors with the `AccordionItemSection` contribution.

2020-12-28 16:09 UTC, TalZa1810 commented
Another thought- maybe adding a unit test for the render function should be added. Something similar to [this](https://github.com/wix/wix-style-react/blob/master/src/DropdownLayout/test/DropdownLayout.spec.js#L282).

2020-12-28 16:10 UTC, TalZa1810 requested changes
Another thought- maybe adding a unit test for the render function should be added. Something similar to [this](https://github.com/wix/wix-style-react/blob/master/src/DropdownLayout/test/DropdownLayout.spec.js#L282).

2020-12-29 08:18 UTC, shlomitc commented on src/Accordion/Accordion.js
> +      PropTypes.arrayOf(PropTypes.func),
is this still correct?. I see that you now expect a `render()` method on the items object

2020-12-29 08:18 UTC, shlomitc commented on src/Accordion/test/Accordion.spec.js
> +      await sleep(350).then(async () => {
doesn't it make sense that the driver will do the `sleep`ing?

2020-12-29 09:34 UTC, EgoziE commented on src/Accordion/test/Accordion.spec.js
> +      await sleep(350).then(async () => {
Good idea! thanks

2020-12-29 14:19 UTC, merged