<FunnelChart> - add new prop - displayValue
wix/wix-style-react pull request #6457
Opened 2020-12-29 12:48 UTC by seifange

### 🔦 Summary

...

### ✅ Checklist

- [ ] 👨‍💻 API change is approved by the UI Infra Developers 
- [ ] 👨‍🎨 UX change is approved by the Design System UX 
- 📚 Change is documented
  - [ ] Story
  - [ ] API description
  - [ ] Cheatsheet
  - [ ] Other (explain)
- 🔬 Change is tested
  - [ ] Component
  - [ ] Visual test

2020-12-29 12:59 UTC, WixBuildServer commented
### 🤖 Hi, I'm #Janet!

  A deploy preview of your PR was successfully released 🖼.

  You can find it under one of the following URLs:
  * https://preview.wix-style-react.com/pr_6457

2020-12-29 14:26 UTC, EgoziE requested changes
I can approve the visual tests, but maybe just add "displayValue" to them instead?

2020-12-29 14:26 UTC, EgoziE commented on src/FunnelChart/FunnelLabel/FunnelLabel.js
> +  const numberToPresent = displayValue ? displayValue : value ? value : '-';
This condition is too complicated.
Lets add:
```
FunnelLabel.defaultProps = {
  value: '-',
}
```

2020-12-29 14:37 UTC, seifange commented on src/FunnelChart/FunnelLabel/FunnelLabel.js
> +  const numberToPresent = displayValue ? displayValue : value ? value : '-';
sure np i'll fix!

2020-12-30 09:25 UTC, EgoziE approved these changes

2020-12-30 10:47 UTC, merged