<MarketingLayout/> - update size tiny columns and spacing
wix/wix-style-react pull request #6458
Opened 2020-12-29 15:52 UTC by yogevitz

### 🔦 Summary

updated the layout columns and spacing for `<MarketingLayout/>` when using size tiny
set image columns span to be 4 columns instead of 3
set spacing between columns to be 12px instead of 30px

### ✅ Checklist

- [ ] 👨‍💻 API change is approved by the UI Infra Developers 
- [x] 👨‍🎨 UX change is approved by the Design System UX @milkyfruit

2020-12-29 16:02 UTC, WixBuildServer commented
### 🤖 Hi, I'm #Janet!

  A deploy preview of your PR was successfully released 🖼.

  You can find it under one of the following URLs:
  * https://preview.wix-style-react.com/pr_6458

2021-01-05 14:01 UTC, milkyfruit requested changes
@yogevitz please change the gap width from 12 to 24 pixels. The rest is great and it can be merged afterwards!

2021-01-06 09:16 UTC, EgoziE approved these changes

2021-01-06 13:53 UTC, TalZa1810 commented
@yogevitz, there are 4 visuals diffs that I'm not sure whether this is the desired result.
Let's have a quick call so we can go over them together. I think it'll be faster this way.
Ping me when you are available.

2021-01-13 08:15 UTC, TalZa1810 commented
The visual diffs are approved by Domas.

2021-01-13 08:48 UTC, milkyfruit approved these changes

2021-01-13 08:48 UTC, merged