<DatePicker/> - Adding Unidriver
wix/wix-style-react pull request #6466
Opened 2020-12-31 09:05 UTC by roibWix

### 🔦 Summary

...

### ✅ Checklist

- [ ] 👨‍💻 API change is approved by the UI Infra Developers 
- [ ] 👨‍🎨 UX change is approved by the Design System UX 
- 📚 Change is documented
  - [ ] Story
  - [ ] API description
  - [ ] Cheatsheet
  - [ ] Other (explain)
- 🔬 Change is tested
  - [ ] Component
  - [ ] Visual test

2020-12-31 09:06 UTC, roibWix commented
@EgoziE 
I'm pretty sure it's the wrong way to do it in the Input.uni.driver.js.
Let me know what you think.

2020-12-31 09:16 UTC, WixBuildServer commented
### 🤖 Hi, I'm #Janet!

  A deploy preview of your PR was successfully released 🖼.

  You can find it under one of the following URLs:
  * https://preview.wix-style-react.com/pr_6466

2020-12-31 09:34 UTC, shlomitc commented
@sivanharel

2021-01-04 11:17 UTC, sivanharel commented
@roibWix - very nice work :)
I have a small question, why do you need the `getDataHook` method in the `input.uni.driver`?

2021-01-04 11:37 UTC, roibWix commented
Hey @sivanharel ,
We don't need.
It's my next commit. just wanted to make sure that the unit tests pass

2021-01-05 13:15 UTC, TalZa1810 requested changes
Hi Roi,
I've added some comments. I hope everything is clear. Let me know if something is unclear.

2021-01-05 13:15 UTC, TalZa1810 commented on src/DatePicker/test/DatePicker.spec.js
> +          setTimeout(async () => {
same comment

2021-01-05 13:15 UTC, TalZa1810 commented on src/DatePicker/test/DatePicker.spec.js
> +      it('should pass inputProps to input component', async () => {
After deleting these methods this test can be deleted as well.

2021-01-05 13:15 UTC, TalZa1810 commented on src/Input/Input.uni.driver.d.ts
> +  hasRightBorderRadius: () => Promise<boolean>;
delete these methods

2021-01-05 13:15 UTC, TalZa1810 commented on src/Input/Input.uni.driver.d.ts
> +  hasLeftBorderRadius: () => Promise<boolean>;
delete

2021-01-05 13:15 UTC, TalZa1810 commented on src/Input/Input.js
> +    this._isMounted && this.setState({ focus: true });
Why do we need to add this to the logic of the component? Same comment as the DatePicker.js

2021-01-06 06:04 UTC, roibWix commented on src/DatePicker/test/DatePicker.spec.js
> +  async function runTests(render) {
done

2021-01-06 06:05 UTC, roibWix commented on src/DatePicker/test/DatePicker.spec.js
> +    afterEach(() => cleanup());
done

2021-01-06 06:07 UTC, roibWix commented on src/DatePicker/DatePicker.js
> +    this._isMounted = false;
![image](https://user-images.githubusercontent.com/36195609/103735170-2c607480-4ff6-11eb-8f2f-e636b677afff.png)

2021-01-06 06:09 UTC, roibWix commented on src/DatePicker/test/DatePicker.spec.js
> +        expect(await driver.exists()).toBe(true);
oopppss,fixed

2021-01-06 06:14 UTC, roibWix commented on src/DatePicker/test/DatePicker.spec.js
> +          await inputDriver.trigger('click');
done

2021-01-06 06:14 UTC, roibWix commented on src/DatePicker/test/DatePicker.spec.js
> +          await inputDriver.trigger('click');
done

2021-01-06 06:17 UTC, roibWix commented on src/Input/Input.js
> +    this._isMounted && this.setState({ focus: true });
![image](https://user-images.githubusercontent.com/36195609/103735832-94638a80-4ff7-11eb-9640-4aa5df4dab56.png)

2021-01-06 06:28 UTC, roibWix commented
@TalZa1810  fixed all the simple stuff.

2021-01-06 12:21 UTC, roibWix commented on src/DatePicker/DatePicker.js
> +    this._isMounted = false;
talk to moshe

2021-01-06 12:23 UTC, roibWix commented on src/DatePicker/DatePicker.uni.driver.js
> +  const driver = {
add descriptions altoght it doesnt

2021-01-06 12:24 UTC, roibWix commented on src/DatePicker/README.TESTKIT.md
> -### Polyfills
talk with egozi where to place it

2021-01-06 12:36 UTC, roibWix commented on src/Input/Input.uni.driver.js
> +    hasRightBorderRadius: async () => !(await base.attr(DATA_ATTR.RIGHTBORDERRADIUS)),
deleted

2021-01-06 12:44 UTC, roibWix commented on src/DatePicker/constants.js
> +  datePickerInput: 'date-picker-input',
done

2021-01-06 12:45 UTC, roibWix commented on src/Input/Input.uni.driver.js
> +    hasLeftBorderRadius: async () => !(await base.attr(DATA_ATTR.LEFTBORDERRADIUS)),
done

2021-01-06 13:38 UTC, roibWix commented on src/DatePicker/test/DatePicker.spec.js
> +          setTimeout(async () => {
done

2021-01-06 13:38 UTC, roibWix commented on src/DatePicker/test/DatePicker.spec.js
> +          setTimeout(async () => expect(await calendarDriver.isVisible()).toBe(false), 0);
done

2021-01-06 13:38 UTC, roibWix commented on src/DatePicker/test/DatePicker.spec.js
> +          setTimeout(async () => {
done

2021-01-06 13:38 UTC, roibWix commented on src/Input/Input.uni.driver.d.ts
> +  hasRightBorderRadius: () => Promise<boolean>;
done

2021-01-07 10:06 UTC, mosheKerbel approved these changes

2021-01-10 10:27 UTC, TalZa1810 approved these changes
After merging this PR please create the following PRs:
**First PR:** 
1. Making sure that the uni driver methods are properly documented. I think that the Polyfills which are used within our own tests should be documented as well.
2. Adding the locales description to the `DatePicker customizations` example. 

**Second PR:**
Deleting and moving the relevant Input tests to be visual (the border radius related tests).

2021-01-10 10:27 UTC, TalZa1810 commented on src/DatePicker/README.md
> -# DatePicker
I think that the locals description should be added to the `DatePicker customizations` example.

2021-01-10 12:30 UTC, merged

2021-01-10 12:43 UTC, roibWix commented
Hey @TalZa1810 ,
regarding the first PR:
the polyfills are not relevant. they were created because jsdoc didn't support those methods. They are supported today so i'll remove them.

2021-01-11 08:27 UTC, roibWix commented
@TalZa1810 ,
Egozi is now working on the input component so he'll work on the tests.