<GooglePreview> - Adjustments
wix/wix-style-react pull request #6474
Opened 2020-12-31 14:58 UTC by tomershk

### 🔦 Summary

Make the google preview component up to date.

1. Enable options of multi-line in title and description: 
- new props: `titleMaxLines` `descriptionMaxLines`

2. Enable option of transparent BG:
- new prop: `backgroundColor` with the options: `white` or `transparent`
- In case value is `transparent` border will also be hidden

3. Change the UI of the component to match the Google existing design:
- Move url to top
- Change url color to according to google.

Link to monday: https://wix.monday.com/boards/535450707/pulses/938373975

### ✅ Checklist

- [ ] 👨‍💻 API change is approved by the UI Infra Developers 
- [x] 👨‍🎨 UX change is approved by the Design System UX @ayeletr 
- 📚 Change is documented
  - [x] Story
  - [x] API description
- 🔬 Change is tested
  - [x] Visual test

2020-12-31 16:41 UTC, TalZa1810 commented
Hi @tomershk 
Can you please [sign your commits](https://github.com/wix/wix-style-react/blob/master/docs/contribution/CREATE_PR.md#sign-commits) so that the CI will run?
Thanks

2020-12-31 17:07 UTC, EgoziE requested changes
Please add all new props to types & type test file (index.d.ts & GooglePreview.tsx)

2020-12-31 18:58 UTC, tomershk commented
> Hi @tomershk
> Can you please [sign your commits](https://github.com/wix/wix-style-react/blob/master/docs/contribution/CREATE_PR.md#sign-commits) so that the CI will run?
> Thanks

Will do.
What should I do with the current commit? how can I sign it?

2020-12-31 19:06 UTC, TalZa1810 commented
> sign your commits

The instructions are here:
https://github.com/wix/wix-style-react/blob/master/docs/contribution/CREATE_PR.md#sign-commits

2020-12-31 22:16 UTC, WixBuildServer commented
### 🤖 Hi, I'm #Janet!

  A deploy preview of your PR was successfully released 🖼.

  You can find it under one of the following URLs:
  * https://preview.wix-style-react.com/pr_6474

2020-12-31 22:24 UTC, tomershk commented on src/GooglePreview/GooglePreview.js
> +  backgroundColor: PropTypes.oneOf(['white', 'transparent']),
Agreed 😄

2021-01-01 07:45 UTC, tomershk commented
Visual test updated to align with the updated look

2021-01-04 16:28 UTC, EgoziE approved these changes

2021-01-04 16:29 UTC, merged