Accordion section item style
wix/wix-style-react pull request #6475
Opened 2020-12-31 15:57 UTC by mjurfest

### 🔦 Summary

- Change accordion section item style
- Change accordion item header padding to 30px

### ✅ Checklist

- [X] 👨‍🎨 UX change is approved by the Design System UX @ayeletr

2020-12-31 16:07 UTC, WixBuildServer commented
### 🤖 Hi, I'm #Janet!

  A deploy preview of your PR was successfully released 🖼.

  You can find it under one of the following URLs:
  * https://preview.wix-style-react.com/pr_6475

2020-12-31 16:41 UTC, EgoziE requested changes

2020-12-31 16:41 UTC, EgoziE commented on src/Accordion/AccordionSectionItem/AccordionSectionItem.js
> +      <Text skin="standard" weight="bold" size="small">
Might need ellipsis by default

2020-12-31 19:15 UTC, EgoziE commented on src/Foundation/stylable/colors.st.css
> +  B70: #F9FBFC; /* Accordion Section Item */
We decided not to add this color to the palette.

2020-12-31 19:28 UTC, mjurfest commented on src/Foundation/stylable/colors.st.css
> +  B70: #F9FBFC; /* Accordion Section Item */
Do you mean to add the color directly to the `AccordionSectionItem.st.css` file or not to use it at all?
Kfir told me that the color was approved.

2021-01-03 10:40 UTC, EgoziE commented on src/Foundation/stylable/colors.st.css
> +  B70: #F9FBFC; /* Accordion Section Item */
Not to use it at all.

2021-01-05 15:44 UTC, EgoziE approved these changes

2021-01-06 09:04 UTC, milkyfruit reviewed
@ayeletr accordion title is the same size as the item:
![image](https://user-images.githubusercontent.com/1684587/103749852-b6b4d280-500e-11eb-812b-3afcada34aec.png)

Shouldn't it be the same size as card subheader?
![image](https://user-images.githubusercontent.com/1684587/103749914-cb916600-500e-11eb-8595-ce861f1f9bd1.png)

Also, why do we need yet another component for a section title? We already have card.subheader.

2021-01-06 09:32 UTC, ayeletr commented
@EgoziE @mjurfest 
1. the height is incorrect. needs to be 48px.
2. there should be a line at the bottom like in the spec.
3. did you use text style definitions that are connected to the system? (It just look a little weird)
4. in the first example in SB - please show the header in a separate example with small size Accordion Item.

2021-01-06 17:26 UTC, ayeletr commented
@milkyfruit 
1. The size of the component is incorrect, but it's also not according to card section title.
it's what kfir defined in zeplin for his need. we can change it if we think it should be smaller.

2. according to dev we can't use here the card section title, we need a component for accordion. that's the answer I got.

2021-01-06 17:51 UTC, mjurfest commented
@ayeletr
3. Yes, I used `<Text skin="standard" weight="bold" size="small" ellipsis>`

2021-01-10 11:30 UTC, merged