Floating Notification migration to stylable
wix/wix-style-react pull request #6494
Opened 2021-01-05 10:56 UTC by egidijusja

### 🔦 Summary

...

### ✅ Checklist

- [ ] 👨‍💻 API change is approved by the UI Infra Developers 
- [ ] 👨‍🎨 UX change is approved by the Design System UX 
- 📚 Change is documented
  - [ ] Story
  - [ ] API description
  - [ ] Cheatsheet
  - [ ] Other (explain)
- 🔬 Change is tested
  - [ ] Component
  - [ ] Visual test

2021-01-05 11:07 UTC, WixBuildServer commented
### 🤖 Hi, I'm #Janet!

  A deploy preview of your PR was successfully released 🖼.

  You can find it under one of the following URLs:
  * https://preview.wix-style-react.com/pr_6494

2021-01-14 12:54 UTC, EgoziE requested changes

2021-01-14 12:54 UTC, EgoziE commented on src/FloatingNotification/FloatingNotification.st.css
> +}
I see all our :global(.rtl) styles here are related to margin and padding.
Let's remove all of them in favor of:

- margin-block-start
- margin-block-end
- padding-block-start
- padding-block-end

Note, In order to follow our browser support guidelines, don't use `margin-block` or `padding-block` without the starts/end suffix

2021-01-14 12:54 UTC, EgoziE commented on src/FloatingNotification/FloatingNotification.st.css
> +}
You can take this PR as reference if needed - https://github.com/wix/wix-style-react/pull/6432

2021-01-14 14:57 UTC, egidijusja commented on src/FloatingNotification/FloatingNotification.st.css
> +}
Updated with margin-inline-start, margin-inline-end, etc. to be able to remove :global(.rtl) styles.

2021-01-15 08:01 UTC, mykas commented on src/FloatingNotification/FloatingNotification.st.css
> +    background-color: value(B50);
Lets fix those empty spaces

2021-01-15 08:01 UTC, mykas commented on src/FloatingNotification/FloatingNotification.st.css
> +    background-color: value(G50);
Lets fix those empty spaces

2021-01-15 08:57 UTC, mykas approved these changes
Awesome job!

2021-01-15 08:57 UTC, merged