<Input/> - add border prop
wix/wix-style-react pull request #6496
Opened 2021-01-05 12:44 UTC by EgoziE

2021-01-05 12:56 UTC, WixBuildServer commented
### 🤖 Hi, I'm #Janet!

  A deploy preview of your PR was successfully released 🖼.

  You can find it under one of the following URLs:
  * https://preview.wix-style-react.com/pr_6496

2021-01-06 08:42 UTC, milkyfruit approved these changes

2021-01-10 10:01 UTC, TalZa1810 requested changes
Few questions and comments I was not sure about

2021-01-10 10:08 UTC, EgoziE commented on src/Input/Input.js
> -const borderRadiusValidator = (props, propName) => {
It was supposed to be deleted in wsr 7 -> 8 and we missed it by mistake

2021-01-10 10:09 UTC, EgoziE commented on src/TimeInput/TimeInput.js
> +      border,
Noted!
All non-input components will do in my 3rd PR, thanks

2021-01-10 10:10 UTC, EgoziE commented on src/Input/Input.js
> +  border: 'default',
You're right, my mistake, should keep one name only

2021-01-10 10:11 UTC, EgoziE commented on src/Input/test/Input.visual.js
> +        <WrappedInputAffix border="round" />
It's the theme's owner to style it.
No action from our side needed.

2021-01-10 10:11 UTC, EgoziE commented on src/Input/index.d.ts
> +  border?: 'standard' | 'round' | 'bottomLine';
will fix thanks!

2021-01-10 10:12 UTC, EgoziE commented on src/Input/test/Input.visual.js
> +            <WrappedInput
No need for double tests.
I'll improve that section in my 2nd or 3rd PR
But thanks!

2021-01-10 13:38 UTC, merged

2021-01-10 16:33 UTC, TalZa1810 commented on src/Input/Input.js
> +  border: PropTypes.oneOf(['standard', 'round', 'borderless']),
`borderless` should be changed to `bottomLine`, no?

2021-01-10 17:23 UTC, EgoziE commented on src/Input/Input.js
> +  border: PropTypes.oneOf(['standard', 'round', 'borderless']),
changing