<Accordion/> - add bottom shadow to open item
wix/wix-style-react pull request #6509
Opened 2021-01-06 15:39 UTC by mjurfest

### 🔦 Summary

- Change accordion item shadow to the inner item
- Add bottom shadow to the inner item

### ✅ Checklist

- [x] 👨‍💻 API change is approved by the UI Infra Developers @EgoziE 
- 📚 Change is documented
  - [x] Story

2021-01-06 16:07 UTC, WixBuildServer commented
### 🤖 Hi, I'm #Janet!

  A deploy preview of your PR was successfully released 🖼.

  You can find it under one of the following URLs:
  * https://preview.wix-style-react.com/pr_6509

2021-01-06 17:56 UTC, EgoziE requested changes

2021-01-06 17:56 UTC, EgoziE commented on src/Accordion/AccordionItem/AccordionItem.st.css
> +    inset 0px -15px 8px -10px rgba(22, 45, 61, 0.05);
`rgba(22, 45, 61, 0.05)` is not a valid color for a shadow.

2021-01-06 17:56 UTC, EgoziE commented on src/Accordion/AccordionItem/AccordionItem.st.css
> +    inset 0px -15px 8px -10px rgba(22, 45, 61, 0.05);
Ask Kfir to talk with Ayelet

2021-01-07 12:08 UTC, milkyfruit requested changes

2021-01-07 12:08 UTC, milkyfruit commented on src/Accordion/AccordionItem/AccordionItem.st.css
> +    inset 0px -15px 8px -10px rgba(22, 45, 61, 0.05);
I played around a bit how to recreate the same style as Shadow30, but as inner: https://codepen.io/milkyfruit/pen/MWjXrVB

We should introduce new variables:
Inner shadow 30 top:
```
inset 0  36px  18px -18px rgba(22,45,61,0.12),
inset 0  12px   6px  -6px rgba(22,45,61,0.06)
```
Inner shadow 30 bottom:
```
inset 0 -36px  18px -18px rgba(22,45,61,0.12),
inset 0 -12px   6px  -6px rgba(22,45,61,0.06)
```

2021-01-07 14:59 UTC, merged