Themes | Business Dashboard - Tag - styling override.
wix/wix-style-react pull request #6514
Opened 2021-01-07 09:41 UTC by netanel89

### 🔦 Summary

...

### ✅ Checklist

- [ ] 👨‍💻 API change is approved by the UI Infra Developers 
- [ ] 👨‍🎨 UX change is approved by the Design System UX 
- 📚 Change is documented
  - [ ] Story
  - [ ] API description
  - [ ] Cheatsheet
  - [ ] Other (explain)
- 🔬 Change is tested
  - [ ] Component
  - [ ] Visual test

2021-01-07 09:52 UTC, WixBuildServer commented
### 🤖 Hi, I'm #Janet!

  A deploy preview of your PR was successfully released 🖼.

  You can find it under one of the following URLs:
  * https://preview.wix-style-react.com/pr_6514

2021-01-10 17:33 UTC, EgoziE commented
Please rebase.

2021-01-11 14:57 UTC, EgoziE requested changes

2021-01-11 14:57 UTC, EgoziE commented on src/Tag/Tag.st.css
> +  -st-extends: Text;
Please pay attention so Stylable warnings

2021-01-11 15:56 UTC, adicicurel approved these changes

2021-01-11 16:26 UTC, EgoziE approved these changes

2021-01-11 19:59 UTC, merged