<Badge/> - fix badge icon size
wix/wix-style-react pull request #6515
Opened 2021-01-07 11:49 UTC by roibWix

### 🔦 Summary

...

### ✅ Checklist

- [ ] 👨‍💻 API change is approved by the UI Infra Developers 
- [ ] 👨‍🎨 UX change is approved by the Design System UX 
- 📚 Change is documented
  - [ ] Story
  - [ ] API description
  - [ ] Cheatsheet
  - [ ] Other (explain)
- 🔬 Change is tested
  - [ ] Component
  - [ ] Visual test

2021-01-07 12:00 UTC, WixBuildServer commented
### 🤖 Hi, I'm #Janet!

  A deploy preview of your PR was successfully released 🖼.

  You can find it under one of the following URLs:
  * https://preview.wix-style-react.com/pr_6515

2021-01-11 14:02 UTC, EgoziE requested changes

2021-01-11 14:02 UTC, EgoziE commented on src/Badge/Badge.st.css
> +  max-height: 24px;
Why is it needed?

2021-01-11 14:02 UTC, EgoziE commented on src/Badge/Badge.st.css
> +  max-height: 18px;
Why is it needed?

2021-01-11 14:02 UTC, EgoziE commented on src/Badge/Badge.st.css
> +  max-height: 24px;
try to remove it and use margin auto maybe

2021-01-12 08:28 UTC, roibWix commented on src/Badge/Badge.st.css
> +  max-height: 18px;
@EgoziE according to the spec the small badge should be 18px
same for the medium 24px

2021-01-12 08:29 UTC, roibWix commented on src/Badge/Badge.st.css
> +  max-height: 24px;
@EgoziE in case of using a regular size icon the height grows to 36px instead of 24px like in the spec.
what do you think?

2021-01-12 08:57 UTC, roibWix commented on src/Badge/Badge.st.css
> +  smallWithIcon: 2px 3px 2px 3px;
done

2021-01-13 10:05 UTC, EgoziE approved these changes
Ready for UX review

2021-01-13 13:17 UTC, milkyfruit requested changes
@roibWix there are few visual changes comparing it to production and zeplin spec:
- [ ] side paddings should be 12px for medium size nad 6px for small size
- [ ] Both sizes should use small 18x18 icons

link to specs: https://zpl.io/adln18R

2021-01-13 19:45 UTC, roibWix commented
@milkyfruit, can you elaborate? 
do you mean badge or badgeSelect component? it's inconsistent regarding the side paddings.  
same for the ' Both sizes should use small 18x18 icons' comment

2021-01-14 15:24 UTC, milkyfruit commented
> @milkyfruit, can you elaborate?
> do you mean badge or badgeSelect component? it's inconsistent regarding the side paddings.
> same for the ' Both sizes should use small 18x18 icons' comment

@roibWix 
1. I see that side paddings were already fixed in "match icon padding to spec" commit.
2. Regarding the icon size, storybook examples should promote icon usage in the badges to be with a suffix "Small":
Specs:
![image](https://user-images.githubusercontent.com/1684587/104610789-15242580-568d-11eb-9667-ecc42c9e72b2.png)
How example in `Badge` story should be:
```
<Layout cols={2} gap={0} justifyItems="center">
  <Badge size="small" suffixIcon={<Icons.ChevronDownSmall />}>
    small badge
  </Badge>
  <Badge size="medium" suffixIcon={<Icons.ChevronDownSmall />}>
    medium badge
  </Badge>
</Layout>;
```

2021-01-20 17:13 UTC, EgoziE commented
The scope is bigger than we estimated, I'm closing this PR.
When we decided to take it, we'll take in mind this component requires a makeover.

2021-01-20 17:13 UTC, closed without merging