<SelectorList/> -  add visual tests
wix/wix-style-react pull request #6528
Opened 2021-01-10 12:29 UTC by bamai

2021-01-10 12:39 UTC, WixBuildServer commented
### 🤖 Hi, I'm #Janet!

  A deploy preview of your PR was successfully released 🖼.

  You can find it under one of the following URLs:
  * https://preview.wix-style-react.com/pr_6528

2021-01-10 13:12 UTC, TalZa1810 requested changes
few tiny comments

2021-01-10 13:12 UTC, TalZa1810 commented on src/SelectorList/test/SelectorList.visual.js
> +import { Text } from '../../Text';
redundant import

2021-01-10 13:12 UTC, TalZa1810 commented on src/SelectorList/test/SelectorList.visual.js
> +const EmptyExample = props => (
It's similar to the regular example. The only difference is the `dataSource` and `emptyState` props. so this can be added as props instead of creating a new example.

2021-01-10 13:12 UTC, TalZa1810 commented on src/SelectorList/test/SelectorList.visual.js
> +storiesOf('SelectorList', module)
you can create another variable of `tests` instead of `interactiveTests` and run the tests in a similar why of the interactive ones, similar to what we have [here](https://github.com/wix/wix-style-react/blob/master/src/FeatureList/test/FeatureList.visual.js#L112). Also, in this case, you don't need to send `componentDidMount` but simply using the `prop`.

2021-01-10 16:35 UTC, TalZa1810 commented on src/SelectorList/test/SelectorList.visual.js
> +        componentDidMount: () => {},
no need for `componentDidMount` here

2021-01-13 15:08 UTC, TalZa1810 requested changes
Few more comments

2021-01-13 15:08 UTC, TalZa1810 commented on src/SelectorList/test/SelectorList.visual.js
> +    describe: 'image shape',
let's create a constants file which has the following:
```
export const IMAGE_SHAPE = {
  rectangle: 'rectangle',
  circle: 'circle',
};
```

Afterwards, we can map them over. [Here's](https://github.com/wix/wix-style-react/blob/master/src/Notification/test/Notification.visual.js#L17) an example as a reference.

2021-01-13 15:08 UTC, TalZa1810 commented on src/SelectorList/test/SelectorList.visual.js
> +    describe: 'circle image size',
There's no need to check the combination of the props.

2021-01-13 15:08 UTC, TalZa1810 commented on src/SelectorList/test/SelectorList.visual.js
> +    describe: 'image size',
sizes can be exported to a constant as well

2021-01-13 17:21 UTC, TalZa1810 approved these changes

2021-01-14 09:27 UTC, merged