<InputWithOptions/> - fix highlighting for builder options
wix/wix-style-react pull request #6538
Opened 2021-01-11 14:54 UTC by gendeld

### 🔦 Summary

...

### ✅ Checklist

- [ ] 👨‍💻 API change is approved by the UI Infra Developers 
- [ ] 👨‍🎨 UX change is approved by the Design System UX 
- 📚 Change is documented
  - [ ] Story
  - [ ] API description
  - [ ] Cheatsheet
  - [ ] Other (explain)
- 🔬 Change is tested
  - [ ] Component
  - [ ] Visual test

2021-01-11 15:03 UTC, WixBuildServer commented
### 🤖 Hi, I'm #Janet!

  A deploy preview of your PR was successfully released 🖼.

  You can find it under one of the following URLs:
  * https://preview.wix-style-react.com/pr_6538

2021-01-11 17:09 UTC, EgoziE requested changes

2021-01-11 17:09 UTC, EgoziE commented on src/ListItemSelect/test/ListItemSelect.private.uni.driver.js
> +  const getByDataHook = dataHook => base.$(`[data-hook=${dataHook}]`);
Can it be changed to:
```
import { findByHook } from '../../test/utils/unidriver';
```
?

2021-01-11 17:09 UTC, EgoziE commented on src/ListItemSelect/ListItemSelect.js
> +    const { title, optionId = '' } = this.props;
Can `optionId = ''` be part of the default props?

2021-01-12 08:13 UTC, TalZa1810 reviewed
Few comments

2021-01-12 08:33 UTC, gendeld commented on src/ListItemSelect/index.d.ts
> +  optionId?: string | number;
I think I need it for the dataHook on the highlighter

2021-01-12 08:41 UTC, TalZa1810 commented on src/ListItemSelect/index.d.ts
> +  optionId?: string | number;
Adding a prop just for a `dataHook`? The `dataHook` is needed for testing something that is visual so I think we can avoid adding this prop and testing the Highlight in a visual test instead.

2021-01-13 10:00 UTC, EgoziE approved these changes

2021-01-13 11:58 UTC, TalZa1810 reviewed
few leftovers from the previous change

2021-01-13 13:18 UTC, TalZa1810 approved these changes
Looks good :)
I think that we can add a usage example since we're getting some questions about this feature. We can do it in another PR if you want to merge this first.

2021-01-13 13:52 UTC, merged

2021-01-13 13:55 UTC, TalZa1810 commented on src/InputWithOptions/InputWithOptions.driver.js
> -    isOptionWrappedToHighlighter: optionId => {
For transparency- we saw that this method is not used by our consumers. We've tested this using visual tests and removed this method.