make zIndex configurable for dragging layer
wix/wix-style-react pull request #6563
Opened 2021-01-15 08:45 UTC by Cwallice

### 🔦 Summary

...

### ✅ Checklist

- [ ] 👨‍💻 API change is approved by the UI Infra Developers 
- [ ] 👨‍🎨 UX change is approved by the Design System UX 
- 📚 Change is documented
  - [ ] Story
  - [ ] API description
  - [ ] Cheatsheet
  - [ ] Other (explain)
- 🔬 Change is tested
  - [ ] Component
  - [ ] Visual test

2021-01-15 09:43 UTC, WixBuildServer commented
### 🤖 Hi, I'm #Janet!

  A deploy preview of your PR was successfully released 🖼.

  You can find it under one of the following URLs:
  * https://preview.wix-style-react.com/pr_6563

2021-01-15 10:20 UTC, AndriiTsarenko approved these changes
Hey. Thanks for your PR, and improving the component.
Seems good to me.

2021-01-17 08:20 UTC, shlomitc requested changes
minor change

2021-01-17 08:20 UTC, shlomitc commented on src/NestableList/API.md
> +  | dragLayerZIndex        | number     | 100           | -          | zindex of the list item drag container |
```suggestion
  | dragLayerZIndex  | number     | 100           | -          | zindex of the list item drag container |
```

2021-01-18 07:45 UTC, Cwallice commented on src/NestableList/DragLayer.js
> +          })}
sure
flapped out of my mind

2021-01-18 11:46 UTC, merged