<MarketingLayout/>-  reduce spacing
wix/wix-style-react pull request #6568
Opened 2021-01-17 11:01 UTC by TalZa1810

### 🔦 Summary
reduce spacing

### ✅ Checklist

- [ ] 👨‍💻 API change is approved by the UI Infra Developers 
- [ ] 👨‍🎨 UX change is approved by the Design System UX 
- 📚 Change is documented
  - [ ] Story
  - [ ] API description
  - [ ] Cheatsheet
  - [ ] Other (explain)
- 🔬 Change is tested
  - [ ] Component
  - [ ] Visual test

2021-01-17 11:12 UTC, WixBuildServer commented
### 🤖 Hi, I'm #Janet!

  A deploy preview of your PR was successfully released 🖼.

  You can find it under one of the following URLs:
  * https://preview.wix-style-react.com/pr_6568

2021-01-18 13:34 UTC, TalZa1810 commented
@justinara , do we want to remove the Large example completely? 
Also, I've added a deprecation log when rendering large size. I will add also a notation within the API itself that this size is deprecated. Let me know if there are other fixes that needs to be done.

2021-01-19 08:03 UTC, justinara commented
@TalZa1810 yes, large size will have to be removed completely

2021-01-19 08:03 UTC, justinara approved these changes

2021-01-19 11:55 UTC, EgoziE requested changes

2021-01-19 11:55 UTC, EgoziE commented on packages/wix-style-react/src/MarketingLayout/MarketingLayout.st.css
> +  direction: rtl;
not needed

2021-01-19 14:35 UTC, merged