<AvatarGroup/> - avatar group new component
wix/wix-style-react pull request #6584
Opened 2021-01-18 18:41 UTC by roibWix

### 🔦 Summary

...

### ✅ Checklist

- [ ] 👨‍💻 API change is approved by the UI Infra Developers 
- [ ] 👨‍🎨 UX change is approved by the Design System UX 
- 📚 Change is documented
  - [ ] Story
  - [ ] API description
  - [ ] Cheatsheet
  - [ ] Other (explain)
- 🔬 Change is tested
  - [ ] Component
  - [ ] Visual test

2021-01-18 18:52 UTC, WixBuildServer commented
### 🤖 Hi, I'm #Janet!

  A deploy preview of your PR was successfully released 🖼.

  You can find it under one of the following URLs:
  * https://preview.wix-style-react.com/pr_6584

2021-01-28 12:46 UTC, EgoziE requested changes

2021-01-28 12:46 UTC, EgoziE commented on packages/wix-style-react/perfer.config.js
> +  ['AvatarGroup.bundle.min.js', 57],
Sort

2021-01-28 12:46 UTC, EgoziE commented on packages/wix-style-react/stories/index.js
> +require('../src/AvatarGroup/docs/index.story');
sort

2021-01-28 12:46 UTC, EgoziE commented on packages/wix-style-react/src/index.js
> -export { default as SkeletonLine } from './SkeletonLine';
Don't delete other components! 😂

2021-01-28 12:46 UTC, EgoziE commented on packages/wix-style-react/src/AvatarGroup/index.d.ts
> +export type AvatarGroupSize = 'medium' | 'small';
Move up, so GroupType is first defined, then used.

2021-01-28 12:46 UTC, EgoziE commented on packages/wix-style-react/src/AvatarGroup/AvatarGroup.uni.driver.js
> +     * @param {number} Avatar index
The pattern is:
@param {<type>} <name> <description>


     * @param {number} index Avatar index

2021-01-28 12:46 UTC, EgoziE commented on packages/wix-style-react/src/AvatarGroup/AvatarGroup.uni.driver.js
> +    getAvatarContentByIndex: async n =>
Change "n" to "index"

2021-01-28 12:46 UTC, EgoziE commented on packages/wix-style-react/src/AvatarGroup/AvatarGroup.uni.driver.d.ts
> +  getAvatarContentByIndex(times: number): Promise<string>;
change "times" to "index"

2021-01-28 12:46 UTC, EgoziE commented on packages/wix-style-react/src/AvatarGroup/AvatarGroup.st.css
> +}
Let's talk about extending css in Stylable!
Please schedule 30 min meeting next week.

2021-01-28 14:01 UTC, shlomitc commented on packages/wix-style-react/src/AvatarGroup/AvatarGroup.js
> +  avatars: PropTypes.arrayOf(Avatar),
looks redundant

2021-02-02 12:35 UTC, milkyfruit requested changes
@roibWix I noticed two UI issues:

- [ ] More number indicator is missing when size is small
![image](https://user-images.githubusercontent.com/1684587/106600870-a63b3d80-6563-11eb-9485-1bf5d3abc569.png)

- [ ] Divider is missing 12px margin from the right side
![image](https://user-images.githubusercontent.com/1684587/106600963-c408a280-6563-11eb-9d5c-d36ffc43cc96.png)

2021-02-03 06:53 UTC, roibWix commented
@milkyfruit,
Where did you see the margin-right issue?

2021-02-03 09:00 UTC, milkyfruit commented
> @milkyfruit,
> Where did you see the margin-right issue?

It doesn't show up anymore, it looked fixed.

2021-02-03 09:00 UTC, milkyfruit approved these changes

2021-02-03 09:23 UTC, shlomitc commented
@roibWix @EgoziE 
I'm not entirely sure regarding the `moreItemContet` prop
1. it's not documented
2. doc doesn't look good
![image](https://user-images.githubusercontent.com/6093192/106725362-f5d84280-6611-11eb-9c1c-4dcebb6a991d.png)
3. I have some concerns regarding its usage. Seems like it is always a popover, but is this the only case? Can it be a simple button click?
I remember there was a request for a dropdown there. Obviously, you can compose `DropdownLayout`, but then not all a11y features are met. Maybe it should be a bit more open to composition?

2021-02-03 10:51 UTC, justinara commented
@shlomitc @roibWix i double checked it with @ayeletr who defined this component - primary idea is that more indication can be clickable, but popover is not a default and single option it opens. It could open, let's say, a modal instead, or anything else basically.  I think it should behave little more like a button, with onClick handler, etc.

2021-02-03 10:55 UTC, shlomitc commented
Thanks @justinara !
In that case we probably need to do some API adjustments to become more composable

2021-02-03 12:45 UTC, justinara commented
@roibWix this is a doc, which includes component description, updated examples with descriptions, also improved prop descriptions for API section: https://docs.google.com/document/d/1seHSUTej2WKqY2Ar6mX-reuITXyTzY8up-u9nPHoRlc/edit?usp=sharing

@shlomitc fyi

2021-02-16 10:01 UTC, EgoziE requested changes

2021-02-17 06:46 UTC, roibWix commented on packages/wix-style-react/src/AvatarGroup/AvatarGroup.uni.driver.js
> +    hover: async () => await findByHookAtIndex(base, dataHooks.avatarGroupItem).hover()
On second thought, it's unnecessary.

2021-02-17 08:24 UTC, roibWix commented on packages/wix-style-react/src/AvatarGroup/AvatarGroup.uni.driver.js
> +    getAvatarContentTypeByIndex: async index => {
same here, unnecessary

2021-02-21 06:13 UTC, WixBuildServer commented
### 🤖 Hi, I'm #Janet!

  A deploy preview of your PR was successfully released 🖼.

  Project Name: **wix-ui-tpa**

  You can find it under one of the following URLs:
  * https://bo.wix.com/pages/wix-ui-tpa.pr_6584/

2021-02-21 06:18 UTC, WixBuildServer commented
### 🤖 Hi, I'm #Janet!

  A deploy preview of your PR was successfully released 🖼.

  Project Name: **wix-style-react**

  You can find it under one of the following URLs:
  * https://preview.wix-style-react.com/pr_6584

2021-02-21 10:02 UTC, EgoziE requested changes

2021-02-21 10:02 UTC, EgoziE commented on packages/wix-style-react/src/AvatarGroup/AvatarGroup.st.css
> +  -st-states: size(enum(small, medium)), type(enum(stretched, condensed));
states should be first

2021-02-21 12:26 UTC, EgoziE approved these changes

2021-02-22 08:45 UTC, justinara requested changes
Well done! A few tiny requests: 
1. Use **Layout** instead of **Box** to layout component in separate rows in size and group type examples. As per doc here: https://docs.google.com/document/d/1seHSUTej2WKqY2Ar6mX-reuITXyTzY8up-u9nPHoRlc/edit?usp=sharing
2. I've updated each example description a little bit - could we update them in the story too? Same doc: https://docs.google.com/document/d/1seHSUTej2WKqY2Ar6mX-reuITXyTzY8up-u9nPHoRlc/edit?usp=sharing
3. Divider should have an equal 12px distance from avatars on both sides - left and right. It seems to be a little closer to the list on the right at the moment:
![image](https://user-images.githubusercontent.com/67683352/108683844-d179d280-74fa-11eb-9b5f-ee1ed6e3c18b.png) zeplin: https://zpl.io/VD0DzxJ

2021-02-22 10:06 UTC, TalZa1810 commented
Hi @roibWix ,
Can you please add this component to the cheatsheet ?
You can do it in a separate PR if you prefer (after merging). 
You can find the instructions how to do it [here](https://github.com/wix/wix-style-react/blob/master/packages/wix-style-react/docs/contribution/CHEATSHEET_GUIDLINES.md).

Feel free to ask me questions if you have any.

Thanks.

2021-02-22 15:17 UTC, justinara approved these changes
Description for 'Size' example is not up to date

2021-02-22 15:18 UTC, merged