Themes | Business Dashboard - VerticalTabsItem update
wix/wix-style-react pull request #6595
Opened 2021-01-19 15:17 UTC by adicicurel

### 🔦 Summary

...

### ✅ Checklist

- [ ] 👨‍💻 API change is approved by the UI Infra Developers 
- [ ] 👨‍🎨 UX change is approved by the Design System UX 
- 📚 Change is documented
  - [ ] Story
  - [ ] API description
  - [ ] Cheatsheet
  - [ ] Other (explain)
- 🔬 Change is tested
  - [ ] Component
  - [ ] Visual test

2021-01-19 15:28 UTC, WixBuildServer commented
### 🤖 Hi, I'm #Janet!

  A deploy preview of your PR was successfully released 🖼.

  You can find it under one of the following URLs:
  * https://preview.wix-style-react.com/pr_6595

2021-01-21 12:07 UTC, mykas commented on packages/wix-style-react/src/VerticalTabsItem/VerticalTabsItem.st.css
> -
please remove this redundant change

2021-01-21 12:52 UTC, mykas approved these changes

2021-01-24 09:54 UTC, EgoziE requested changes

2021-01-24 09:54 UTC, EgoziE commented on packages/wix-style-react/src/Themes/businessDashboard/components/VerticalTabsItem.st.css
> +    -webkit-transform:rotate(45deg) skew(18deg, 18deg);
-webkit-transform is not needed.
transform is fully supported by all browsers

2021-01-24 09:56 UTC, EgoziE approved these changes

2021-01-24 12:23 UTC, merged