Counter badge shadow and light skin
wix/wix-style-react pull request #6614
Opened 2021-01-20 15:12 UTC by mjurfest

### 🔦 Summary

- Add `light` skin
- Add `showShadow` prop

### ✅ Checklist

- [X] 👨‍🎨 UX change is approved by the Design System UX  @milkyfruit 
- 📚 Change is documented
  - [X] Story
  - [X] API description

2021-01-20 15:25 UTC, WixBuildServer commented
### 🤖 Hi, I'm #Janet!

  A deploy preview of your PR was successfully released 🖼.

  You can find it under one of the following URLs:
  * https://preview.wix-style-react.com/pr_6614

2021-01-20 17:26 UTC, EgoziE requested changes

2021-01-20 17:26 UTC, EgoziE commented on packages/wix-style-react/src/CounterBadge/docs/examples.js
> +  </Cell>
Should be extracted to a separate example

2021-01-20 17:27 UTC, EgoziE commented
@milkyfruit Ready for UX review
Try the shadow prop with all skins, something like:
```
<Layout>
  <Cell>
    <CounterBadge skin="general" showShadow>
      1
    </CounterBadge>
  </Cell>
  <Cell>
    <CounterBadge skin="standard" showShadow>
      1
    </CounterBadge>
  </Cell>
  <Cell>
    <CounterBadge skin="neutralStandard" showShadow>
      1
    </CounterBadge>
  </Cell>
  <Cell>
    <CounterBadge skin="danger" showShadow>
      1
    </CounterBadge>
  </Cell>
  <Cell>
    <CounterBadge skin="warning" showShadow>
      1
    </CounterBadge>
  </Cell>
  <Cell>
    <CounterBadge skin="urgent" showShadow>
      1
    </CounterBadge>
  </Cell>
  <Cell>
    <CounterBadge skin="success" showShadow>
      1
    </CounterBadge>
  </Cell>
  <Cell>
    <CounterBadge skin="light" showShadow>
      1
    </CounterBadge>
  </Cell>
</Layout>
```

2021-01-25 07:15 UTC, milkyfruit approved these changes
@EgoziE @mjurfest from a design side, both props look good.

2021-01-25 09:41 UTC, EgoziE approved these changes

2021-01-25 10:47 UTC, merged