Calendar header change arrows to buttons
wix/wix-style-react pull request #6635
Opened 2021-01-24 16:47 UTC by sivanharel

### 🔦 Summary

...

### ✅ Checklist

- [ ] 👨‍💻 API change is approved by the UI Infra Developers 
- [ ] 👨‍🎨 UX change is approved by the Design System UX 
- 📚 Change is documented
  - [ ] Story
  - [ ] API description
  - [ ] Cheatsheet
  - [ ] Other (explain)
- 🔬 Change is tested
  - [ ] Component
  - [ ] Visual test

2021-01-24 17:01 UTC, WixBuildServer commented
### 🤖 Hi, I'm #Janet!

  A deploy preview of your PR was successfully released 🖼.

  You can find it under one of the following URLs:
  * https://preview.wix-style-react.com/pr_6635

2021-01-26 13:47 UTC, TalZa1810 requested changes
few tiny comments

2021-01-26 13:47 UTC, TalZa1810 commented on packages/wix-style-react/src/IconButton/IconButton.js
> +    ariaLabel: PropTypes.string,
If these are new props, they should be added to the tsx files as well.

2021-01-26 13:47 UTC, TalZa1810 commented on packages/wix-style-react/src/Calendar/DatePickerHead/DatePickerHead.js
> +      <IconButton
do we have a visual test for this?

2021-01-26 13:51 UTC, sivanharel commented on packages/wix-style-react/src/Calendar/DatePickerHead/DatePickerHead.js
> +      <IconButton
Yes, there are a lot of visual tests :)
All the tests are passed since the light skin of the Icon button has the same design as was implemented in this component :)

2021-01-26 13:56 UTC, TalZa1810 approved these changes

2021-01-27 07:42 UTC, merged