<PulseAnimation/> - Add new component
wix/wix-style-react pull request #6656
Opened 2021-01-27 15:18 UTC by mjurfest

### 🔦 Summary

- New component: <PulseAnimation/>

### ✅ Checklist

- [ ] 👨‍💻 API change is approved by the UI Infra Developers 
- [ ] 👨‍🎨 UX change is approved by the Design System UX
- 📚 Change is documented
  - [ ] Story
  - [ ] API description
  - [ ] Cheatsheet
  - [ ] Other (explain)
- 🔬 Change is tested
  - [ ] Component
  - [ ] Visual test

2021-01-28 10:18 UTC, TalZa1810 commented
Hi @ZilvinasMaciulis ,
Can you please review the examples? which examples should we add to this story page?

2021-01-28 14:40 UTC, TalZa1810 commented
Hi @mjurfest ,
You should add the `children` prop to the component definition, like we have in `<BounceAnimation/>`:
https://github.com/wix/wix-style-react/blob/master/packages/wix-style-react/testkit/component-definitions.js#L39

Otherwise, unit tests are failing and it doesn't publish this to storybook.

Thanks :)

2021-01-28 15:48 UTC, WixBuildServer commented
### 🤖 Hi, I'm #Janet!

  A deploy preview of your PR was successfully released 🖼.

  You can find it under one of the following URLs:
  * https://preview.wix-style-react.com/pr_6656

2021-02-01 12:32 UTC, TalZa1810 requested changes

2021-02-01 12:32 UTC, TalZa1810 commented on packages/wix-style-react/src/PulseAnimation/PulseAnimation.st.css
> +  -st-states: active, loop, size(enum(small, medium)), color(enum(B10, R10, P10, G10));
Adding `width: fit-content` to the root class so that the animation is wrapping the children component. We need to make sure that there's also a border radius for the box shadow

2021-02-01 12:32 UTC, TalZa1810 commented on packages/wix-style-react/stories/index.js
> +require('../src/PulseAnimation/docs/index.story');
Please move this to the correct position (alphabetically)

2021-02-01 12:32 UTC, TalZa1810 commented on packages/wix-style-react/src/PulseAnimation/docs/index.story.js
> +          example({
Hi @ZilvinasMaciulis 
Do we need all examples? Which examples should we add to the story page? Of which components?

Thanks

2021-02-01 18:32 UTC, ZilvinasMaciulis commented
The pulse effect (border-radius) should follow the visual shape of the component. Now the check toggle is round while the effect is square. See the image below. 

The effect should be applied to components without any external text. It should be used on buttons, badges but not on the inputs, dropdowns. Unless the effect is applied to the input itself.  See the example. For the "end" example please use the icon button with a tooltip

According to the inspect panel, animation takes around 700ms. It should be 1050ms. Please check if the animation setup meets specs. 

![image](https://user-images.githubusercontent.com/44393332/106502083-958bb880-64cc-11eb-89af-53822f77a997.png)

2021-02-02 07:31 UTC, TalZa1810 commented
@ZilvinasMaciulis 
We're aware that the animation is ready yet. We just wanted a list of examples we would like to present in the storybook page and their descriptions.
Do we want to show this with the CheckToggle? Input? Which components should we use?

Thanks.

2021-02-02 11:49 UTC, ZilvinasMaciulis commented
@TalZa1810 

As discussed before, this component is meant to draw users' attention with a continuous loop. Loop lasts until the user provides the required action. In some rare cases, the loop might last a certain amount of time.  Also, it has a color. That being said I think there is a need to demonstrate that:

its default state (loop is a default prop)
It has a color
It can have a delay

The first application for this wrapper will be on the button. Therefore I think the button is the best example to use it on.

Use plain HTML button for play/stop animation.

Other options like play once, or show something on animation end should not be included in this example. 

![image](https://user-images.githubusercontent.com/44393332/106596277-738e4680-655d-11eb-9ef3-8caf27ce46ce.png)

2021-02-03 08:25 UTC, TalZa1810 commented
> The pulse effect (border-radius) should follow the visual shape of the component. Now the check toggle is round while the effect is square. See the image below. 
> 
> The effect should be applied to components without any external text. It should be used on buttons, badges but not on the inputs, dropdowns. Unless the effect is applied to the input itself.  See the example. For the "end" example please use the icon button with a tooltip
> 
> According to the inspect panel, animation takes around 700ms. It should be 1050ms. Please check if the animation setup meets specs. 
> 
> ![image](https://user-images.githubusercontent.com/44393332/106502083-958bb880-64cc-11eb-89af-53822f77a997.png)

Hey @mjurfest ,
Let's expose a `borderRadius` prop for the `<PulseAnimation/>` that can be customized by the user. 
Also, please make sure that the animation values are the same as mentioned in the specs. If you're not sure, please contact Zilvinas regarding the desired values. 

Thanks :)

2021-02-03 16:39 UTC, TalZa1810 requested changes
Hey,
I've added some comments. Let me know if something is not clear :)

2021-02-03 16:39 UTC, TalZa1810 commented on packages/wix-style-react/src/Animate/Animate.js
> +  borderRadius: PropTypes.string,
This prop is relevant just for the `<PulseAnimation/>`. We're not sure if it's relevant for other types on animations as well.

Let's rename this to `animateInlineStyle` so that next time we will be able to add more inline styles when necessary.

2021-02-03 16:39 UTC, TalZa1810 commented on packages/wix-style-react/src/Animate/index.d.ts
> +  borderRadius?: React.CSSProperties['borderRadius'];
same comment

2021-02-03 16:39 UTC, TalZa1810 commented on packages/wix-style-react/src/PulseAnimation/PulseAnimation.js
> +        borderRadius={borderRadius}
Let's rename this prop to `animateInlineStyle`. Moreover, I think that using css variable for the inline styling is a better solution. 

```suggestion
        animateInlineStyle={[ [vars.borderRadius]: borderRadius ] }
```


There's an example with usage of [css variable](https://github.com/wix/wix-style-react/blob/master/packages/wix-style-react/src/CardFolderTabs/CardFolderTabs.js#L23)

2021-02-03 16:39 UTC, TalZa1810 commented on packages/wix-style-react/src/PulseAnimation/constants.js
> +export const dataHooks = {};
not used. can be removed

2021-02-03 16:39 UTC, TalZa1810 commented on packages/wix-style-react/src/PulseAnimation/test/PulseAnimation.tsx
> +      color = "B10"
add the borderRadius prop here as well

2021-02-07 10:43 UTC, TalZa1810 requested changes
Great job :) 
Few more tiny comments and I think that we can merge this.

2021-02-07 10:43 UTC, TalZa1810 commented on packages/wix-style-react/src/Animate/index.d.ts
> +  animateInlineStyle?: React.CSSProperties['animateInlineStyle'];
```suggestion
  animateInlineStyle?: React.CSSProperties;
```

2021-02-07 10:43 UTC, TalZa1810 commented on packages/wix-style-react/src/PulseAnimation/docs/index.story.js
> +    label: 'Default example',
```suggestion
    label: 'Button',
```

2021-02-07 10:43 UTC, TalZa1810 commented on packages/wix-style-react/src/PulseAnimation/docs/index.story.js
> +  componentProps: { children: exampleChildren[0].value },
```suggestion
  componentProps: { 
    children: exampleChildren[0].value, 
    color:"B10",
    borderRadius: "18px",
    active: true 
},
```

2021-02-09 09:20 UTC, TalZa1810 commented on packages/wix-style-react/src/PulseAnimation/docs/examples.js
> +        <PulseAnimation onEnd={()=>setActive(false)} active={active} color="P10" borderRadius="18px">
The `onEnd` is irrelevant if the `loop` prop is true by default. It is not executed because it is defined as `infinite` within the css. So, we should add `loop={false}` so that the `onEnd` callback would be executed.

2021-02-09 13:20 UTC, mjurfest commented on packages/wix-style-react/src/PulseAnimation/docs/examples.js
> +        <PulseAnimation onEnd={()=>setActive(false)} active={active} color="P10" borderRadius="18px">
I agree. I will remove the onEnd and keep the default loop behavior

2021-02-09 14:22 UTC, TalZa1810 approved these changes

2021-02-09 16:38 UTC, ZilvinasMaciulis approved these changes

2021-02-10 07:23 UTC, merged