[wix-style-react] Reduce spacing corrections
wix/wix-style-react pull request #6668
Opened 2021-01-31 09:08 UTC by TalZa1810

### 🔦 Summary
Small corrections- reduce spacing:
- `<Table/>`
- `<TableListItem/>`

### ✅ Checklist

- [ ] 👨‍💻 API change is approved by the UI Infra Developers 
- [ ] 👨‍🎨 UX change is approved by the Design System UX 
- 📚 Change is documented
  - [ ] Story
  - [ ] API description
  - [ ] Cheatsheet
  - [ ] Other (explain)
- 🔬 Change is tested
  - [ ] Component
  - [ ] Visual test

2021-01-31 09:24 UTC, WixBuildServer commented
### 🤖 Hi, I'm #Janet!

  A deploy preview of your PR was successfully released 🖼.

  You can find it under one of the following URLs:
  * https://preview.wix-style-react.com/pr_6668

2021-02-01 11:10 UTC, justinara requested changes
There are a few tiny issues:
1. SelectableAccordion - padding on the left is fixed, but list item still has 30px padding on the right: https://prnt.sc/xyw9q3
2. TableListItem - side paddings should be 24px from both left and right sides (when no drag handle) and 18px on the left, and 24px on the right when with enabled drag handle. Currently it has 30px on the left at all times

2021-02-01 16:07 UTC, TalZa1810 commented on packages/wix-style-react/src/SelectableAccordion/Item/Item.st.css
> +  padding-inline-end: 24px;
```suggestion
  padding-inline-end: 18px;
```

2021-02-01 16:21 UTC, TalZa1810 commented on packages/wix-style-react/src/SelectableAccordion/Item/Item.st.css
> +  padding-inline-end: 18px;
```suggestion
  padding-inline-end: 24px;
```

2021-02-01 16:22 UTC, TalZa1810 commented on packages/wix-style-react/src/TableListItem/TableListItem.st.css
> +  padding-inline-start: 24px;
```suggestion
  padding-inline-start: 18px;
```

2021-02-02 08:20 UTC, justinara approved these changes

2021-02-02 09:26 UTC, merged

2021-02-20 03:46 UTC, WixBuildServer commented
### 🤖 Hi, I'm #Janet!

  A deploy preview of your PR was successfully released 🖼.

  Project Name: **wix-ui-tpa**

  You can find it under one of the following URLs:
  * https://bo.wix.com/pages/wix-ui-tpa.pr_6668/

2021-02-20 03:47 UTC, WixBuildServer commented
### 🤖 Hi, I'm #Janet!

  A deploy preview of your PR was successfully released 🖼.

  Project Name: **wix-style-react**

  You can find it under one of the following URLs:
  * https://preview.wix-style-react.com/pr_6668