<PageSection/>- new component
wix/wix-style-react pull request #6686
Opened 2021-02-01 16:05 UTC by TalZa1810

### 🔦 Summary
New component

### ✅ Checklist

- [ ] 👨‍💻 API change is approved by the UI Infra Developers 
- [ ] 👨‍🎨 UX change is approved by the Design System UX 
- 📚 Change is documented
  - [ ] Story
  - [ ] API description
  - [ ] Cheatsheet
  - [ ] Other (explain)
- 🔬 Change is tested
  - [ ] Component
  - [ ] Visual test

2021-02-01 16:18 UTC, WixBuildServer commented
### 🤖 Hi, I'm #Janet!

  A deploy preview of your PR was successfully released 🖼.

  You can find it under one of the following URLs:
  * https://preview.wix-style-react.com/pr_6686

2021-02-11 13:58 UTC, TalZa1810 commented on packages/wix-style-react/src/PageSection/docs/index.story.js
> +              'This line here should briefly describe component in just a sentence or two. It should be short and easy to read.',
@justinara 
Can you please send me the component descrition?

2021-02-14 09:42 UTC, TalZa1810 commented on packages/wix-style-react/src/PageSection/PageSection.st.css
> +  /*padding-inline-start: 48px;*/
The vertical paddings are part of the `<Page.Content/>` component so they are not needed here
@justinara

2021-02-14 09:55 UTC, TalZa1810 commented on packages/wix-style-react/src/Page/Page.js
> +  /** Accepts these components as children: `Page.Header`, `Page.Section`, `Page.Tail`, `Page.Content`, `Page.FixedContent`. Order is insignificant. */
The page section is a child component of the page content, so I wasn't sure whether to mention this here or not.

2021-02-14 09:55 UTC, TalZa1810 commented on packages/wix-style-react/src/PageSection/docs/index.story.js
> +              '- Divide content into sections on a page.\n' +
When using bullets, the text size is a bit bigger than without bullets. This is how storybook utils works. FYI
@justinara

2021-02-15 08:48 UTC, mykas commented on packages/wix-style-react/src/Page/Page.js
> +  /** Accepts these components as children: `Page.Header`, `Page.Section`, `Page.Tail`, `Page.Content`, `Page.FixedContent`. Order is insignificant. */
I believe it is important to not mention here if Page.Section is specifically meant for Page.Content.

2021-02-15 09:18 UTC, mykas commented on packages/wix-style-react/src/PageSection/PageSection.js
> +class PageSection extends React.PureComponent {
I would suggest converting this class already to just function. I know we did not decide yet on general use case, but more and more components are coming as function rather classses.

2021-02-15 10:34 UTC, justinara requested changes
- [x] missing 12px bottom padding for a content (bottom divider is too close to title)

2021-02-15 11:48 UTC, TalZa1810 commented
> * [ ]  missing 12px bottom padding for a content (bottom divider is too close to title)

I did that but it was not published to storybook for some reason. I'll try to dummy commit this so it is published to storybook as well.

2021-02-15 11:56 UTC, mykas commented on packages/wix-style-react/src/PageSection/test/PageSection.visual.js
> +        props: {},
Shouldn't props here include some title? Or you rely on commonProps?

2021-02-15 11:57 UTC, mykas commented on packages/wix-style-react/src/PageSection/PageSection.uni.driver.js
> +    ...baseUniDriverFactory(base, body),
I believe our users would like to have methods like these:
```
titleExists(),
subtitleExists(),
getTitle(),
getSubtitle()
```

2021-02-15 12:02 UTC, TalZa1810 commented on packages/wix-style-react/src/PageSection/test/PageSection.visual.js
> +        props: {},
I rely on commonProps, but I can add here a different title just to be sure

2021-02-15 12:03 UTC, mykas commented on packages/wix-style-react/src/PageSection/docs/examples.js
> +export const simpleUsage = `
@justinara following our new guidelines - do you think it make sense to have such example as the basic example for our users? Maybe it should state that its structure example and then go prop by prop example as separate ones?

2021-02-15 12:05 UTC, mykas commented on packages/wix-style-react/src/PageSection/docs/index.story.js
> +            title: 'Ellipsis',
From the title it seems like `Ellipsis` is actually a prop. Maybe different name should be used here for component behaviour under layout restriction. @justinara maybe you have ideas?

2021-02-15 12:07 UTC, mykas commented on packages/wix-style-react/src/PageSection/docs/examples.js
> +<Page>
IMO from the visuals I can't understand where these sections are used in. Maybe adding Page Heading might be beneficial to get immediate understanding what this component is about?

2021-02-15 12:14 UTC, mykas commented on packages/wix-style-react/src/PageSection/docs/index.story.js
> +      sourceUrl: `https://github.com/wix/wix-style-react/tree/master/src/${PageSection.displayName}/`,
Missing component in header representation.

2021-02-15 12:36 UTC, TalZa1810 commented on packages/wix-style-react/src/PageSection/docs/index.story.js
> +            title: 'Simple Usage',
```suggestion
            title: 'Structure',
```

2021-02-15 13:46 UTC, justinara requested changes
I missed one tiny thing:
- [ ] Subtitle font colour should be D20

2021-02-17 08:27 UTC, justinara approved these changes

2021-02-17 08:27 UTC, merged