<TimeInputWip /> - new component
wix/wix-style-react pull request #6693
Opened 2021-02-02 12:46 UTC by vidmantasa

### 🔦 Summary

New Component

### ✅ Checklist

- [ ] 👨‍💻 API change is approved by the UI Infra Developers 
- [ ] 👨‍🎨 UX change is approved by the Design System UX
- 📚 Change is documented
  - [ ] Story
  - [ ] API description
  - [ ] Cheatsheet
  - [ ] Other (explain)
- 🔬 Change is tested
  - [ ] Component
  - [ ] Visual test

2021-02-02 12:57 UTC, WixBuildServer commented
### 🤖 Hi, I'm #Janet!

  A deploy preview of your PR was successfully released 🖼.

  You can find it under one of the following URLs:
  * https://preview.wix-style-react.com/pr_6693

2021-02-02 13:05 UTC, EgoziE requested changes

2021-02-02 13:05 UTC, EgoziE commented on packages/wix-style-react/src/TimeInputWip/TimeInputWip.js
> +              style={{ width: width || 'auto' }}
1. Width already has a default through `TimeInputWip.defaultProps`
2. We don't use the "style" attribute because it's not the Stylable way :)

If you really want to adjust the style you should extend the component - https://stylable.io/docs/references/extend-stylesheet

2021-02-02 13:05 UTC, EgoziE commented on packages/wix-style-react/src/TimeInputWip/TimeInputWip.st.css
> +:import {
This file can be removed for now

2021-02-02 13:44 UTC, EgoziE requested changes

2021-02-02 13:44 UTC, EgoziE commented on packages/wix-style-react/src/TimeInputWip/TimeInputWip.js
> +            return value.toLocaleUpperCase();
From what I see the `dayPeriod` is already in upper case.
But we're in a different locales, is it lower case for you?

2021-02-02 13:44 UTC, EgoziE commented on packages/wix-style-react/src/TimeInputWip/TimeInputWip.js
> +    })
The `_getFormattedDate` function is called a-lot! (for example it's called 96 times from `_getOptions`)
So the Intl object is created many times over (with the new operator)
I suggest you create it once in a different function that is called once the component is created and updated.

2021-02-02 13:44 UTC, EgoziE commented on packages/wix-style-react/src/TimeInputWip/TimeInputWip.js
> +    const step = this.props.step * 60000;
always destruct `this.props` and `this.state` in all functions

2021-02-02 16:15 UTC, vidmantasa commented on packages/wix-style-react/src/TimeInputWip/TimeInputWip.js
> +            return value.toLocaleUpperCase();
yes, it's lowercase for me.

2021-02-03 09:24 UTC, EgoziE requested changes

2021-02-03 09:24 UTC, EgoziE commented on packages/wix-style-react/src/TimeInputWip/test/TimeInputWip.spec.js
> +  });
Missing "onChange" to be called test
(I think that the implementation of getValue might throw an error when the component is disabled because you can't open the dropdown - please check it)

2021-02-03 09:24 UTC, EgoziE commented on packages/wix-style-react/src/TimeInputWip/test/TimeInputWip.visual.js
> +  },
"default" can be removed

2021-02-03 09:24 UTC, EgoziE commented on packages/wix-style-react/src/TimeInputWip/test/TimeInputWip.visual.js
> +  },
Please add one test for width: "auto" (should stretch)

2021-02-03 14:35 UTC, EgoziE requested changes

2021-02-03 14:59 UTC, vidmantasa commented on packages/wix-style-react/src/TimeInputWip/index.d.ts
> +  width?: React.CSSProperties['width'];
Fixed all except timeStyle
https://github.com/microsoft/TypeScript/issues/35865

2021-02-04 08:10 UTC, EgoziE approved these changes

2021-02-04 08:10 UTC, merged