<AddItem/> - add subtitle prop
wix/wix-style-react pull request #6699
Opened 2021-02-03 13:58 UTC by egidijusja

### 🔦 Summary

...

### ✅ Checklist

- [ ] 👨‍💻 API change is approved by the UI Infra Developers 
- [ ] 👨‍🎨 UX change is approved by the Design System UX 
- 📚 Change is documented
  - [ ] Story
  - [ ] API description
  - [ ] Cheatsheet
  - [ ] Other (explain)
- 🔬 Change is tested
  - [ ] Component
  - [ ] Visual test

2021-02-03 14:11 UTC, WixBuildServer commented
### 🤖 Hi, I'm #Janet!

  A deploy preview of your PR was successfully released 🖼.

  You can find it under one of the following URLs:
  * https://preview.wix-style-react.com/pr_6699

2021-02-03 14:19 UTC, egidijusja commented
Hey @milkyfruit, we have added subtitle prop for `addItem` component. In this PR I have added new subtitle example, could you review and give better description for it?

2021-02-04 08:29 UTC, milkyfruit requested changes
@egidijusja two changes are needed:
- [x] Subtitle color should be `D20`
- [x] Please change example to:
### Subtitle
Component has a `subtitle` prop, it's meant to explain how "add" action works. This is especially useful when AddItem is used together with [Dropzone](url) component and it's important to list supported file formats.
```
<Layout gap={10} cols={1}>
  <AddItem
    size="large"
    subtitle="You can upload jpeg, png and gif files up to 5 mb size"
  >
    Drag here to upload
  </AddItem>
</Layout>;
```

2021-02-04 12:54 UTC, milkyfruit approved these changes

2021-02-08 07:27 UTC, mykas commented on packages/wix-style-react/src/AddItem/AddItem.st.css
> +.subtitle {
I see the purpose of this classname is to control the padding between main content and subtitle. Because you already created a class called `contentBody` - I am wondering why not to have the padding controlled there? You wouldn't need this subtitle classname anymore.

2021-02-08 07:29 UTC, mykas commented on packages/wix-style-react/src/AddItem/AddItem.st.css
> +.subtitle:skin(standard) {
oh I see there is another reason to have this.

2021-02-17 13:57 UTC, mykas approved these changes
Looks good!

2021-02-18 13:28 UTC, merged