<MobileDrawer /> - New Component
wix/wix-style-react pull request #6751
Opened 2021-02-13 21:36 UTC by ErezPaperny

### 🔦 Summary

Create new component <MobileDrawer />
MobileDrawers provide access to destinations and functionality menus, such as Action Menus, Filter Dropdown etc. This component should be used on MOBILE ONLY.

Documents: 
- https://docs.google.com/document/d/1Mm4B0tqlD4R4TQtMTReES61R7qrVH4BwtAVT2eJwB-M/edit#
- https://zeroheight.com/7sjjzhgo2/p/447d36-06-overlays/b/08cd42/t/98687d

### ✅ Checklist

- [V] 👨‍💻 API change is approved by the UI Infra Developers @sivanharel  
- [V] 👨‍🎨 UX change is approved by the Design System UX @michalvardi  
- 📚 Change is documented
  - [V] Story
  - [V] API description
  - [V] Cheatsheet
  - [V] Other (explain)- Example of menu's / Share social mobile drawers

- 🔬 Change is tested
  - [V] Component
  - [X] Visual test - There is no visual test for modal so can't test it visually except manually

2021-02-13 21:49 UTC, WixBuildServer commented
### 🤖 Hi, I'm #Janet!

  A deploy preview of your PR was successfully released 🖼.

  You can find it under one of the following URLs:
  * https://bo.wix.com/pages/wix-ui-tpa.pr_6751/

2021-02-14 15:35 UTC, sivanharel requested changes
Very nice!
Thanks

2021-02-14 15:35 UTC, sivanharel commented on packages/wix-ui-tpa/src/components/MobileDrawer/MobileDrawer.tsx
> +import { classes } from './MobileDrawer.st.css';
```suggestion
import { st, classes } from './MobileDrawer.st.css';
```

You should use the st function

2021-02-14 15:35 UTC, sivanharel commented on packages/wix-ui-tpa/src/components/MobileDrawer/MobileDrawer.visual.tsx
> +    snap('default props', <MobileDrawer>Children</MobileDrawer>);
```suggestion
    snap('default props', <MobileDrawer isOpen>Children</MobileDrawer>);
```

2021-02-14 15:35 UTC, sivanharel commented on packages/wix-ui-tpa/src/components/MobileDrawer/MobileDrawer.visual.tsx
> +    snap('default props', <MobileDrawer>Children</MobileDrawer>);
We have a mobile wrapper for the visual tests but it has issues so we don't want to use it now.
So let's just add the same examples as you created in the example.tsx file.
I mean let's pass `actionMenuLayout` and `SocialBar` as children.

2021-02-14 15:38 UTC, sivanharel commented on packages/wix-ui-tpa/src/components/MobileDrawer/MobileDrawer.visual.tsx
> +    snap('default props', <MobileDrawer>Children</MobileDrawer>);
In order to see the visual test story page, you could run: `npm run eyes-storybook-debug` and click on the link `http://localhost:6007/`

2021-02-14 22:25 UTC, ErezPaperny reviewed
@sivanharel, I agree and fixed most, few comments left open with my answer. Please review and advice if more info is needed.

2021-02-16 09:12 UTC, sivanharel reviewed
Great work!
I added some comments.

We just have one issue. We need to think about another solution for updating the visible state. It couldn't run each render.

2021-02-16 12:41 UTC, jonathanadler reviewed
I think it might work without settimeout.
I'm not 100% sure, but probably something like this:

```jsx
export class MobileDrawer extends React.Component {
  state = {
    showDrawer: this.props.isOpen,
  }

  _hideDrawer() {
    const { showDrawer } = this.state;
    const { isOpen } = this.props;

    if (!isOpen && showDrawer) {
      this.setState({ showDrawer: false});
    }
  }

  render() {
    const { showDrawer } = this.state;
    const { isOpen } = this.props;
    
    return (
      <Modal isOpen={isOpen || showDrawer}>
        <div className={classnames(
                  classes.drawer, 
                  [classes.show]: showDrawer,
                )} 
                onTransitionEnd={this._hideDrawer}
                ></div>
      </Modal>
    );
  }
}
```
and the css will look like this:
```css
.drawer {
  position: absolute;
  bottom: -100%;
  left: 0;
  transition: bottom .2s ease;
}

.drawer.show {
  bottom: 0;
}
```

2021-02-17 06:58 UTC, ErezPaperny commented on packages/wix-ui-tpa/src/components/MobileDrawer/MobileDrawer.spec.tsx
> +    });
Hi in my opinion it is part of the testkit but I will IZROM with you and move it out of the test kit describe ;-).

2021-02-17 06:58 UTC, ErezPaperny commented on packages/wix-ui-tpa/src/components/MobileDrawer/MobileDrawer.st.css
> +transform: translateY(320px);
MAGNIV, changed, 10x

2021-02-17 06:58 UTC, ErezPaperny commented on packages/wix-ui-tpa/src/components/MobileDrawer/MobileDrawer.tsx
> +    }
cool, with the componentDidUpdate its actually resolve the needs of the setTimeOut and its work perfectlly. Thanks for the idea,

2021-02-17 09:16 UTC, sivanharel approved these changes
Looks good!
I will ask Michal to review it.

The visual tests fail since it takes the screenshot before the transition end. So we need to fix it somehow :) I will take a look on it later.

2021-02-21 09:30 UTC, WixBuildServer commented
### 🤖 Hi, I'm #Janet!

  A deploy preview of your PR was successfully released 🖼.

  Project Name: **wix-ui-tpa**

  You can find it under one of the following URLs:
  * https://bo.wix.com/pages/wix-ui-tpa.pr_6751/

2021-02-21 09:33 UTC, WixBuildServer commented
### 🤖 Hi, I'm #Janet!

  A deploy preview of your PR was successfully released 🖼.

  Project Name: **wix-style-react**

  You can find it under one of the following URLs:
  * https://preview.wix-style-react.com/pr_6751

2021-02-22 08:52 UTC, merged