<TABLE/>: fix disabling checkbox in a specific row
wix/wix-style-react pull request #6753
Opened 2021-02-14 14:05 UTC by naamagr

### 🔦 Summary

This PR fixes the bug described in this ticket: 
https://jira.wixpress.com/browse/DSM-1525

In addition, it fixes a bug that occurs when setting `selectionDisabled` , in which case the checkboxes appeared as disabled but the user was still able to check them.

### ✅ Checklist

- [ ] 👨‍💻 API change is approved by the UI Infra Developers 
- [ ] 👨‍🎨 UX change is approved by the Design System UX 
- 📚 Change is documented
  - [x] Story
  - [ ] API description
  - [ ] Cheatsheet
  - [ ] Other (explain)
- 🔬 Change is tested
  - [x] Component
  - [ ] Visual test

2021-02-15 09:41 UTC, WixBuildServer commented
### 🤖 Hi, I'm #Janet!

  A deploy preview of your PR was successfully released 🖼.

  You can find it under one of the following URLs:
  * https://bo.wix.com/pages/wix-ui-tpa.pr_6753/

2021-02-18 07:40 UTC, mykas commented
Hi, thanks for the contribution! The code looks nice, but I have some concerns on introducing new props. 

Introducing new props to component that is already complex might get things messy even more. I would suggest changing how `selectionDisabled` works.  For example if you provide a boolean to it - it would work the same as before, but if you provide a function then your feature could start working.


Next time please consult with us first about possible implementation, because Table component is complex.

2021-02-18 12:31 UTC, mykas commented on packages/wix-style-react/src/Table/Table.spec.js
> +        it(`should disable row selection when it matches 'isRowDisabled' prop`, async () => {
I think isRowDisabled prop should be changed to selectionDisabled.

2021-02-18 12:58 UTC, mykas commented on packages/wix-style-react/src/Table/BulkSelection/BulkSelection.js
> +      this.props.selectionDisabled !== nextProps.selectionDisabled ||
This equality will never work because I don't think functions can be checked by the equality.

2021-02-18 13:04 UTC, naamagr commented on packages/wix-style-react/src/Table/BulkSelection/BulkSelection.js
> +      this.props.selectionDisabled !== nextProps.selectionDisabled ||
why not?

2021-02-18 13:21 UTC, mykas commented on packages/wix-style-react/src/Table/BulkSelection/BulkSelection.js
> +      this.props.selectionDisabled !== nextProps.selectionDisabled ||
I think the references of the selectionDisabled might be different. I might be wrong. Let me check.

2021-02-22 07:32 UTC, mykas requested changes

2021-02-22 07:32 UTC, mykas commented on packages/wix-style-react/src/Table/BulkSelection/BulkSelection.js
> +  selectionDisabled: PropTypes.oneOfType([PropTypes.bool, PropTypes.func]),
Please also update index.d.ts file where selectionDIsabled is defined

2021-02-22 08:51 UTC, WixBuildServer commented
### 🤖 Hi, I'm #Janet!

  A deploy preview of your PR was successfully released 🖼.

  Project Name: **wix-ui-tpa**

  You can find it under one of the following URLs:
  * https://bo.wix.com/pages/wix-ui-tpa.pr_6753/

2021-02-22 08:56 UTC, WixBuildServer commented
### 🤖 Hi, I'm #Janet!

  A deploy preview of your PR was successfully released 🖼.

  Project Name: **wix-style-react**

  You can find it under one of the following URLs:
  * https://preview.wix-style-react.com/pr_6753

2021-02-22 09:58 UTC, mykas approved these changes

2021-02-22 09:58 UTC, merged