Adding 'aria-*' to <Text/>
wix/wix-style-react pull request #6755
Opened 2021-02-15 10:28 UTC by barboaron

### 🔦 Summary

...

### ✅ Checklist

- [ ] 👨‍💻 API change is approved by the UI Infra Developers 
- [ ] 👨‍🎨 UX change is approved by the Design System UX 
- 📚 Change is documented
  - [ ] Story
  - [ ] API description
  - [ ] Cheatsheet
  - [ ] Other (explain)
- 🔬 Change is tested
  - [ ] Component
  - [ ] Visual test

2021-02-15 11:25 UTC, WixBuildServer commented
### 🤖 Hi, I'm #Janet!

  A deploy preview of your PR was successfully released 🖼.

  You can find it under one of the following URLs:
  * https://bo.wix.com/pages/wix-ui-tpa.pr_6755/

2021-02-16 12:36 UTC, nitayneeman requested changes

2021-02-16 12:36 UTC, nitayneeman commented on packages/wix-ui-tpa/src/components/Text/Text.tsx
> +      ...rest
This is a bit problematic because now the component accepts any attribute as a prop...
I think we should be more explicit - what are the specific `aria` attrs you need to use?

2021-02-17 12:06 UTC, barboaron commented on packages/wix-ui-tpa/src/components/Text/Text.tsx
> +      ...rest
@giladartzi

2021-02-18 08:47 UTC, nitayneeman approved these changes
We discussed this approach during the daily and we decided to give it a try

2021-02-18 11:02 UTC, merged

2021-03-10 04:06 UTC, WixBuildServer commented
### 🤖 Hi, I'm #Janet!

  A deploy preview of your PR was successfully released 🖼.

  Project Name: **wix-style-react**

  You can find it under one of the following URLs:
  * https://preview.wix-style-react.com/pr_6755