<ListItemSelect/> - fix type
wix/wix-style-react pull request #6778
Opened 2021-02-17 16:28 UTC by EgoziE

2021-02-17 16:29 UTC, TalZa1810 approved these changes

2021-02-17 16:31 UTC, TalZa1810 requested changes

2021-02-17 16:31 UTC, TalZa1810 commented on packages/wix-style-react/src/ListItemSelect/test/ListItemSelect.tsx
>    const { disabled, id, overrideOptionStyle, value } = listItemSelectBuilder({
label should be added here too

2021-02-17 16:33 UTC, EgoziE commented on packages/wix-style-react/src/ListItemSelect/test/ListItemSelect.tsx
>    const { disabled, id, overrideOptionStyle, value } = listItemSelectBuilder({
right

2021-02-17 16:56 UTC, WixBuildServer commented
### 🤖 Hi, I'm #Janet!

  A deploy preview of your PR was successfully released 🖼.

  You can find it under one of the following URLs:
  * https://bo.wix.com/pages/wix-ui-tpa.pr_6778/

2021-02-18 08:10 UTC, merged

2021-03-10 04:06 UTC, WixBuildServer commented
### 🤖 Hi, I'm #Janet!

  A deploy preview of your PR was successfully released 🖼.

  Project Name: **wix-style-react**

  You can find it under one of the following URLs:
  * https://preview.wix-style-react.com/pr_6778