<AddItem /> - added icon prop for illustrations
wix/wix-style-react pull request #6786
Opened 2021-02-18 12:13 UTC by egidijusja

### 🔦 Summary

...

### ✅ Checklist

- [ ] 👨‍💻 API change is approved by the UI Infra Developers 
- [ ] 👨‍🎨 UX change is approved by the Design System UX 
- 📚 Change is documented
  - [ ] Story
  - [ ] API description
  - [ ] Cheatsheet
  - [ ] Other (explain)
- 🔬 Change is tested
  - [ ] Component
  - [ ] Visual test

2021-02-18 12:31 UTC, WixBuildServer commented
### 🤖 Hi, I'm #Janet!

  A deploy preview of your PR was successfully released 🖼.

  You can find it under one of the following URLs:
  * https://bo.wix.com/pages/wix-ui-tpa.pr_6786/

2021-02-18 14:04 UTC, egidijusja commented
Hey @milkyfruit, we have added `icon` to enable users to use illustrations by providing src of them. I have added one example for it. Can you review it? Also `icon` prop allows user to pass react node (e.g. he wants some custom icon/component instead of default addIcon) - should we have example for this case as well?

2021-02-19 09:15 UTC, milkyfruit requested changes
- [ ] Change prop name from `icon` to `illustration`. It will match the zeplin specs nad Modal API which has a similar case.
- [ ] Simplify the example by showing only the first option. The second option doesn't follow design rules.
```
<AddItem icon="generic_add_item_illustration.svg" size="large">
  Drag here to upload
</AddItem>
```

@egidijusja

2021-02-22 07:07 UTC, WixBuildServer commented
### 🤖 Hi, I'm #Janet!

  A deploy preview of your PR was successfully released 🖼.

  Project Name: **wix-ui-tpa**

  You can find it under one of the following URLs:
  * https://bo.wix.com/pages/wix-ui-tpa.pr_6786/

2021-02-22 07:10 UTC, WixBuildServer commented
### 🤖 Hi, I'm #Janet!

  A deploy preview of your PR was successfully released 🖼.

  Project Name: **wix-style-react**

  You can find it under one of the following URLs:
  * https://preview.wix-style-react.com/pr_6786

2021-02-22 13:08 UTC, egidijusja commented
> * [ ]  Change prop name from `icon` to `illustration`. It will match the zeplin specs nad Modal API which has a similar case.
> * [ ]  Simplify the example by showing only the first option. The second option doesn't follow design rules.
> 
> **Overriding Icon**
> Component allows to override the icon with an illustration. It’s useful when add item contains important functionality that needs emphasis. For example drag and drop file uploading.
> 
> ```
> <AddItem icon="generic_add_item_illustration.svg" size="large">
>   Drag here to upload
> </AddItem>
> ```
> 
> I think it doesn't need additional example showing how a node works.
> 
> @egidijusja

As discussed on call will leave `icon` prop name to ensure consistency inside component with other prop `showIcon`. Other things were fixed.

2021-02-25 08:37 UTC, milkyfruit approved these changes

2021-02-26 11:43 UTC, mykas approved these changes

2021-02-26 11:44 UTC, mykas commented
@jonathanadler Please review the changes for wix-ui-tpa.

2021-02-28 07:19 UTC, jonathanadler commented
> @jonathanadler Please review the changes for wix-ui-tpa.

@sivanharel can you review?

2021-02-28 07:39 UTC, sivanharel requested changes
Looks good!
Just change the bundle sizes according to my comment :)

2021-02-28 07:39 UTC, sivanharel commented on packages/wix-ui-tpa/perfer.config.js
> +  'AddItemPerfExtended.bundle.min.js': 43,
```suggestion
  'AddItem.bundle.min.js': 41.701,
  'AddItemPerfBasic.bundle.min.js': 41.942,
  'AddItemPerfExtended.bundle.min.js': 42.475,
```

2021-02-28 07:39 UTC, sivanharel commented on packages/wix-ui-tpa/perfer.config.js
> +  'AddItemPerfExtended.bundle.min.js': 43,
We set the actual bundle size here in order to know what is the real size.
We do have a 1kb delta which is the max size that is allowed.

![Screen Shot 2021-02-28 at 9 34 57](https://user-images.githubusercontent.com/66675260/109411094-3a07fa00-79a8-11eb-94bb-225db92106f5.png)

2021-03-01 08:05 UTC, sivanharel approved these changes

2021-03-01 08:42 UTC, merged