<Input /> - story according new guidelines
wix/wix-style-react pull request #6795
Opened 2021-02-19 14:43 UTC by egidijusja

### 🔦 Summary

...

### ✅ Checklist

- [ ] 👨‍💻 API change is approved by the UI Infra Developers 
- [ ] 👨‍🎨 UX change is approved by the Design System UX 
- 📚 Change is documented
  - [ ] Story
  - [ ] API description
  - [ ] Cheatsheet
  - [ ] Other (explain)
- 🔬 Change is tested
  - [ ] Component
  - [ ] Visual test

2021-02-19 14:55 UTC, WixBuildServer commented
### 🤖 Hi, I'm #Janet!

  A deploy preview of your PR was successfully released 🖼.

  You can find it under one of the following URLs:
  * https://bo.wix.com/pages/wix-ui-tpa.pr_6795/

2021-02-22 15:15 UTC, WixBuildServer commented
### 🤖 Hi, I'm #Janet!

  A deploy preview of your PR was successfully released 🖼.

  Project Name: **wix-ui-tpa**

  You can find it under one of the following URLs:
  * https://bo.wix.com/pages/wix-ui-tpa.pr_6795/

2021-02-22 15:19 UTC, WixBuildServer commented
### 🤖 Hi, I'm #Janet!

  A deploy preview of your PR was successfully released 🖼.

  Project Name: **wix-style-react**

  You can find it under one of the following URLs:
  * https://preview.wix-style-react.com/pr_6795

2021-02-24 11:41 UTC, mykas commented on packages/wix-style-react/src/Input/docs/examples.js
> +() => {
Lets minimise this example to:
```
() => {
  const [inputText, setInputText] = React.useState(
    'Click clear button to erase this value',
  );

  return (
    <Input
      value={inputText}
      clearButton
      onChange={e => setInputText(e.target.value)}
      onClear={() => setInputText('')}
    />
  );
};
```

2021-02-24 11:45 UTC, mykas commented on packages/wix-style-react/src/Input/docs/examples.js
> +export const inputAsTitle = `
I think this example is a bit too complicated to understand. Lets follow this guideline tip to make it more readable https://gist.github.com/mykas/6fa3cac9e08a5c6455ef2ce5545739e1#4-complex-structure-components-examples-can-be-daunting-to-comprehend-in-such-cases-there-is-value-in-abstracting-code-into-smaller-modules-in-order-to-reduce-mental-effort-in-understanding-the-code

2021-02-24 11:47 UTC, mykas commented on packages/wix-style-react/src/Input/docs/examples.js
> +export const compoundInput = `
This is snippet is also a bit too much to read. Lets follow these tips to construct better example:
1. Large data sets should be added to meaningfull variables: https://gist.github.com/mykas/6fa3cac9e08a5c6455ef2ce5545739e1#3-in-case-property-requires-large-data-sets-for-interpretation---functional-snippets-can-be-used-to-move-big-data-sets-to-meaningful-variables
2. https://gist.github.com/mykas/6fa3cac9e08a5c6455ef2ce5545739e1#3-in-case-property-requires-large-data-sets-for-interpretation---functional-snippets-can-be-used-to-move-big-data-sets-to-meaningful-variables

2021-02-24 11:52 UTC, egidijusja commented on packages/wix-style-react/src/Input/docs/examples.js
> +() => {
Fixed

2021-02-24 16:10 UTC, milkyfruit requested changes
@egidijusj

- [ ] Please make "compound input" example with format validation. Egozi's example can be used: https://github.com/wix/wix-style-react/issues/4627
![image](https://user-images.githubusercontent.com/1684587/109028683-b9f14400-76ca-11eb-9a08-9812a07097e9.png)
- [ ] Let's change input's value next to image to "Cooking recipes album"
![image](https://user-images.githubusercontent.com/1684587/109029010-15233680-76cb-11eb-86ff-2d47fc8ffd3a.png)
- [ ] Please add text formatting to Feedback section:
"You can help us improve this component by providing feedback, asking questions or leaving any other comments via **#wix-style-ux** or **#wix-style-react** Slack channels or GitHub. Found a bug? Please report it to: https://goo.gl/forms/wrVuHnyBrEISXUPF2"
- [ ] Please swap placeholder values:
![image](https://user-images.githubusercontent.com/1684587/109029950-07ba7c00-76cc-11eb-9329-774e820c5d5a.png)

2021-02-24 18:55 UTC, egidijusj commented
@milkyfruit you most likely intended to tag @egidijusja, not me

2021-02-25 13:27 UTC, milkyfruit approved these changes
Looks great!

2021-02-26 08:22 UTC, mykas approved these changes

2021-02-26 08:23 UTC, merged