<Radio/> - move code from ui-core RadioButton
wix/wix-style-react pull request #6796
Opened 2021-02-19 15:11 UTC by Zivilekin

2021-02-19 15:24 UTC, WixBuildServer commented
### 🤖 Hi, I'm #Janet!

  A deploy preview of your PR was successfully released 🖼.

  You can find it under one of the following URLs:
  * https://bo.wix.com/pages/wix-ui-tpa.pr_6796/

2021-02-22 08:56 UTC, WixBuildServer commented
### 🤖 Hi, I'm #Janet!

  A deploy preview of your PR was successfully released 🖼.

  Project Name: **wix-ui-tpa**

  You can find it under one of the following URLs:
  * https://bo.wix.com/pages/wix-ui-tpa.pr_6796/

2021-02-22 09:02 UTC, WixBuildServer commented
### 🤖 Hi, I'm #Janet!

  A deploy preview of your PR was successfully released 🖼.

  Project Name: **wix-style-react**

  You can find it under one of the following URLs:
  * https://preview.wix-style-react.com/pr_6796

2021-02-22 10:30 UTC, mykas requested changes

2021-02-22 10:30 UTC, mykas commented on packages/wix-style-react/src/Radio/Radio.st.css
> +  padding:0 !important;
I don't think we need this `!important` here. If this is overriding the agent stylesheet for input then simple usage of padding should be enough to override, but please double check it.

2021-02-22 10:30 UTC, mykas commented on packages/wix-style-react/src/Radio/Radio.st.css
> +.root .label {
Lets scope this even more: `.root > .label`.

2021-02-22 10:30 UTC, mykas commented on packages/wix-style-react/src/Radio/Radio.st.css
> +.root .icon::after {
Lets scope it as direct child: `.root > .icon`

2021-02-22 10:39 UTC, mykas commented
I think you also forgot to move index.d.ts some types from core to wix-style-react

2021-02-22 12:13 UTC, egidijusja requested changes

2021-02-22 12:13 UTC, egidijusja commented on packages/wix-style-react/src/Radio/Radio.driver.js
> +    exists: () => !!element,
In all `.unidriver.js` files we have `element` exposed by default, but when it comes to `.driver.js` sometimes we have element and sometimes we don't. Here we don't have element exposed, is it OK?

2021-02-22 12:13 UTC, egidijusja commented on packages/wix-style-react/src/Radio/Radio.js
> +      onChange={handleInputChange}
When is `onChange` event fired for this `div`?

2021-02-22 12:13 UTC, egidijusja commented on packages/wix-style-react/src/Radio/Radio.js
> +      aria-checked={checked ? checked : false}
minor, but maybe it is enough to have:
```
aria-checked={!!checked}
```

2021-02-22 12:33 UTC, Zivilekin commented on packages/wix-style-react/src/Radio/Radio.js
> +      onChange={handleInputChange}
Good question. When user navigates through radio buttons by keyboard. Though I think I could move it directly on input

2021-02-23 07:49 UTC, Zivilekin commented on packages/wix-style-react/src/Radio/Radio.js
> +      onChange={handleInputChange}
It seems that onChange is unnecessary, so I removed it and left only onClick since it handles keyboard navigation after all

2021-02-23 08:50 UTC, egidijusja approved these changes

2021-02-23 12:27 UTC, mykas approved these changes

2021-02-23 12:28 UTC, merged