<Badge/> - fix font color when it is wider then max width
wix/wix-style-react pull request #6809
Opened 2021-02-22 10:08 UTC by bamai

https://jira.wixpress.com/browse/DSM-1521

2021-02-22 10:33 UTC, WixBuildServer commented
### 🤖 Hi, I'm #Janet!

  A deploy preview of your PR was successfully released 🖼.

  Project Name: **wix-style-react**

  You can find it under one of the following URLs:
  * https://preview.wix-style-react.com/pr_6809

2021-02-22 11:34 UTC, justinara approved these changes

2021-02-22 12:19 UTC, EgoziE requested changes

2021-02-22 12:19 UTC, EgoziE commented on packages/wix-style-react/src/Badge/Badge.st.css
> +
ALLLLLLLLLLLLLL this can be encapsulated into one rule:

```
.BadgeStyle .text {
  color: value(color);
}
```

2021-02-24 11:29 UTC, EgoziE approved these changes

2021-02-24 11:51 UTC, merged