<TableActionCell/> - Add primaryAction icon affixes
wix/wix-style-react pull request #6831
Opened 2021-02-23 16:25 UTC by omeb

### 🔦 Summary

Adding the ability to render button affixes inside primary action button.

...

### ✅ Checklist

- [ ] 👨‍💻 API change is approved by the UI Infra Developers 
- [ ] 👨‍🎨 UX change is approved by the Design System UX 
- 📚 Change is documented
  - [x] Story
  - [x] API description
  - [ ] Cheatsheet
  - [ ] Other (explain)
- 🔬 Change is tested
  - [x] Component
  - [x] Visual test

2021-02-24 08:25 UTC, milkyfruit commented
@omeb could you fix the build?  Preview doesn't appear in storybook:
https://preview.wix-style-react.com/pr_6831/

2021-02-24 09:18 UTC, omeb commented
@milkyfruit - tnx, I had issue with signing the commit, resolved it now.
How can I re-trigger the build? I've tried closing and reopening the PR but they're still not triggered...

Tnx!

2021-02-24 09:24 UTC, TalZa1810 commented
@omeb just add a dummy commit to re-trigger CI

2021-02-24 09:42 UTC, omeb commented
@TalZa1810 - now it seems that tests are failing due to some CI issue...
Do you have an idea what could be wrong here?

![image](https://user-images.githubusercontent.com/7505578/108981266-3cf7a780-7695-11eb-94df-fd09bf58dbd2.png)


Tnx!

2021-02-24 09:59 UTC, omeb commented
@TalZa1810 - I've tried recreating my `gpg` signature and pushed again, waiting to see if that does the trick... :)

2021-02-24 10:17 UTC, WixBuildServer commented
### 🤖 Hi, I'm #Janet!

  A deploy preview of your PR was successfully released 🖼.

  Project Name: **wix-ui-tpa**

  You can find it under one of the following URLs:
  * https://bo.wix.com/pages/wix-ui-tpa.pr_6831/

2021-02-24 10:23 UTC, WixBuildServer commented
### 🤖 Hi, I'm #Janet!

  A deploy preview of your PR was successfully released 🖼.

  Project Name: **wix-style-react**

  You can find it under one of the following URLs:
  * https://preview.wix-style-react.com/pr_6831

2021-02-25 08:45 UTC, milkyfruit reviewed
The feature looks great, the added example is a bit confusing.
@omeb please split items to separate divs or demonstrate just one type affix:
![image](https://user-images.githubusercontent.com/1684587/109126927-81974780-7756-11eb-9eb7-05b52d55f7f2.png)
Once example is fixed, PR can be merged.

2021-03-01 07:35 UTC, milkyfruit approved these changes

2021-03-01 07:37 UTC, milkyfruit commented
@TalZa1810 I approved this change, feature and storybook examples look good. Please merge it when it's ready.

2021-03-01 15:15 UTC, egidijusja requested changes

2021-03-01 15:15 UTC, egidijusja commented on packages/wix-style-react/src/TableActionCell/TableActionCell.uni.driver.d.ts
> +  getIsPrimaryActionButtonAffixIconExists: () => Promise<boolean>;
Please add the same new methods (with the same naming) to unidriver testkit as you've added to driver testkit.

2021-03-01 15:15 UTC, egidijusja commented on packages/wix-style-react/src/TableActionCell/test/TableActionCell.spec.js
> +
At the moment tests are failing. Could you please test both newly added methods (suffix and prefix)

2021-03-01 15:15 UTC, egidijusja commented on packages/wix-style-react/src/TableActionCell/TableActionCell.uni.driver.js
> +  const getIsPrimaryActionButtonAffixIconExists = () => Boolean(base.$('button > svg').exists()),
At the end of the line semicolon should be used instead of comma. This breaks your builds

2021-03-01 15:20 UTC, omeb commented on packages/wix-style-react/src/TableActionCell/TableActionCell.uni.driver.d.ts
> +  getIsPrimaryActionButtonAffixIconExists: () => Promise<boolean>;
I have no way to test a specific `affix` as Button driver does not expose it in its testkit, nor does it create a data-hook for it...

2021-03-01 15:21 UTC, omeb commented on packages/wix-style-react/src/TableActionCell/TableActionCell.driver.d.ts
> +  getIsPrimaryActionButtonSuffixIconExists: () => boolean;
Sure thing, changed

2021-03-01 15:23 UTC, omeb commented on packages/wix-style-react/src/TableActionCell/test/TableActionCell.spec.js
> +
how do you trigger these specific tests locally?

2021-03-01 15:32 UTC, egidijusja commented on packages/wix-style-react/src/TableActionCell/test/TableActionCell.spec.js
> +
Go to root folder of repo and run command `npm run wsr test:unit`

2021-03-01 20:02 UTC, omeb commented on packages/wix-style-react/src/TableActionCell/TableActionCell.uni.driver.d.ts
> +  getIsPrimaryActionButtonAffixIconExists: () => Promise<boolean>;
done, tnx!

2021-03-02 07:42 UTC, mykas commented on packages/wix-style-react/src/TableActionCell/TableActionCell.uni.driver.js
> +    primaryActionButtonPrefixIconExists: primaryActionButtonAffixIconExists,
Hey, this method needs to use buttonDriverFactory official testkit methods. As I can see there are missing methods there that could be used here: prefixIconExists() and suffixIconExists(). You should add them to the wix-ui-core button unidriver and legacy driver and then come back here to reuse it here.

2021-03-02 07:45 UTC, mykas requested changes

2021-03-02 07:45 UTC, mykas commented on packages/wix-style-react/src/TableActionCell/test/TableActionCell.e2e.js
> +    'Primary action icon prefix': 'story-primary-with-icon-prefix',
We have few ways how we test our components:
1. e2e - meant for interactivity
2. visuals - meant for static visual screenshooting
3. unit tests - meant for logic testing

In your case you just need to do a screenshot test of how suffix and prefix are addded. Considering redoing this to visual tests instead of e2e.

2021-03-02 07:56 UTC, mykas commented on packages/wix-style-react/src/TableActionCell/TableActionCell.uni.driver.js
> +    primaryActionButtonPrefixIconExists: primaryActionButtonAffixIconExists,
Write me up if you want more details on how to do it

2021-03-02 11:49 UTC, omeb commented on packages/wix-style-react/src/TableActionCell/TableActionCell.uni.driver.js
> +    primaryActionButtonPrefixIconExists: primaryActionButtonAffixIconExists,
@mykas - tnx, where do I add that, [here](https://github.com/wix/wix-style-react/blob/master/packages/wix-style-react/src/Button/Button.uni.driver.js#L7)?

2021-03-02 11:51 UTC, omeb commented on packages/wix-style-react/src/TableActionCell/test/TableActionCell.e2e.js
> +    'Primary action icon prefix': 'story-primary-with-icon-prefix',
I've added all of the above...
Storybook is also going through visual tests.

2021-03-02 11:56 UTC, mykas commented on packages/wix-style-react/src/TableActionCell/TableActionCell.uni.driver.js
> +    primaryActionButtonPrefixIconExists: primaryActionButtonAffixIconExists,
First here: https://github.com/wix/wix-ui/blob/master/packages/wix-ui-core/src/components/button-next/button-next.uni.driver.ts#L16 , then in your mentioned place

2021-03-08 11:19 UTC, omeb commented on packages/wix-style-react/src/TableActionCell/TableActionCell.uni.driver.js
> +    primaryActionButtonPrefixIconExists: primaryActionButtonAffixIconExists,
@mykas - [my PR](https://github.com/wix/wix-ui/pull/2047) to `wix-ui` was merged but it seems like the package is not published (last version was published a week ago by `wix-ci-publisher <netanelg@wix.com>`). How can we publish the new minor version of the package? I need it published so I could consume the new testkit handlers inside `Button.uni.driver.js`.

Tnx!

2021-03-10 14:27 UTC, mykas requested changes
Please convert e2e tests to visual tests.

2021-03-11 12:21 UTC, omeb commented
Any chance we could merge?

2021-03-11 12:25 UTC, merged

2021-04-01 04:12 UTC, WixBuildServer commented
<!-- PRֹֹֹ_COMMENT_FOR:wix-style-react -->

### 🤖 Hi, I'm #Janet!

A deploy preview of your PR was successfully released 🖼.

Project Name: **wix-style-react**

You can find it under one of the following URLs:
* https://preview.wix-style-react.com/pr_6831

2021-04-01 05:03 UTC, WixBuildServer commented
<!-- PRֹֹֹ_COMMENT_FOR:wix-ui-tpa -->

### 🤖 Hi, I'm #Janet!

A deploy preview of your PR was successfully released 🖼.

Project Name: **wix-ui-tpa**

You can find it under one of the following URLs:
* https://bo.wix.com/pages/wix-ui-tpa.pr_6831/