Migrate non-scoped to scoped pacakges
wix/wix-style-react pull request #6855
Opened 2021-03-02 08:33 UTC by jonathanadler

https://github.com/wix-private/migrate-to-wix-scoped-packages

2021-03-02 08:56 UTC, mykas commented on packages/wix-style-react/package.json
> +    "@wix/draft-js": "^0.11.7",
Hey, are you sure we are using our internal scope of draft-js?

2021-03-02 09:07 UTC, jonathanadler commented on packages/wix-style-react/package.json
> +    "@wix/draft-js": "^0.11.7",
I'm not sure at all 😄 
I used the migrator tool https://github.com/wix-private/migrate-to-wix-scoped-packages
I believe this tool knows which packages should be scoped and which aren't, but we can ask them about it in the wix-scope-migration slack channel

2021-03-02 09:16 UTC, argshook commented on packages/wix-style-react/package.json
> +    "@wix/draft-js": "^0.11.7",
the migrator checks our dependencies against a generated list of
packages that exist in wix npm registry.

thus, because `@wix/draft-js` exists, the migrator chooses to use it.
to my knowledge scoping open source packages is part of the security
issue mitigation

2021-03-02 10:01 UTC, mykas commented on packages/wix-style-react/package.json
> +    "@wix/draft-js": "^0.11.7",
so its like if we have internal - use internal eve though it might be just same name repo?

2021-03-02 10:03 UTC, argshook commented on packages/wix-style-react/package.json
> +    "@wix/draft-js": "^0.11.7",
yes, that's what the migrator is doing

2021-03-02 10:05 UTC, mykas commented on packages/wix-style-react/package.json
> +    "@wix/draft-js": "^0.11.7",
what if draft-js inside our scope is different already to the original?

2021-03-02 10:40 UTC, shlomitc requested changes

2021-03-02 10:40 UTC, shlomitc commented on packages/wix-style-react-test-runtime/package.json
>      "yoshi-style-dependencies": "^4.71.0"
this can be scoped as well

2021-03-02 10:40 UTC, shlomitc commented on packages/wix-style-react-test-runtime/package.json
>      "yoshi-stylable-dependencies": "^4.0.0",
just mentioning that this should stay non scoped since it should be public (and a direct dependency in the dependencies list)

2021-03-02 10:40 UTC, shlomitc commented on packages/wix-style-react/.storybook/webpack.config.js
>  const StylableWebpackPlugin = require('yoshi-common/build/@stylable/webpack-plugin')
looks like this should be scoped as well

2021-03-02 10:40 UTC, shlomitc commented on packages/wix-style-react/package.json
>      "yoshi-runtime": "1.0.732",
should be scoped?

2021-03-02 10:40 UTC, shlomitc commented on packages/wix-style-react/package.json
>      "yoshi-style-dependencies": "^4.228.0"
should be scoped?

2021-03-02 10:40 UTC, shlomitc commented on packages/wix-style-react/package.json
> +    "@wix/draft-js": "^0.11.7",
`draft-js` is an open-source package that should **not** be scoped.
in wix we have a fork under the same name, which is bad.

2021-03-02 10:40 UTC, shlomitc commented on packages/wix-ui-tpa/.autotools/node-require-hooks.js
>  require('yoshi-runtime').wixCssModulesRequireHook('./src');
scope

2021-03-02 11:45 UTC, argshook commented on packages/wix-style-react-test-runtime/package.json
>      "yoshi-stylable-dependencies": "^4.0.0",
though here it's `wix-style-react-test-runtime` package, not really important in here
but it's very important in `wix-style-react`, should be unscopped and under `dependencies` as Shlomi said

2021-03-02 12:17 UTC, nitayneeman commented on packages/wix-style-react/package.json
> +    "@wix/draft-js": "^0.11.7",
> `draft-js` is an open-source package that should **not** be scoped.
> in wix we have a fork under the same name, which is bad.

@jonathanadler In this case we don't want the fork of Wix as Shlomi said. The fork contains a couple of workarounds that were done by the RCE team and aren't relevant for us. Also we want to be aligned with the official package.

2021-03-03 10:19 UTC, jonathanadler commented on packages/wix-style-react-test-runtime/package.json
>      "yoshi-stylable-dependencies": "^4.0.0",
Are you referring to `yoshi-stylable-dependencies`?

2021-03-03 10:30 UTC, WixBuildServer commented
### 🤖 Hi, I'm #Janet!

  A deploy preview of your PR was successfully released 🖼.

  Project Name: **wix-ui-tpa**

  You can find it under one of the following URLs:
  * https://bo.wix.com/pages/wix-ui-tpa.pr_6855/

2021-03-03 10:32 UTC, WixBuildServer commented
### 🤖 Hi, I'm #Janet!

  A deploy preview of your PR was successfully released 🖼.

  Project Name: **wix-style-react**

  You can find it under one of the following URLs:
  * https://preview.wix-style-react.com/pr_6855

2021-03-03 10:40 UTC, jonathanadler commented
So it seems that all the `yoshi` packages that weren't migrated, should stay that way
https://wix.slack.com/archives/C01MY3N0ZV5/p1614669755221000

2021-03-04 13:44 UTC, argshook commented on packages/wix-style-react-test-runtime/package.json
>      "yoshi-stylable-dependencies": "^4.0.0",
yep, `yoshi-stylable-dependencies` must land in users `node_modules` at the root level, that's why we should keep it as dependency

2021-03-04 14:19 UTC, argshook commented on packages/wix-style-react-test-runtime/package.json
>      "yoshi-stylable-dependencies": "^4.0.0",
`yoshi-stylable-dependencies`
`yoshi-style-dependencies`

these are both under `dependencies` and i think should not be scoped, because

* they bring other open source dependencies
* if we scope them, wix-style-react wont be installable for open source users

2021-03-04 14:19 UTC, argshook commented on packages/wix-style-react/package.json
>      "yoshi-runtime": "1.0.732",
`@wix/yoshi-runtime` is unavailable, only `yoshi-runtime` exists, so it shouldn't be scoped for now

2021-03-04 14:36 UTC, jonathanadler commented on packages/wix-style-react-test-runtime/package.json
>      "yoshi-stylable-dependencies": "^4.0.0",
So there's nothing I need to change here, no?
I just need to leave it like it is

2021-03-04 14:43 UTC, argshook commented on packages/wix-style-react-test-runtime/package.json
>      "yoshi-stylable-dependencies": "^4.0.0",
yep

2021-03-04 14:47 UTC, argshook approved these changes

2021-03-04 15:05 UTC, merged