<DatePicker /> fix next / previous week arrows position on responsive width
wix/wix-style-react pull request #6863
Opened 2021-03-03 07:40 UTC by poseneror

### 🔦 Summary

When resizing the component in a responsive way, the navigation arrows shift their position:
![Screen Shot 2021-03-02 at 5 17 03 PM](https://user-images.githubusercontent.com/30498431/109770274-0b865b00-7c04-11eb-8352-54ace7868135.png)

The best solution we could come up with, is add a margin (in percentage), as the gap grows bigger and bigger as the component grows wider.
![Screen Shot 2021-03-02 at 5 18 11 PM](https://user-images.githubusercontent.com/30498431/109770280-0f19e200-7c04-11eb-892a-87c434b559d5.png)

This solution was reviewed UI wise on our side, and was approved.
...

### ✅ Checklist

- [ ] 👨‍💻 API change is approved by the UI Infra Developers 
- [ ] 👨‍🎨 UX change is approved by the Design System UX 

- 🔬 Change is tested

  - [ ] Visual test

2021-03-03 07:53 UTC, WixBuildServer commented
### 🤖 Hi, I'm #Janet!

  A deploy preview of your PR was successfully released 🖼.

  Project Name: **wix-ui-tpa**

  You can find it under one of the following URLs:
  * https://bo.wix.com/pages/wix-ui-tpa.pr_6863/

2021-03-03 07:56 UTC, WixBuildServer commented
### 🤖 Hi, I'm #Janet!

  A deploy preview of your PR was successfully released 🖼.

  Project Name: **wix-style-react**

  You can find it under one of the following URLs:
  * https://preview.wix-style-react.com/pr_6863

2021-03-03 08:46 UTC, sivanharel requested changes
This change broke all the other sizes :(
We should think on a different solution.

![Screen Shot 2021-03-03 at 10 45 15](https://user-images.githubusercontent.com/66675260/109778522-96b81e80-7c0d-11eb-8b7d-13f4ea5d2391.png)

2021-03-03 08:55 UTC, poseneror commented
> This change broke all the other sizes :(
> We should think on a different solution.
> 
> ![Screen Shot 2021-03-03 at 10 45 15](https://user-images.githubusercontent.com/66675260/109778522-96b81e80-7c0d-11eb-8b7d-13f4ea5d2391.png)

I know it is not the same, I've investigated other options, they don't seem to be fizzible.
I went over that with Leigh and we agreed that it's ok... can you maybe take it with michal?

2021-03-03 09:07 UTC, sivanharel commented
It should be aligned to the spec. If it is not possible we should get approval from Michal and consider changing the spec or find another solution. Please write about it on the Slack channel.

2021-03-04 09:34 UTC, sivanharel commented
Closing since I created a new PR.
https://github.com/wix/wix-style-react/pull/6872

2021-03-04 09:34 UTC, closed without merging