fix onfocus triggered twice when suffix icon is clicked
wix/wix-style-react pull request #6873
Opened 2021-03-04 09:45 UTC by roibWix

### 🔦 Summary

...

### ✅ Checklist

- [ ] 👨‍💻 API change is approved by the UI Infra Developers 
- [ ] 👨‍🎨 UX change is approved by the Design System UX 
- 📚 Change is documented
  - [ ] Story
  - [ ] API description
  - [ ] Cheatsheet
  - [ ] Other (explain)
- 🔬 Change is tested
  - [ ] Component
  - [ ] Visual test

2021-03-04 09:58 UTC, WixBuildServer commented
### 🤖 Hi, I'm #Janet!

  A deploy preview of your PR was successfully released 🖼.

  Project Name: **wix-ui-tpa**

  You can find it under one of the following URLs:
  * https://bo.wix.com/pages/wix-ui-tpa.pr_6873/

2021-03-04 10:02 UTC, WixBuildServer commented
### 🤖 Hi, I'm #Janet!

  A deploy preview of your PR was successfully released 🖼.

  Project Name: **wix-style-react**

  You can find it under one of the following URLs:
  * https://preview.wix-style-react.com/pr_6873

2021-03-07 12:30 UTC, EgoziE requested changes
There's a Testkit function `clickMenuArrow` that I see we don't test along with spies onFocus/onBlur props.
Please write a test for it and compare before and after your change.

2021-03-09 12:42 UTC, EgoziE requested changes
Only 1 comment, other than that I approve.

2021-03-09 12:42 UTC, EgoziE commented on packages/wix-style-react/src/Input/test/Input.spec.js
> +        expect(onFocus).toBeCalledTimes(1);
Also add a "before" test:
```
expect(onFocus).not.toBeCalled();
expect(onInputClicked).not.toBeCalled();
```

2021-03-09 13:07 UTC, EgoziE approved these changes

2021-03-10 09:48 UTC, merged