add support for twitter preview as part of social preview component
wix/wix-style-react pull request #6922
Opened 2021-03-15 09:43 UTC by tzachvw

#pr

2021-03-15 09:44 UTC, tzachvw commented
@mykas 
This is just a preliminary pr, containing only functional code.
I'll add tests, documentation and examples after this is reviewed.

2021-03-15 11:04 UTC, mykas commented on packages/wix-style-react/src/SocialPreview/SocialPreview.js
> +        <Box>{media}</Box>
Is there is a need for Box component here?

2021-03-15 11:05 UTC, mykas commented on packages/wix-style-react/src/SocialPreview/SocialPreview.js
> +        <Box
Lets in general not use Box component in SocialPreview. We as component library can use native html elements and in this case I think its too much to use Box. Can this be converted to div with a classname?

2021-03-15 11:05 UTC, mykas commented on packages/wix-style-react/src/SocialPreview/SocialPreview.js
> +          <Box marginBottom="3px">
This marginBottom can be added to the classname of `socialPreviewTitle`

2021-03-15 11:06 UTC, mykas commented on packages/wix-style-react/src/SocialPreview/SocialPreview.js
> +          <Box marginBottom="3px">
Same here as above.

2021-03-15 11:06 UTC, mykas commented on packages/wix-style-react/src/SocialPreview/SocialPreview.js
> +              light={false}
No need to say that `light` is false 🤔  it should be dark by default

2021-03-15 11:10 UTC, mykas commented on packages/wix-style-react/src/SocialPreview/SocialPreview.js
> +              dataHook="socialPreview-title"
Lets put all of these dataHooks to `constants.js` file to be reused later in the testkit.

2021-03-15 13:23 UTC, egidijusja requested changes

2021-03-15 13:23 UTC, egidijusja commented on packages/wix-style-react/src/SocialPreview/SocialPreview.js
> +    size: PropTypes.oneOf(['small', 'large']),
You've added two new props: `skin` and `size`. Can we add default prop values as well? 
```
  static defaultProps = {
    skin: 'social',
    size: 'large',
  };
```

2021-03-15 13:23 UTC, egidijusja commented on packages/wix-style-react/src/SocialPreview/SocialPreview.js
> +        className={st(classes.root, { twitter: isTwitter })}
maybe let's operate with actual prop names in stylable files as well?
```
className={st(classes.root, { skin })}
```

2021-03-15 13:58 UTC, tzachvw commented on packages/wix-style-react/src/SocialPreview/SocialPreview.js
> +        <Box
Box is already in use in SocialPreview (before my changes).
changing that would possibly affect existing behavior which I want to avoid.
If use div for only the new twitter layouts, I risk bugs and inconsistency relative the exiting (social) layout.
WDYT?

2021-03-16 07:43 UTC, egidijusja requested changes
According zeplin specs we have to make sure that our content always stays vertically centered when we are on twitter skin with size small.
3 cases to verify:
1) no description
2) description of 1 line
3) description of 2 lines

Currently it is not aligned correctly:
![Screenshot 2021-03-16 at 09 39 05](https://user-images.githubusercontent.com/75983295/111273047-02ea4780-863c-11eb-9750-638c43de1ee4.png)

2021-03-16 07:43 UTC, egidijusja commented on packages/wix-style-react/src/SocialPreview/constants.js
> +export const socialPreviewUrlDataHook = 'socialPreview-url';
Our common practice for dataHooks is to have one object for them, which is exported:
```
export const dataHooks = {
  socialPreviewTitle: 'socialPreview-title',
  socialPreviewDescription: 'socialPreview-description',
  socialPreviewUrl: 'socialPreview-url',
};
```

2021-03-16 07:43 UTC, egidijusja commented on packages/wix-style-react/src/SocialPreview/SocialPreview.st.css
> +  min-width: 0; /* needed to support text with ellipsis inside a container in flex. see https://css-tricks.com/flexbox-truncated-text/ */
I tried removing this line and played around with ellipsis and didn't find an issue. Could you tell me how to reproduce it, when we don't set min-width: 0 ?

2021-03-16 08:24 UTC, tzachvw commented on packages/wix-style-react/src/SocialPreview/SocialPreview.st.css
> +  min-width: 0; /* needed to support text with ellipsis inside a container in flex. see https://css-tricks.com/flexbox-truncated-text/ */
if you remove min-width and add a very long title, you'll see it overflowing the container instead of proper ellipsis.

![image](https://user-images.githubusercontent.com/50169994/111278066-ce798a00-8641-11eb-9851-cee8303785ba.png)

2021-03-16 09:39 UTC, egidijusja requested changes

2021-03-16 09:39 UTC, egidijusja commented on packages/wix-style-react/src/SocialPreview/constants.js
> +};
Minor, but can we remove `DataHook` postfix from variable names as the name of dataHooks object already suggests that:
```
export const dataHooks = {
  socialPreviewTitle: 'socialPreview-title',
  socialPreviewDescription: 'socialPreview-description',
  socialPreviewUrl: 'socialPreview-url',
};
```

2021-03-16 12:01 UTC, egidijusja requested changes

2021-03-16 12:01 UTC, egidijusja commented on packages/wix-style-react/src/SocialPreview/test/SocialPreview.visual.js
> +      description: 'a short description for a site'.repeat(20),
minor, but can we rename it to `'a long description for a site'.repeat(20)`

2021-03-16 12:01 UTC, egidijusja commented on packages/wix-style-react/src/SocialPreview/test/SocialPreview.visual.js
> +      description: 'a short description for a site'.repeat(20),
again: would be better to rename - short --> long

2021-03-16 16:00 UTC, tzachvw commented on packages/wix-style-react/src/SocialPreview/test/SocialPreview.visual.js
> +      description: 'a short description for a site'.repeat(20),
this is already being used in an existing test, so changing it would break that test.

2021-03-16 16:00 UTC, tzachvw commented on packages/wix-style-react/src/SocialPreview/test/SocialPreview.visual.js
> +      description: 'a short description for a site'.repeat(20),
this is already being used in an existing test, so changing it would break that test.

2021-03-17 09:22 UTC, WixBuildServer commented
### 🤖 Hi, I'm #Janet!

  A deploy preview of your PR was successfully released 🖼.

  Project Name: **wix-ui-tpa**

  You can find it under one of the following URLs:
  * https://bo.wix.com/pages/wix-ui-tpa.pr_6922/

2021-03-17 09:26 UTC, WixBuildServer commented
### 🤖 Hi, I'm #Janet!

  A deploy preview of your PR was successfully released 🖼.

  Project Name: **wix-style-react**

  You can find it under one of the following URLs:
  * https://preview.wix-style-react.com/pr_6922

2021-03-18 12:54 UTC, mykas commented on packages/wix-style-react/src/SocialPreview/test/SocialPreview.tsx
> +      data-skin="social"
data-skin and data-size are not official APi of component

2021-03-18 12:56 UTC, tzachvw commented on packages/wix-style-react/src/SocialPreview/test/SocialPreview.tsx
> +      data-skin="social"
I know. they're used by the driver to get the property values.
I saw this pattern in other components.

2021-03-18 12:56 UTC, mykas commented on packages/wix-style-react/src/SocialPreview/SocialPreview.js
> +        <div className={st(classes.socialPreviewUrlContainer, { skin })}>
What if previewUrl is not passed to the component? I see that it renders the link anyway. Even though this is not the way Twitter preview should look, but is possible that users might not added it. Don't render the div if previewUrl is not defined.

2021-03-18 13:49 UTC, mykas commented on packages/wix-style-react/src/SocialPreview/test/SocialPreview.tsx
> +      data-skin="social"
Those data-attributes are used inside the component and not exposed as props.

2021-03-18 14:38 UTC, mykas approved these changes

2021-03-22 10:01 UTC, merged

2021-04-06 04:02 UTC, WixBuildServer commented
<!-- PRֹֹֹ_COMMENT_FOR:wix-ui-tpa -->

### 🤖 Hi, I'm #Janet!

A deploy preview of your PR was successfully released 🖼.

Project Name: **wix-ui-tpa**

You can find it under one of the following URLs:
* https://bo.wix.com/pages/wix-ui-tpa.pr_6922/

2021-04-06 04:06 UTC, WixBuildServer commented
<!-- PRֹֹֹ_COMMENT_FOR:wix-style-react -->

### 🤖 Hi, I'm #Janet!

A deploy preview of your PR was successfully released 🖼.

Project Name: **wix-style-react**

You can find it under one of the following URLs:
* https://preview.wix-style-react.com/pr_6922