<SelectableAccordion /> Add disabled state
wix/wix-style-react pull request #6928
Opened 2021-03-16 08:29 UTC by domakas

### 🔦 Summary

Added disabled state for <SelectableAccordion />. When providing this property, controls becomes disabled, and all interactions are turned off.

### ✅ Checklist

- [ ] 👨‍💻 API change is approved by the UI Infra Developers @milkyfruit @mykas elevant team member -->
- 📚 Change is documented
  - [x] Story
  - [x] API description
- 🔬 Change is tested
  - [x] Component

2021-03-16 08:41 UTC, WixBuildServer commented
### 🤖 Hi, I'm #Janet!

  A deploy preview of your PR was successfully released 🖼.

  Project Name: **wix-ui-tpa**

  You can find it under one of the following URLs:
  * https://bo.wix.com/pages/wix-ui-tpa.pr_6928/

2021-03-16 08:47 UTC, WixBuildServer commented
### 🤖 Hi, I'm #Janet!

  A deploy preview of your PR was successfully released 🖼.

  Project Name: **wix-style-react**

  You can find it under one of the following URLs:
  * https://preview.wix-style-react.com/pr_6928

2021-03-16 13:17 UTC, milkyfruit requested changes
@domakas please change disabled from being for all items to disabled per item. Then it will be consistent with `<Accordion/>` component:
https://www.wix-style-react.com/?activeTab=Description&path=%2Fstory%2Fcomponents-api-components--accordion
![image](https://user-images.githubusercontent.com/1684587/111315142-c255f280-866a-11eb-915f-48b71114db6a.png)

2021-03-17 08:40 UTC, milkyfruit approved these changes
@domakas looks great now!
@mykas could you check the code and merge the PR?

2021-03-17 08:44 UTC, mykas commented on packages/wix-style-react/src/SelectableAccordion/Item/Item.js
> +            data-disabled={disabled ? 'disabled' : ''}
```suggestion
            data-disabled={disabled}
```

2021-03-17 08:44 UTC, mykas commented on packages/wix-style-react/src/SelectableAccordion/SelectableAccordion.uni.driver.js
> +      return itemState === 'disabled';
Disabled property for data-disable should be boolean instead

2021-03-17 08:54 UTC, mykas approved these changes
Good job! lets wait for build to get green and then I'll merge it.

2021-03-17 11:05 UTC, merged

2021-04-05 03:55 UTC, WixBuildServer commented
<!-- PRֹֹֹ_COMMENT_FOR:wix-ui-tpa -->

### 🤖 Hi, I'm #Janet!

A deploy preview of your PR was successfully released 🖼.

Project Name: **wix-ui-tpa**

You can find it under one of the following URLs:
* https://bo.wix.com/pages/wix-ui-tpa.pr_6928/

2021-04-05 03:58 UTC, WixBuildServer commented
<!-- PRֹֹֹ_COMMENT_FOR:wix-style-react -->

### 🤖 Hi, I'm #Janet!

A deploy preview of your PR was successfully released 🖼.

Project Name: **wix-style-react**

You can find it under one of the following URLs:
* https://preview.wix-style-react.com/pr_6928