<Box /> - gap
wix/wix-style-react pull request #6929
Opened 2021-03-16 13:09 UTC by egidijusja

### 🔦 Summary

...

### ✅ Checklist

- [ ] 👨‍💻 API change is approved by the UI Infra Developers 
- [ ] 👨‍🎨 UX change is approved by the Design System UX 
- 📚 Change is documented
  - [ ] Story
  - [ ] API description
  - [ ] Cheatsheet
  - [ ] Other (explain)
- 🔬 Change is tested
  - [ ] Component
  - [ ] Visual test

2021-03-16 13:27 UTC, WixBuildServer commented
### 🤖 Hi, I'm #Janet!

  A deploy preview of your PR was successfully released 🖼.

  Project Name: **wix-ui-tpa**

  You can find it under one of the following URLs:
  * https://bo.wix.com/pages/wix-ui-tpa.pr_6929/

2021-03-16 13:31 UTC, WixBuildServer commented
### 🤖 Hi, I'm #Janet!

  A deploy preview of your PR was successfully released 🖼.

  Project Name: **wix-style-react**

  You can find it under one of the following URLs:
  * https://preview.wix-style-react.com/pr_6929

2021-03-16 13:37 UTC, shlomitc requested changes

2021-03-16 13:37 UTC, shlomitc commented on packages/wix-style-react/src/Box/Box.st.css
>  }
take into consideration rtl support

2021-03-16 13:37 UTC, shlomitc commented on packages/wix-style-react/src/Box/Box.st.css
> +@st-global-custom-property --gap;
why not use stylable's hashing instead?

2021-03-16 13:37 UTC, shlomitc commented on packages/wix-style-react/src/Box/Box.js
> +  gap,
`gap` is a css api that is going to be adopted soon as a standard in all major browsers, so this means it will override the native one.
https://caniuse.com/?search=gap

maybe we should give it a different name

2021-03-16 13:46 UTC, mykas commented on packages/wix-style-react/src/Box/Box.js
> +  gap,
Hey Shlomi, the reason we decided to use this prop is basically because it is not supported in safari yet.

About changing the name - I don't think we want to change this to something else because this is universal name that is known not only in Box but also in Layout. 

@egidijusja soon will update this pr with new approach where we will use stylable mixins to check browser support and based on that either return native `gap` or apply custom solution with margins that would work in safari and other unsupported browsers.

2021-03-16 13:48 UTC, mykas commented on packages/wix-style-react/src/Box/Box.st.css
> +@st-global-custom-property --gap;
Because we would not be able to pass css var from javascript otherwise. Check this out: https://github.com/wix/wix-style-react/pull/6929/files#diff-c01be18ed0796f31b8c348e248a78e2a91baf36c59ee1490c34190156838cd50R197

2021-03-16 13:51 UTC, mykas commented on packages/wix-style-react/src/Box/Box.st.css
> +@st-global-custom-property --gap;
oh never mind. I just saw that in stylable you can reuse css vars in JS too.

2021-03-16 14:14 UTC, shlomitc commented on packages/wix-style-react/src/Box/Box.js
> +  gap,
I understand the intention, but in `Box` every API is handled as the original property as a style property.

Since it's not a 1-1 polyfill, we should be very careful with it.
See the differences between your implementation and the native behavior

![image](https://user-images.githubusercontent.com/6093192/111323572-ace4c680-8672-11eb-817d-156b86b64804.png)

```jsx
<>
  <Box gap="6px" flexWrap="wrap" width="150px">
    <Box border="1px solid black">Box</Box>
    <Box border="1px solid black">Box</Box>
    <Box border="1px solid black">Box</Box>
    <Box border="1px solid black">Box</Box>
    <Box border="1px solid black">Box</Box>
    <Box border="1px solid black">Box</Box>
  </Box>
  <hr />
  <div
    style={{ display: 'flex', gap: '6px', flexWrap: 'wrap', width: '150px' }}
  >
    <Box border="1px solid black">Box</Box>
    <Box border="1px solid black">Box</Box>
    <Box border="1px solid black">Box</Box>
    <Box border="1px solid black">Box</Box>
    <Box border="1px solid black">Box</Box>
    <Box border="1px solid black">Box</Box>
  </div>
</>;
```

2021-03-18 07:34 UTC, egidijusja commented on packages/wix-style-react/src/Box/Box.st.css
>  }
Verified that with current solution rtl is supported.

2021-03-18 07:38 UTC, mykas approved these changes
Best solution in a year!

2021-03-18 08:14 UTC, merged

2021-04-06 04:02 UTC, WixBuildServer commented
<!-- PRֹֹֹ_COMMENT_FOR:wix-ui-tpa -->

### 🤖 Hi, I'm #Janet!

A deploy preview of your PR was successfully released 🖼.

Project Name: **wix-ui-tpa**

You can find it under one of the following URLs:
* https://bo.wix.com/pages/wix-ui-tpa.pr_6929/

2021-04-06 04:06 UTC, WixBuildServer commented
<!-- PRֹֹֹ_COMMENT_FOR:wix-style-react -->

### 🤖 Hi, I'm #Janet!

A deploy preview of your PR was successfully released 🖼.

Project Name: **wix-style-react**

You can find it under one of the following URLs:
* https://preview.wix-style-react.com/pr_6929