<DropdownLayout /> - fix uni driver when using infinite scroll
wix/wix-style-react pull request #6937
Opened 2021-03-17 12:27 UTC by eugenevwix

Motivation: When using `infiniteScroll` uni driver methods returns wrong options.

2021-03-17 12:40 UTC, WixBuildServer commented
### 🤖 Hi, I'm #Janet!

  A deploy preview of your PR was successfully released 🖼.

  Project Name: **wix-ui-tpa**

  You can find it under one of the following URLs:
  * https://bo.wix.com/pages/wix-ui-tpa.pr_6937/

2021-03-17 12:44 UTC, WixBuildServer commented
### 🤖 Hi, I'm #Janet!

  A deploy preview of your PR was successfully released 🖼.

  Project Name: **wix-style-react**

  You can find it under one of the following URLs:
  * https://preview.wix-style-react.com/pr_6937

2021-03-18 07:43 UTC, mykas requested changes

2021-03-18 07:43 UTC, mykas commented on packages/wix-style-react/src/DropdownLayout/DropdownLayout.uni.driver.js
> +      .$$(`[data-hook=${await getOptionsContainerDataHook()}] > *`)
Lets add a unit test that failed before and now is green

2021-03-18 09:35 UTC, eugenevwix commented on packages/wix-style-react/src/DropdownLayout/DropdownLayout.uni.driver.js
> +      .$$(`[data-hook=${await getOptionsContainerDataHook()}] > *`)
added

2021-03-18 09:55 UTC, mykas approved these changes
Nice! Thank you

2021-03-18 10:41 UTC, merged

2021-04-06 04:02 UTC, WixBuildServer commented
<!-- PRֹֹֹ_COMMENT_FOR:wix-ui-tpa -->

### 🤖 Hi, I'm #Janet!

A deploy preview of your PR was successfully released 🖼.

Project Name: **wix-ui-tpa**

You can find it under one of the following URLs:
* https://bo.wix.com/pages/wix-ui-tpa.pr_6937/

2021-04-06 04:06 UTC, WixBuildServer commented
<!-- PRֹֹֹ_COMMENT_FOR:wix-style-react -->

### 🤖 Hi, I'm #Janet!

A deploy preview of your PR was successfully released 🖼.

Project Name: **wix-style-react**

You can find it under one of the following URLs:
* https://preview.wix-style-react.com/pr_6937