BusinessDashboard Theme | Override Divider dark skin
wix/wix-style-react pull request #6946
Opened 2021-03-18 14:45 UTC by liorf-wix

Dashboard Theme - Add Dark Skin Divider to dashboard theme
Jira: https://jira.wixpress.com/browse/OSB-440

### ✅ Checklist

- [ ] 👨‍💻 API change is approved by the UI Infra Developers 
- [ ] 👨‍🎨 UX change is approved by the Design System UX  - Ayelet Livne
- 📚 Change is documented
  - [X] Story
  - [ ] API description
  - [ ] Cheatsheet
  - [ ] Other (explain)
- 🔬 Change is tested
  - [ ] Component
  - [X] Visual test

2021-03-21 06:47 UTC, adicicurel commented on packages/wix-style-react/src/Themes/businessDashboard/components/Divider.st.css
> +}
add line break

2021-03-21 06:53 UTC, adicicurel commented on packages/wix-style-react/src/Themes/businessDashboard/test/businessDashboard.visual.js
> +import { runTests as DividerTests } from '../../../Divider/test/Divider.visual';
@liorf-wix you need to implement the runTests in the Divider.visual

2021-03-21 06:53 UTC, adicicurel requested changes
@liorf-wix you need to implement the runTests in the Divider.visual

2021-03-21 12:01 UTC, adicicurel approved these changes

2021-03-22 11:06 UTC, WixBuildServer commented
### 🤖 Hi, I'm #Janet!

  A deploy preview of your PR was successfully released 🖼.

  Project Name: **wix-ui-tpa**

  You can find it under one of the following URLs:
  * https://bo.wix.com/pages/wix-ui-tpa.pr_6946/

2021-03-22 11:10 UTC, WixBuildServer commented
### 🤖 Hi, I'm #Janet!

  A deploy preview of your PR was successfully released 🖼.

  Project Name: **wix-style-react**

  You can find it under one of the following URLs:
  * https://preview.wix-style-react.com/pr_6946

2021-03-22 12:52 UTC, merged

2021-04-10 04:17 UTC, env-github-token commented
<!-- PRֹֹֹ_COMMENT_FOR:wix-ui-tpa -->

### 🤖 Hi, I'm #Janet!

A deploy preview of your PR was successfully released 🖼.

Project Name: **wix-ui-tpa**

You can find it under one of the following URLs:
* https://bo.wix.com/pages/wix-ui-tpa.pr_6946/

2021-04-10 04:22 UTC, env-github-token commented
<!-- PRֹֹֹ_COMMENT_FOR:wix-style-react -->

### 🤖 Hi, I'm #Janet!

A deploy preview of your PR was successfully released 🖼.

Project Name: **wix-style-react**

You can find it under one of the following URLs:
* https://preview.wix-style-react.com/pr_6946