SectionHelper os theme
wix/wix-style-react pull request #6950
Opened 2021-03-21 19:17 UTC by adamg-wix

### 🔦 Summary

...

### ✅ Checklist

- [ ] 👨‍💻 API change is approved by the UI Infra Developers 
- [ ] 👨‍🎨 UX change is approved by the Design System UX 
- 📚 Change is documented
  - [ ] Story
  - [ ] API description
  - [ ] Cheatsheet
  - [ ] Other (explain)
- 🔬 Change is tested
  - [ ] Component
  - [ ] Visual test

2021-03-21 19:30 UTC, WixBuildServer commented
### 🤖 Hi, I'm #Janet!

  A deploy preview of your PR was successfully released 🖼.

  Project Name: **wix-ui-tpa**

  You can find it under one of the following URLs:
  * https://bo.wix.com/pages/wix-ui-tpa.pr_6950/

2021-03-21 19:34 UTC, WixBuildServer commented
### 🤖 Hi, I'm #Janet!

  A deploy preview of your PR was successfully released 🖼.

  Project Name: **wix-style-react**

  You can find it under one of the following URLs:
  * https://preview.wix-style-react.com/pr_6950

2021-03-25 08:42 UTC, adicicurel commented on packages/wix-style-react/src/SectionHelper/test/SectionHelper.visual.js
> +
runTests should wrap the original testing

2021-03-25 08:43 UTC, adicicurel commented on packages/wix-style-react/src/Themes/businessDashboard/components/SectionHelper.st.css
> +  -st-named: SP1, SP2, SP3, SP4, SP5, SP6, SP7, SP8;
Import only what in use

2021-03-25 08:44 UTC, adicicurel commented on packages/wix-style-react/src/Themes/businessDashboard/components/SectionHelper.st.css
> +}
is it part of the theme according to UX?

2021-03-25 08:44 UTC, adicicurel commented on packages/wix-style-react/src/Themes/businessDashboard/components/SectionHelper.st.css
> +  border-color: transparent;
border: none ?

2021-03-25 08:45 UTC, adicicurel commented on packages/wix-style-react/src/Themes/businessDashboard/components/SectionHelper.st.css
> +  border-color: transparent;
same

2021-03-25 08:45 UTC, adamg-wix commented on packages/wix-style-react/src/SectionHelper/test/SectionHelper.visual.js
> +
If i do that wouldn't it remove the non-themed tests ?

2021-03-25 08:45 UTC, adicicurel commented on packages/wix-style-react/src/Themes/businessDashboard/components/SectionHelper.st.css
> +  position: absolute;
why changing its position?

2021-03-25 08:47 UTC, adicicurel commented on packages/wix-style-react/src/Themes/businessDashboard/foundations/colors.st.css
> +
were those approved with Ayelet Livne?

2021-03-25 08:47 UTC, adicicurel commented on packages/wix-style-react/src/Themes/businessDashboard/foundations/colors.st.css
> +  R40: #FDE3E1;
were this approved with Ayelet Livne?

2021-03-25 08:47 UTC, adamg-wix commented on packages/wix-style-react/src/Themes/businessDashboard/components/SectionHelper.st.css
> +}
I just assumed i have to support RTL as well. it's just the reverse of the regular closeButton padidng.

2021-03-25 08:47 UTC, adicicurel requested changes
comments inside.

2021-03-25 08:48 UTC, adamg-wix commented on packages/wix-style-react/src/Themes/businessDashboard/foundations/colors.st.css
> +  R40: #FDE3E1;
see https://jira.wixpress.com/browse/OSA-306

2021-03-25 08:48 UTC, adamg-wix commented on packages/wix-style-react/src/Themes/businessDashboard/foundations/colors.st.css
> +
https://jira.wixpress.com/browse/OSA-306

2021-03-25 09:04 UTC, adamg-wix commented on packages/wix-style-react/src/Themes/businessDashboard/components/SectionHelper.st.css
> +  position: absolute;
Added

2021-03-25 09:18 UTC, adamg-wix commented on packages/wix-style-react/src/Themes/businessDashboard/components/SectionHelper.st.css
> +  -st-named: SP1, SP2, SP3, SP4, SP5, SP6, SP7, SP8;
done

2021-03-25 09:18 UTC, adamg-wix commented on packages/wix-style-react/src/Themes/businessDashboard/components/SectionHelper.st.css
> +  border-color: transparent;
done

2021-03-25 09:18 UTC, adamg-wix commented on packages/wix-style-react/src/Themes/businessDashboard/components/SectionHelper.st.css
> +  border-color: transparent;
done

2021-04-04 05:23 UTC, adicicurel approved these changes

2021-04-06 06:11 UTC, mykas commented on packages/wix-style-react/src/Themes/businessDashboard/components/SectionHelper.st.css
> +}
Please don't use `:global` params. In order to support rtl based padding you can use `padding-inline` https://developer.mozilla.org/en-US/docs/Web/CSS/padding-inline

2021-04-06 06:12 UTC, mykas reviewed
See my reply in comments of `:global` params usage.

2021-04-07 05:31 UTC, adamg-wix commented on packages/wix-style-react/src/Themes/businessDashboard/components/SectionHelper.st.css
> +}
@mykas this is how it is done in the original component as well i was just following it's lead :)
I worry that if i use a different implementation here the output might not be the same.

2021-04-07 07:46 UTC, mykas commented on packages/wix-style-react/src/Themes/businessDashboard/components/SectionHelper.st.css
> +}
oh thats true. Allright

2021-04-07 08:58 UTC, merged