WIP: Run only changed visual tests in WSR
wix/wix-style-react pull request #6962
Opened 2021-03-23 15:03 UTC by argshook

This is an unpolished implementation of a script that finds changed components and configures visual tests to run tests only on them

2021-03-23 17:58 UTC, WixBuildServer commented
### 🤖 Hi, I'm #Janet!

  A deploy preview of your PR was successfully released 🖼.

  Project Name: **wix-ui-tpa**

  You can find it under one of the following URLs:
  * https://bo.wix.com/pages/wix-ui-tpa.pr_6962/

2021-03-23 18:03 UTC, WixBuildServer commented
### 🤖 Hi, I'm #Janet!

  A deploy preview of your PR was successfully released 🖼.

  Project Name: **wix-style-react**

  You can find it under one of the following URLs:
  * https://preview.wix-style-react.com/pr_6962

2021-03-23 21:57 UTC, shlomitc requested changes

2021-03-23 21:57 UTC, shlomitc commented on packages/wix-style-react/.storybook/visual/config.js
> +}
This should be done only in the test mode of eyes-storybook and not in the start/debug mode.

2021-03-23 21:57 UTC, shlomitc commented on scripts/find-changed-visuals.js
> +const fs = require("fs");
wdyt about adding this logic as part of `wuf update`?

since you already have a meta-data file for all components, you can add a "dirty" flag or similar indicating if a component was changed or not.

2021-03-23 21:57 UTC, shlomitc commented on scripts/find-changed-visuals.js
> +        [".js", ".jsx", ".ts", ".tsx"].some((extension) =>
`.st.css` / `.scss` files

2021-03-24 07:41 UTC, argshook commented on scripts/find-changed-visuals.js
> +const fs = require("fs");
this should definitely go to `wuf`, didn't think of where exactly yet. Maybe to `wuf update` as you suggest.
but before that happens just want to try it out as a script. if it's successful then it'll mature to `wuf`

2021-03-26 09:48 UTC, mykas commented on packages/wix-style-react/src/Search/Search.js
> +// test
Lets remove this one?

2021-03-26 09:49 UTC, mykas commented on packages/wix-style-react/src/Search/Search.js
> +// test
```suggestion

```

2021-03-26 09:49 UTC, argshook commented on packages/wix-style-react/src/Search/Search.js
> +// test
yes, i added this to try out the script in CI and see it working

2021-03-26 09:49 UTC, mykas approved these changes
Love this! Now if that could work too with our e2es.... but ok ok I am asking too much!

2021-03-26 09:54 UTC, argshook commented
> Love this! Now if that could work too with our e2es.... but ok ok I am asking too much!

it will!

the plan is:

* try out the approach if it really works well
* if it's a yes, then generalise the implementation to be more reusable
* use it for protractor e2e, wix-ui-tpa, maybe something else in future

2021-03-29 13:03 UTC, WixBuildServer commented
<!-- PRֹֹֹ_COMMENT_FOR:wix-ui-tpa -->

### 🤖 Hi, I'm #Janet!

A deploy preview of your PR was successfully released 🖼.

Project Name: **wix-ui-tpa**

You can find it under one of the following URLs:
* https://bo.wix.com/pages/wix-ui-tpa.pr_6962/

2021-03-29 13:07 UTC, WixBuildServer commented
<!-- PRֹֹֹ_COMMENT_FOR:wix-style-react -->

### 🤖 Hi, I'm #Janet!

A deploy preview of your PR was successfully released 🖼.

Project Name: **wix-style-react**

You can find it under one of the following URLs:
* https://preview.wix-style-react.com/pr_6962

2021-03-29 13:31 UTC, merged