Grid to Layout: deprecation message for grid, migration doc, existing docs updates
wix/wix-style-react pull request #6966
Opened 2021-03-24 11:40 UTC by egidijusja

### 🔦 Summary

...

### ✅ Checklist

- [ ] 👨‍💻 API change is approved by the UI Infra Developers 
- [ ] 👨‍🎨 UX change is approved by the Design System UX 
- 📚 Change is documented
  - [ ] Story
  - [ ] API description
  - [ ] Cheatsheet
  - [ ] Other (explain)
- 🔬 Change is tested
  - [ ] Component
  - [ ] Visual test

2021-03-24 11:53 UTC, WixBuildServer commented
### 🤖 Hi, I'm #Janet!

  A deploy preview of your PR was successfully released 🖼.

  Project Name: **wix-ui-tpa**

  You can find it under one of the following URLs:
  * https://bo.wix.com/pages/wix-ui-tpa.pr_6966/

2021-03-24 11:58 UTC, WixBuildServer commented
### 🤖 Hi, I'm #Janet!

  A deploy preview of your PR was successfully released 🖼.

  Project Name: **wix-style-react**

  You can find it under one of the following URLs:
  * https://preview.wix-style-react.com/pr_6966

2021-03-24 12:25 UTC, shlomitc requested changes

2021-03-24 12:25 UTC, shlomitc commented on packages/wix-style-react/src/Grid/Grid.js
> +  deprecationLog(DEPRECATION_MESSAGE);
this will run on each render, so you better make it stateful instead

2021-03-24 12:25 UTC, shlomitc commented on packages/wix-style-react/src/Grid/Grid.js
> +  deprecationLog(DEPRECATION_MESSAGE);
@mykas @egidijusj - did we try replacing the internal implementation of `Grid` with `Layout`?

2021-03-24 12:38 UTC, egidijusj commented on packages/wix-style-react/src/Grid/Grid.js
> +  deprecationLog(DEPRECATION_MESSAGE);
@egidijusja

2021-03-24 12:38 UTC, shlomitc commented on packages/wix-style-react/src/Grid/Grid.js
> +  deprecationLog(DEPRECATION_MESSAGE);
omg your github users are so similar. sorry

2021-03-25 15:15 UTC, egidijusja commented on packages/wix-style-react/src/Grid/Grid.js
> +  deprecationLog(DEPRECATION_MESSAGE);
If we would try to use Layout internally this might cause some problems. I checked for Grid usages and there are things that are not supported by Layout.

1. Proper Grid usage structure is
```
<Container>
  <Row>
    <Cell>
      ...
    </Cell>
  </Row>
</Container>
```
Although users sometimes place divs in between (e.g. <Container><div><Row>...), sometimes they use only Container wrapper without Row and Cols, and there are more cases when proper Grid structure is not followed. Layout wouldn't work as expected if we would place div between <Layout> and <Cell> components.

2. All Grid components support custom classname prop. This is not supported by Layout components.

If we would use Layout inside Grid some applications would likely break because of these reasons and people would have to do some rework in order to update WSR minor version where this change is introduced.

2021-03-27 11:11 UTC, shlomitc commented on packages/wix-style-react/src/Grid/Grid.js
> +  deprecationLog(DEPRECATION_MESSAGE);
Regardless to users that misuse the components and lack of className - would the component work the same?

2021-03-31 09:56 UTC, mykas approved these changes
Looks good!

2021-03-31 10:16 UTC, egidijusja commented on packages/wix-style-react/src/Grid/Grid.js
> +  deprecationLog(DEPRECATION_MESSAGE);
Will check this possibility in separate PR.

2021-03-31 10:28 UTC, WixBuildServer commented
<!-- PRֹֹֹ_COMMENT_FOR:wix-ui-tpa -->

### 🤖 Hi, I'm #Janet!

A deploy preview of your PR was successfully released 🖼.

Project Name: **wix-ui-tpa**

You can find it under one of the following URLs:
* https://bo.wix.com/pages/wix-ui-tpa.pr_6966/

2021-03-31 10:31 UTC, WixBuildServer commented
<!-- PRֹֹֹ_COMMENT_FOR:wix-style-react -->

### 🤖 Hi, I'm #Janet!

A deploy preview of your PR was successfully released 🖼.

Project Name: **wix-style-react**

You can find it under one of the following URLs:
* https://preview.wix-style-react.com/pr_6966

2021-04-01 06:24 UTC, merged