BusinessDashboard Theme | <Popover> - Changed colors
wix/wix-style-react pull request #6991
Opened 2021-03-31 12:39 UTC by shelly-goldblit

### 🔦 Summary

...

### ✅ Checklist

- [ ] 👨‍💻 API change is approved by the UI Infra Developers 
- [ ] 👨‍🎨 UX change is approved by the Design System UX 
- 📚 Change is documented
  - [ ] Story
  - [ ] API description
  - [ ] Cheatsheet
  - [ ] Other (explain)
- 🔬 Change is tested
  - [ ] Component
  - [x] Visual test

2021-03-31 12:54 UTC, WixBuildServer commented
<!-- PRֹֹֹ_COMMENT_FOR:wix-ui-tpa -->

### 🤖 Hi, I'm #Janet!

A deploy preview of your PR was successfully released 🖼.

Project Name: **wix-ui-tpa**

You can find it under one of the following URLs:
* https://bo.wix.com/pages/wix-ui-tpa.pr_6991/

2021-03-31 12:56 UTC, WixBuildServer commented
<!-- PRֹֹֹ_COMMENT_FOR:wix-style-react -->

### 🤖 Hi, I'm #Janet!

A deploy preview of your PR was successfully released 🖼.

Project Name: **wix-style-react**

You can find it under one of the following URLs:
* https://preview.wix-style-react.com/pr_6991

2021-04-04 07:26 UTC, adicicurel requested changes
Add visual tests

2021-04-05 09:35 UTC, adicicurel commented on packages/wix-style-react/src/Popover/test/Popover.visual.js
> +
remove empty line

2021-04-05 09:42 UTC, wix-fed-exam approved these changes

2021-04-05 09:43 UTC, adicicurel approved these changes

2021-04-06 06:04 UTC, mykas commented on packages/wix-style-react/src/Themes/businessDashboard/components/Popover.st.css
> +:import {
There is no need for this import. The arrow and popoverContent are already available in Popover stylesheet which you can override. Just like you did here: https://github.com/wix/wix-style-react/blob/master/packages/wix-style-react/src/Page/PageSticky.js#L35

2021-04-07 10:46 UTC, merged