<Date Picker /> - fix rtl arrows position in responsive designs
wix/wix-style-react pull request #7009
Opened 2021-04-07 06:56 UTC by poseneror

### 🔦 Summary

...

### ✅ Checklist

- 🔬 Change is tested
  - [ ] Visual test

2021-04-07 07:09 UTC, WixBuildServer commented
<!-- PRֹֹֹ_COMMENT_FOR:wix-ui-tpa -->

### 🤖 Hi, I'm #Janet!

A deploy preview of your PR was successfully released 🖼.

Project Name: **wix-ui-tpa**

You can find it under one of the following URLs:
* https://bo.wix.com/pages/wix-ui-tpa.pr_7009/

2021-04-07 07:13 UTC, WixBuildServer commented
<!-- PRֹֹֹ_COMMENT_FOR:wix-style-react -->

### 🤖 Hi, I'm #Janet!

A deploy preview of your PR was successfully released 🖼.

Project Name: **wix-style-react**

You can find it under one of the following URLs:
* https://preview.wix-style-react.com/pr_7009

2021-04-07 13:28 UTC, sivanharel commented on packages/wix-ui-tpa/src/components/DatePicker/DatePicker.visual.tsx
> +      <div dir="rtl">
<TPAComponentsConsumer>
```suggestion
      <div dir="rtl">
           <TPAComponentsProvider value={{ rtl: true }}>
```

2021-04-07 13:28 UTC, sivanharel commented on packages/wix-ui-tpa/src/components/DatePicker/DatePicker.visual.tsx
> +        />
```suggestion
        />
  </TPAComponentsProvider value={{ rtl: true }}>
```

2021-04-07 14:00 UTC, sivanharel requested changes
Great!
We just need to add the  TPAComponentsProvider as well here see the comment.

2021-04-08 06:42 UTC, sivanharel commented on packages/wix-ui-tpa/src/components/DatePicker/DatePicker.visual.tsx
> +  </TPAComponentsProvider value={{ rtl: true }}>
```suggestion
  </TPAComponentsProvider>
```

2021-04-08 06:50 UTC, sivanharel approved these changes

2021-04-11 06:49 UTC, merged

2021-04-11 07:34 UTC, poseneror commented
Thanks @sivanharel :)