#WOSBM-3878| change hover and active bg color for sidebar section item
wix/wix-style-react pull request #7015
Opened 2021-04-07 15:01 UTC by katyamois

### 🔦 Summary
Change hover and selected background color under experiment and under dashboard theme
...

### ✅ Checklist

- [ ] 👨‍💻 API change is approved by the UI Infra Developers 
- [ ] 👨‍🎨 UX change is approved by the Design System UX 
- 📚 Change is documented
  - [ ] Story
  - [ ] API description
  - [ ] Cheatsheet
  - [ ] Other (explain)
- 🔬 Change is tested
  - [ ] Component
  - [ ] Visual test

2021-04-07 16:02 UTC, miby-wix requested changes

2021-04-07 16:02 UTC, miby-wix commented on packages/wix-style-react/src/SidebarSectionItem/SidebarSectionItem.uni.driver.d.ts
> +  getButtonClass: () => Promise<string>;
This is going to be added to the official WSR SidebarSectionItem testkit here: https://www.wix-style-react.com/?activeTab=Testkit&path=%2Fstory%2Fcomponents-api-components--sidebarsectionitem
I think it shouldn't be added to the driver and you should do it in the test directly.I can't see external usage that needs this...

2021-04-07 16:14 UTC, katyamois commented on packages/wix-style-react/src/SidebarSectionItem/test/SidebarSectionItem.private.uni.driver.js
> +    getButtonClass: () => base.$(`button`).attr('class')
there is no data-hook on the button

2021-04-07 16:15 UTC, katyamois commented on packages/wix-style-react/src/SidebarSectionItem/SidebarSectionItem.uni.driver.d.ts
> +  getButtonClass: () => Promise<string>;
yes I forgot to remove it

2021-04-07 17:07 UTC, katyamois commented on packages/wix-style-react/src/SidebarSectionItem/SidebarSectionItem.uni.driver.d.ts
> +  getButtonClass: () => Promise<string>;
fixed

2021-04-07 17:07 UTC, katyamois commented on packages/wix-style-react/src/SidebarSectionItem/test/SidebarSectionItem.spec.js
> +  it('should not use useBmSidebarNewDesign if not passed', async () => {
fixed

2021-04-07 17:37 UTC, miby-wix approved these changes
Approving from BizMgr side - we still need WSR approval and merge.

2021-04-07 17:37 UTC, miby-wix commented on packages/wix-style-react/src/SidebarSectionItem/test/SidebarSectionItem.private.uni.driver.js
> +    getSidebarSectionItemClass: async (hook) => await findByHook(base, hook).attr('class')
I think the naming should be more accurate - getClassByDataHook(). Or even change the implementation to getByataHook() and get the class in the test. Let's see what the WSR reviewer say before you fix it - they probably have their own conventions.

2021-04-07 17:38 UTC, miby-wix requested changes

2021-04-07 17:38 UTC, miby-wix commented on packages/wix-style-react/src/Themes/businessDashboard/foundations/colors.st.css
> +  selectedBackgroundColorNew: #42454C;
We need to see what the WSR reviewer say - it might be available to everybody. Not sure we want that. Maybe the colors should be hard coded in the specific css for now. Waiting on this one.

2021-04-08 06:44 UTC, mykas commented on packages/wix-style-react/src/SidebarSectionItem/test/SidebarSectionItem.private.uni.driver.js
> +    getClassByDataHook: async (hook) => await findByHook(base, hook).attr('class')
Testing with classes is not the right pattern we suggest. You can pass additional `data-useBmSidebarNewDesign` paramater on the button and search for it.

2021-04-08 06:44 UTC, mykas commented on packages/wix-style-react/src/Themes/businessDashboard/components/SidebarSectionItem.st.css
> +.root:useBmSidebarNewDesign:skin(dark):hover, .root:useBmSidebarNewDesign:skin(dark):hover:selected:not(:disabled) {
Please fix this extra spacing

2021-04-08 06:47 UTC, mykas commented on packages/wix-style-react/src/Themes/businessDashboard/components/SidebarSectionItem.st.css
> +  background-color: value(selectedBackgroundColorNew);
I am bit confused here. You defined these states inside this stylesheets but in the code there is nothing that applies this state.

2021-04-08 06:49 UTC, mykas commented on packages/wix-style-react/src/Themes/businessDashboard/components/SidebarSectionItem.st.css
> +  -st-named: sidebarBackgroundColor, selectedTextColor, selectedBackgroundColor, selectedBackgroundColorNew, hoveredBackgroundColor, hoveredBackgroundColorNew,  disabledBackgroundColor, textColor, se
But colors here in the foundation do not have these defined nor you added them. If these colors are specific for your experiment - hardcode them here.

2021-04-08 06:53 UTC, mykas commented on packages/wix-style-react/src/Themes/businessDashboard/foundations/colors.st.css
> +  selectedBackgroundColorNew: #42454C;
If this is specific for the experiment - this is not the place to store it but rather inside the stylesheet

2021-04-08 06:59 UTC, mykas commented on packages/wix-style-react/src/SidebarSectionItem/test/SidebarSectionItem.spec.js
> +  it('should not use useBmSidebarNewDesign if not passed', async () => {
Actually there is no need for unit testing. The only part that you need to test is the visuals. We have visual tests for that where you can wrap the component with the provider and do a screenshot.

2021-04-08 07:06 UTC, katyamois commented on packages/wix-style-react/src/Themes/businessDashboard/components/SidebarSectionItem.st.css
> +.root:useBmSidebarNewDesign:skin(dark):hover, .root:useBmSidebarNewDesign:skin(dark):hover:selected:not(:disabled) {
which space?

2021-04-08 07:24 UTC, mykas commented on packages/wix-style-react/src/Themes/businessDashboard/components/SidebarSectionItem.st.css
> +.root:useBmSidebarNewDesign:skin(dark):hover, .root:useBmSidebarNewDesign:skin(dark):hover:selected:not(:disabled) {
Github shows a plug sign next to the `.root:useBmSidebarNewDesign:skin(dark):hover`

2021-04-08 07:53 UTC, mykas commented on packages/wix-style-react/src/Themes/businessDashboard/components/SidebarSectionItem.st.css
> +.root:useBmSidebarNewDesign:skin(dark):hover, .root:useBmSidebarNewDesign:skin(dark):hover:selected:not(:disabled) {
Or maybe this is not a space..rather how github shows it.

2021-04-08 08:32 UTC, katyamois commented on packages/wix-style-react/src/SidebarSectionItem/test/SidebarSectionItem.spec.js
> +  it('should not use useBmSidebarNewDesign if not passed', async () => {
added visual test (not sure it they are correct), should I remove the unit ones?

2021-04-08 08:32 UTC, katyamois commented on packages/wix-style-react/src/Themes/businessDashboard/foundations/colors.st.css
> +  selectedBackgroundColorNew: #42454C;
fixed

2021-04-08 08:40 UTC, mykas commented on packages/wix-style-react/src/SidebarSectionItem/test/SidebarSectionItem.spec.js
> +  it('should not use useBmSidebarNewDesign if not passed', async () => {
yes, its redundant

2021-04-08 09:23 UTC, WixBuildServer commented
<!-- PRֹֹֹ_COMMENT_FOR:wix-ui-tpa -->

### 🤖 Hi, I'm #Janet!

A deploy preview of your PR was successfully released 🖼.

Project Name: **wix-ui-tpa**

You can find it under one of the following URLs:
* https://bo.wix.com/pages/wix-ui-tpa.pr_7015/

2021-04-08 09:28 UTC, WixBuildServer commented
<!-- PRֹֹֹ_COMMENT_FOR:wix-style-react -->

### 🤖 Hi, I'm #Janet!

A deploy preview of your PR was successfully released 🖼.

Project Name: **wix-style-react**

You can find it under one of the following URLs:
* https://preview.wix-style-react.com/pr_7015

2021-04-08 13:21 UTC, mykas approved these changes
Looks good! Good job. Lets wait for the build to get green

2021-04-08 13:49 UTC, merged