<SidebarSectionItem/><SidebarSectionTitle/><SidebarDivider/> - sidebar experiment for reduce horizontal padding and height for sidebar items
wix/wix-style-react pull request #7025
Opened 2021-04-12 08:30 UTC by katyamois

### 🔦 Summary

...

### ✅ Checklist

- [ ] 👨‍💻 API change is approved by the UI Infra Developers 
- [ ] 👨‍🎨 UX change is approved by the Design System UX 
- 📚 Change is documented
  - [ ] Story
  - [ ] API description
  - [ ] Cheatsheet
  - [ ] Other (explain)
- 🔬 Change is tested
  - [ ] Component
  - [ ] Visual test

2021-04-12 08:44 UTC, env-github-token commented
<!-- PRֹֹֹ_COMMENT_FOR:wix-ui-tpa -->

### 🤖 Hi, I'm #Janet!

A deploy preview of your PR was successfully released 🖼.

Project Name: **wix-ui-tpa**

You can find it under one of the following URLs:
* https://bo.wix.com/pages/wix-ui-tpa.pr_7025/

2021-04-12 08:50 UTC, env-github-token commented
<!-- PRֹֹֹ_COMMENT_FOR:wix-style-react -->

### 🤖 Hi, I'm #Janet!

A deploy preview of your PR was successfully released 🖼.

Project Name: **wix-style-react**

You can find it under one of the following URLs:
* https://preview.wix-style-react.com/pr_7025

2021-04-13 06:38 UTC, miby-wix requested changes

2021-04-13 06:38 UTC, miby-wix commented on packages/wix-style-react/src/SidebarSectionItem/SidebarSectionItem.st.css
> +.root:useBmSidebarNewDesign {
where is it wrapped on SidebarSecrtionItem with the provider? was it on previous PR?

2021-04-13 06:38 UTC, miby-wix commented on packages/wix-style-react/src/SidebarSectionItem/SidebarSectionItem.st.css
> +.root:useBmSidebarNewDesign {
Pending on this one only.

2021-04-13 09:16 UTC, katyamois commented on packages/wix-style-react/src/SidebarSectionItem/SidebarSectionItem.st.css
> +.root:useBmSidebarNewDesign {
yes it was on previous pr

2021-04-14 08:42 UTC, miby-wix approved these changes

2021-04-14 09:50 UTC, mykas approved these changes

2021-04-14 10:07 UTC, merged