[wix-ui-tpa] Adding char-count - tests, code and css (wip)
wix/wix-style-react pull request #7037
Opened 2021-04-14 07:58 UTC by yaelz

#pr

one test is failing, and still missing visual test and storybook support

2021-04-18 17:53 UTC, env-github-token commented
<!-- PRֹֹֹ_COMMENT_FOR:wix-ui-tpa -->

### 🤖 Hi, I'm #Janet!

A deploy preview of your PR was successfully released 🖼.

Project Name: **wix-ui-tpa**

You can find it under one of the following URLs:
* https://bo.wix.com/pages/wix-ui-tpa.pr_7037/

2021-04-18 17:56 UTC, env-github-token commented
<!-- PRֹֹֹ_COMMENT_FOR:wix-style-react -->

### 🤖 Hi, I'm #Janet!

A deploy preview of your PR was successfully released 🖼.

Project Name: **wix-style-react**

You can find it under one of the following URLs:
* https://preview.wix-style-react.com/pr_7037

2021-04-21 07:32 UTC, sivanharel commented on packages/wix-ui-tpa/src/components/TextField/docs/examples.ts
> +export const charCount = `
Please add an example for the char count in theme `box` as well.

2021-04-21 08:07 UTC, sivanharel requested changes
Great!
I wrote some comments.
In addition, you could do a rebase now and it will fix the issue with the setting panel.
Tell me if you need any help with the rebase

2021-04-21 08:07 UTC, sivanharel commented on packages/wix-ui-tpa/src/components/TextField/TextField.driver.ts
> +    isCharCountExist() {
```suggestion
    /**
     * Whether the charCount exists and displayed
     * @return {Promise<boolean>}
     */
    isCharCountExist() {
```

2021-04-21 08:07 UTC, sivanharel commented on packages/wix-ui-tpa/src/components/TextField/TextField.driver.ts
> +    getCharCountText() {
```suggestion
    /**
     * Gets the ratio of characters used and the total character limit
     * @return {Promise<string>}
     */
    getCharCountText() {
```

2021-04-21 08:07 UTC, sivanharel commented on packages/wix-ui-tpa/src/components/TextField/TextField.driver.ts
> +        .innerHTML;
```suggestion
        .textContent;
```

2021-04-26 12:36 UTC, yaelz commented on packages/wix-ui-tpa/src/components/TextField/TextField.driver.ts
> +      return parseInt(getDataAttributeValue('maxLength'), 10);
I'd rather return a number, this way it means what it should. WDYT?

2021-04-26 12:39 UTC, yaelz commented on packages/wix-ui-tpa/src/components/TextField/TextField.st.css
> +}
I checked it works with Hebrew. Is that enough?

2021-04-26 12:39 UTC, yaelz commented on packages/wix-ui-tpa/src/components/TextField/TextField.visual.tsx
> +      },
I hope I got it

2021-04-26 12:39 UTC, yaelz commented on packages/wix-ui-tpa/src/components/TextField/docs/examples.ts
> +export const charCount = `
I hope I did what you meant for me to do

2021-04-26 12:46 UTC, sivanharel commented on packages/wix-ui-tpa/src/components/TextField/TextField.visual.tsx
>    snap(
You have to add a text for the snap name that this example is with `CharCount` otherwise it will override other tests

2021-04-27 08:05 UTC, sivanharel approved these changes
Great!
We just need to ask our product designer to review it.

2021-04-28 13:13 UTC, merged