wix-ui-tpa/TextField-add-label
wix/wix-style-react pull request #7041
Opened 2021-04-14 13:06 UTC by urig-wix

### 🔦 Summary

...

### ✅ Checklist

- [ ] 👨‍💻 API change is approved by the UI Infra Developers 
- [ ] 👨‍🎨 UX change is approved by the Design System UX 
- 📚 Change is documented
  - [ ] Story
  - [ ] API description
  - [ ] Cheatsheet
  - [ ] Other (explain)
- 🔬 Change is tested
  - [ ] Component
  - [ ] Visual test

2021-04-14 13:19 UTC, env-github-token commented
<!-- PRֹֹֹ_COMMENT_FOR:wix-ui-tpa -->

### 🤖 Hi, I'm #Janet!

A deploy preview of your PR was successfully released 🖼.

Project Name: **wix-ui-tpa**

You can find it under one of the following URLs:
* https://bo.wix.com/pages/wix-ui-tpa.pr_7041/

2021-04-14 13:22 UTC, env-github-token commented
<!-- PRֹֹֹ_COMMENT_FOR:wix-style-react -->

### 🤖 Hi, I'm #Janet!

A deploy preview of your PR was successfully released 🖼.

Project Name: **wix-style-react**

You can find it under one of the following URLs:
* https://preview.wix-style-react.com/pr_7041

2021-04-18 14:28 UTC, sivanharel requested changes
Thanks!!
Very nice :)
I wrote some small comments.

2021-04-18 14:28 UTC, sivanharel commented on packages/wix-ui-tpa/src/components/TextField/TextField.st.css
> +    margin-bottom: 8px;
You should add `font` and `color` styling.
The default font should be `"{theme: 'Body-M', size: '14px', lineHeight: '1.4'}"`
the default color should be color-5
and it should be overridable from outside so you need to add style params. 
`LabelTextColor`, `LabelFont`.

2021-04-18 14:28 UTC, sivanharel commented on packages/wix-ui-tpa/src/components/TextField/TextField.st.css
> +    margin-bottom: 8px;
There is also a design for disabled mode.
https://zeroheight.com/7sjjzhgo2/p/157dab-04-inputs/t/41572c

2021-04-18 16:49 UTC, urig-wix commented
tnx for the comments! done.
I've tested the new props at the panel settings tab and it seems not to work well (and appear strange). I think that i implemented the stylable vars at the exact same way as other vars were implemented. any idea for why the settings panel looks weird?

2021-04-19 06:58 UTC, sivanharel commented on packages/wix-ui-tpa/src/components/TextField/TextField.st.css
> +    MainLabelTextColor: color-5;
```suggestion
    MainLabelTextColor: --overridable;
```

2021-04-19 07:00 UTC, sivanharel commented on packages/wix-ui-tpa/src/components/TextField/TextField.st.css
> +    MainLabelTextColor: color-5;
Actually, it should also change in the `MainTextColor`.
It might be the reason that the settings panel doesn't work

2021-04-19 08:48 UTC, sivanharel commented on packages/wix-ui-tpa/src/components/TextField/TextField.tsx
> +      <div>
I found the issue :)
The root class must be on the wrapper div of the component.

2021-04-19 11:49 UTC, urig-wix commented on packages/wix-ui-tpa/src/components/TextField/TextField.tsx
> +      <div>
interesting
so what should have been done?
When i add `className={classes.root}` on the div at line 184 it breaks the component (and it looks bad)

2021-04-19 12:15 UTC, sivanharel commented on packages/wix-ui-tpa/src/components/TextField/TextField.tsx
> +      <div>
You have to put the `root` class to the wrapper div and then create a new className for the `input` element and move all the styles of the `root` to this new class.

2021-04-19 16:44 UTC, urig-wix commented on packages/wix-ui-tpa/src/components/TextField/TextField.tsx
> +      <div>
tried to do that at my last commit, but now the styles at the settings panel stopped working, wdidw?

2021-04-20 07:29 UTC, sivanharel commented on packages/wix-ui-tpa/src/components/TextField/TextField.tsx
> +      <div>
I fixed it :)

2021-04-20 08:56 UTC, sivanharel approved these changes
I will ask our designer to do a review for it!

2021-04-20 09:01 UTC, urig-wix commented on packages/wix-ui-tpa/src/components/TextField/TextField.tsx
> +      <div>
you rock ! tnx

2021-04-21 06:22 UTC, merged