<SectionNotification /> - sizes
wix/wix-style-react pull request #7043
Opened 2021-04-15 07:28 UTC by frontned

### 🔦 Summary

...

### ✅ Checklist

- [ ] 👨‍💻 API change is approved by the UI Infra Developers 
- [ ] 👨‍🎨 UX change is approved by the Design System UX 
- 📚 Change is documented
  - [ ] Story
  - [ ] API description
  - [ ] Cheatsheet
  - [ ] Other (explain)
- 🔬 Change is tested
  - [ ] Component
  - [ ] Visual test

2021-04-15 07:43 UTC, env-github-token commented
<!-- PRֹֹֹ_COMMENT_FOR:wix-ui-tpa -->

### 🤖 Hi, I'm #Janet!

A deploy preview of your PR was successfully released 🖼.

Project Name: **wix-ui-tpa**

You can find it under one of the following URLs:
* https://bo.wix.com/pages/wix-ui-tpa.pr_7043/

2021-04-15 07:46 UTC, env-github-token commented
<!-- PRֹֹֹ_COMMENT_FOR:wix-style-react -->

### 🤖 Hi, I'm #Janet!

A deploy preview of your PR was successfully released 🖼.

Project Name: **wix-style-react**

You can find it under one of the following URLs:
* https://preview.wix-style-react.com/pr_7043

2021-04-18 13:12 UTC, sivanharel requested changes
Thanks! You did a very good job!

Some comments:
1. **index.story.tsx** - You should add the size prop for the `exampleProps` object. This will add this prop with all the values for the storybook `playground` tab.
https://github.com/wix/wix-style-react/blob/83882e07c36ce82df127d1fc5c21ea63595ef762/packages/wix-ui-tpa/src/components/SectionNotification/docs/index.story.tsx#L80

2. You should add the Settings Panel tab for the storybook.
In order to do it you should do the following:
a.  **SectionNotificationWiringExample.tsx** - Create this file and add an example for the usage of the component with the type `wired`. You should also add className={root}.b. **SectionNotificationWiringExample.st.css** - Create this file and use st-mixin in order to pass the values of the variables that you will define for the settings panel in the index.story.tsx file.c.  **index.story.tsx** - Add this tab for the story page of the component. 
You can see a reference in the DatePicker component:
https://github.com/wix/wix-style-react/blob/83882e07c36ce82df127d1fc5c21ea63595ef762/packages/wix-ui-tpa/src/components/DatePicker/docs/index.story.tsx#L156

https://github.com/wix/wix-style-react/blob/master/packages/wix-ui-tpa/src/components/DatePicker/docs/DatePickerWiringExample.st.css
 https://github.com/wix/wix-style-react/blob/master/packages/wix-ui-tpa/src/components/DatePicker/docs/DatePickerWiringExample.tsx#L15 (In your case, you only need to add one simple example.)
 
Let me know if something is not clear enough :)

2021-04-18 13:12 UTC, sivanharel commented on packages/wix-ui-tpa/src/components/SectionNotification/SectionNotification.st.css
> +}
I would check with our designer what should be defined here and will let you know.

2021-04-19 07:04 UTC, frontned commented on packages/wix-ui-tpa/src/components/SectionNotification/SectionNotification.visual.tsx
> +      }),
I think the `getTests` function makes sure that all types are tested, bacause it maps through the types?

2021-04-19 07:34 UTC, frontned commented on packages/wix-ui-tpa/src/components/SectionNotification/SectionNotification.st.css
> +}
Hey, I have fixed all the comments but this one.

2021-04-19 08:04 UTC, sivanharel reviewed
Awesome!
Just a small comment :)
I will send a link for our designer for review.

2021-04-19 08:56 UTC, sivanharel approved these changes
Great :)

2021-04-20 15:00 UTC, sivanharel commented
The test fails, you should run `npm run wut lint:fix` and then commit and push

2021-04-22 06:58 UTC, merged