[wsr] Expose unidrivers for our users
wix/wix-style-react pull request #7048
Opened 2021-04-15 13:04 UTC by mykas

This is PR that introduces generator template for unidriver expose. We need to expose this so that our users could composite our components unidrivers and create other libraries just like Cairo project does.

2021-04-15 13:16 UTC, env-github-token commented
<!-- PRֹֹֹ_COMMENT_FOR:wix-ui-tpa -->

### 🤖 Hi, I'm #Janet!

A deploy preview of your PR was successfully released 🖼.

Project Name: **wix-ui-tpa**

You can find it under one of the following URLs:
* https://bo.wix.com/pages/wix-ui-tpa.pr_7048/

2021-04-15 13:21 UTC, argshook requested changes
i understand the inspiration is taken from wix-ui-core https://github.com/wix/wix-ui/blob/master/packages/wix-ui-core/.wuf/testkits/unidriver.template.ejs

unfortunately it's not a good example there. the template in wix-ui-core directly mimics whatever was done manually before the generator to reduce the chance of broken builds. but what was done before generating from template is not a good approach. would be best not to repeat it in wix-style-react

2021-04-15 13:21 UTC, argshook commented on packages/wix-style-react/testkit/unidriver.js
> +  ...require("./../dist/src/Accordion/Accordion.uni.driver"),
add this file to `.gitignore`

2021-04-15 13:21 UTC, argshook commented on packages/wix-style-react/.wuf/testkits/unidriver.template.ejs
> +%>  ...require("<%= driverPath %>"),
i'd strongly suggest to explicitly name the exports instead of using the spread operator.

the `...require` is used in wix-ui-core and it's troublesome, because one require can potentially override another, there's a chance something random can get exported, plus the only way to know what's exported is to evaluate code. It should be enough to just read it.

before the exports file generation in wix-ui-core, there was a manually written file with all the `...require`s. thus, when changing it to be generated i left it with same spread, just to reduce the chance of broken builds. but it's not a good approach to take an example from.

i think this template should be similar to other testkit templates, with one major difference - no testkit factory function, just exported testkit.

2021-04-15 13:21 UTC, argshook commented on packages/wix-style-react/testkit/unidriver.js
> +  ...require("./../dist/src/AddressInputItem/AddressInputItem.uni.driver"),
checkout these newlines. not a big deal but by tweaking `.ejs` file you can avoid these

2021-04-15 13:21 UTC, argshook commented on packages/wix-style-react/.wuf/testkits/unidriver.template.ejs
> +        './../dist/src/',
```suggestion
        '../dist/src/',
```

2021-04-15 13:21 UTC, argshook commented on packages/wix-style-react/.wuf/testkits/unidriver.template.ejs
> +    if(component.name === 'Themes') {
since we already have two `.filter`s above, it would make sense to also use `.filter` for `Themes`

2021-04-15 13:21 UTC, argshook commented on packages/wix-style-react/.wuf/testkits/unidriver.template.ejs
> +    ((component.hasVanillaDriver || component.hasProtractorDriver) && component.hasUnidriver)
`.hasUnidriver` does not exist in wix-style-react definitions.js

2021-04-15 13:21 UTC, env-github-token commented
<!-- PRֹֹֹ_COMMENT_FOR:wix-style-react -->

### 🤖 Hi, I'm #Janet!

A deploy preview of your PR was successfully released 🖼.

Project Name: **wix-style-react**

You can find it under one of the following URLs:
* https://preview.wix-style-react.com/pr_7048

2021-04-15 13:32 UTC, mykas commented on packages/wix-style-react/.wuf/testkits/unidriver.template.ejs
> +%>  ...require("<%= driverPath %>"),
yes! totally make sense! thanks for pointing this out.

2021-04-16 09:13 UTC, argshook approved these changes

2021-04-16 10:58 UTC, mykas commented
Now the big question is - should we expose this through documentation? And where should be the right place. @shlomitc @EgoziE can you give us your opinion on this?

2021-04-18 09:03 UTC, shlomitc commented
Definitely expose it in our docs.
Regarding where it should sit - I'd say that the same way as other testkits are documented in the storybook, and also in this doc: https://github.com/wix/wix-style-react/blob/master/packages/wix-style-react/docs/usage/COMPONENTS_DRIVERS.md#supported-platforms

2021-04-21 07:43 UTC, merged