<HorizontalTimeline /> - add new props to component(skin, alignLabel, line, skin for icons, new icons)
wix/wix-style-react pull request #7049
Opened 2021-04-16 09:42 UTC by TetianaStashchenko

### 🔦 Summary

...
- ✅ 👨‍💻 API change is approved by the UI Infra Developers 
-  ✅  👨‍🎨 UX change is approved by the Design System UX 
- 📚 Change is documented
  - ✅  Story
- 🔬 Change is tested
  - [✅  Visual test

2021-04-16 10:00 UTC, mykas commented on packages/wix-style-react/src/HorizontalTimeline/HorizontalTimeline.js
> +            <div className={st(classes.column, className)} key={i} style={{ width }}>
```suggestion
            <div className={st(classes.column, {},  className)} key={i} style={{ width }}>
```

2021-04-16 10:01 UTC, mykas commented on package.json
> +    "@stylable/runtime": "^3.5.0",
I believe these changes are redundant. Please remove this changes from this pr

2021-04-16 10:02 UTC, mykas commented on packages/wix-style-react/src/HorizontalTimeline/HorizontalTimeline.js
> +    const { items, dataHook, className, skin: globalSkin = defaultProps.globalSkin, alignLabel = defaultProps.alignLabel } = this.props;
You don't need to pass default values for skin and alignLabel. you can just add those default values in defaultProps

2021-04-16 10:03 UTC, mykas commented on packages/wix-style-react/src/HorizontalTimeline/HorizontalTimeline.js
> +const defaultProps = {
Thats not how defaultProps are defined. You can add the component class this:
```js
static defaultProps = etc
```

2021-04-16 10:20 UTC, env-github-token commented
<!-- PRֹֹֹ_COMMENT_FOR:wix-ui-tpa -->

### 🤖 Hi, I'm #Janet!

A deploy preview of your PR was successfully released 🖼.

Project Name: **wix-ui-tpa**

You can find it under one of the following URLs:
* https://bo.wix.com/pages/wix-ui-tpa.pr_7049/

2021-04-16 10:24 UTC, env-github-token commented
<!-- PRֹֹֹ_COMMENT_FOR:wix-style-react -->

### 🤖 Hi, I'm #Janet!

A deploy preview of your PR was successfully released 🖼.

Project Name: **wix-style-react**

You can find it under one of the following URLs:
* https://preview.wix-style-react.com/pr_7049

2021-04-16 11:38 UTC, mykas commented on packages/wix-style-react/src/HorizontalTimeline/HorizontalTimeline.js
> +    itemSkin: 'light',
Thats not the props that we have. I believe you want to introduce `items` prop with default values

2021-04-16 11:38 UTC, mykas commented on packages/wix-style-react/src/HorizontalTimeline/HorizontalTimeline.js
> +  skin = skin || 'dark';
This should be moved to default props.

```js
HorizontalTimeline.DefaultIcon.defaultProps = {
   skin: 'dark'
 }
 ```

2021-04-19 09:17 UTC, mykas requested changes

2021-04-19 09:17 UTC, mykas commented on packages/wix-style-react/src/HorizontalTimeline/HorizontalTimeline.js
> +    itemSkin: 'light',
`defaultProps` in component must be same as props. `itemSkin` is not a prop that component exposes but rather its part of `item` prop.

2021-04-19 09:17 UTC, mykas commented on packages/wix-style-react/src/HorizontalTimeline/HorizontalTimeline.js
> +          skin = skin || HorizontalTimeline.defaultProps.itemSkin;
Lets not mutate the properties from the function. If you want to add default values you can do so in here:
https://github.com/wix/wix-style-react/pull/7049/files#diff-475000f38a15063585f364ebe88658299e0ca95ff143703acdafac9fab1bc05cR30

2021-04-19 09:17 UTC, mykas commented on packages/wix-style-react/src/HorizontalTimeline/HorizontalTimeline.js
> +        {items.map(({ label, width, skin, icon, line }, i) => {
```suggestion
        {items.map(({ label, width, skin = 'skin', icon, line = 'filled' }, i) => {
```

2021-04-19 09:17 UTC, mykas commented on packages/wix-style-react/src/HorizontalTimeline/HorizontalTimeline.js
> +          const nextItemLine = items[i + 1] && items[i + 1].line;
add default value here instead of this line https://github.com/wix/wix-style-react/pull/7049/files#diff-475000f38a15063585f364ebe88658299e0ca95ff143703acdafac9fab1bc05cR30

2021-04-19 12:25 UTC, mykas commented on packages/wix-style-react/src/HorizontalTimeline/HorizontalTimeline.js
> +    const defaultItemsProps = {
Move this variable outside of class.

2021-04-19 12:25 UTC, mykas commented on packages/wix-style-react/src/HorizontalTimeline/HorizontalTimeline.js
> +                  {isString(label) ? (
```suggestion
                  {typeof label === 'string' ? (
```

2021-04-21 09:55 UTC, mykas approved these changes
Good job!

2021-04-21 09:55 UTC, merged